### ISSUE TITLE
When a drawdown license expires there is no active license even with a valid Daily Usage

### ISSUE THREAD

**Issue by gally47** [Graylog2/graylog2-server#20109] opened 2024-08-07 15:11 UTC
When a drawdown license expires there is no active license even with a valid Daily Usage

![Screenshot 2024-08-07 at 11 13 15](https://github.com/user-attachments/assets/fa7d6516-1672-4b71-81dc-16a0672e06a3)

**Comment by grotlue** [comment] 2024-08-07 15:18
@AntonEbel @patrickmann I think this problem is with reassigning an active license?

**Comment by patrickmann** [comment] 2024-08-08 07:37
This is by design. You need to manually delete the expired draw-down license.

Reasoning:
Switching between license types is tricky, since we track traffic separately for daily versus draw-down licenses. Also, it is not expected to be a real-world occurrence. Customers that have switched to draw-down should no longer have a daily license. It was therefore decided not to include support for automatic switch-over in 6.1

**Closed by patrickmann** 2024-08-08 07:37 UTC
Labels: bug
