### ISSUE TITLE
"Stop input" command should survive Graylog-server restart

### ISSUE THREAD

**Issue by HolgerOpenSource** [Graylog2/graylog2-server#3081] opened 2016-11-10 13:00 UTC
Manually stopped inputs are started again after a Graylog server restart.

## Expected Behavior
Stopped inputs should stay stopped after restart.

## Current Behavior
Inputs are in status "started" after Graylog server restart.

## Possible Solution
Save status in mongoDB and read status after server restart.

## Steps to Reproduce (for bugs)
1. stop input manually
2. restart Graylog server

## Context
We want to stop inputs reliably for a longer time period.

## Your Environment

Versions:
- Graylog 2.1.1
- elasticsearch 2.3.5
- mongoDB 3.2.1
- Linux SLES 11
- Browser Firefox ESR 45.2.0
---

**Comment by edmundoa** [comment] 2016-11-10 13:10
Hi,

I'm closing this issue, as it is duplicating #967. Please subscribe to that issue and add comments there for any remarks you have and to track the progress of the issue.

Thank you!

**Comment by joschi** [comment] 2016-11-10 13:11
Duplicate of #967

**Closed by edmundoa** 2016-11-10 13:10 UTC
