### ISSUE TITLE
Unable to view metrics of node, There was a problem fetching node metrics.

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#14351] opened 2023-01-03 16:34 UTC
> There was a problem fetching node metrics. Graylog will keep trying to get them in the background.

![image](https://user-images.githubusercontent.com/107503402/210399331-459efa10-b25d-4d39-961e-3cf071a9bcc9.png)

This also causes a large spike is CPU load:

![image](https://user-images.githubusercontent.com/107503402/210399588-5c141129-40d0-4b70-bae4-019653d086b6.png)

I have tried restarting `graylog-server` which did not resolve loading the metrics page.

## Expected Behavior

Metrics browser loads

## Current Behavior

Unable to load metrics

## Steps to Reproduce (for bugs)

1. Navigate to `/system/metrics/node/<nodeId>`

## Your Environment

* Graylog Version: 5.0.1
* Java Version: 17.0.5
* Elasticsearch Version: OpenSearch 2.4.1
* MongoDB Version: 5.0.14
* Operating System: Ubuntu Server 20.04 LTS
* Browser version: Chrome (Arm) 108.0.5359.124

**Comment by drewmiranda-gl** [comment] 2023-01-03 17:34
Appears to be accompanied with the following:

```
2023-01-03T08:40:49.042-06:00 ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:232) ~[graylog.jar:?]
	at okio.AsyncTimeout.exit(AsyncTimeout.java:286) ~[graylog.jar:?]
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241) ~[graylog.jar:?]
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:358) ~[graylog.jar:?]
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230) ~[graylog.jar:?]
	at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242) ~[graylog.jar:?]
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213) ~[graylog.jar:?]
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115) ~[graylog.jar:?]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[graylog.jar:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[graylog.jar:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[graylog.jar:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[graylog.jar:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[graylog.jar:?]
	at org.graylog2.rest.RemoteInterfaceProvider.lambda$get$0(RemoteInterfaceProvider.java:61) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[graylog.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[graylog.jar:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[graylog.jar:?]
	at okhttp3.RealCall.execute(RealCall.java:81) ~[graylog.jar:?]
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204) ~[graylog.jar:?]
	at org.graylog2.rest.resources.cluster.ClusterNodeMetricsResource.byNamespace(ClusterNodeMetricsResource.java:122) ~[graylog.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [graylog.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) [graylog.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) [graylog.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [graylog.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.net.SocketException: Socket closed
	at sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:248) ~[?:?]
	at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:327) ~[?:?]
	at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[?:?]
	at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[?:?]
	at java.net.Socket$SocketInputStream.read(Socket.java:966) ~[?:?]
	at okio.Okio$2.read(Okio.java:140) ~[graylog.jar:?]
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237) ~[graylog.jar:?]
	... 52 more
```

**Comment by bernd** [comment] 2023-01-09 15:25
@drewmiranda-gl Can you reproduce this every time or was this a busy machine?

**Comment by drewmiranda-gl** [comment] 2023-01-12 23:19
I just tried again when both the host pc and the graylog cluster were idle and was able to reproduce it. It looks like when the metric page is loaded and it says it will keep retrying it sends a new metrics api request once a second but each request takes 25-30 sec to time out.

![image](https://user-images.githubusercontent.com/107503402/212201751-c6ec1c2b-c420-4233-a9cc-0ae738dd8fee.png)

The XHR request response is

```json
{"type":"ApiError","message":"timeout"}
```

**Comment by bernd** [comment] 2023-01-13 09:32
@drewmiranda-gl, can you share your Graylog configuration file? I suspect a problematic `http_puhlish_uri` and `http_external_uri` configuration. If you can reproduce this reliably, there is probably a misconfiguration somewhere, and the Graylog nodes can't properly talk to each other.

**Comment by drewmiranda-gl** [comment] 2023-01-13 18:01
For what its worth this is a recent problem seemingly introduced in 5.x (possibly in 5.0.1 but i cannot be sure). I was previously able to view node metrics.

`server.conf`

```
is_leader = true
node_id_file = /etc/graylog/server/node-id
password_secret = <redacted>
root_password_sha2 = <redacted>
bin_dir = /usr/share/graylog-server/bin
data_dir = /var/lib/graylog-server
plugin_dir = /usr/share/graylog-server/plugin
http_bind_address = 0.0.0.0:9000
http_publish_uri = http://graylog.drew.local:9000/
http_enable_cors = false
elasticsearch_hosts = http://192.168.0.81:9200
rotation_strategy = count
elasticsearch_max_docs_per_index = 20000000
elasticsearch_max_number_of_indices = 20
retention_strategy = delete
elasticsearch_shards = 4
elasticsearch_replicas = 0
elasticsearch_index_prefix = graylog
allow_leading_wildcard_searches = false
allow_highlighting = false
elasticsearch_analyzer = standard
output_batch_size = 500
output_flush_interval = 1
output_fault_count_threshold = 5
output_fault_penalty_seconds = 30
processbuffer_processors = 10
outputbuffer_processors = 8
processor_wait_strategy = blocking
ring_size = 65536
inputbuffer_ring_size = 65536
inputbuffer_processors = 2
inputbuffer_wait_strategy = blocking
message_journal_enabled = true
message_journal_dir = /var/lib/graylog-server/journal
lb_recognition_period_seconds = 3
mongodb_uri = mongodb://localhost/graylog
mongodb_max_connections = 1000
mongodb_threads_allowed_to_block_multiplier = 5
proxied_requests_thread_pool_size = 32
prometheus_exporter_enabled = true
prometheus_exporter_bind_address = 192.168.0.98:9833
prometheus_exporter_mapping_file_path_custom = /usr/share/graylog-server/prometheus-exporter-mapping-custom.yml 
```

For good measure, the contents of the referenced custom prom metrics file:

```
metric_mappings:
  - metric_name: "jvm_buffers_direct_capacity"
    match_pattern: "jvm.buffers.direct.capacity"

  - metric_name: "jvm_buffers_direct_count"
    match_pattern: "jvm.buffers.direct.count"

  - metric_name: "jvm_buffers_direct_used"
    match_pattern: "jvm.buffers.direct.used"

  - metric_name: "jvm_buffers_mapped_capacity"
    match_pattern: "jvm.buffers.mapped.capacity"

  - metric_name: "jvm_buffers_mapped_count"
    match_pattern: "jvm.buffers.mapped.count"

  - metric_name: "jvm_buffers_mapped_used"
    match_pattern: "jvm.buffers.mapped.used"

  - metric_name: "jvm_cl_loaded"
    match_pattern: "jvm.cl.loaded"

  - metric_name: "jvm_cl_unloaded"
    match_pattern: "jvm.cl.unloaded"

  - metric_name: "jvm_gc_ConcurrentMarkSweep_count"
    match_pattern: "jvm.gc.ConcurrentMarkSweep.count"

  - metric_name: "jvm_gc_ConcurrentMarkSweep_time"
    match_pattern: "jvm.gc.ConcurrentMarkSweep.time"

  - metric_name: "jvm_gc_ParNew_count"
    match_pattern: "jvm.gc.ParNew.count"

  - metric_name: "jvm_gc_ParNew_time"
    match_pattern: "jvm.gc.ParNew.time"

  - metric_name: "jvm_gc_G1_Old_Generation_count"
    match_pattern: "jvm.gc.G1-Old-Generation.count"

  - metric_name: "jvm_gc_G1_Old_Generation_time"
    match_pattern: "jvm.gc.G1-Old-Generation.time"

  - metric_name: "jvm_gc_G1_Young_Generation_count"
    match_pattern: "jvm.gc.G1-Young-Generation.count"

  - metric_name: "jvm_gc_G1_Young_Generation_time"
    match_pattern: "jvm.gc.G1-Young-Generation.time"

  - metric_name: "jvm_gc_ZGC_cycles_count"
    match_pattern: "jvm.gc.ZGC-Cycles.count"

  - metric_name: "jvm_gc_ZGC_cycles_time"
    match_pattern: "jvm.gc.ZGC-Cycles.time"

  - metric_name: "jvm_gc_ZGC_Pauses_count"
    match_pattern: "jvm.gc.ZGC-Pauses.count"

  - metric_name: "jvm_gc_ZGC_Pauses_time"
    match_pattern: "jvm.gc.ZGC-Pauses.time"

  - metric_name: "jvm_memory_heap_committed"
    match_pattern: "jvm.memory.heap.committed"

  - metric_name: "jvm_memory_heap_init"
    match_pattern: "jvm.memory.heap.init"

  - metric_name: "jvm_memory_heap_max"
    match_pattern: "jvm.memory.heap.max"

  - metric_name: "jvm_memory_heap_usage"
    match_pattern: "jvm.memory.heap.usage"

  - metric_name: "jvm_memory_heap_used"
    match_pattern: "jvm.memory.heap.used"

  - metric_name: "jvm_memory_non_heap_committed"
    match_pattern: "jvm.memory.non-heap.committed"

  - metric_name: "jvm_memory_non_heap_init"
    match_pattern: "jvm.memory.non-heap.init"

  - metric_name: "jvm_memory_non_heap_max"
    match_pattern: "jvm.memory.non-heap.max"

  - metric_name: "jvm_memory_non_heap_usage"
    match_pattern: "jvm.memory.non-heap.usage"

  - metric_name: "jvm_memory_non_heap_used"
    match_pattern: "jvm.memory.non-heap.used"

  - metric_name: "jvm_memory_pools_CMS-Old-Gen_committed"
    match_pattern: "jvm.memory.pools.CMS-Old-Gen.committed"

  - metric_name: "jvm_memory_pools_CMS-Old-Gen_init"
    match_pattern: "jvm.memory.pools.CMS-Old-Gen.init"

  - metric_name: "jvm_memory_pools_CMS-Old-Gen_max"
    match_pattern: "jvm.memory.pools.CMS-Old-Gen.max"

  - metric_name: "jvm_memory_pools_CMS-Old-Gen_usage"
    match_pattern: "jvm.memory.pools.CMS-Old-Gen.usage"

  - metric_name: "jvm_memory_pools_CMS-Old-Gen_used"
    match_pattern: "jvm.memory.pools.CMS-Old-Gen.used"

  - metric_name: "jvm_memory_pools_CMS-Old-Gen_used-after_gc"
    match_pattern: "jvm.memory.pools.CMS-Old-Gen.used-after-gc"

  - metric_name: "jvm_memory_pools_CodeHeap_non_nmethods_committed"
    match_pattern: "jvm.memory.pools.CodeHeap-non-methods.committed"

  - metric_name: "jvm_memory_pools_CodeHeap_non_nmethods_init"
    match_pattern: "jvm.memory.pools.CodeHeap-non-methods.init"

  - metric_name: "jvm_memory_pools_CodeHeap_non_nmethods_max"
    match_pattern: "jvm.memory.pools.CodeHeap-non-methods.max"

  - metric_name: "jvm_memory_pools_CodeHeap_non_nmethods_usage"
    match_pattern: "jvm.memory.pools.CodeHeap-non-methods.usage"

  - metric_name: "jvm_memory_pools_CodeHeap_non_nmethods_used"
    match_pattern: "jvm.memory.pools.CodeHeap-non-methods.used"

  - metric_name: "jvm_memory_pools_CodeHeap_non_profiled_nmethods_committed"
    match_pattern: "jvm.memory.pools.CodeHeap-non-profiled-nmethods.committed"

  - metric_name: "jvm_memory_pools_CodeHeap_non_profiled_nmethods_init"
    match_pattern: "jvm.memory.pools.CodeHeap-non-profiled-nmethods.init"

  - metric_name: "jvm_memory_pools_CodeHeap_non_profiled_nmethods_max"
    match_pattern: "jvm.memory.pools.CodeHeap-non-profiled-nmethods.max"

  - metric_name: "jvm_memory_pools_CodeHeap_non_profiled_nmethods_usage"
    match_pattern: "jvm.memory.pools.CodeHeap-non-profiled-nmethods.usage"

  - metric_name: "jvm_memory_pools_CodeHeap_non_profiled_nmethods_used"
    match_pattern: "jvm.memory.pools.CodeHeap-non-profiled-nmethods.used"

  - metric_name: "jvm_memory_pools_CodeHeap_profiled_nmethods_committed"
    match_pattern: "jvm.memory.pools.CodeHeap-profiled-nmethods.committed"

  - metric_name: "jvm_memory_pools_CodeHeap_profiled_nmethods_init"
    match_pattern: "jvm.memory.pools.CodeHeap-profiled-nmethods.init"

  - metric_name: "jvm_memory_pools_CodeHeap_profiled_nmethods_max"
    match_pattern: "jvm.memory.pools.CodeHeap-profiled-nmethods.max"

  - metric_name: "jvm_memory_pools_CodeHeap_profiled_nmethods_usage"
    match_pattern: "jvm.memory.pools.CodeHeap-profiled-nmethods.usage"

  - metric_name: "jvm_memory_pools_CodeHeap_profiled_nmethods_used"
    match_pattern: "jvm.memory.pools.CodeHeap-profiled-nmethods.used"

  - metric_name: "jvm_memory_pools_Compressed_Class_Space_committed"
    match_pattern: "jvm.memory.pools.Compressed-Class-Space.committed"

  - metric_name: "jvm_memory_pools_Compressed_Class_Space_init"
    match_pattern: "jvm.memory.pools.Compressed-Class-Space.init"

  - metric_name: "jvm_memory_pools_Compressed_Class_Space_max"
    match_pattern: "jvm.memory.pools.Compressed-Class-Space.max"

  - metric_name: "jvm_memory_pools_Compressed_Class_Space_usage"
    match_pattern: "jvm.memory.pools.Compressed-Class-Space.usage"

  - metric_name: "jvm_memory_pools_Compressed_Class_Space_used"
    match_pattern: "jvm.memory.pools.Compressed-Class-Space.used"

  - metric_name: "jvm_memory_pools_G1_Eden_Space_committed"
    match_pattern: "jvm.memory.pools.G1-Eden-Space.committed"

  - metric_name: "jvm_memory_pools_G1_Eden_Space_init"
    match_pattern: "jvm.memory.pools.G1-Eden-Space.init"

  - metric_name: "jvm_memory_pools_G1_Eden_Space_max"
    match_pattern: "jvm.memory.pools.G1-Eden-Space.max"

  - metric_name: "jvm_memory_pools_G1_Eden_Space_usage"
    match_pattern: "jvm.memory.pools.G1-Eden-Space.usage"

  - metric_name: "jvm_memory_pools_G1_Eden_Space_used"
    match_pattern: "jvm.memory.pools.G1-Eden-Space.used"

  - metric_name: "jvm_memory_pools_G1_Eden_Space_used_after_gc"
    match_pattern: "jvm.memory.pools.G1-Eden-Space.used-after-gc"

  - metric_name: "jvm_memory_pools_G1_Old_Gen_committed"
    match_pattern: "jvm.memory.pools.G1-Old-Gen.committed"

  - metric_name: "jvm_memory_pools_G1_Old_Gen_init"
    match_pattern: "jvm.memory.pools.G1-Old-Gen.init"

  - metric_name: "jvm_memory_pools_G1_Old_Gen_max"
    match_pattern: "jvm.memory.pools.G1-Old-Gen.max"

  - metric_name: "jvm_memory_pools_G1_Old_Gen_usage"
    match_pattern: "jvm.memory.pools.G1-Old-Gen.usage"

  - metric_name: "jvm_memory_pools_G1_Old_Gen_used"
    match_pattern: "jvm.memory.pools.G1-Old-Gen.used"

  - metric_name: "jvm_memory_pools_G1_Old_Gen_used_after_gc"
    match_pattern: "jvm.memory.pools.G1-Old-Gen.used-after-gc"

  - metric_name: "jvm_memory_pools_G1_Survivor_Space_committed"
    match_pattern: "jvm.memory.pools.G1-Survivor-Space.committed"

  - metric_name: "jvm_memory_pools_G1_Survivor_Space_init"
    match_pattern: "jvm.memory.pools.G1-Survivor-Space.init"

  - metric_name: "jvm_memory_pools_G1_Survivor_Space_max"
    match_pattern: "jvm.memory.pools.G1-Survivor-Space.max"

  - metric_name: "jvm_memory_pools_G1_Survivor_Space_usage"
    match_pattern: "jvm.memory.pools.G1-Survivor-Space.usage"

  - metric_name: "jvm_memory_pools_G1_Survivor_Space_used"
    match_pattern: "jvm.memory.pools.G1-Survivor-Space.used"

  - metric_name: "jvm_memory_pools_G1_Survivor_Space_used_after_gc"
    match_pattern: "jvm.memory.pools.G1-Survivor-Space.used-after-gc"

  - metric_name: "jvm_memory_pools_Metaspace_committed"
    match_pattern: "jvm.memory.pools.Metaspace.committed"

  - metric_name: "jvm_memory_pools_Metaspace_init"
    match_pattern: "jvm.memory.pools.Metaspace.init"

  - metric_name: "jvm_memory_pools_Metaspace_max"
    match_pattern: "jvm.memory.pools.Metaspace.max"

  - metric_name: "jvm_memory_pools_Metaspace_usage"
    match_pattern: "jvm.memory.pools.Metaspace.usage"

  - metric_name: "jvm_memory_pools_Metaspace_used"
    match_pattern: "jvm.memory.pools.Metaspace.used"

  - metric_name: "jvm_memory_pools_Par_Eden_Space_committed"
    match_pattern: "jvm.memory.pools.Par-Eden-Space.committed"

  - metric_name: "jvm_memory_pools_Par_Eden_Space_init"
    match_pattern: "jvm.memory.pools.Par-Eden-Space.init"

  - metric_name: "jvm_memory_pools_Par_Eden_Space_max"
    match_pattern: "jvm.memory.pools.Par-Eden-Space.max"

  - metric_name: "jvm_memory_pools_Par_Eden_Space_usage"
    match_pattern: "jvm.memory.pools.Par-Eden-Space.usage"

  - metric_name: "jvm_memory_pools_Par_Eden_Space_used"
    match_pattern: "jvm.memory.pools.Par-Eden-Space.used"

  - metric_name: "jvm_memory_pools_Par_Eden_Space_used_after_gc"
    match_pattern: "jvm.memory.pools.Par-Eden-Space.used-after-gc"

  - metric_name: "jvm_memory_pools_Par_Survivor_Space_committed"
    match_pattern: "jvm.memory.pools.Par-Survivor-Space.committed"

  - metric_name: "jvm_memory_pools_Par_Survivor_Space_init"
    match_pattern: "jvm.memory.pools.Par-Survivor-Space.init"

  - metric_name: "jvm_memory_pools_Par_Survivor_Space_max"
    match_pattern: "jvm.memory.pools.Par-Survivor-Space.max"

  - metric_name: "jvm_memory_pools_Par_Survivor_Space_usage"
    match_pattern: "jvm.memory.pools.Par-Survivor-Space.usage"

  - metric_name: "jvm_memory_pools_Par_Survivor_Space_used"
    match_pattern: "jvm.memory.pools.Par-Survivor-Space.used"

  - metric_name: "jvm_memory_pools_Par_Survivor_Space_used_after_gc"
    match_pattern: "jvm.memory.pools.Par-Survivor-Space.used-after-gc"

  - metric_name: "jvm_memory_pools_Zheap_committed"
    match_pattern: "jvm.memory.pools.Zheap.committed"

  - metric_name: "jvm_memory_pools_Zheap_init"
    match_pattern: "jvm.memory.pools.Zheap.init"

  - metric_name: "jvm_memory_pools_Zheap_max"
    match_pattern: "jvm.memory.pools.Zheap.max"

  - metric_name: "jvm_memory_pools_Zheap_usage"
    match_pattern: "jvm.memory.pools.Zheap.usage"

  - metric_name: "jvm_memory_pools_Zheap_used"
    match_pattern: "jvm.memory.pools.Zheap.used"

  - metric_name: "jvm_memory_pools_Zheap_used_after_gc"
    match_pattern: "jvm.memory.pools.Zheap.used-after-gc"

  - metric_name: "jvm_memory_total_committed"
    match_pattern: "jvm.memory.total.committed"

  - metric_name: "jvm_memory_total_init"
    match_pattern: "jvm.memory.total.init"

  - metric_name: "jvm_memory_total_max"
    match_pattern: "jvm.memory.total.max"

  - metric_name: "jvm_memory_total_used"
    match_pattern: "jvm.memory.total.used"

  - metric_name: "jvm_threads_blocked_count"
    match_pattern: "jvm.threads.blocked.count"

  - metric_name: "jvm_threads_count"
    match_pattern: "jvm.threads.count"

  - metric_name: "jvm_threads_daemon_count"
    match_pattern: "jvm.threads.daemon.count"

  - metric_name: "jvm_threads_deadlock_count"
    match_pattern: "jvm.threads.deadlock.count"

  - metric_name: "jvm_threads_deadlocks"
    match_pattern: "jvm.threads.deadlocks"

  - metric_name: "jvm_threads_new_count"
    match_pattern: "jvm.threads.new.count"

  - metric_name: "jvm_threads_runnable_count"
    match_pattern: "jvm.threads.runnable.count"

  - metric_name: "jvm_threads_terminated_count"
    match_pattern: "jvm.threads.terminated.count"

  - metric_name: "jvm_threads_timed_waiting_count"
    match_pattern: "jvm.threads.timed_waiting.count"

  - metric_name: "jvm_threads_waiting_count"
    match_pattern: "jvm.threads.waiting.count"

  - metric_name: "throughput_input_1_sec_rate"
    match_pattern: "org.graylog2.throughput.input.1-sec-rate"
    additional_labels:
      type: "input"

  - metric_name: "throughput_output_1_sec_rate"
    match_pattern: "org.graylog2.throughput.output.1-sec-rate"
    additional_labels:
      type: "output"

  - metric_name: "processBuffer_decodeTime"
    match_pattern: "org.graylog2.shared.buffers.ProcessBuffer.decodeTime"

  - metric_name: "processBuffer_parseTime"
    match_pattern: "org.graylog2.shared.buffers.ProcessBuffer.parseTime"

  - metric_name: "processBufferProcessor_processTime"
    match_pattern: "org.graylog2.shared.buffers.processors.ProcessBufferProcessor.processTime"
```

**Comment by drewmiranda-gl** [comment] 2023-01-13 18:04
Just to be certain, i removed the value for `prometheus_exporter_mapping_file_path_custom` and restarted to see if this changed anything but it did not, still same behavior.

**Comment by thll** [comment] 2023-04-24 07:48
@drewmiranda-gl, did that issue ever happen again? Fwiw, I don't expect the Prometheus exporter settings to be related because the metrics page is not using those.

We've changed how metrics are fetched internally with https://github.com/Graylog2/graylog2-server/pull/14462 to be more resilient to high load. If the problem didn't occur again, I think we can close this issue.

**Comment by drewmiranda-gl** [comment] 2023-04-24 21:22
It does still happen. It seems to be some sort of timeout but not sure what is causing it. Is it possible i've enabled metrics that are not enabled by default that could cause that? I don't get the behavior on a fresh install but do have it persist with my environment which makes me thing theres something (in the config file? mongo?) persisting it?

<img width="1316" alt="image" src="https://user-images.githubusercontent.com/107503402/234119734-cbd48b8e-c719-4f0c-b9b4-3d33f1daa897.png">

**Comment by thll** [comment] 2023-04-25 08:39
The metrics requests are proxied through the server that the UI hits with the request. We should check how long the actual request takes that hits the problematic node. Can you run a request like in the following example against all nodes in your cluster, after adjusting user/pw and host/port?

```
$ curl -so /dev/null -w "http_code: %{http_code}; time_total: %{time_total}\n" -u admin:admin http://localhost:9000/api/system/metrics/namespace/org
http_code: 200; time_total: 3.937595
```

**Comment by drewmiranda-gl** [comment] 2023-05-02 13:27
Mine outputs

> 8327

😬

**Comment by drewmiranda-gl** [comment] 2023-05-03 15:16
> That's still not an excessively high number. Do you have Illuminate installed? I suppose in that case it's expected because Illuminate adds a large number of metrics.

I do. Thanks for meeting with me :) . It is quite the mystery.

**Comment by thll** [comment] 2023-05-04 06:42
Just a quick summary of the current findings:

Fetching metrics from the `/api/system/metrics/namespace/` is very slow (~23 seconds) vs fetching metrics via the prometheus endpoint (~1s). Also, the runtime of the request seems to be proportional to the number of metrics fetched. This can be controlled by requesting different namespaces like `org` or `org.graylog2`.

A notable difference between the JSON endpoint and the prometheus endpoint is that the former perfoms permissions checks for each and every metric fetched. That might be a candidate for the performance bottleneck.

The next step would be to confirm this by temporarily disabling the permission checks and looking into this with a profiler or by adding tracing instrumentation.

**Comment by drewmiranda-gl** [comment] 2023-09-14 17:22
After spending some $$$ on a new lab server i can now load the metrics page! 🎉 

![image](https://github.com/Graylog2/graylog2-server/assets/107503402/98c93783-a9c5-41f6-a493-37d84f9ab228)

**Comment by bernd** [comment] 2023-09-19 09:29
@drewmiranda-gl Great to hear! So we can close this issue?

**Comment by drewmiranda-gl** [comment] 2023-09-19 13:42
> @drewmiranda-gl Great to hear! So we can close this issue?

up to y'all. It does seem like there may be room for performance improvement but i'll leave that up to y'all. Freel free to close though!

Thanks again!

**Closed** 2023-09-19 13:58 UTC
Labels: bug, to-verify

**Comment by drewmiranda-gl** [comment] 2024-07-17 14:24
I noticed today what seems to cause this behavior is the count of unique metrics. With my newer hardware i can load the metrics page without issue, except if i disable pipeline debug metrics. Once I disable pipeline debug metrics, even if i disable them again, the metrics persist (even though they are not updated) and this appears to cause the timeout.
