### ISSUE TITLE
Indices Range-Start Tooltip gone after upgrade to 2.0

### ISSUE THREAD

**Issue by gruselglatz** [Graylog2/graylog2-server#2549] opened 2016-07-27 07:55 UTC
### Problem description
In Version 1.3 there was a useful tooltip when you hover over the "Contains messages from ... to ...." text on the "Indices" Page.

In Cases like "Contains messages from 5 years ago up to 14 days ago", you could fast get the detailed range when you hover over the text. In 2.0+ i have to make API-Calls to get to it which takes much longer...

### Steps to reproduce the problem

1. Go to Indices Page
2. Hover over the part which indicates the start and end of the index range
3. See that you see nothing :(

### Environment

* Graylog Version: 2.0.3
* Elasticsearch Version: -
* MongoDB Version: -
* Operating System: Windows 7
* Browser version: Chrome 50+

**Comment by kroepke** [comment] 2016-07-27 07:57
Good point, that should be trivial to add back in 2.1

**Comment by kroepke** [comment] 2016-07-27 08:01
@edmundoa this could probably just use the Timestamp component instead of DateTime directly, right?

**Comment by edmundoa** [comment] 2016-07-27 09:19
@kroepke I think so, will take a look.

**Comment by coffee-squirrel** [comment] 2016-07-27 15:11
Duplicate of #2486 ?

**Comment by kroepke** [comment] 2016-07-27 15:12
@coffee-squirrel true, sorry I missed it :(

**Comment by kroepke** [comment] 2016-07-27 15:13
I'll close the original one because this already has a PR attached.

**Comment by coffee-squirrel** [comment] 2016-07-27 15:13
@kroepke No worries, I'm glad to see there's a PR!

**Closed** 2016-07-28 10:18 UTC
Labels: bug, P4, S4
