### ISSUE TITLE
 Graylog Custom Report Scheduling

### ISSUE THREAD

**Issue by DhruvTrivedi99** [Graylog2/graylog2-server#11230] opened 2021-08-31 04:47 UTC
We have been using the Weekly and Daily Report section of graylog for quite some time, but now we have a different requestment for getting a respective Report every four hours.

We need your help in guiding us through such kind of custom report scheduling,

=====================
graylog-4.1-repository/stable,stable,now 1-3 all [installed]
graylog-enterprise-integrations-plugins/stable,stable,now 4.1.3-1 all [installed]
graylog-enterprise-plugins/stable,stable,now 4.1.3-1 all [installed]
graylog-integrations-plugins/stable,stable,now 4.1.3-1 all [installed]
graylog-plugin-redis/now 0.1.1 all [installed,local]
graylog-server/stable,stable,now 4.1.3-1 all [installed]
graylog-sidecar/now 1.1.0-1 amd64 [installed,local]
mongodb-org/now 4.0.9 amd64 [installed,local]
mongodb-org-mongos/now 4.0.9 amd64 [installed,local]
mongodb-org-server/now 4.0.9 amd64 [installed,local]
mongodb-org-shell/now 4.0.9 amd64 [installed,local]
mongodb-org-tools/now 4.0.9 amd64 [installed,local]
elasticsearch/now 7.10.0 amd64 [installed,local]
graylog-sidecar/now 1.1.0-1 amd64 [installed,local]****

**Comment by dennisoelkers** [comment] 2021-08-31 07:43
Hey @DhruvTrivedi99,

thanks for reporting this! Unfortunately we are not supporting report frequencies smaller than daily at the moment. We are already tracking this feature request though and will work on it.

Therefore I am closing this as a duplicate of #8591.

**Closed by dennisoelkers** 2021-08-31 07:43 UTC
Labels: feature
