### ISSUE TITLE
Feature idea: Combine corresponding log messages e.g. Cisco ESA

### ISSUE THREAD

**Issue by ps-gm** [Graylog2/graylog2-server#2733] opened 2016-08-24 07:52 UTC
I'm getting a bunch of logs from a Cisco IronPort ESA appliance and they are in a format looking like that:

![image](https://cloud.githubusercontent.com/assets/20421183/17922643/5cb8559a-69e0-11e6-8acd-4e7e2e867db9.png)

![image](https://cloud.githubusercontent.com/assets/20421183/17922680/8fb6ff0a-69e0-11e6-967c-bf4abcd99f93.png)

It would be awesome having the possibility after doing successful GROK field identification. For example grouping all logs where the message ID is 234989 for example.

This is possible by simply searching for MID:234989, but usually you are looking for an e-mail message based on "SENDER" "RECIPIENT" "SUBJECT" etc.

So it would be very nice having a group-by or combine feature available in Graylog!!!

**Comment by joschi** [comment] 2016-08-24 07:55
Duplicate of #679.

**Closed by joschi** 2016-08-24 07:55 UTC

**Comment by desertjedi85** [comment] 2016-09-16 19:42
In lieu of this you can do a custom log entry in Ironport and put the fields that you want in there so they come in 1 log

**Comment by ps-gm** [comment] 2016-09-20 13:53
Thanks! We've tried using the "Action Variables" which would be working quite ($Subject, $Time,...) well, but unfortunately it is not possible adding further information about policy actions and anti virus etc. information. Any updates on a possible way correlating that in Graylog?

**Comment by dsever** [comment] 2017-04-25 11:53
Hi, 

have you manage to resolve this request?

Dubravko
