### ISSUE TITLE
Stopped Input starts again on graylog restart

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2185] opened 2016-05-04 18:16 UTC
### Problem description
Stopped Input starts again on graylog restart

### Steps to reproduce the problem

1. Stop Input
2. Restart graylog-server
3. Stopped Input started again

### Environment

* Graylog Version: 2.0 GA

**Comment by dennisoelkers** [comment] 2016-05-09 08:43
Thanks for reporting this. I am closing this though, because it is a duplicate of #967.

**Closed by dennisoelkers** 2016-05-09 08:43 UTC
