### ISSUE TITLE
The field order is wrong and can not be changed in table dashboard in view 

### ISSUE THREAD

**Issue by yoke88** [Graylog2/graylog2-server#6808] opened 2019-11-15 01:00 UTC
The field order is wrong and can not be changed in table dashboard in view 

## Expected Behavior
The property order should match the order which i set in fields,but the displayed order is wrong and no way to change it
## Current Behavior

![image](https://user-images.githubusercontent.com/3146226/68908167-713ba300-0785-11ea-9f4a-e37830e6e7b9.png)

## Possible Solution

i do not know
## Steps to Reproduce (for bugs)

create a message table in view ,and custom the props, the displayed order of props is wrong

## Context
1. I want to change the prop order ,because i want the most import column to display at the first column ,for example, timestamp column . but there is no easy way to change the order of props, even i change the order ,the order is wrong .

## Your Environment

* Graylog Version: Graylog 3.1.3+cda805f on localhost (Oracle Corporation 1.8.0_171 on Linux 3.10.0-1062.4.1.el7.x86_64)
* Elasticsearch Version:
* MongoDB Version:
* Operating System: centos 7.9
* Browser version: chrome  78.0.3904.97

**Comment by dennisoelkers** [comment] 2019-11-15 08:55
Hey @yoke88, thanks for reporting this. I cannot reproduce it neither on `3.1.3` nor on current `master`. Do you see any errors in your browser's JS console while changing the sorting?

**Comment by yoke88** [comment] 2019-11-15 11:32
there is no error in chrome console, you can see in the screenshoot, timestamp is the first column and src_user is the last prop,but the displayed table shows src_user at the first column,and timestamp is at the seventh column

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dennisoelkers** [comment] 2019-12-20 10:35
This should be fixed in `3.2.0`. If you still encounter it after upgrading to `3.2.0`, please reopen the issue.

**Comment by freelancer42** [comment] 2020-02-18 12:01
I'm having this same issue on a fresh install of Graylog 3.2.1 on Ubuntu 18.04 LTS, using Chrome on my client.

I create a new message table on a new dashboard and add fields in a certain order, but they are displayed in a different seemingly random (but always the same) order.

I'm currently evaluating Graylog for centralizing our firewall logs, but this feels very bad from a user experience perspective.

**Comment by freelancer42** [comment] 2020-02-18 12:03
Because I'm not the one who submitted this issue I can't reopen it. Not sure if I should submit a new issue for the same thing?

**Comment by dennisoelkers** [comment] 2020-02-18 14:42
Hey @freelancer42, thanks for getting in touch with us.

Can you provide steps to reproduce this issue and/or record your screen? I have just tried to reproduce it, but was unable to do that.

**Comment by freelancer42** [comment] 2020-02-18 14:53
I've got one CEF UDP input receiving data from a FortiGate firewall. The messages are properly decoded and fields like sourceAddress, sourcePort, destinationAddress and destinationPort are created/mapped for each message.

I've created a new dashboard and created a Message Table inside it. I then edit the table and add fields in the order I would like them to be displayed. In the field list on the left side of the edit window the fields are in the correct order, but in the actual table they are not (see screenshot below).

I've also created a simple stream that I'm using as a filter for the dashboard.

![message table](https://user-images.githubusercontent.com/16519229/74747003-8e8d7b00-5266-11ea-90fb-c5de59a254b8.png)

**Comment by dennisoelkers** [comment] 2020-02-19 09:26
Thanks @freelancer42! It looks like we are finally able to reproduce the issue and fix it. A PR that is addressing this issue is in the works and will most probably go into `3.2.2`, which is due in the next few days.

**Comment by freelancer42** [comment] 2020-02-19 09:51
Good to hear! Let me know when it's ready and I'll test it right away.

**Closed** 2020-02-19 12:29 UTC
Labels: bug, needs-input, triaged

**Comment by dennisoelkers** [comment] 2020-02-21 09:36
@freelancer42: The fix has landed in `3.2.2`, so it is now accessible for you to test! We would love to hear your feedback.

**Comment by freelancer42** [comment] 2020-02-21 12:25
Tried it now, seems to be working as expected. Thanks for the quick fix!
