### ISSUE TITLE
Syslog input "store_full_message" change does not apply during runtime

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#2504] opened 2016-07-19 21:29 UTC
### Problem description

Editing an input and changing the `store_full_message` config parameter does not take effect until restarting `graylog-server`.

* Graylog Version: Graylog 2.1.0-alpha.3-SNAPSHOT+53aade9
* Elasticsearch Version: 2.3.1
* MongoDB Version: 3.0.0
* Operating System: OSX
* Browser version: n/a

**Comment by joschi** [comment] 2016-07-23 10:37
@lennart I couldn't reproduce this using Graylog 2.1.0-alpha.3-SNAPSHOT+97521bf2bd8170101173aa6c39a1cf025e6ab1e8.

After disabling `store_full_message` for a Syslog UDP input and a Syslog TCP input, new messages didn't include the `full_message` field anymore.

Vice versa, enabling `store_full_message` for a Syslog UDP input and a Syslog TCP input, the `full_message` field started to appear again for messages received with those inputs.

I'm closing this ticket as I can't reproduce the described problem. Please re-open the ticket if you find this happening again.

**Closed by joschi** 2016-07-23 10:37 UTC
Labels: bug
