### ISSUE TITLE
Race conditions on cycling deflector?

### ISSUE THREAD

**Issue by plprofetes** [Graylog2/graylog2-server#1277] opened 2015-07-01 09:46 UTC
hello,
we've been successfully using Graylog solution since 0.20. Unfortunately recent releases (from 1.0 for sure, maybe earlier) tend to crash randomly on cycling the deflector. 75% cyclings are failed in my case.

It fails for every cycle rule: count, time, size.
I run single server, avg message rate is 10-50 rq/s.

The only solution is to restart server again and again until new index is acknowledged. Sometimes I need to perform 5 restarts or more for index to switch. In really stubborn cases I manually remove index from elasticsearch.

My server was set to cycle deflector every 2.000.000 messages, after that I changed it to 250MB. Issue still happend. I usually keep 4 indices.

I happend for both elasticsearch 1.3.9 and current 1.6.0.
I know I have given little RAM for Graylog, but it does not affect the issue. If Graylog has more RAM is still fails to cycle deflector.

below I present logs of this happening.
```
2015-07-01 09:31:55,103 INFO : org.graylog2.shared.inputs.InputStateListener - Input [Syslog UDP/54ec5557e4b0df50f2d608a6] is now RUNNING
2015-07-01 09:31:55,109 INFO : org.graylog2.shared.inputs.InputStateListener - Input [Syslog UDP/54ec5557e4b0df50f2d608a7] is now RUNNING
2015-07-01 09:31:55,114 INFO : org.graylog2.shared.inputs.InputStateListener - Input [Syslog UDP/551abd2fe4b00ef0e387a54f] is now RUNNING
2015-07-01 09:31:55,117 INFO : org.graylog2.shared.inputs.InputStateListener - Input [GELF UDP/54ec5569e4b0df50f2d608d0] is now RUNNING
2015-07-01 09:31:57,634 INFO : org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Enabling session validation scheduler...
2015-07-01 09:38:59,271 WARN : org.graylog2.periodical.NodePingThread - Did not find meta info of this node. Re-registering.
2015-07-01 09:50:47,324 WARN : org.graylog2.periodical.NodePingThread - Did not find meta info of this node. Re-registering.
2015-07-01 09:53:59,865 WARN : org.graylog2.periodical.NodePingThread - Did not find meta info of this node. Re-registering.
2015-07-01 10:06:47,141 WARN : org.graylog2.periodical.NodePingThread - Did not find meta info of this node. Re-registering.
2015-07-01 10:23:56,672 WARN : org.graylog2.periodical.NodePingThread - Did not find meta info of this node. Re-registering.
2015-07-01 10:31:57,638 INFO : org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
2015-07-01 10:31:57,650 INFO : org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
2015-07-01 10:46:27,021 WARN : org.graylog2.periodical.NodePingThread - Did not find meta info of this node. Re-registering.
2015-07-01 10:55:08,904 INFO : org.graylog2.periodical.IndexRotationThread - Deflector index <graylog_2> should be rotated, Pointing deflector to new index now!
2015-07-01 10:55:08,922 INFO : org.graylog2.indexer.Deflector - Cycling deflector to next index now.
2015-07-01 10:55:08,925 INFO : org.graylog2.indexer.Deflector - Cycling from <graylog_2> to <graylog_3>
2015-07-01 10:55:08,925 INFO : org.graylog2.indexer.Deflector - Creating index target <graylog_3>...
2015-07-01 10:55:09,501 INFO : org.graylog2.indexer.Deflector - Done!
2015-07-01 10:55:09,501 INFO : org.graylog2.indexer.Deflector - Pointing deflector to new target index....
2015-07-01 10:55:09,696 INFO : org.graylog2.system.jobs.SystemJobManager - Submitted SystemJob <e095dcf0-1fce-11e5-ad08-005056010238> [org.graylog2.indexer.SetIndexReadOnlyJob]
2015-07-01 10:55:09,703 INFO : org.graylog2.system.jobs.SystemJobManager - Submitted SystemJob <e0a01620-1fce-11e5-ad08-005056010238> [org.graylog2.indexer.ranges.CreateNewSingleIndexRangeJob]
2015-07-01 10:55:09,703 INFO : org.graylog2.indexer.ranges.CreateNewSingleIndexRangeJob - Calculating ranges for index graylog_2.
2015-07-01 10:55:09,710 INFO : org.graylog2.system.jobs.SystemJobManager - Submitted SystemJob <e0a0d970-1fce-11e5-ad08-005056010238> [org.graylog2.indexer.ranges.CreateNewSingleIndexRangeJob]
2015-07-01 10:55:09,710 INFO : org.graylog2.indexer.Deflector - Done!
2015-07-01 10:55:09,711 INFO : org.graylog2.indexer.ranges.CreateNewSingleIndexRangeJob - Calculating ranges for index graylog_3.
2015-07-01 10:55:09,734 INFO : org.graylog2.indexer.ranges.CreateNewSingleIndexRangeJob - Created ranges for index graylog_3.
2015-07-01 10:55:09,735 INFO : org.graylog2.system.jobs.SystemJobManager - SystemJob <e0a0d970-1fce-11e5-ad08-005056010238> [org.graylog2.indexer.ranges.CreateNewSingleIndexRangeJob] finished in 23ms.
2015-07-01 10:55:10,378 INFO : org.graylog2.indexer.ranges.RebuildIndexRangesJob - Calculated range of [graylog_2] in [655ms].
2015-07-01 10:55:10,380 INFO : org.graylog2.indexer.ranges.IndexRangeServiceImpl - Removed range meta-information of [graylog_2]
2015-07-01 10:55:10,385 INFO : org.graylog2.indexer.ranges.CreateNewSingleIndexRangeJob - Created ranges for index graylog_2.
2015-07-01 10:55:10,385 INFO : org.graylog2.system.jobs.SystemJobManager - SystemJob <e0a01620-1fce-11e5-ad08-005056010238> [org.graylog2.indexer.ranges.CreateNewSingleIndexRangeJob] finished in 681ms.
2015-07-01 10:55:18,962 WARN : org.graylog2.periodical.IndexRotationThread - Deflector is pointing to [graylog_3], not the newest one: [graylog_2]. Re-pointing.
2015-07-01 10:55:18,981 INFO : org.graylog2.periodical.IndexRotationThread - Deflector index <graylog_2> should be rotated, Pointing deflector to new index now!
2015-07-01 10:55:18,981 INFO : org.graylog2.indexer.Deflector - Cycling deflector to next index now.
2015-07-01 10:55:18,983 INFO : org.graylog2.indexer.Deflector - Cycling from <graylog_2> to <graylog_3>
2015-07-01 10:55:18,983 INFO : org.graylog2.indexer.Deflector - Creating index target <graylog_3>...
2015-07-01 10:55:19,355 ERROR: org.graylog2.periodical.IndexRotationThread - Couldn't point deflector to a new index
org.elasticsearch.indices.IndexAlreadyExistsException: [graylog_3] already exists
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validateIndexName(MetaDataCreateIndexService.java:160)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validate(MetaDataCreateIndexService.java:551)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.access$200(MetaDataCreateIndexService.java:88)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:230)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:374)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:188)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2015-07-01 10:55:28,906 INFO : org.graylog2.periodical.IndexRotationThread - Deflector index <graylog_2> should be rotated, Pointing deflector to new index now!
2015-07-01 10:55:28,906 INFO : org.graylog2.indexer.Deflector - Cycling deflector to next index now.
2015-07-01 10:55:28,908 INFO : org.graylog2.indexer.Deflector - Cycling from <graylog_2> to <graylog_3>
2015-07-01 10:55:28,908 INFO : org.graylog2.indexer.Deflector - Creating index target <graylog_3>...
2015-07-01 10:55:28,915 ERROR: org.graylog2.periodical.IndexRotationThread - Couldn't point deflector to a new index
org.elasticsearch.indices.IndexAlreadyExistsException: [graylog_3] already exists
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validateIndexName(MetaDataCreateIndexService.java:160)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validate(MetaDataCreateIndexService.java:551)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.access$200(MetaDataCreateIndexService.java:88)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:230)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:374)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:188)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2015-07-01 10:55:38,904 INFO : org.graylog2.periodical.IndexRotationThread - Deflector index <graylog_2> should be rotated, Pointing deflector to new index now!
2015-07-01 10:55:38,905 INFO : org.graylog2.indexer.Deflector - Cycling deflector to next index now.
2015-07-01 10:55:38,909 INFO : org.graylog2.indexer.Deflector - Cycling from <graylog_2> to <graylog_3>
2015-07-01 10:55:38,909 INFO : org.graylog2.indexer.Deflector - Creating index target <graylog_3>...
2015-07-01 10:55:38,915 ERROR: org.graylog2.periodical.IndexRotationThread - Couldn't point deflector to a new index
org.elasticsearch.indices.IndexAlreadyExistsException: [graylog_3] already exists
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validateIndexName(MetaDataCreateIndexService.java:160)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validate(MetaDataCreateIndexService.java:551)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.access$200(MetaDataCreateIndexService.java:88)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:230)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:374)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:188)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2015-07-01 10:55:39,696 INFO : org.graylog2.indexer.SetIndexReadOnlyJob - Flushing old index <graylog_2>.
2015-07-01 10:55:39,995 INFO : org.graylog2.indexer.SetIndexReadOnlyJob - Setting old index <graylog_2> to read-only.
2015-07-01 10:55:40,019 INFO : org.graylog2.system.jobs.SystemJobManager - Submitted SystemJob <f2b28d20-1fce-11e5-ad08-005056010238> [org.graylog2.indexer.indices.jobs.OptimizeIndexJob]
2015-07-01 10:55:40,019 INFO : org.graylog2.indexer.indices.jobs.OptimizeIndexJob - Optimizing index <graylog_2>.
2015-07-01 10:55:40,021 INFO : org.graylog2.system.jobs.SystemJobManager - SystemJob <e095dcf0-1fce-11e5-ad08-005056010238> [org.graylog2.indexer.SetIndexReadOnlyJob] finished in 324ms.
2015-07-01 10:55:48,905 INFO : org.graylog2.periodical.IndexRotationThread - Deflector index <graylog_2> should be rotated, Pointing deflector to new index now!
2015-07-01 10:55:48,905 INFO : org.graylog2.indexer.Deflector - Cycling deflector to next index now.
2015-07-01 10:55:48,908 INFO : org.graylog2.indexer.Deflector - Cycling from <graylog_2> to <graylog_3>
2015-07-01 10:55:48,908 INFO : org.graylog2.indexer.Deflector - Creating index target <graylog_3>...
2015-07-01 10:55:48,922 ERROR: org.graylog2.periodical.IndexRotationThread - Couldn't point deflector to a new index
org.elasticsearch.indices.IndexAlreadyExistsException: [graylog_3] already exists
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validateIndexName(MetaDataCreateIndexService.java:160)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validate(MetaDataCreateIndexService.java:551)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.access$200(MetaDataCreateIndexService.java:88)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:230)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:374)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:188)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2015-07-01 10:55:58,906 INFO : org.graylog2.periodical.IndexRotationThread - Deflector index <graylog_2> should be rotated, Pointing deflector to new index now!
2015-07-01 10:55:58,906 INFO : org.graylog2.indexer.Deflector - Cycling deflector to next index now.
2015-07-01 10:55:58,908 INFO : org.graylog2.indexer.Deflector - Cycling from <graylog_2> to <graylog_3>
2015-07-01 10:55:58,908 INFO : org.graylog2.indexer.Deflector - Creating index target <graylog_3>...
2015-07-01 10:55:58,926 ERROR: org.graylog2.periodical.IndexRotationThread - Couldn't point deflector to a new index
org.elasticsearch.indices.IndexAlreadyExistsException: [graylog_3] already exists
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validateIndexName(MetaDataCreateIndexService.java:160)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validate(MetaDataCreateIndexService.java:551)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.access$200(MetaDataCreateIndexService.java:88)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:230)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:374)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:188)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2015-07-01 10:56:07,075 INFO : org.graylog2.system.jobs.SystemJobManager - SystemJob <f2b28d20-1fce-11e5-ad08-005056010238> [org.graylog2.indexer.indices.jobs.OptimizeIndexJob] finished in 27056ms.
2015-07-01 10:56:38,897 INFO : org.graylog2.periodical.IndexRetentionThread - Elasticsearch cluster not available, skipping index retention checks.
2015-07-01 11:01:38,898 INFO : org.graylog2.periodical.IndexRetentionThread - Elasticsearch cluster not available, skipping index retention checks.
2015-07-01 11:06:38,897 INFO : org.graylog2.periodical.IndexRetentionThread - Elasticsearch cluster not available, skipping index retention checks.
2015-07-01 11:10:01,602 WARN : org.graylog2.periodical.NodePingThread - Did not find meta info of this node. Re-registering.
2015-07-01 11:11:38,897 INFO : org.graylog2.periodical.IndexRetentionThread - Elasticsearch cluster not available, skipping index retention checks.
```

after that I restarted server and that was successful:

```
2015-07-01 11:25:42,387 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugins: [Anonymous Usage Statistics 1.0.7 [org.graylog.plugins.usagestatistics.UsageStatsPlugin]]
2015-07-01 11:25:42,532 INFO : org.graylog2.configuration.MongoDbConfiguration - You're using deprecated configuration options for MongoDB. Please use mongodb_uri.
2015-07-01 11:25:42,738 INFO : org.graylog2.configuration.MongoDbConfiguration - Suggested value for mongodb_uri = mongodb://xxxxxxxxx/graylog2
2015-07-01 11:25:42,890 INFO : org.graylog2.bootstrap.CmdLineTool - Running with JVM arguments: -Djava.library.path=./bin/../lib/sigar -Xms256m -Xmx512m -XX:NewRatio=1 -XX:PermSize=128m -XX:MaxPermSize=256m -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow
2015-07-01 11:25:51,665 INFO : org.graylog2.shared.buffers.InputBufferImpl - Message journal is enabled.
2015-07-01 11:25:53,148 INFO : kafka.log.LogManager - Found clean shutdown file. Skipping recovery for all logs in data directory '/opt/graylog-1.1.3/data/journal'
2015-07-01 11:25:53,151 INFO : kafka.log.LogManager - Loading log 'messagejournal-0'
2015-07-01 11:25:53,411 INFO : org.graylog2.shared.journal.KafkaJournal - Initialized Kafka based journal at data/journal
2015-07-01 11:25:53,421 INFO : org.graylog2.shared.buffers.InputBufferImpl - Initialized InputBufferImpl with ring size <65536> and wait strategy <SleepingWaitStrategy>, running 1 parallel message handlers.
2015-07-01 11:25:54,309 INFO : org.graylog2.plugin.system.NodeId - Node ID: dcf330d6-9172-43de-9738-cd68fd17d57b
2015-07-01 11:25:55,333 INFO : org.elasticsearch.node - [graylog2-server] version[1.5.2], pid[13038], build[62ff986/2015-04-27T09:21:06Z]
2015-07-01 11:25:55,334 INFO : org.elasticsearch.node - [graylog2-server] initializing ...
2015-07-01 11:25:55,370 INFO : org.elasticsearch.plugins - [graylog2-server] loaded [graylog2-monitor], sites []
2015-07-01 11:26:02,081 INFO : org.elasticsearch.node - [graylog2-server] initialized
2015-07-01 11:26:02,128 INFO : org.graylog2.shared.buffers.ProcessBuffer - Initialized ProcessBuffer with ring size <65536> and wait strategy <SleepingWaitStrategy>.
2015-07-01 11:26:07,652 INFO : org.graylog2.bindings.providers.RulesEngineProvider - No static rules file loaded.
2015-07-01 11:26:07,843 INFO : org.graylog2.buffers.OutputBuffer - Initialized OutputBuffer with ring size <65536> and wait strategy <SleepingWaitStrategy>.
2015-07-01 11:26:08,524 INFO : org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 5.1.3.Final
2015-07-01 11:26:09,866 INFO : org.graylog2.bootstrap.ServerBootstrap - Graylog server 1.1.3 (611c8b2) starting up. (JRE: Oracle Corporation 1.7.0_80 on Linux 3.8.0-29-generic)
2015-07-01 11:26:10,021 INFO : org.graylog2.shared.initializers.PeriodicalsService - Starting 21 periodicals ...
2015-07-01 11:26:10,030 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.ThroughputCounterManagerThread] periodical in [0s], polling every [1s].
2015-07-01 11:26:10,051 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.ThroughputCalculator] periodical in [0s], polling every [1s].
2015-07-01 11:26:10,039 INFO : org.elasticsearch.node - [graylog2-server] starting ...
2015-07-01 11:26:10,056 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.AlertScannerThread] periodical in [10s], polling every [60s].
2015-07-01 11:26:10,058 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.BatchedElasticSearchOutputFlushThread] periodical in [0s], polling every [1s].
2015-07-01 11:26:10,058 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.ClusterHealthCheckThread] periodical in [0s], polling every [20s].
2015-07-01 11:26:10,059 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.ContentPackLoaderPeriodical] periodical, running forever.
2015-07-01 11:26:10,071 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.DeadLetterThread] periodical, running forever.
2015-07-01 11:26:10,081 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.GarbageCollectionWarningThread] periodical, running forever.
2015-07-01 11:26:10,082 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.IndexerClusterCheckerThread] periodical in [0s], polling every [30s].
2015-07-01 11:26:10,092 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.IndexRetentionThread] periodical in [0s], polling every [300s].
2015-07-01 11:26:10,093 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.IndexRotationThread] periodical in [0s], polling every [10s].
2015-07-01 11:26:10,094 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.NodePingThread] periodical in [0s], polling every [1s].
2015-07-01 11:26:10,095 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.StreamThroughputCounterManagerThread] periodical in [0s], polling every [1s].
2015-07-01 11:26:10,095 INFO : org.graylog2.periodical.IndexRetentionThread - Elasticsearch cluster not available, skipping index retention checks.
2015-07-01 11:26:10,104 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.VersionCheckThread] periodical in [0s], polling every [1800s].
2015-07-01 11:26:10,105 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.ThrottleStateUpdaterThread] periodical in [1s], polling every [1s].
2015-07-01 11:26:10,107 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.events.ClusterEventPeriodical] periodical in [0s], polling every [1s].
2015-07-01 11:26:10,108 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.events.ClusterEventCleanupPeriodical] periodical in [0s], polling every [300s].
2015-07-01 11:26:10,113 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.ClusterIdGeneratorPeriodical] periodical, running forever.
2015-07-01 11:26:10,114 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.PurgeExpiredCollectorsThread] periodical in [0s], polling every [3600s].
2015-07-01 11:26:10,133 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog.plugins.usagestatistics.UsageStatsNodePeriodical] periodical in [300s], polling every [21600s].
2015-07-01 11:26:10,134 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog.plugins.usagestatistics.UsageStatsClusterPeriodical] periodical in [300s], polling every [21600s].
2015-07-01 11:26:10,310 INFO : org.graylog2.periodical.IndexerClusterCheckerThread - Indexer not fully initialized yet. Skipping periodic cluster check.
2015-07-01 11:26:11,026 INFO : org.elasticsearch.transport - [graylog2-server] bound_address {inet[/xxx.xxx.xxx.xxx:9350]}, publish_address {inet[sc-fe/xxx.xxx.xxx.xxx:9350]}
2015-07-01 11:26:11,185 INFO : org.elasticsearch.discovery - [graylog2-server] graylog/T9h363YcT2KShSROE-lSXA
2015-07-01 11:26:11,684 INFO : org.reflections.Reflections - Reflections took 1318 ms to scan 1 urls, producing 2 keys and 2 values 
2015-07-01 11:26:14,186 WARN : org.elasticsearch.discovery - [graylog2-server] waited for 3s and no initial state was set by the discovery
2015-07-01 11:26:14,189 INFO : org.elasticsearch.node - [graylog2-server] started
2015-07-01 11:26:14,526 INFO : org.elasticsearch.cluster.service - [graylog2-server] detected_master [Energizer][a7cIAm0USNK93AJrJjjglQ][sc-fe][inet[/xxx.xxx.xxx.xxx:9300]], added {[Energizer][a7cIAm0USNK93AJrJjjglQ][sc-fe][inet[/xxx.xxx.xxx.xxx:9300]],}, reason: zen-disco-receive(from master [[Energizer][a7cIAm0USNK93AJrJjjglQ][sc-fe][inet[/xxx.xxx.xxx.xxx:9300]]])
2015-07-01 11:26:20,126 WARN : org.graylog2.periodical.IndexRotationThread - Deflector is pointing to [graylog_2], not the newest one: [graylog_3]. Re-pointing.
2015-07-01 11:26:28,698 INFO : org.graylog2.shared.initializers.RestApiService - Adding security context factory: <org.graylog2.security.ShiroSecurityContextFactory@59589a86>
2015-07-01 11:26:28,758 INFO : org.graylog2.shared.initializers.RestApiService - Started REST API at <http://xxx.xxx.xxx.xxx:12900/>
2015-07-01 11:26:28,759 INFO : org.graylog2.shared.initializers.ServiceManagerListener - Services are healthy
2015-07-01 11:26:28,761 INFO : org.graylog2.bootstrap.ServerBootstrap - Services started, startup times in ms: {GroovyShellSetupService [RUNNING]=5, InputSetupService [RUNNING]=17, OutputSetupService [RUNNING]=28, BufferSynchronizerService [RUNNING]=30, MetricsReporterService [RUNNING]=32, KafkaJournal [RUNNING]=33, JournalReader [RUNNING]=37, PeriodicalsService [RUNNING]=124, DashboardRegistryService [RUNNING]=219, IndexerSetupService [RUNNING]=4559, RestApiService [RUNNING]=18739}
2015-07-01 11:26:28,761 INFO : org.graylog2.shared.initializers.InputSetupService - Triggering launching persisted inputs, node transitioned from Uninitialized [LB:DEAD] to Running [LB:ALIVE]
2015-07-01 11:26:28,766 INFO : org.graylog2.bootstrap.ServerBootstrap - Graylog server up and running.
2015-07-01 11:26:28,883 INFO : org.graylog2.shared.inputs.InputStateListener - Input [Syslog UDP/551abd2fe4b00ef0e387a54f] is now STARTING
2015-07-01 11:26:28,885 INFO : org.graylog2.shared.inputs.InputStateListener - Input [Syslog UDP/54ec5557e4b0df50f2d608a7] is now STARTING
2015-07-01 11:26:28,887 INFO : org.graylog2.shared.inputs.InputStateListener - Input [GELF UDP/54ec5569e4b0df50f2d608d0] is now STARTING
2015-07-01 11:26:28,889 INFO : org.graylog2.shared.inputs.InputStateListener - Input [Syslog UDP/54ec5557e4b0df50f2d608a6] is now STARTING
2015-07-01 11:26:28,920 WARN : org.graylog2.plugin.inputs.transports.NettyTransport - receiveBufferSize (SO_RCVBUF) for input org.graylog2.inputs.syslog.udp.SyslogUDPInput@4183b1f5 should be 1048576 but is 65536.
2015-07-01 11:26:28,922 WARN : org.graylog2.plugin.inputs.transports.NettyTransport - receiveBufferSize (SO_RCVBUF) for input org.graylog2.inputs.syslog.udp.SyslogUDPInput@4950b1f5 should be 1048576 but is 65536.
2015-07-01 11:26:28,926 INFO : org.graylog2.shared.inputs.InputStateListener - Input [Syslog UDP/551abd2fe4b00ef0e387a54f] is now RUNNING
2015-07-01 11:26:28,923 WARN : org.graylog2.plugin.inputs.transports.NettyTransport - receiveBufferSize (SO_RCVBUF) for input org.graylog2.inputs.syslog.udp.SyslogUDPInput@4950b1f4 should be 1048576 but is 65536.
2015-07-01 11:26:28,920 WARN : org.graylog2.plugin.inputs.transports.NettyTransport - receiveBufferSize (SO_RCVBUF) for input org.graylog2.inputs.gelf.udp.GELFUDPInput@af36506c should be 1048576 but is 65536.
2015-07-01 11:26:28,938 INFO : org.graylog2.shared.inputs.InputStateListener - Input [Syslog UDP/54ec5557e4b0df50f2d608a7] is now RUNNING
2015-07-01 11:26:28,942 INFO : org.graylog2.shared.inputs.InputStateListener - Input [Syslog UDP/54ec5557e4b0df50f2d608a6] is now RUNNING
2015-07-01 11:26:28,944 INFO : org.graylog2.shared.inputs.InputStateListener - Input [GELF UDP/54ec5569e4b0df50f2d608d0] is now RUNNING
2015-07-01 11:26:33,069 INFO : org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Enabling session validation scheduler...
```

I suspect some race conditions.

If you guys need more info - let me know.

**Comment by joschi** [comment] 2015-07-01 10:12
Duplicate of #779.

**Closed by joschi** 2015-07-01 10:12 UTC
