### ISSUE TITLE
Aggregation Group-By does not allow use of beats fields

### ISSUE THREAD

**Issue by tellistone** [Graylog2/graylog2-server#12430] opened 2022-04-08 11:20 UTC
Very strange. Graylog 4.2.7, ES 7.10, fresh install plus beats input and beats.

I can use Beats fields in the Metric, but not in the Group By area.

If I set any Beats field in the "Field" area of Group By, and hit apply, Graylog returns to the search window but the changes don't take effect on the aggregation.

All my logs have a Beats source, and this all have the Beats fields.

Example:

Before -

![image](https://user-images.githubusercontent.com/85873295/162425670-56b48aeb-8794-452d-a47b-9e736dd46e02.png)

Edit Aggregation -

![image](https://user-images.githubusercontent.com/85873295/162425811-939d9bd0-9212-407e-8c3c-58ae3ca1df4e.png)

![image](https://user-images.githubusercontent.com/85873295/162425706-66d1ab85-057f-40e6-bb5f-74391928fd2e.png)

- After I hit apply, no change to the aggregation:

![image](https://user-images.githubusercontent.com/85873295/162425774-0b694128-530c-4480-8f43-da43d3881466.png)

This only seems to affect the Beats fields. It seems to affect all of them.

**Comment by tellistone** [comment] 2022-04-08 11:22
If I delete the group-by

Add a new group-by

select a Beats field.

Red text saying a value in the "field is Required" doesn't go away.

![image](https://user-images.githubusercontent.com/85873295/162426076-239c68fd-030e-4424-a353-1b0dd0f649f2.png)

**Comment by timukas** [comment] 2022-04-13 12:31
I had the same issue. Was struggling for hours and i think found the fix.

In my setup i have Apache in front of Graylog.
I have following header setting

`RequestHeader set X-Graylog-Server-URL "https://10.10.10.10/"`

If i access Graylog with hostname https://myhost.is.here/ in the browser, then i get red "Field is required" error.

And i came out with following:

If you have X-Graylog-Server-URL set as IP address, then access Graylog (through Apache) as IP address.
If you have X-Graylog-Server-URL set to hostname, then access Graylog with hostname.

Then it fixes the issue.

**Comment by tellistone** [comment] 2022-04-22 08:56
I knew I wasn't imagining this, its happening again on my lab (4.2.7)

**Comment by riskersen** [comment] 2022-05-20 10:02
I'm also affected with a newly created string field from the pipeline.

Did you find anything in the mean time?

**Comment by tellistone** [comment] 2022-05-21 18:12
@dennisoelkers reproduced this on May 2nd

"was able to reproduce it in 4.2.x, actually. you should use a field for an aggregation and then switch to a stream that does not have that field. when you reopen the widget, the field input is empty"

**Comment by dennisoelkers** [comment] 2022-05-23 11:57
@riskersen: The issue is fixed in `4.3` though, which will be released soon.

**Closed by dennisoelkers** 2022-05-23 11:57 UTC
Labels: bug, triaged, search
