### ISSUE TITLE
Elasticsearch Aggregate Error

### ISSUE THREAD

**Issue by GTownson** [Graylog2/graylog2-server#4848] opened 2018-06-18 11:16 UTC
Graylog attempts to run an Elasticsearch aggregation search, which throws an error then Graylog stops processing messages for about five minutes and then resumes.

## Expected Behavior
Graylog and Elasticsearch should be able to handle aggregations without significant pauses in message processing.

## Current Behavior
https://pastebin.com/qsCgy9Yk
 I get the aggregate error shown in the link above, then Graylog will stop processing messages for about five minutes, which causes a backlog in the journal, then Graylog starts processing again and clears out the backlog

## Context
Graylog stops processing messages for around five minutes, we have seen it take longer to resume processing messages which means in some cases we are losing logs.
## Your Environment

* Graylog Version: 2.4.4
* Elasticsearch Version: 5.6.9
* MongoDB Version: 2.6.10
* Operating System: Ubutnu 16.04  LTS

**Comment by GTownson** [comment] 2018-06-18 14:13
I have asked the guys on the Elasticearch forum what is causing this issue and they have provided some responses, that seem to come closer to workoing out what's going on here. Below is the link to the forum post.

https://discuss.elastic.co/t/elasticsearch-aggregation-error/135946/2

**Comment by GTownson** [comment] 2018-06-22 11:08
This bug appears to be associated with `https://github.com/Graylog2/graylog2-server/issues/4847`

**Comment by dennisoelkers** [comment] 2020-11-05 14:29
Closing this. The issue is now more than two years old, has been reported only a single time and is not reproducible. @GTownson, if you still encounter this with a recent Graylog version, please reopen this issue with new information.

**Closed by dennisoelkers** 2020-11-05 14:29 UTC
Labels: bug, elasticsearch, search, to-verify
