### ISSUE TITLE
When creating event definitions, message about leaving the page is shown.

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#18771] opened 2024-03-25 11:27 UTC
## Current Behavior

When trying to create an event definition, in the last step of the summary when clicking on "Create event definition", `window.confirm` is being called as if the user would be leaving the (dirty) page.

![event-definition-window-confirm](https://github.com/Graylog2/graylog2-server/assets/41929/78128af0-0644-4626-9d5b-3926790e0ad8)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Java Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by danotorrey** [comment] 2024-04-01 21:42
@dennisoelkers I am not able to reproduce this so far. Are you still seeing this issue? 

When creating an Event Definition in the General perspective and attempting to save, the save is successful (even after previously triggering validation errors and resolving them).

**Comment by rich-graylog** [comment] 2024-04-02 17:29
@danotorrey I just found a duplicate issue with another video showing recreation steps: https://github.com/Graylog2/graylog2-server/issues/18481

**Closed** 2024-04-03 22:05 UTC
Labels: bug, triaged, blocker, secdev-cycle2
