### ISSUE TITLE
Graylog 3.x does not work with Elasticsearch 7.x!

### ISSUE THREAD

**Issue by dinuta** [Graylog2/graylog2-server#6912] opened 2019-12-02 11:26 UTC
Graylog 3.x does not work with Elasticsearch 7.x!

**Comment by dinuta** [comment] 2019-12-02 11:27
If does not work on 7.x then you push people use Kibana.

**Comment by jalogisch** [comment] 2019-12-02 11:31
Dear @dinuta 

yes - that is a known limitation an and this is a duplicate of https://github.com/Graylog2/graylog2-server/issues/5933

In addition this is documented, what would be the feature/reason to have that support in Graylog? That will move you away from Graylog because this is the essential feature you need to have available?

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Closed by jalogisch** 2019-12-02 11:31 UTC

**Comment by dinuta** [comment] 2019-12-02 11:47
Hi @jalogisch 

Well i saw some articles where the guys were using graylog and it seems very interesting for me.
I am developing a microservice stack where the log architecture is:

microservice => fluentd => elasticsearch => kibana

And i want also to try Graylog because i am not 100% happy with kibana web interface, and want also to compare some things by trying them.

No special requirements from my side.

**Comment by jalogisch** [comment] 2019-12-02 12:58
ok, but Graylog is not only a Kibana replacement. In addition you can work only with data that is ingest via Graylog into the storage.

But you have no special requirement for Elasticsearch 7 ... thx.

**Comment by mfrahm2** [comment] 2020-01-31 17:23
Hi @jalogisch ,
our company has the following requirement for elasticsearch 7:
https://www.elastic.co/guide/en/elasticsearch/reference/current/date_nanos.html

Elasticsearch 6 has only a microsecond time resolution, so many log messages have the same time stamp and are sorted in a random order and not in the order they arrived. This would be solved with a nanosecond time resolution.

So are you planning to support Elasticsearch 7?

**Comment by kroepke** [comment] 2020-02-03 11:30
There are substantial compatibility issues with supporting multiple versions of Elasticsearch concurrently.

@mfrahm2 Even worse the nanosecond resolution support uses an entirely different field type, which makes it incompatible with previous indices using the 'normal' timestamp type.
What's more, there is a severe limitation, which renders the entire point moot,anyway:
```
Aggregations are still on millisecond resolution, even when using a date_nanos field.
```
via https://www.elastic.co/guide/en/elasticsearch/reference/current/date_nanos.html#date-nanos-limitations
