### ISSUE TITLE
Inputs not starting because of missing fields

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#1211] opened 2015-06-03 15:11 UTC
For the current state of the master branch, the server refuses to start inputs which are missing certain fields (like tls_enable for GELF TCP Inputs or even global, boolean fields like throttling_allowed) which were not present during input creation. 

This might make sense from the perspective of consistency, but it also means that installations which have been upgraded will refuse to start those inputs after the upgrade. We need some kind of soft migration for this to prevent surprises.

![screen shot 2015-06-03 at 17 09 45](https://cloud.githubusercontent.com/assets/41929/7963548/87bd8ab8-0a13-11e5-99a5-c7771c76ae71.png)

**Comment by kroepke** [comment] 2015-06-05 11:26
Is this in 1.1 as well? I guess it is, but I would like to make sure.

**Comment by dennisoelkers** [comment] 2015-06-08 13:24
No, it isn't, happens only on master for me.

**Comment by bernd** [comment] 2015-08-05 06:40
@dennisoelkers Is this still an issue?

**Comment by bernd** [comment] 2015-08-11 10:25
Closing this because I am unable to reproduce it on master.

**Closed by bernd** 2015-08-11 10:25 UTC
Labels: bug, P3, S3 - High
