### ISSUE TITLE
Importing content pack fails

### ISSUE THREAD

**Issue by einot** [Graylog2/graylog2-server#1872] opened 2016-03-01 08:22 UTC
### Problem description
When trying to import a content pack nothing happens besides the page reload. Javascript console shows these messages:

```
Form contains enctype=multipart/form-data, but does not contain method=post.  Submitting normally with method=GET and no enctype instead. contentpacks
Form contains a file input, but is missing method=POST and enctype=multipart/form-data on the form.  The file will not be sent. contentpacks
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create plugin.org.graylog.plugins.map-widget.MapWidget.ddd103b678992ca86b75.js:9906:415
```

### Steps to reproduce the problem

1. Import content pack

### Environment

* Graylog Version: alpha 4
* Elasticsearch Version: 2.2.0
* MongoDB Version: 2.6.11
* Operating System: RHEL7

**Comment by dennisoelkers** [comment] 2016-03-10 16:37
Thanks for reporting this. Which browser are you using? Which content pack are you trying to import?

**Comment by edmundoa** [comment] 2016-03-23 15:37
Hi @einot,

Any updates on this? :)

**Comment by bernd** [comment] 2016-03-30 09:40
@einot I am unable to reproduce this with 2.0.0-beta.1.

I am closing this issue now, please re-open if you still have that problem. In that case please let us know which content pack you are trying to import. Thank you!

**Closed by bernd** 2016-03-30 09:40 UTC
Labels: bug, P1, S3
