### ISSUE TITLE
app reloads on search

### ISSUE THREAD

**Issue by colmaengus** [Graylog2/graylog2-server#2488] opened 2016-07-14 21:34 UTC
### Problem description
app reloads when you click search 

### Steps to reproduce the problem

1. Navigate to Search tab in application
2. Click the search icon and the whole application reloads rather than using XHR to perform search

### Environment

* Graylog Version: 2.0.3-2
* Elasticsearch Version: 
* MongoDB Version:
* Operating System: docker (brower on windows)
* Browser version: chrome 51.0.2704.103 m

**Comment by gruselglatz** [comment] 2016-07-20 09:11
We are facing the same problems since 2.0.3.
Searches now take 10+ seconds, this makes it really unusable.
It doesn't depends on the amount of messages, i only have 50 Messages in this setup so far.

Environment

Graylog Version: 2.0.3-2
Elasticsearch Version:
MongoDB Version:
Operating System: CentOS 7
Browser version: chrome 50.0.2661.102 m

When it's helpful i could provide you with our timeline-log.

**Comment by edmundoa** [comment] 2016-07-20 09:36
Hi @gruselglatz,

I wonder if there is some issue in your setup when loading the page takes more than 10 seconds. Did you check where the time is being used?

**Comment by gruselglatz** [comment] 2016-07-20 10:24
I used the Chrome TimelineTool and i could share it with you, if it would be helpful. I'm not a Webdeveloper, so i can't read much out of it.

**Comment by edmundoa** [comment] 2016-07-20 10:57
@gruselglatz That would be great. I'm not sure how helpful it would be, but at least I can take a look and see if I can extract something from it. Thank you!

**Comment by gruselglatz** [comment] 2016-07-20 11:07
@edmundoa I've sent it to you via Email. I hope you could see something.

**Comment by edmundoa** [comment] 2016-07-20 12:16
@gruselglatz email received, thank you!

**Comment by gruselglatz** [comment] 2016-07-20 12:23
UDAPTE: After i dismissed the "First Start Help" the Search now loads in half the time: 4-6 seconds.

`Scripts name` **Time**
`https://xxxx.local/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.124facd49c87779f691b.js`   **1,27s**

`https://xxxx.local/plugin/org.graylog.plugins.map.MapWidgetPlugin/plugin.org.graylog.plugins.map.MapWidgetPlugin.3a6e86e960b80407f74e.js`  **1,37s**

`https://xxxx.local/plugin/org.graylog.plugins.collector.CollectorPlugin/plugin.org.graylog.plugins.collector.CollectorPlugin.74e8dfee2c1d6b11bc87.js` **0,5s**

`https://graylogtest.atliwest.local/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.124facd49c87779f691b.js` **0,5s AND 0,4s**

`https://xxxx.local/plugin/org.graylog.plugins.enterprise_integration.EnterpriseIntegrationPlugin/plugin.org.graylog.plugins.enterprise_integration.EnterpriseIntegrationPlugin.7f1e11d52a66d206799c.js` **0,5s**

`https://xxxx.local/4.4.f2a88026f0d0e7332f17.js` **1,31s**

**Comment by dennisoelkers** [comment] 2016-07-20 14:00
Can you see what takes so long? Connection buildup, downloading JS, interpreting, running?

**Comment by gruselglatz** [comment] 2016-07-20 14:55
@dennisoelkers i have sent three of my timeline logs to @edmundoa maybe he could send it to you for further investigations. I've listed the names of the scripts that were on top of the "fire-graph", where i can see what time is used for Connection buildup, downloading JS, interpreting, running?

**Comment by hc4** [comment] 2016-07-28 17:29
I found Interesting thing.
In search mode, if you click ![image](https://cloud.githubusercontent.com/assets/17475270/17222610/e538443c-5501-11e6-92d0-607da7f1e28a.png) tab - view refreshes very fast, but if you click ![image](https://cloud.githubusercontent.com/assets/17475270/17222596/d4552176-5501-11e6-87ac-fdb367f60b8a.png) button - it will reload whole app and take 5 seconds.

**Comment by gruselglatz** [comment] 2016-07-29 06:33
@hc4 i can confirm that on 2.0.3 also.

It seems when you hit only the "Search"-tab none of the exhausting functions get called. only the "PiplineProcessorPlugin"-function.

So after the Mouse-Click-Event it takes 336ms for scripts to run and 1,9ms for rendering the new messages. Compare that to the other values above.

**Comment by edmundoa** [comment] 2016-07-29 07:43
That is an expected behaviour since 2.0.x, @hc4 and @gruselglatz. The reason for this is mostly legacy now, but we still need to do some clean up to use the new search stores to fetch data instead of submitting the form as it was done in the past versions.

**Comment by bernd** [comment] 2016-09-12 10:29
This has been fixed in https://github.com/Graylog2/graylog2-server/pull/2798 and will be included in the upcoming 2.1.1 release.

**Closed by bernd** 2016-09-12 10:29 UTC
Labels: improvement, web
