### ISSUE TITLE
systemctl restart graylog-server.service starts ALL inputs, even if they were stopped

### ISSUE THREAD

**Issue by NEO-AMiGA** [Graylog2/graylog2-server#12028] opened 2022-01-24 18:50 UTC
When doing a 'systemctl restart graylog-server.service' all inputs I have are started, even ones I have manually stopped. 

## Expected Behavior
Only start inputs that were running when 'restart' were initiated.

## Current Behavior
All inputs, no matter their status on restart, are started. 

## Possible Solution
Store state of inputs before stop and read that back on start

## Steps to Reproduce (for bugs)
1. Disable a few inputs. 
2. systemctl restart graylog-server.service
3. Look at the inputs and bite your lip when all of them starts

## Context
I'm new to graylog and have a ton of different inputs I don't want running. So super annoying when everyting fires up after a restart. 

## Your Environment

* Graylog Version: 4.2.5-1
* Java Version: 
java-1.8.0-openjdk-headless.x86_64                 1:1.8.0.312.b07-2.el8_5 
javapackages-filesystem.noarch                     5.3.0-1.module_el8.0.0+11+5b8c10bd 

* Elasticsearch Version: elasticsearch-oss.x86_64                           7.10.2-1  
* MongoDB Version:  4.2.17-1.el8   
* Operating System: CentOS Linux release 8.5.2111
* Browser version: Firefox 96.0.1 (64-bit)

**Comment by dennisoelkers** [comment] 2022-01-25 08:59
Hey @NEO-AMiGA,

thanks for reporting this! We already have an issue for it though, so I am closing this one. Feel free to reopen if you feel that it's not matching the issue you reported.

Duplicate of #967.

**Closed by dennisoelkers** 2022-01-25 08:59 UTC
Labels: bug
