### ISSUE TITLE
Pipeline Rule allows invocation of function "set_field()" without setting a value for the new field.

### ISSUE THREAD

**Issue by willman42** [Graylog2/graylog2-server#6696] opened 2019-10-30 18:29 UTC
The documentation for Pipeline Rule function "set_field()" states that the second argument "value" is a required parameter for the function. However, Graylog allows me to invoke the function without specifying that argument.

## Expected Behavior
When writing the Pipeline Rule, an error message should appear and Graylog should forbid the user from saving the Rule until the issue is resolved, as is the behavior for other functions if not invoked correctly.

## Current Behavior
I am able to save the Pipeline Rule without supplying an argument for the "value" parameter. However the Rule does not appear to work, as the new field that is supposed to be created does not show up in logs.

## Possible Solution
Force the user to fix the error in the Pipeline Rule by supplying an argument for the "value" parameter in the "set_field()" function.

## Steps to Reproduce (for bugs)
1. Create Pipeline Rule like the following example:
```
rule "test set_field()"
when
   true
then
   set_field("foo");
end
```
2. Save the Rule, connect it to a Stream receiving logs.
3. Go to Stream, generate new logs.
4. Note that new logs do not have the field "foo" at all.

## Context
Since Pipeline Rules have no "elif" or "else" clauses, this makes setting binary fields useless, as instead you can just test for the existence of the field itself. Take the a modified version of the above Pipeline Rule for example:
```
rule "If true, create field foo and set to true"
when
   // List of conditions:
   $message.condition1 == "x"
then
   set_field("foo", true)
end
```

If want to avoid acting upon all logs that don't match the supplied condition, there's no reason for me to write a separate Pipeline Rule to set field "foo" to false, as it is implied by not matching against the above Rule.

Therefore, why must I set "foo" to any value at all? If the supplied conditions match, "foo" will equal Boolean True, and if conditions don't match, the field won't be set at all. So it would be more efficient to simply test for the existence of the field "foo", as its mere existence implies its value equal to Boolean True.

Honestly, instead of forcing the user to set a value for the new field in the set_field() function, why not make it officially optional? Until Pipeline Rules can extend beyond strictly "if/then" scenarios and include "elif" and "else" clauses, there is no reason for setting Boolean values at all, as demonstrated above.

In addition, currently the only way to test the existence of a field is by employing the "is_null()" and "is_not_null()" functions, which is rather indirect. Could a new function be written strictly for checking the existence of a field, like the "_exists_" search term in Graylog Search?

## Your Environment

* Graylog Version: 3.0.2
* Elasticsearch Version: 6.x
* MongoDB Version: 4.0.8
* Operating System: Oracle Linux 7.5

**Comment by kroepke** [comment] 2019-11-04 11:20
Thanks for your report!

The cause was a missing check in the parser. The rule itself would fail, because the parameter would be missing at runtime, but the parser never threw an error for it.

We'll include the fix in the upcoming 3.1.3 release.

**Comment by kroepke** [comment] 2019-11-04 11:28
The reason that the field requires a value is that we cannot store it without one.
`set_field` never allowed the value to be missing, it was just that the parser didn't complain where it should've.
In your use case the correct way of doing so is to set the field to a value of your choosing, because due to the way Elasticsearch handles field mapping one needs to make sure the types are compatible.
Simply defaulting to `true` on Graylog's end could greatly confuse users and it offers little benefit over making the value explicit.

There already is a function to check the existence of a field, regardless of the value:
`has_field(field, [message]) : Boolean`

Hope that helps!

**Comment by bernd** [comment] 2019-11-06 09:35
Fixed in https://github.com/Graylog2/graylog2-server/pull/6716.

**Closed by bernd** 2019-11-06 09:35 UTC
Labels: #S, bug, processing, triaged
