### ISSUE TITLE
Adjustments off Sigma rules dont take affect

### ISSUE THREAD

**Issue by rkmbaxed** [Graylog2/graylog2-server#13956] opened 2022-11-14 12:23 UTC
Adjustment off Sigma rules dont take affect until the rule was disabled and enabled again

## Expected Behavior
I expected it to work, if a rule is enabled, right after the rules are adjusted. (Same as pipline rules worked)

## Current Behavior
The adjustment of a Sigma rule worked only after a disable and enable the rule again.

## Steps to Reproduce (for bugs)
1. Create a Sigma rule
2. Enable the Sigma rule
3. Adjust the Sigma rule

## Your Environment

* Graylog Version: 5.0 beta 4 (Graylog 5.0.0-beta.4+2d0b0a6)
* Java Version: 17
* Opensearch Version: 2.3
* MongoDB Version: 6.0
* Operating System: SLES15
* Browser version: Edge / Chrome / Firefox current version

**Comment by danotorrey** [comment] 2022-11-15 13:01
@rkmbaxed Thanks for the report. I tested, but could not reproduce this. To test for it, I created a rule, enabled it, confirmed that it runs, then edited it once again (edited a `detection > selection` field name). The update to the rule was effective when the rule ran without needing an enable/disable.

Can you please let me know if there is a specific step that was done in your case to trigger the issue?

**Comment by rkmbaxed** [comment] 2022-11-15 17:31
I edited this rule at 18:12 PM today and last update shows still the date from yesterday. The rule was already activated when I do some edits.

![image](https://user-images.githubusercontent.com/33449202/201985087-8b638db0-2a53-484f-bbaa-5a6b74f579ba.png)

After disable the rule it shows the current time/date but not the time/date of adjustment of the rule.

![image](https://user-images.githubusercontent.com/33449202/201985423-b556d5f2-74bb-465c-ad37-0a4977a51605.png)

After enable it again the time/date changes to the current time/date again.

![image](https://user-images.githubusercontent.com/33449202/201985752-4d03c436-b380-4102-b1c0-2e0017c2510b.png)

I have to recheck if the rule adjustment worked and only the timestamps are not shown correctly.

**Comment by danotorrey** [comment] 2022-11-15 19:44
Thank you @rkmbaxed. This issue has been fixed and will be included in tomorrow's `5.0.0-beta.5` release. Please let me know if you experience any more trouble once you upgrade to that release. 

Thank you again for testing out the new Sigma Rules feature.

**Closed** 2022-11-15 19:46 UTC
Labels: bug, triaged, secdev-cycle6
