### ISSUE TITLE
Cannot search while RebuildIndexRangesJob is running (1.1-beta1)

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-server#1167] opened 2015-05-22 07:06 UTC
All searches report 0 results while the RebuildIndexRangesJob is running - this is something that used to work correctly in 1.0 ...

**Comment by kroepke** [comment] 2015-05-22 10:32
Is there any kind of exception in the logs or as the response to the search?

There should be no relevant changes to the code, so I'm wondering what's going on :)

**Comment by kroepke** [comment] 2015-05-26 16:04
@henrikjohansen do you have any input in the issue?
Unfortunately I cannot reproduce it locally.

**Comment by henrikjohansen** [comment] 2015-05-26 18:06
@kroepke sorry - I've been busy the last couple of days ... is there a way to trigger a RebuildIndexRangesJob manually so that I can test again?

**Comment by kroepke** [comment] 2015-05-26 18:08
A deflector cycle will trigger it, after a short delay (20 secs or so)

Thanks!

**Comment by henrikjohansen** [comment] 2015-05-26 18:18
Well - once the background jobs starts running all searches return 0 results as reported ...
There are a few exceptions when searching during that time : 

http://pastie.org/private/vkm3dz0zi4elmlrnptq1q

**Comment by kroepke** [comment] 2015-05-26 18:19
Great, thank you!

I'll take a look tomorrow.

**Comment by kroepke** [comment] 2015-05-29 10:29
This looks like a problem with the indexranges not being up to date after retention has run.

There's an exception that we should catch and then ignore that index.

**Comment by henrikjohansen** [comment] 2015-06-04 11:18
We had this (or at least a similar issue) today ... this time Graylog reported that there were no background jobs running ?


![screen shot 2015-06-04 at 12 28 37](https://cloud.githubusercontent.com/assets/1473308/7982968/266528b2-0abc-11e5-99f4-3ef2e984dbc8.png)

![screen shot 2015-06-04 at 12 29 17](https://cloud.githubusercontent.com/assets/1473308/7982971/2af72fba-0abc-11e5-97c8-12ca822af7f9.png)


Exceptions can be found here : https://gist.github.com/henrikjohansen/a95e52c7a9a0a3e0adeb

**Comment by kroepke** [comment] 2015-06-05 15:07
The previous comment should be addressed in #1217

**Comment by joschi** [comment] 2015-08-26 10:13
This should be fixed with the index ranges refactoring. Please reopen the issue if the problem still exists in Graylog 1.2.0.

**Closed by joschi** 2015-08-26 10:13 UTC
Labels: bug, P2, S2 - Critical
