### ISSUE TITLE
from_input() pipeline rule function does not work

### ISSUE THREAD

**Issue by williamtrelawny** [Graylog2/graylog2-server#15534] opened 2023-05-18 14:02 UTC
The `from_input()` pipeline rule function does not work when given either the Input name or ID. A pipeline rule using this function in its `when` clause does not trigger when a log is received on the specified Input.

This issue occurs regardless of the placement of the Pipeline Processor in the Message Processors Configuration order.

## Expected Behavior
`from_input()` should cause pipeline rule to trigger if given an Input ID or Name.

## Steps to Reproduce (for bugs)
1. Send logs to Input named "InputA"
1. Attach the following pipeline rule to the Default Stream:
```
rule "test from_input()"
when from_input(name: "inputA")
then debug("space moose");
end
```
1. Observe in server.log that "space moose" does not appear.

## Context
This prevents the ability to act on messages based on the Input they are received.

## Your Environment

* Graylog Version: 5.0.7
* Java Version: bundled w/ Graylog
* Opensearch Version: 2.5.0
* MongoDB Version: 6.0.4
* Operating System: Debian 11.6
* Browser version: any

ref: HS-1557548817

**Comment by bernd** [comment] 2023-05-22 14:18
@williamtrelawny Is this the same issue as https://github.com/Graylog2/graylog-plugin-enterprise/issues/5198?

**Comment by williamtrelawny** [comment] 2023-05-25 15:07
@bernd it seems quite similar, except that issue is specifically about Forwarder Inputs which use a different database for name/id matching queries. This issue is about System Inputs that don't suffer from this database abstraction, which makes it seem like an issue with the `from_input()` function itself.

**Comment by patrickmann** [comment] 2023-08-01 06:13
@williamtrelawny I cannot reproduce the issue: neither on test system running 5.0.9 nor on current master. Are you still able to reproduce? If so, please share some more details, e.g. what type of system input, on-prem or cloud, ...

**Comment by patrickmann** [comment] 2023-08-09 10:48
Please re-open if you encounter this again. 
Closing for now as unable to reproduce.

**Closed by patrickmann** 2023-08-09 10:48 UTC
Labels: bug, triaged
