### ISSUE TITLE
Prevent webserver crashing due to too large CSV export

### ISSUE THREAD

**Issue by Ikke** [Graylog2/graylog2-server#1678] opened 2016-01-08 08:36 UTC
We notice the webserver crashes when people export large resultsets to csv.

In the application.log, we see a lot of errors similar to:

> 2016-01-07T14:41:18.079Z - [ERROR] - from org.graylog2.restclient.lib.ApiClient in pool-50-thread-1
API call Interrupted
java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1039) ~[na:1.8.0_66]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328) ~[na:1.8.0_66]
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277) ~[na:1.8.0_66]
        at com.ning.http.client.providers.netty.future.NettyResponseFuture.get(NettyResponseFuture.java:158) ~[com.ning.async-http-client-1.9.31.jar:na]
        at org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.executeOnAll(ApiClientImpl.java:608) ~[org.graylog2.graylog2-rest-client--1.3.0-1.3.0.jar:na]
        at controllers.api.MetricsController$PollingJob.run(MetricsController.java:117) [graylog-web-interface.graylog-web-interface-1.3.0.jar:1.3.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_66]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_66]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_66]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]

The webinterface switches from seeing the graylog server available or not. Sometimes it sees it as available, but then we get an API error in the webinterface.

Restarting graylog-web fixes this issue. We use graylog-web version 1.3.0.

**Comment by runningman84** [comment] 2016-01-20 12:14
The is a known problem :/
https://github.com/Graylog2/graylog2-web-interface/issues/1696

**Comment by bernd** [comment] 2016-02-11 13:28
Duplicate of https://github.com/Graylog2/graylog2-web-interface/issues/1696

**Closed by bernd** 2016-02-11 13:28 UTC
