### ISSUE TITLE
NPE at org.graylog2.indexer.indices.Indices.checkForReopened(Indices.java:379)

### ISSUE THREAD

**Issue by gitfrederic** [Graylog2/graylog2-server#2380] opened 2016-06-17 20:06 UTC
Running Graylog 2.0.2 and ElasticSearch 2.3.2, i.e.

``` shell
...
16:47:02.100 [main] INFO  org.elasticsearch.node - [graylog-6e4a7a0a-50fe-4e01-8af2-d12af71eea98] version[2.3.2], pid[5020], build[b9e4a6a/2016-04-21T16:03:47Z]
...
16:47:07.511 [main] INFO  org.graylog2.bootstrap.ServerBootstrap - Graylog server 2.0.2 (4da1379) starting up
16:47:07.511 [main] INFO  org.graylog2.bootstrap.ServerBootstrap - JRE: Oracle Corporation 1.8.0_72 on Linux 3.10.0-123.el7.x86_64
16:47:07.512 [main] INFO  org.graylog2.bootstrap.ServerBootstrap - Deployment: unknown
16:47:07.512 [main] INFO  org.graylog2.bootstrap.ServerBootstrap - OS: CentOS Linux 7 (Core) (centos)
16:47:07.512 [main] INFO  org.graylog2.bootstrap.ServerBootstrap - Arch: amd64
...
```

Found the following NPE in the Graylog Server log:

``` code
19:57:02.963 [rest-worker-7] ERROR org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
java.lang.NullPointerException
    at org.graylog2.indexer.indices.Indices.checkForReopened(Indices.java:379) ~[graylog.jar:?]
    at org.graylog2.indexer.indices.Indices.lambda$areReopened$1(Indices.java:374) ~[graylog.jar:?]
    at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321) ~[?:1.8.0_72]
    at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:1.8.0_72]
    at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540) ~[?:1.8.0_72]
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_72]
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_72]
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_72]
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_72]
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_72]
    at org.graylog2.indexer.indices.Indices.areReopened(Indices.java:373) ~[graylog.jar:?]
    at org.graylog2.rest.resources.system.indexer.IndexerOverviewResource.index(IndexerOverviewResource.java:82) ~[graylog.jar:?]
    at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
    at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
    at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[graylog.jar:?]
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog.jar:?]
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
    at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
    at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
    at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
    at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
    at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
    at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
    at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
```

**Comment by joschi** [comment] 2016-06-20 08:57
@gitfrederic Are there any other error message before the NPE you've posted?

**Comment by gitfrederic** [comment] 2016-06-21 21:58
Here's what's showing beforehand:

```shell
18:47:27.645 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
18:47:27.652 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
18:54:22.212 [elasticsearch[graylog-6e4a7a0a-50fe-4e01-8af2-d12af71eea98][scheduler][T#1]] WARN  org.elasticsearch.monitor.jvm - [graylog-6e4a7a0a-50fe-4e01-8af2-d12af71eea98] [gc][young][7622][49] duration [1.1s], collections [1]/[1.8s], total [1.1s]/[24.7s], memory [5.2gb]->[2.8gb]/[11.7gb], all_pools {[young] [2.3gb]->[2.4mb]/[2.4gb]}{[survivor] [72.3mb]->[25mb]/[307.1mb]}{[old] [2.8gb]->[2.8gb]/[9gb]}
19:08:53.806 [elasticsearch[graylog-6e4a7a0a-50fe-4e01-8af2-d12af71eea98][scheduler][T#1]] WARN  org.elasticsearch.monitor.jvm - [graylog-6e4a7a0a-50fe-4e01-8af2-d12af71eea98] [gc][young][8493][50] duration [1.2s], collections [1]/[1.3s], total [1.2s]/[25.9s], memory [5.2gb]->[2.8gb]/[11.7gb], all_pools {[young] [2.4gb]->[1.9mb]/[2.4gb]}{[survivor] [25mb]->[8.4mb]/[307.1mb]}{[old] [2.8gb]->[2.8gb]/[9gb]}
19:26:54.636 [elasticsearch[graylog-6e4a7a0a-50fe-4e01-8af2-d12af71eea98][scheduler][T#1]] WARN  org.elasticsearch.monitor.jvm - [graylog-6e4a7a0a-50fe-4e01-8af2-d12af71eea98] [gc][young][9573][51] duration [1.3s], collections [1]/[1.5s], total [1.3s]/[27.3s], memory [5.2gb]->[2.8gb]/[11.7gb], all_pools {[young] [2.3gb]->[893.6kb]/[2.4gb]}{[survivor] [8.4mb]->[6.1mb]/[307.1mb]}{[old] [2.8gb]->[2.8gb]/[9gb]}
19:42:52.874 [elasticsearch[graylog-6e4a7a0a-50fe-4e01-8af2-d12af71eea98][scheduler][T#1]] WARN  org.elasticsearch.monitor.jvm - [graylog-6e4a7a0a-50fe-4e01-8af2-d12af71eea98] [gc][young][10530][52] duration [1.1s], collections [1]/[2s], total [1.1s]/[28.4s], memory [5.2gb]->[2.8gb]/[11.7gb], all_pools {[young] [2.3gb]->[4.6mb]/[2.4gb]}{[survivor] [6.1mb]->[5.7mb]/[307.1mb]}{[old] [2.8gb]->[2.8gb]/[9gb]}
19:47:27.645 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
19:47:27.652 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
19:55:34.140 [elasticsearch[graylog-6e4a7a0a-50fe-4e01-8af2-d12af71eea98][scheduler][T#1]] WARN  org.elasticsearch.monitor.jvm - [graylog-6e4a7a0a-50fe-4e01-8af2-d12af71eea98] [gc][young][11290][53] duration [1.3s], collections [1]/[2s], total [1.3s]/[29.8s], memory [5.2gb]->[2.8gb]/[11.7gb], all_pools {[young] [2.3gb]->[778kb]/[2.4gb]}{[survivor] [5.7mb]->[6.9mb]/[307.1mb]}{[old] [2.8gb]->[2.8gb]/[9gb]}
19:57:02.963 [rest-worker-7] ERROR org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
java.lang.NullPointerException
...
```

Another example:

```shell
01:03:19.854 [scheduled-21] INFO  kafka.log.Log - Rolled new log segment for 'messagejournal-0' in 10 ms.
01:03:19.854 [scheduled-21] INFO  kafka.log.Log - Scheduling log segment 847484414 for log messagejournal-0 for deletion.
01:03:30.269 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
01:03:30.277 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
01:04:19.858 [kafka-journal-scheduler-0] INFO  kafka.log.Log - Deleting segment 847484414 from log messagejournal-0.
01:04:19.904 [kafka-journal-scheduler-0] INFO  kafka.log.OffsetIndex - Deleting index /app/graylog-server/data/journal/messagejournal-0/00000000000847484414.index.deleted
01:37:13.280 [rest-worker-0] ERROR org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
java.lang.NullPointerException
	at org.graylog2.indexer.indices.Indices.checkForReopened(Indices.java:379) ~[graylog.jar:?]
	at org.graylog2.indexer.indices.Indices.lambda$areReopened$1(Indices.java:374) ~[graylog.jar:?]
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321) ~[?:1.8.0_72]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:1.8.0_72]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540) ~[?:1.8.0_72]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_72]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_72]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_72]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_72]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_72]
	at org.graylog2.indexer.indices.Indices.areReopened(Indices.java:373) ~[graylog.jar:?]
	at org.graylog2.rest.resources.system.indexer.IndexerOverviewResource.index(IndexerOverviewResource.java:82) ~[graylog.jar:?]
	at sun.reflect.GeneratedMethodAccessor125.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
02:03:30.269 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
02:03:30.278 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
03:03:30.269 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Validating all active sessions...
03:03:30.276 [Thread-7] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Finished session validation.  No sessions were stopped.
...
```

**Comment by joschi** [comment] 2017-01-03 12:12
Duplicate of #2628.

**Closed by joschi** 2017-01-03 12:12 UTC
Labels: bug, triaged
