### ISSUE TITLE
Support pausing of alert handling

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-server#1015] opened 2015-03-02 12:52 UTC
When you're processing a backlog of journaled messages it would make sense to allow users to pause alert handling for a given node - currently you might receive alerts that are either too old (because the messages in the journal might be old) or because the node is processing messages at a much higher rate that normal (which could trigger the message count condition)

**Comment by dfch** [comment] 2015-03-03 12:14
@henrikjohansen do you intend to pause the alarm rules or the actions triggered by an AlarmCallback plugin. If you mean the latter then this is duplicate of #986 .

**Comment by henrikjohansen** [comment] 2015-03-03 12:20
My intend was to temporarily disable the alarm rules ... but both usecases make sense to me.

**Comment by dennisoelkers** [comment] 2017-01-06 14:01
Closed in favor of #3182.

**Closed by dennisoelkers** 2017-01-06 14:01 UTC
Labels: alerting, feature
