### ISSUE TITLE
graylog gets confused when LDAP contains groups with groupOfNames and posixGroup

### ISSUE THREAD

**Issue by 4nd3r** [Graylog2/graylog2-server#5199] opened 2018-10-11 13:35 UTC
in **LDAP Settings** I have:
- Group Search Base DN: `ou=groups,dc=example,dc=com`
- Group Search Pattern: `(objectClass=posixGroup)`

under **LDAP Group Mapping** all groups with objectClass=posixGroup show up.

I also have "special groups" in LDAP with objectClass=groupOfNames,

but those groups are not under `ou=groups,dc=example,dc=com`, so graylog shouldn't see them, right?

when I test with user, who IS NOT in "special group", everything is fine - graylog finds all correct groups:

```
TRACE [LdapConnector] Connecting to LDAP server ldap.example.com:636, binding with user null
TRACE [LdapConnector] Search LDAP for (&(objectClass=inetOrgPerson)(uid=user1)), starting at ou=users,dc=example,dc=com
TRACE [LdapConnector] LDAP search for groups: (objectClass=posixGroup) starting at ou=groups,dc=example,dc=com
---snip---
TRACE [LdapConnector] LDAP search found entry for DN uid=user1,ou=users,dc=example,dc=com with search filter (&(objectClass=inetOrgPerson)(uid=user1)):---snip---, groups=[group1, group2]}
```

when I test with user, WHO IS in "special group", this happens:

```
TRACE [LdapConnector] Connecting to LDAP server ldap.example.com:636, binding with user null
TRACE [LdapConnector] Search LDAP for (&(objectClass=inetOrgPerson)(uid=user2)), starting at ou=users,dc=example,dc=com
TRACE [LdapConnector] Looking up group cn=specialgroup,dc=example,dc=com
TRACE [LdapConnector] Resolved cn=specialgroup,dc=example,dc=com to group cn: specialgroup
```
for some reason, graylog doesn't respect Group Search Base DN and Pattern here.

## Your Environment

* Graylog Version: 2.4.6
* Elasticsearch Version: 5.6.12
* MongoDB Version: 3.2.11-2+deb9u1
* Operating System: Debian 9 with openjdk-8-jre version 8u181-b13-1~deb9u1
* LDAP server: OpenLDAP

**Comment by 4nd3r** [comment] 2018-10-11 13:48
users, who are in "special groups", also have operational attr `memberOf`.

**Comment by jalogisch** [comment] 2018-10-15 10:07
related to: https://github.com/Graylog2/graylog2-server/issues/1436

is this 'SpecialGroup' a group of groups? If yes, this is a duplicate of the above-linked issue. 

Should the user only be a member of the 'SpecialGroup' and then having problems to log in this is something that is related but not the same.

Can you please verify and write in what Groups the users are in and what is working and what not.

Thanks

**Comment by 4nd3r** [comment] 2018-10-15 21:48
> is this 'SpecialGroup' a group of groups? 

no. SpecialGroup contains DNs of users, not other groups.

> Should the user only be a member of the 'SpecialGroup' and then having problems to log in this is something that is related but not the same.

user, who can't log in, is member of both types of groups - groups defined using `objectClass: posixGroup` (members defined with `memberUid: user`) and SpecialGroup defined using `objectClass: groupOfNames` (members defined with `member: uid=user,ou=users,dc=example,dc=com`). membership of SpecialGroup can also be queried as operational attribute when OpenLDAP has memberOf overlay configured.

for example: 

```
# ldapsearch -x uid=user + | grep memberOf
memberOf: cn=specialgroup,dc=example,dc=com
```
(notice the `+` sign)

as much as I understand the code, the bad guy here is memberOf attribute. when it's present, other group lookups don't happen. if I remove user from SpecialGroup, then memberOf operational is not present and other group lookups with Group Search Base DN and Pattern happen.

**Comment by bernd** [comment] 2020-12-01 18:55
This should not be an issue anymore in Graylog 4.0. Please open a new issue if you still see the problem. Thank you!

**Closed by bernd** 2020-12-01 18:55 UTC
Labels: bug, ldap, triaged
