### ISSUE TITLE
Cannot Create Extractor

### ISSUE THREAD

**Issue by dramones-his** [Graylog2/graylog2-server#2227] opened 2016-05-12 16:55 UTC
### Problem description
Re-re-Deploying a new cluster for version new 2.0.1-2 from #2222 using the vmware ova templates.

When attempting to create an extractor a simple copy and replace k=v extractor greeted with the following message:

`
Could not create extractor Creating extractor failed: Error: cannot POST http://<masternode_ip>:12900/system/inputs/5734a1d5c8ac710825a84f16/extractors (404)
`

### Steps to reproduce the problem

1. Pick syslog (514) udp input
2. Create extractor
3. pick copy and replace 
4. drop down on input and pick message field
5.  copy, always try to extract, store as message, copy extraction, title k=v extractor, add key=value pairs as fields. 

### Environment

* Graylog Version: 2.0.1-2
* Vmware 6
* Browser version: Chrome 50.0.2661.94 m (64-bit)

**Comment by jalogisch** [comment] 2016-05-24 11:26
Hej @dramones-his tried to reproduce your error, but for me it was not possible. Did you follow the [Documentation](http://docs.graylog.org/en/2.0/pages/extractors.html#automatically-extract-all-key-value-pairs) about automatically extract of key=value ?

Will close this as i can't reproduce. If you still have the issue please add more information and maybe screenshots that shows what you did where.

thx
/jd

**Closed by jalogisch** 2016-05-24 11:26 UTC
Labels: to-verify

**Comment by galebepe** [comment] 2016-06-27 20:00
Have the same problem.  "creating extractor failed: Error: cannot POST http://10.0.3.120:12900...." 
...ideas? thanks!
