### ISSUE TITLE
import grok pattern should support common EOL types

### ISSUE THREAD

**Issue by jesusch** [Graylog2/graylog2-server#3183] opened 2016-12-12 13:09 UTC
## Expected Behavior
"System -> Grok patterns -> Import pattern file"
Grok import should support different EOL seperators

## Current Behavior
Only Unix LF seems to be supported

## Possible Solution
Support CR (Mac), CR LF (Windows), and LF (Unix)

## Your Environment
* Graylog Version: 2.1.2+50e449a

**Comment by joschi** [comment] 2016-12-12 13:22
Duplicate of #2465.

**Comment by jesusch** [comment] 2016-12-12 14:47
Hi @joschi ,

I disagree that this issue is a duplicate of #2465 
This issue is not about multiline extractors but about grok patterns.
I mean "System -> Grok patterns -> Import pattern file"

**Comment by joschi** [comment] 2016-12-12 14:51
@jesusch Ah, okay. Got it. I'll reopen this issue.

**Comment by joschi** [comment] 2016-12-21 17:01
@jesusch This time the correct issue: Duplicate of #3003

**Closed by joschi** 2016-12-21 17:01 UTC
