### ISSUE TITLE
If more than 10 index sets are using time based retention and rotate daily, ERROR thrown in log 'ERROR [SetIndexReadOnlyJob] Cannot optimize index'

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#15756] opened 2023-06-14 21:35 UTC
While doing periodic log review of my graylog `server.log`, i came across the following error that appears in my log once every 24 hours, at 00:00 UTC:

```
2023-06-14T00:00:43.917Z ERROR [SetIndexReadOnlyJob] Cannot optimize index <{{index name}}>.
org.graylog2.system.jobs.SystemJobConcurrencyException: The maximum of parallel [org.graylog2.indexer.indices.jobs.OptimizeIndexJob] is locked to <10> but <10> are running.
	at org.graylog2.system.jobs.SystemJobManager.checkAllowedConcurrency(SystemJobManager.java:123) ~[graylog.jar:?]
	at org.graylog2.system.jobs.SystemJobManager.submitWithDelay(SystemJobManager.java:73) ~[graylog.jar:?]
	at org.graylog2.system.jobs.SystemJobManager.submit(SystemJobManager.java:67) ~[graylog.jar:?]
	at org.graylog2.indexer.SetIndexReadOnlyJob.execute(SetIndexReadOnlyJob.java:96) [graylog.jar:?]
	at org.graylog2.indexer.indices.jobs.SetIndexReadOnlyAndCalculateRangeJob.execute(SetIndexReadOnlyAndCalculateRangeJob.java:75) [graylog.jar:?]
	at org.graylog2.system.jobs.SystemJobManager.executeJob(SystemJobManager.java:115) [graylog.jar:?]
	at org.graylog2.system.jobs.SystemJobManager$1.run(SystemJobManager.java:92) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedScheduledExecutorService$InstrumentedRunnable.run(InstrumentedScheduledExecutorService.java:241) [graylog.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

What i believe is happening is that i have more than 10 index sets that use daily retention policy, and when triggered, more than 10 index sets attempt to rotate at the same time.

I'm not sure if these jobs are retried and are then successful, or if they fail and do not retry. The logging via `/system/overview` is a bit difficult to decode because it is always continously refreshing and the message doesn't contain a corresponding index or index set name: `SystemJob <7f51f490-0a46-11ee-ac0e-0242ea5a24cc> [org.graylog2.indexer.indices.jobs.OptimizeIndexJob] finished in 35279ms.`

## Expected Behavior

My expectation is that if this is normal behavior and everything is working correctly, these errors are not logged unless they are fatal, meaning the job failed and was unable to retry, and this will cause issues for the health of the graylog cluster. If the error is transient, and quickly addressed, the errors are false positives.

## Current Behavior

What appears to be error logging that doesn't actually indicate an error and does not indicate any issue

## Possible Solution

Only log on a true error

## Steps to Reproduce (for bugs)

Have more than 10 index sets with retention that will rotate all at the same time, e.g. daily.

## Your Environment

* Graylog Version: 5.1.2
* Java Version: Bundled
* ~~Elasticsearch~~ Opensearch Version: 2.8.0
* MongoDB Version: 6.0.6
* Operating System: Ubuntu Server 22.04 LTS
* Browser version: Google Chrome Version 114.0.5735.133 (Official Build) (arm64)

Please let me know if there are any questions or if more data or any testing is needed. Thanks!

**Comment by luk-kaminski** [comment] 2023-06-30 10:31
Code observations:
1.
`SetIndexReadOnlyAndCalculateRangeJob` contains two sub-jobs:

- `CreateNewSingleIndexRangeJob`
- `SetIndexReadOnlyJob`

The first one invokes its code inside its `execute` method.
The second one does not do it, instead it submits a task to `SystemJobManager` for invocation.
If `SetIndexReadOnlyAndCalculateRangeJob` takes the last, 10th place for the job, its sub-job of `SetIndexReadOnlyJob` will likely not be able to complete and will throw an exception.

The question: 
When we invoke a job inside another job, shouldn't we always do it directly, instead of submitting it to `SystemJobManager`?
(@dennisoelkers  ? @bernd ?)

2.
`SystemJobManager` does not seem to provide a retry mechanism. But jobs that are submitted to it, which come from Periodical, will be in fact retried (in this case by `IndexRotationThread`, which by default runs every 10 seconds).

3.
We do handle `SystemJobConcurrencyException` in a consistent way.
During execution of the job, we tend to swallow it silently (The job fails, but there is no info about it) - `SystemJobManager`, line 99. 
During submission of the job, we log an error (The job fails) - `SystemJobManager`, line 73. 

The question: 
Should we always swallow this exception without notifying about it? Do we expect that all jobs come from Periodicals and will be executed sooner or late?
(@dennisoelkers  ? @bernd ?)

**Comment by bernd** [comment] 2023-06-30 12:37
@luk-kaminski 

1. Yes. Resubmitting the nested job via the system job manager is probably unnecessary. 
2. The `SystemJobManager` doesn't support retries. It's a fire-and-forget type of system. The idea is to remove that system at some point and use the job scheduler we already use for events, reports, and other jobs. That one supports retries.
3. Good catch. We should log the error in `SystemJobManager`.

> Do we expect that all jobs come from Periodicals and will be executed sooner or later?

Periodicals don't do retries and just run on a regular basis. If a periodical job submits a `SetIndexReadOnlyJob`, this is for a specific index. If that job fails, it will not be retried. Next time, the periodical will submit a `SetIndexReadOnlyJob` for a different index.

**Comment by luk-kaminski** [comment] 2023-06-30 12:51
@bernd - won't Periodical do the same check on the same index next time?
Which means that after one `SetIndexReadOnlyJob` fails, after 10 sec. a new job for the same index is created, which is kind of similar to retry mechanism?

**Comment by bernd** [comment] 2023-06-30 13:02
> @bernd - won't Periodical do the same check on the same index next time? Which means that after one `SetIndexReadOnlyJob` fails, after 10 sec. a new job for the same index is created, which is kind of similar to retry mechanism?

@luk-kaminski 
It depends on what the periodical job does. Do you have a specific example where a periodical job is similar to a retry?

**Comment by luk-kaminski** [comment] 2023-07-04 09:51
#15846 PR should limit a problem.

Issue #15868 summarizes the desired solution, as it was discussed with @bernd.

**Comment by luk-kaminski** [comment] 2023-07-13 13:11
Hi @drewmiranda-gl,

We have decided to abandon the #15846 PR. While it has a potential to limit a problem, there is also a risk that OptimizeIndexJobs will overwhelm the SystemJobManager thread pool or issues like this one will reappear: #3066.

Could you please to increase elasticsearch_index_optimization_jobs config property to a greater value and check if it solves the problem for now?

(Issue https://github.com/Graylog2/graylog2-server/issues/15868 is still considered as a desired solution, but it will take us some time to get it done the proper way).

**Comment by drewmiranda-gl** [comment] 2023-07-13 13:55
@luk-kaminski do you happen to know the config file property? Strangely i can't find any documentation from opensearch with a list of available configuration options :(

**Comment by drewmiranda-gl** [comment] 2023-07-21 13:52
I set `elasticsearch_index_optimization_jobs` to 10

![image](https://github.com/Graylog2/graylog2-server/assets/107503402/690b1c9b-8b8a-4f3c-a3f2-e9e5cfe8c909)

However, it didn't seem to change anything in regards to the error in the log.

![image](https://github.com/Graylog2/graylog2-server/assets/107503402/a81c5032-2206-4cd9-8bdd-345c4644a523)

I don't believe this is actually an error as the job is retried and does succeed afterwards. Not sure if the error should be suppressed or the severity changed? Is this something we would expect a customer/user should see in the log during normal operation?

**Comment by luk-kaminski** [comment] 2023-07-24 09:43
Hi @drewmiranda-gl ,
By setting `elasticsearch_index_optimization_jobs` to 10 you have NOT increased the default value.
So it is not surprising that nothing has changed...

When it comes to your last comments - do you suggest that we need to mask those errors, before the problem is properly solved in #15868?

**Comment by luk-kaminski** [comment] 2023-07-26 10:35
Hi @drewmiranda-gl ,
The default value is 10. I can understand your confusion, it seems that in some `.conf` files the old value of 20 is left.

**Comment by luk-kaminski** [comment] 2023-12-18 11:14
Hi @drewmiranda-gl,

Could you please remind me the status of this ticket?
Has a trick with modifying `elasticsearch_index_optimization_jobs` helped?

**Comment by drewmiranda-gl** [comment] 2023-12-18 16:16
Reviewing my logs, i stopped seeing this error, however, i believe the reason is because i switched to Time Size Optimize (TSO) strategy so i'm not having all my indexes attempt to rotate all at once.

If i were to modify `elasticsearch_index_optimization_jobs` what value do you suggest? I did previously set it to 10, would raising this value help address the original error?

Thanks!

**Comment by luk-kaminski** [comment] 2023-12-19 10:34
Hi @drewmiranda-gl ,

Just to summarize, we have https://github.com/Graylog2/graylog2-server/issues/15868 task that would solve the issue, but we do not have time to take care of it now.
If you don't face the problem and no client has reported it, we would probably postpone the resolution and won't feel that bad about it.

If you believe that the problem is important, however, you can try to play with `elasticsearch_index_optimization_jobs = 20` to see if it helps in any way or inform us that you'd need the fix soon - we will then have to check if we can change some priorities...

**Comment by drewmiranda-gl** [comment] 2023-12-19 14:49
Sounds good to me. It didn't seem like anything was actually failing because the job would just retry anyways. Appreciate your help!

**Comment by luk-kaminski** [comment] 2024-07-23 10:06
@Emy-01 - As it was decided not to fix it, I am un-assigning myself.

**Closed** 2024-07-23 15:45 UTC
Labels: bug, triaged, to-verify, won't fix, Low Prio
