### ISSUE TITLE
COMMONAPACHELOG Grok Pattern  

### ISSUE THREAD

**Issue by PantsOnHead** [Graylog2/graylog2-server#1910] opened 2016-03-08 05:02 UTC
### Problem description
Using COMMONAPACHELOG or COMBINEDAPACHELOG to parse apache messages causes logs to error.
### Steps to reproduce the problem

1. Send Apache logs in
2. Create Extractor using grok pattern on messages
3. Watch the indexer failures pile up.
4. Rename the HTTPDATE:timestamp to resolve.
### Environment

* Graylog Version: v1.3.3 ova image

**Comment by joschi** [comment] 2016-03-08 09:13
Duplicate of #1647.

**Closed by joschi** 2016-03-08 09:13 UTC
