### ISSUE TITLE
Unable to keep master node stable - Logs flooded with "Did not find meta info of this node. Re-registering"

### ISSUE THREAD

**Issue by juliohm1978** [Graylog2/graylog2-server#9903] opened 2021-01-14 07:34 UTC
I'm running a Graylog cluster with 2 nodes, and recently upgraded from 3.x to 4.0.1. After the upgrade, the cluster is unable to sustain the node status.

![image](https://user-images.githubusercontent.com/4145456/104556866-0dc63300-561f-11eb-9f24-7064b60df1af.png)

The **_System/Nodes_** view is inconsistent, sometimes showing one node, both or neither at any moment. Nodes are coming and going very quickly, but they are running and are able to ingest logs normally. Reducing the cluster size to a single node makes the problem go away, but I need the redundancy.

Once the second node is started, the first node is flooded with these log messages that repeat every second.

```
 2021-01-14 07:16:23,502 WARN    [NodePingThread] - Did not find meta info of this node. Re-registering. - {}                                                                                                      
 2021-01-14 07:16:24,502 WARN    [NodePingThread] - Did not find meta info of this node. Re-registering. - {}                                                                                                      
 2021-01-14 07:16:25,502 WARN    [NodePingThread] - Did not find meta info of this node. Re-registering. - {}                                                                                                      
 2021-01-14 07:16:26,502 WARN    [NodePingThread] - Did not find meta info of this node. Re-registering. - {}                                                                                                      
 2021-01-14 07:16:27,502 WARN    [NodePingThread] - Did not find meta info of this node. Re-registering. - {}                                                                                                      
 2021-01-14 07:16:32,067 WARN    [NodePingThread] - Did not find meta info of this node. Re-registering. - {}                                                                                                      
 2021-01-14 07:16:37,066 WARN    [NodePingThread] - Did not find meta info of this node. Re-registering. - {}                                                                                                      
 2021-01-14 07:16:38,067 WARN    [NodePingThread] - Did not find meta info of this node. Re-registering. - {}                                                                                                      
 2021-01-14 07:16:39,069 WARN    [NodePingThread] - Did not find meta info of this node. Re-registering. - {}                                                                                                      
 2021-01-14 07:16:40,067 WARN    [NodePingThread] - Did not find meta info of this node. Re-registering. - {}                                                                                                      
 2021-01-14 07:16:41,067 WARN    [NodePingThread] - Did not find meta info of this node. Re-registering. - {}                                                                                                      
 2021-01-14 07:16:42,067 WARN    [NodePingThread] - Did not find meta info of this node. Re-registering. - {}                                                                                                      
 2021-01-14 07:16:43,067 WARN    [NodePingThread] - Did not find meta info of this node. Re-registering. - {}                                                                                                      
 2021-01-14 07:16:44,067 WARN    [NodePingThread] - Did not find meta info of this node. Re-registering. - {}                                                                                                      
 2021-01-14 07:16:45,072 WARN    [NodePingThread] - Did not find meta info of this node. Re-registering. - {}                                                                                                      
 2021-01-14 07:16:46,067 WARN    [NodePingThread] - Did not find meta info of this node. Re-registering. - {}                                                                                                      
 2021-01-14 07:16:47,067 WARN    [NodePingThread] - Did not find meta info of this node. Re-registering. - {}                                                                                                      
 2021-01-14 07:16:48,067 WARN    [NodePingThread] - Did not find meta info of this node. Re-registering. - {}                                                                                                      
 2021-01-14 07:16:49,067 WARN    [NodePingThread] - Did not find meta info of this node. Re-registering. - {}                                                                                                      
 2021-01-14 07:16:50,067 WARN    [NodePingThread] - Did not find meta info of this node. Re-registering. - {}                                                                                                      
```

I have found discussions that point to clock skews between servers. That has been checked and all hosts are ntp synchronized.

I also managed to increase the log level on the second node, and it does appear to be in a loop constantly updating the mongodb nodes collection and resetting it.

[graylog.log.zip](https://github.com/Graylog2/graylog2-server/files/5812916/graylog.log.zip)

Any ideas what could be causing this?

Kubernetes installation using [KongZ/chart](https://github.com/KongZ/charts):
* Graylog Version: graylog/graylog:4.0.1-1 (docker image)
* Elasticsearch Version: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.13 (docker image)
* MongoDB Version: docker.io/bitnami/mongodb:4.4.1-debian-10-r39 (docker image)
* Operating System: Kubernetes cluster / Ubuntu 18.04 nodes

**Comment by dennisoelkers** [comment] 2021-01-14 08:43
Duplicate of #9902.

**Closed by dennisoelkers** 2021-01-14 08:43 UTC
Labels: bug
