### ISSUE TITLE
2.0a4 'Edit input' - form reloads itself while editing

### ISSUE THREAD

**Issue by SjonHortensius** [Graylog2/graylog2-server#1929] opened 2016-03-15 12:34 UTC
I'm trying to edit a global input on */system/inputs*, but while editing the form reloads the previously saved fields every few seconds. This is very annoying.

Possibly related; I see these notices in my console:

```
unreachable code after return statement plugin.org.graylog.plugins.map-widget.MapWidget.ddd103b678992ca86b75.js:24142:5
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create plugin.org.graylog.plugins.map-widget.MapWidget.ddd103b678992ca86b75.js:9906:416
unreachable code after return statement plugin.org.graylog.plugins.map-widget.MapWidget.ddd103b678992ca86b75.js:24142:5
unreachable code after return statement app.3ae8b0a28a3bb071fe6d.js:4773:4
unreachable code after return statement
```

**Comment by edmundoa** [comment] 2016-03-15 13:28
Hi SjonHortensius,

Which browser are you using?

**Comment by SjonHortensius** [comment] 2016-03-15 13:29
This is **Firefox 45.0**

**Comment by dennisoelkers** [comment] 2016-03-22 09:30
This is a duplicate of #1870, which is closed already. Expect this to be fixed in the next release.

**Closed by dennisoelkers** 2016-03-22 09:30 UTC
Labels: bug, P3, S3
