### ISSUE TITLE
Flexible date dropping msec when converting cisco date from raw/plaintext input

### ISSUE THREAD

**Issue by tacgnol** [Graylog2/graylog2-server#3077] opened 2016-11-10 11:09 UTC
## Expected Behavior

In an extractor, a date in the format 'MMM dd YYYY HH:mm:ss.SSS' converted by Flexible Date should include the milliseconds.

Dates in similar formats (e.g. MMM dd HH:mm:ss.SSS' should work in the same way.

## Current Behavior
When converting a datestamp in the above formats, it always rounds the time to the nearest second by putting all zeros in the .SSS part of the time.

## Steps to Reproduce (for bugs)
1. Create a regex extractor that produces output in the form MMM dd YYYY HH:mm:ss.SSS,  e.g. "Nov 10 2016 10:58:14.458"
2. Add flexible date converter and store in any field name.
3. Field will only have date in the format YYYY-MM-ddTHH:mm:ss.000, e.g. 2016-11-10T10:39:47.000Z

## Context
At times of high activity there may be multiple messages received in a 1 second interval and it is important for correlation purposes to see messages in the order they were generated with high precision on the time. 1 second interval is not always acceptable.

## Your Environment
* Graylog Version: 2.1.2
* Elasticsearch Version: 2.4.1
* MongoDB Version: 2.4.10
* Operating System: Debian 8.6
* Browser version: Safari 10.0.1

**Comment by joschi** [comment] 2016-11-10 11:17
Duplicate of #2323.

**Closed by joschi** 2016-11-10 11:17 UTC
