### ISSUE TITLE
Dashboard pages can not be closed

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/graylog2-server#10848] opened 2021-06-14 11:27 UTC
Hitting the close button does nothing. See browser console log for the error:
[pages.log](https://github.com/Graylog2/graylog2-server/files/6647943/pages.log)

**Comment by dennisoelkers** [comment] 2021-06-14 11:34
Duplicate of #10834.

**Closed by dennisoelkers** 2021-06-14 11:34 UTC
Labels: bug, search, test-day
