### ISSUE TITLE
Error: Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by jeremyjpj0916** [Graylog2/graylog2-server#6604] opened 2019-10-16 19:33 UTC
Odd login bug I am seeing sometimes when I login and get directed here:

http://server.com:9000/search?rangetype=relative&fields=message%2Csource&width=1680&highlightMessage=&relative=604800&q=

```
Cannot read property 'getBoundingClientRect' of null

Stack Trace:

TypeError: Cannot read property 'getBoundingClientRect' of null
    at t._updateHeight (http://server.com:9000/assets/LoggedInPage.24a1414e150e7e2e3ce2.js:1:187199)
    at t.componentDidMount (http://server.com:9000/assets/LoggedInPage.24a1414e150e7e2e3ce2.js:1:186806)
    at t.componentDidMount (http://server.com:9000/assets/vendor.91c91d4a31d54d96392a.js:73:88989)
    at Ro (http://server.com:9000/assets/vendor.91c91d4a31d54d96392a.js:18:82395)
    at Xo (http://server.com:9000/assets/vendor.91c91d4a31d54d96392a.js:18:85070)
    at http://server.com:9000/assets/vendor.91c91d4a31d54d96392a.js:18:98277
    at Object.exports.unstable_runWithPriority (http://server.com:9000/assets/vendor.91c91d4a31d54d96392a.js:35:3284)
    at Os (http://server.com:9000/assets/vendor.91c91d4a31d54d96392a.js:18:98212)
    at Ys (http://server.com:9000/assets/vendor.91c91d4a31d54d96392a.js:18:97988)
    at Ss (http://server.com:9000/assets/vendor.91c91d4a31d54d96392a.js:18:97333)
    at Ls (http://server.com:9000/assets/vendor.91c91d4a31d54d96392a.js:18:96354)
    at Zo (http://server.com:9000/assets/vendor.91c91d4a31d54d96392a.js:18:95228)
    at Object.enqueueSetState (http://server.com:9000/assets/vendor.91c91d4a31d54d96392a.js:18:44755)
    at t.b.setState (http://server.com:9000/assets/vendor.91c91d4a31d54d96392a.js:26:1665)
    at http://server.com:9000/assets/5a9c3e27-75.24a1414e150e7e2e3ce2.js:1:2544
    at l (http://server.com:9000/assets/builtins.24a1414e150e7e2e3ce2.js:104:88608)
    at O._settlePromiseFromHandler (http://server.com:9000/assets/builtins.24a1414e150e7e2e3ce2.js:104:61890)
    at O._settlePromise (http://server.com:9000/assets/builtins.24a1414e150e7e2e3ce2.js:104:62690)
    at O._settlePromise0 (http://server.com:9000/assets/builtins.24a1414e150e7e2e3ce2.js:104:63389)
    at O._settlePromises (http://server.com:9000/assets/builtins.24a1414e150e7e2e3ce2.js:104:64716)
    at http://server.com:9000/assets/builtins.24a1414e150e7e2e3ce2.js:104:18338


Component Stack:

    in DecoratorSidebar
    in div
    in t
    in t
    in div
    in t
    in div
    in t
    in t
    in Uncontrolled(t)
    in div
    in t
    in div
    in AutoAffix
    in SearchSidebar
    in div
    in t
    in div
    in t
    in t
    in t
    in SearchPage
    in Unknown
    in n
    in div
    in t
    in div
    in t
    in div
    in AppWithSearchBar
    in div
    in t
    in t
    in withRouter(t)
    in div
    in App
    in RouterContext
    in Router
    in h
    in t
    in n
    in AppFacade
```

## Context
Trying to login

## Your Environment

Graylog 3.1.2+9e96b08 on server.com (Oracle Corporation 1.8.0_222 on Linux 3.10.0-957.12.2.el7.x86_64)

**Comment by jeremyjpj0916** [comment] 2019-10-16 19:36
Seems if I open incognito browser and try again its fine. Maybe something within my network/enterprise proxies cause it idk.

**Comment by jeremyjpj0916** [comment] 2019-10-16 19:37
Odd, now I logout one more time in regular tab, try to login again and make a message search and it works. Guess we can close this but I will leave the message up above for yah to noodle if there is anything odd about this that needs fixing.

**Comment by bernd** [comment] 2020-11-15 00:07
Closing this as issue author is unable to reproduce it again. The search page also has been replaced with a new implementation.

**Closed by bernd** 2020-11-15 00:07 UTC
Labels: bug, search, triaged

**Comment by djshoxxx** [comment] 2021-08-02 10:49
I am getting this same issue when clicking on "Create New View" it redirects to http://192.168.1.2:9000/extendedsearch with nearly the exact same error and stack trace as the op in this thread

Cannot read property 'getBoundingClientRect' of undefined


Stack Trace:

TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at t._updateHeight (server:9000/assets/ExtendedSearchPage.d5c12e9afb78da9fb1e7.js:1:99514)
    at t.componentDidMount (server:9000/assets/ExtendedSearchPage.d5c12e9afb78da9fb1e7.js:1:98824)
    at t.componentDidMount (server:9000/assets/vendor.91c91d4a31d54d96392a.js:73:88989)
    at Ro (server:9000/assets/vendor.91c91d4a31d54d96392a.js:18:82395)
    at Xo (server:9000/assets/vendor.91c91d4a31d54d96392a.js:18:85070)
    at server:9000/assets/vendor.91c91d4a31d54d96392a.js:18:98277
    at Object.exports.unstable_runWithPriority (server:9000/assets/vendor.91c91d4a31d54d96392a.js:35:3284)
    at Os (server:9000/assets/vendor.91c91d4a31d54d96392a.js:18:98212)
    at Ys (server:9000/assets/vendor.91c91d4a31d54d96392a.js:18:97988)
    at Ss (server:9000/assets/vendor.91c91d4a31d54d96392a.js:18:97333)
    at Ls (server:9000/assets/vendor.91c91d4a31d54d96392a.js:18:96354)
    at Zo (server:9000/assets/vendor.91c91d4a31d54d96392a.js:18:95228)
    at Object.enqueueSetState (server:9000/assets/vendor.91c91d4a31d54d96392a.js:18:44755)
    at g.b.setState (server:9000/assets/vendor.91c91d4a31d54d96392a.js:26:1665)
    at g.<anonymous> (server:9000/assets/app.d5c12e9afb78da9fb1e7.js:102:260361)
    at a.n (server:9000/assets/vendor.91c91d4a31d54d96392a.js:10:1324)
    at a.emit (server:9000/assets/vendor.91c91d4a31d54d96392a.js:90:241068)
    at h.trigger (server:9000/assets/vendor.91c91d4a31d54d96392a.js:10:2199)
    at h._trigger (server:9000/assets/app.d5c12e9afb78da9fb1e7.js:34:73652)
    at server:9000/assets/app.d5c12e9afb78da9fb1e7.js:34:73047
    at s (server:9000/assets/app.d5c12e9afb78da9fb1e7.js:102:224951)
    at P._settlePromiseFromHandler (server:9000/assets/app.d5c12e9afb78da9fb1e7.js:102:198233)
    at P._settlePromise (server:9000/assets/app.d5c12e9afb78da9fb1e7.js:102:199033)
    at P._settlePromise0 (server:9000/assets/app.d5c12e9afb78da9fb1e7.js:102:199732)
    at P._settlePromises (server:9000/assets/app.d5c12e9afb78da9fb1e7.js:102:201059)
    at server:9000/assets/app.d5c12e9afb78da9fb1e7.js:102:154681

Component Stack:

    in FieldList
    in ConnectStoresWrapper[FieldList] stores=selectedFields
    in div
    in div
    in Transition
    in t
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in div
    in AutoAffix
    in div
    in SideBar
    in ConnectStoresWrapper[SideBar] stores=viewMetadata
    in div
    in t
    in span
    in v
    in ConnectStoresWrapper[v] stores=widgets
    in Unknown
    in ConnectStoresWrapper[Unknown/Anonymous] stores=fieldTypes,searches,viewMetadata,viewState
    in div
    in t
    in ExtendedSearchPage
    in ConnectStoresWrapper[ExtendedSearchPage] stores=executionState
    in Unknown
    in t
    in n
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in t
    in withRouter(t)
    in div
    in App
    in RouterContext
    in Router
    in h
    in t
    in n
    in AppFacade


I am still very new to graylog and may not have set it up correctly. It is set up in a docker in unraid. When googling my error it brought me here, of course.



In the docker logs i also keep seeing this error repeatedly:

2021-08-02 03:46:15,068 INFO : org.graylog2.periodical.IndexerClusterCheckerThread - Indexer not fully initialized yet. Skipping periodic cluster check.


Please go easy on me, Im brand new to graylog and this is my first time ever trying to set it up.
