### ISSUE TITLE
Mouse over function in histogram broken

### ISSUE THREAD

**Issue by HolgerOpenSource** [Graylog2/graylog2-server#3590] opened 2017-03-08 09:38 UTC
**Mouse over popup is mostly shown for the wrong bar in histogram. See attached screenshot.**

## Expected Behavior

Popup is shown for the bar the cursor is pointing to.

## Current Behavior

Popup is shown randomly for a bar the cursor isn't pointing to.

## Possible Solution

???

## Steps to Reproduce (for bugs)

1. Display histogram with a few bars.
2. Move cursor on a bar.
3. Look for mouse over popup on wrong bar.

## Your Environment

Versions:
- Graylog 2.2.1 
- elasticsearch 2.4.4
- mongoDB 3.2.1
- Linux SLES 11
- Browser Firefox ESR 45.5.1

**Comment by dennisoelkers** [comment] 2017-03-08 09:40
I am missing the screen shot. Is it just me?

**Comment by HolgerOpenSource** [comment] 2017-03-08 09:41
![2017-03-08 10_27_58-graylog - search](https://cloud.githubusercontent.com/assets/13033312/23698424/c6435d20-03eb-11e7-989c-58c7ef4450ed.png)

**Comment by edmundoa** [comment] 2017-03-08 10:19
Hi @HolgerOpenSource,

Thank you for reporting this issue.

As a bit of context, this is an issue with the graphing library we use in the search page (rickshaw). I've also seen the issue sometimes and I even tried to fix it some time ago but I couldn't. Anyway, the issue is there, so let's see if we can fix it this time.

**Comment by dennisoelkers** [comment] 2020-02-07 11:06
This has been fixed in `3.1.0` by OSSing the views, which are now the default search in `3.2.0`.

**Closed by dennisoelkers** 2020-02-07 11:06 UTC
Labels: bug, triaged
