### ISSUE TITLE
Ldap Group Search Base DN doesn't search recursive

### ISSUE THREAD

**Issue by elcool0r** [Graylog2/graylog2-server#1400] opened 2015-09-08 07:16 UTC
The ldap group mapping only seems to work if the group search base contains groups but not ou's which contains groups.

Doesnt work: OU=Groups,OU=COMPANY,DC=foo,DC=bar
Working (Department OU has Groups in it): OU=Department, OU=Groups,OU=COMPANY,DC=foo,DC=bar

Tested with active directory.

**Comment by kroepke** [comment] 2015-09-08 08:00
I just tried to reproduce this and it works for me in the current 1.2 branch (unchanged code from the first RC):

<img width="680" alt="screenshot" src="https://cloud.githubusercontent.com/assets/52014/9729436/c3dc4d5c-560f-11e5-86ce-7308db792622.png">

<img width="441" alt="screenshot" src="https://cloud.githubusercontent.com/assets/52014/9729522/4318508e-5610-11e5-9a28-93300aabaf11.png">

```
2015-09-08 09:57:10,889 TRACE: org.graylog2.security.ldap.LdapConnector - Connecting to LDAP server 10.0.0.181:389, binding with user administrator@corp.graylog.org
2015-09-08 09:57:10,893 TRACE: org.graylog2.security.ldap.LdapConnector - Search ActiveDirectory for (&(objectClass=user)(sAMAccountName=kay)), starting at dc=corp,dc=graylog,dc=org
2015-09-08 09:57:10,897 TRACE: org.graylog2.security.ldap.LdapConnector - LDAP search for groups: (objectClass=group) starting at ou=graylog,dc=corp,dc=graylog,dc=org
2015-09-08 09:57:10,898 TRACE: org.graylog2.security.ldap.LdapConnector - Group Entry:   Entry
      dn: CN=Net,OU=Ops,OU=graylog,DC=corp,DC=graylog,DC=org
      objectClass: top
      objectClass: group
      uSNCreated: 17093
      cn: Net
      whenChanged: 20150908073521.0Z
      sAMAccountName: Net
      sAMAccountType: 268435456
      groupType: -2147483646
      objectGUID: 0xC2 0x59 0xEB 0x3D 0xB6 0x1C 0x93 0x46 0xBA 0x2D 0xB6 0xF1 0xD5 0x3C 0x52 0x4B 
      member: CN=Kay Roepke,CN=Builtin,DC=corp,DC=graylog,DC=org
      name: Net
      instanceType: 4
      objectSid: 0x01 0x05 0x00 0x00 0x00 0x00 0x00 0x05 0x15 0x00 0x00 0x00 0xCA 0x46 0xFB 0x7D ...
      distinguishedName: CN=Net,OU=Ops,OU=graylog,DC=corp,DC=graylog,DC=org
      whenCreated: 20150908073358.0Z
      objectCategory: CN=Group,CN=Schema,CN=Configuration,DC=corp,DC=graylog,DC=org
      dSCorePropagationData: 20150908075019.0Z
      dSCorePropagationData: 20150908075014.0Z
      dSCorePropagationData: 16010101000002.0Z
      uSNChanged: 17105

2015-09-08 09:57:10,898 TRACE: org.graylog2.security.ldap.LdapConnector - DN CN=Kay Roepke,CN=Builtin,DC=corp,DC=graylog,DC=org == CN=Kay Roepke,CN=Builtin,DC=corp,DC=graylog,DC=org member?
2015-09-08 09:57:10,898 TRACE: org.graylog2.security.ldap.LdapConnector - Group Entry:   Entry
      dn: CN=Hosting,OU=Ops,OU=graylog,DC=corp,DC=graylog,DC=org
      objectClass: top
      objectClass: group
      uSNCreated: 17097
      cn: Hosting
      whenChanged: 20150908073521.0Z
      sAMAccountName: Hosting
      sAMAccountType: 268435456
      groupType: -2147483646
      objectGUID: 0x88 0xCC 0x16 0xEE 0x25 0x43 0xCD 0x45 0xA3 0x02 0x7C 0x7D 0x97 0x6C 0x8B 0x9C 
      member: CN=Kay Roepke,CN=Builtin,DC=corp,DC=graylog,DC=org
      name: Hosting
      instanceType: 4
      objectSid: 0x01 0x05 0x00 0x00 0x00 0x00 0x00 0x05 0x15 0x00 0x00 0x00 0xCA 0x46 0xFB 0x7D ...
      distinguishedName: CN=Hosting,OU=Ops,OU=graylog,DC=corp,DC=graylog,DC=org
      whenCreated: 20150908073414.0Z
      objectCategory: CN=Group,CN=Schema,CN=Configuration,DC=corp,DC=graylog,DC=org
      dSCorePropagationData: 20150908075019.0Z
      dSCorePropagationData: 20150908075014.0Z
      dSCorePropagationData: 16010101000002.0Z
      uSNChanged: 17102
```

Can you please paste the relevant search base DN, filter, name attribute and the output of the test login?
To get the groups Graylog does a subtree search scope, so it should properly find the groups. Maybe the filter is subtly wrong so it doesn't match the groups?

If you prefer you can also send me the info via email to kay@graylog.com if it contains sensitive information.
To obtain the TRACE information shown above, you can perform:
`PUT http://127.0.0.1:12900/system/loggers/org.graylog2.security.ldap.LdapConnector/level/TRACE` with admin credentials. Just be sure to set it back to INFO or WARN as it is _really_ noisy :)

**Comment by elcool0r** [comment] 2015-09-08 08:31
While gathering the data I found the problem. The group search seems to take quite a while and after clicking on LDAP Group Mapping I'm getting "No LDAP/Active Directory Groups found" and after 10-20 seconds all groups pop up. Guess I have to create a better filter than (objectClass=group). 
And just a quick note: the example pattern "(&(objectClass=group)(cn=graylog*)" is missing a bracket in the current version.

**Comment by bernd** [comment] 2015-09-14 10:13
We documented that writing a stricter filter can improve performance here: http://docs.graylog.org/en/1.2/pages/users_roles.html#external-authentication

Thank you for the report! Closing this now.

**Closed by bernd** 2015-09-14 10:13 UTC
Labels: documentation
