### ISSUE TITLE
extract message datetime as timestamp, but the timestamp will always add 8 hours to origin value

### ISSUE THREAD

**Issue by liubin-cm** [Graylog2/graylog2-server#3710] opened 2017-04-19 02:47 UTC
* Graylog Version:
* Elasticsearch Version: 2.4.4
* MongoDB Version: 3.0
* Operating System: centos 7.2 and docker 1.12.6
* Browser version: chrome
* my graylog version: 2.2.3
* server timezone: UTC
* graylog web interface timezone: Shanghai

my extract json:
{
  "extractors": [
    {
      "title": "Timestamp",
      "extractor_type": "grok",
      "converters": [],
      "order": 0,
      "cursor_strategy": "copy",
      "source_field": "message",
      "target_field": "",
      "extractor_config": {
        "grok_pattern": "%{TIMESTAMP_ISO8601:timestamp}",
        "named_captures_only": true
      },
      "condition_type": "none",
      "condition_value": ""
    }
  ],
  "version": "2.2.0-SNAPSHOT"
}

after extract timestamp, the message actual timestamp equal to extracted value added 8 hours, which insert into elasticsearch, but graylog web interface timestamp field show the right timestamp like pic2 below.
what's wrong about graylog? how do i solve it ? thanks. 
details as below pics:
pic1: 
![graytlog1](https://cloud.githubusercontent.com/assets/558679/25161010/23ffc4fa-24ec-11e7-9858-4d7903a51d26.jpg)
pic2: 
![graylog2](https://cloud.githubusercontent.com/assets/558679/25161043/5755609e-24ec-11e7-8dcb-2784b7122d75.jpg)

**Comment by joschi** [comment] 2017-04-19 06:39
Duplicate of #2689.

**Closed by joschi** 2017-04-19 06:39 UTC
