### ISSUE TITLE
Implement Syslog RELP input

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2249] opened 2016-05-18 09:59 UTC
### Problem description
Syslog TCP can loose messages.
AMQP and Kafka is too compliated and requires additional modules for syslogd.
RELP is native protocol in rsyslog (Ubuntu) and didn't require extra infrastructure like AMQP.

I found implementation [here](https://github.com/h0nIg/graylog2-input-relp), but it not work in graylog 2.0.

Protocol documentation can be found [here](http://www.rsyslog.com/doc/relp.html).

**Comment by joschi** [comment] 2016-05-18 09:59
Duplicate of #227.

**Closed by joschi** 2016-05-18 09:59 UTC
