### ISSUE TITLE
Selection by regexp is displaced

### ISSUE THREAD

**Issue by gekmcfh** [Graylog2/graylog2-server#804] opened 2014-12-08 11:24 UTC
Then i try to create regexp-extractor, any selection, which i do is displace on 2 symbols to left. Example:

Example origin message:
"<188>Dec 5 18:30:33 2014 pnz_clck_4fl %%10IFNET/4/INTERFACE UPDOWN(t): Trap 1.3.6.1.6.3.1.1.5.3: Interface 9437220 is Down, ifAdminStatus is 1, ifOperStatus is 2 "

Regexp:
: (.+):

Expected selection:
Trap 1.3.6.1.6.3.1.1.5.3

Getting selection:
: Trap 1.3.6.1.6.3.1.1.5

version: 0.92 from 1st december 2014

**Comment by bernd** [comment] 2015-01-15 13:05
Thank you for the report. This is an URL encoding issue caused by the  `%10` in the message. It only affects the extractor test in the web interface. I will commit a fix for that soon.

![extractor-regex](https://cloud.githubusercontent.com/assets/461/5757832/752fa79e-9cbf-11e4-9692-fc7abcf8ec53.png)

**Comment by bernd** [comment] 2015-01-15 13:09
Fixed by Graylog2/graylog2-web-interface@8bb1add

**Closed by bernd** 2015-01-15 13:09 UTC
Labels: bug, processing
