### ISSUE TITLE
error processing timestamp of messages using graylog 2.3 + gelfj + ES5

### ISSUE THREAD

**Issue by julienlau** [Graylog2/graylog2-server#4027] opened 2017-07-21 14:29 UTC
## Expected Behavior

GELF decoding should be OK
 
## Current Behavior

``` 
2017-07-21 14:23:00,923 ERROR: org.graylog2.shared.buffers.processors.DecodingProcessor - Unable to decode raw message RawMessage{id=19d0e9a0-6e20-11e7-b165-c20569e250d3, journalOffset=12992, codec=gelf, payloadSize=603, timestamp=2017-07-21T14:23:00.922Z, remoteAddress=/10.253.3.134:60446} on input <596cd181cbebdf000884d767>.
2017-07-21 14:23:00,923 ERROR: org.graylog2.shared.buffers.processors.DecodingProcessor - Error processing message RawMessage{id=19d0e9a0-6e20-11e7-b165-c20569e250d3, journalOffset=12992, codec=gelf, payloadSize=603, timestamp=2017-07-21T14:23:00.922Z, remoteAddress=/10.253.3.134:60446}
java.lang.IllegalArgumentException: GELF message <19d0e9a0-6e20-11e7-b165-c20569e250d3> (received from <10.253.3.134:60446>) has invalid "timestamp": 1500646980.655
	at org.graylog2.inputs.codecs.GelfCodec.validateGELFMessage(GelfCodec.java:262) ~[graylog.jar:?]
	at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:129) ~[graylog.jar:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:146) ~[graylog.jar:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:87) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:74) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:42) [graylog.jar:?]
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
2017-07-21 14:23:00,928 ERROR: org.graylog2.shared.buffers.processors.DecodingProcessor - Unable to decode raw message RawMessage{id=19d1d400-6e20-11e7-b165-c20569e250d3, journalOffset=12993, codec=gelf, payloadSize=351, timestamp=2017-07-21T14:23:00.928Z, remoteAddress=/10.253.3.134:60446} on input <596cd181cbebdf000884d767>.
2017-07-21 14:23:00,928 ERROR: org.graylog2.shared.buffers.processors.DecodingProcessor - Error processing message RawMessage{id=19d1d400-6e20-11e7-b165-c20569e250d3, journalOffset=12993, codec=gelf, payloadSize=351, timestamp=2017-07-21T14:23:00.928Z, remoteAddress=/10.253.3.134:60446}
java.lang.IllegalArgumentException: GELF message <19d1d400-6e20-11e7-b165-c20569e250d3> (received from <10.253.3.134:60446>) has invalid "timestamp": 1500646980.661
	at org.graylog2.inputs.codecs.GelfCodec.validateGELFMessage(GelfCodec.java:262) ~[graylog.jar:?]
	at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:129) ~[graylog.jar:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:146) ~[graylog.jar:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:87) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:74) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:42) [graylog.jar:?]
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
```
## Steps to Reproduce (for bugs)

I tried to adapt my previously working pattern layout with no effect on the error.

## Context

Until now I was using graylog2 2.2 last release with an ES2 cluster without any issues.

I wanted to go to ES5 so that I switched to graylog2 v2.3.0-rc.2 available from dockerhub.
I use gelfj 1.1.5 to send my messages from some java apps (spark and standard java).
So I plugged those same java app to this new graylog version.
All my config is green in graylog. The msg are arriving but GELF decoding always fails with the error:

## Your Environment

I use java 1.8 and slf4jlog4j1 (due to spark not compatible with log4j2)
My properties file for gelf-log4j:

```
log4j.rootLogger=INFO, stdout, graylog2
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.EnhancedPatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd' 'HH:mm:ss.SSS}{GMT} %-5p %c{1} - %m%n %X
log4j.appender.stdout.extractStacktrace=true
log4j.appender.stdout.includeLocation=false
log4j.appender.stdout.addExtendedInformation=false
log4j.appender.graylog2=org.graylog2.log.GelfAppender
log4j.appender.graylog2.facility=gelf-java
log4j.appender.graylog2.layout=org.apache.log4j.PatternLayout
#log4j.appender.graylog2.layout=org.apache.log4j.EnhancedPatternLayout
#log4j.appender.graylog2.layout.ConversionPattern=%d{yyyy-MM-dd' 'HH:mm:ss.SSS}{GMT} %-5p %c{1} - %m%n %X
log4j.appender.graylog2.extractStacktrace=false
log4j.appender.graylog2.includeLocation=false
log4j.appender.graylog2.addExtendedInformation=true
log4j.appender.graylog2.graylogHost=tcp:coretech.graylog.marathon.mesos
log4j.appender.graylog2.additionalFields={'_application': %X{_application}, '_environment': %X{_environment}, '_ver': %X{_ver}, '_provider': %X{_provider}, '_tileid' : %X{_tileid}, '_tilestatus' : %X{_tilestatus}, '_tiledate': %X{_tiledate}, '_request_duration': %X{_request_duration}, '_trackingid': %X{_trackingid}}
```

* Graylog Version:2.3.0-rc.2
* Elasticsearch Version:5
* MongoDB Version:
* Operating System:docker DCOS on ubuntu
* Browser version:

**Comment by julienlau** [comment] 2017-07-21 15:00
Note that I cannot find the method 
org.graylog2.inputs.codecs.GelfCodec.validateGELFMessage
If I look in the code from https://github.com/Graylog2/graylog2-server/blob/2fd51fc472192e7491c692f31448f884d8116fd2/graylog2-inputs/src/main/java/org/graylog2/inputs/codecs/GelfCodec.java

Anyway you could have a look if there is something new in there ?

**Comment by joschi** [comment] 2017-07-25 09:21
@julienlau I'm unable to reproduce the error with a *valid* GELF message using the timestamp you've mentioned in the original post.

The problem seems to be that gelfj is using a *string* instead of a floating point number for the `timestamp` field:
https://github.com/t0xa/gelfj/blob/v1.1.15/src/main/java/org/graylog2/GelfMessage.java#L227-L229

This is a violation of the [GELF 1.1 specification](http://docs.graylog.org/en/2.2/pages/gelf.html#gelf-payload-specification) and should be fixed in gelfj.

> Note that I cannot find the method `org.graylog2.inputs.codecs.GelfCodec.validateGELFMessage`

I'm not sure where you've picked up that link, but you can find the correct version of the file at https://github.com/Graylog2/graylog2-server/blob/2.3.0-rc.2/graylog2-server/src/main/java/org/graylog2/inputs/codecs/GelfCodec.java#L225-L264

**Closed** 2017-07-25 13:28 UTC
Labels: blocker, bug, in progress, triaged

**Comment by bernd** [comment] 2017-07-25 13:48
@julienlau Thank you for the report. This will be fixed in the next Graylog 2.3 version.

**Comment by julienlau** [comment] 2017-07-28 14:03
Thanks for having modified it to accept string.
I think that due to to spark being compatible only with log4j12 we are forced to send only string fields.

**Comment by joschi** [comment] 2017-07-28 15:34
@julienlau There are other GELF appenders for Log4j 1.2 which send valid GELF messages:
https://marketplace.graylog.org/addons?tag=log4j

**Comment by khmai** [comment] 2017-12-05 09:58
When I updated Graylog 2.2.3 + 7adc951 to 2.3.2 + 3df951e, the same problem, how to solve?
`2017-12-05T17:41:12.365+08:00 ERROR [DecodingProcessor] Unable to decode raw message RawMessage{id=6e1f9dd1-d9a0-11e7-b619-00163e0e5c7d, journalOffset=7519212810, codec=gelf, payloadSize=59, timestamp=2017-12-05T09:41:12.365Z, remoteAddress=/100.116.181.0:17832} on input <59f2e994d56c0041cbf5908a>.
2017-12-05T17:41:12.366+08:00 ERROR [DecodingProcessor] Error processing message RawMessage{id=6e1f9dd1-d9a0-11e7-b619-00163e0e5c7d, journalOffset=7519212810, codec=gelf, payloadSize=59, timestamp=2017-12-05T09:41:12.365Z, remoteAddress=/100.116.181.0:17832}
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Keepalived': was expecting ('true', 'false' or 'null')
 at [Source: Keepalived agent udp check string(digest=52921), ignore it!; line: 1, column: 11]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[graylog.jar:?]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) ~[graylog.jar:?]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2839) ~[graylog.jar:?]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1903) ~[graylog.jar:?]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:749) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3850) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3799) ~[graylog.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2397) ~[graylog.jar:?]
	at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:127) ~[graylog.jar:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:146) ~[graylog.jar:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:87) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:74) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:42) [graylog.jar:?]
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
`

**Comment by joschi** [comment] 2017-12-05 10:11
@khmai We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
