### ISSUE TITLE
Error NoClassDefFound CollectorService

### ISSUE THREAD

**Issue by jmcomas** [Graylog2/graylog2-server#1932] opened 2016-03-15 15:33 UTC
### Problem description

Working OK with Graylog Alpha 4, when upgrading to Alpha5:
```
2016-03-15_15:08:36.71903 Exception in thread "main" java.lang.NoClassDefFoundError: org/graylog2/collectors/CollectorService
2016-03-15_15:08:36.71906       at java.lang.Class.getDeclaredConstructors0(Native Method)
```
on /var/log/graylog/server/current

### Steps to reproduce the problem

1.Upgrade to graylog alpha 5

### Environment

* Graylog Version:  2.0.0 alpha 5
* Elasticsearch Version:   2.2.0
* MongoDB Version: 
* Operating System: Ubuntu
* Browser version:

**Comment by joschi** [comment] 2016-03-15 15:42
@jmcomas How exactly did you upgrade Graylog? In Graylog 2.0.0-alpha.5, the Graylog Collector functionality has been moved from the core into a plugin and it looks like you're using a mixture of the old and the new version.

**Comment by jmcomas** [comment] 2016-03-15 15:56
Hi Jochen,

- Stopping graylog-server
- Deleting server/
- Renaming graylog-2.0.0-alpha.5/ directory to server/ 
- Starting graylog-server

This upgrade procedure worked ok with alphas 1 to 4, maybe it won't work with 5?

Best,

JM

**Comment by joschi** [comment] 2016-03-15 16:11
@jmcomas I've just downloaded a fresh copy of the [Graylog 2.0.0-alpha.5 tar-ball](https://packages.graylog2.org/releases/graylog/graylog-2.0.0-alpha.5.tgz), extracted it locally, and started Graylog but I couldn't reproduce the problem you're describing.

Please make sure that not parts (e. g. plugins or JAR files) from previous Graylog 2.0.0 alpha versions are on the classpath when starting Graylog.

**Comment by jmcomas** [comment] 2016-03-15 17:19
We can't find out what it's happening, If we revert back to Alpha 4 all works fine. And we're only replacing /server folders. For the record, we're using the Alpha 1 OVA, upgraded ES to 2.2, and since then all the alpha releases worked OK until Alpha 5.

About the classpath, how can we check the loaded libraries?

Best,

JM

**Comment by kroepke** [comment] 2016-03-15 17:24
The collector service was moved into a plugin between alpha.4 and alpha.5: https://github.com/Graylog2/graylog2-server/commit/1f6da403bbb8dd7c7bb06e94ea21a6293e8da948

Please also add the collector plugin jar to your OVA. Ideally don't just replace the jar files, because sometimes other things change as well. Especially for the alpha phase we are sometimes changing things without notice which can break upgrading.

**Comment by joschi** [comment] 2016-03-16 09:47
> For the record, we're using the Alpha 1 OVA, upgraded ES to 2.2, and since then all the alpha releases worked OK until Alpha 5.

@jmcomas If you're using the virtual machine images, you should follow the upgrade procedure outlined at http://docs.graylog.org/en/2.0/pages/installation/graylog_ctl.html#upgrade-graylog and not only replace individual parts of the image.

Also make sure that no old version of the Anonymous Usage Statistics plugin is in the plugin directory of your Graylog server.

I'm closing this issue now since we can't reproduce it and it's very likely to be an issue with manually and individually upgrading parts of the virtual appliance.

**Closed by joschi** 2016-03-16 09:47 UTC
Labels: question
