### ISSUE TITLE
DataTable needs unique key per row

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#1892] opened 2016-03-03 14:27 UTC
### Problem description
When using the `DataTable` component with sorting, the key used on it is not unique, and that may break the re-rendering.

### Steps to reproduce the problem
- Use the `DataTable` component
- On the `dataRowFormatter` prop function, do not add a key to the `<tr>`
- After editing an element of the table which changes the sort order, not all components are re-rendered.

### Environment
* Graylog Version: 2.0.0-alpha.5

**Comment by bernd** [comment] 2016-07-19 16:52
The issue was about the `key` in `DataTableElement`.

```javascript
getFormattedDataRows() {
    let i = 0;
    let sortedDataRows = this.state.filteredRows;
    if (this.props.sortByKey) {
      sortedDataRows = sortedDataRows.sort((a, b) => {
        return a[this.props.sortByKey].localeCompare(b[this.props.sortByKey]);
      });
    }
    const formattedDataRows = sortedDataRows.map((row) => {
      const el = <DataTableElement key={`row-${i}`} element={row} index={i} formatter={this.props.dataRowFormatter} />;
      i++;
      return el;
    });

    return formattedDataRows;
  },
```

I am closing this because we  are not able to reproduce it.

**Closed by bernd** 2016-07-19 16:52 UTC
Labels: bug, P3, S3, web
