### ISSUE TITLE
6.1 RC-1 Area Chart widget Fails to load and has stack trace error

### ISSUE THREAD

**Issue by jivepig** [Graylog2/graylog2-server#20664] opened 2024-10-08 19:25 UTC
Loading a widget that contains an aggregation over time for a field in an area charge throws an error in the widget:
error: "While rendering this widget, the following error occurred: TypeError: a is undefined"

Attached Stack Trace

[StackTrace.txt](https://github.com/user-attachments/files/17298186/StackTrace.txt)

## Expected Behavior
Worked fine in V6.0.7
Upgraded to V6.1RC1 and it broke.

## Current Behavior
required to recreate the widget, it somewhat works but is not working the same way.

## Possible Solution
recreate the widget but find issue.
[content-pack-3391e184-d4cf-414a-ba58-195ac4f2e177-1.json](https://github.com/user-attachments/files/17298218/content-pack-3391e184-d4cf-414a-ba58-195ac4f2e177-1.json)

Attached Content pack for 

## Steps to Reproduce (for bugs)
1. System running on V6.0.7
2.Upgrade to 6.1RC1
3.Widget fails to load

## Context
Could not figure out how to fix the current widget, but manually recreated it seemed to fix it but it does not display the same way.

## Your Environment
Docker single node

* Graylog Version:V6.1RC-1
* Java Version:n/a
* OpenSearch Version:2.12
* MongoDB Version:V6
* Operating System:Ubuntu
* Browser version:NA

**Comment by kmerz** [comment] 2024-11-26 08:35
Cannot reproduce. So it should be fixed.

**Closed by kmerz** 2024-11-26 08:35 UTC
Labels: bug
