### ISSUE TITLE
Indexer Failure: MaxBytesLengthExceededException[bytes can be at most 32766 in length

### ISSUE THREAD

**Issue by eroji** [Graylog2/graylog2-server#1827] opened 2016-02-17 00:24 UTC
We are getting a number of these indexer failures and upgrading the latest Graylog gives us a more detail error message. It appears that the message is too large and is hitting a limit of 32766. I am trying to understand what exactly that number is.

- Based on the message that is 32766 bytes?
- Is that referring to the particular field of a message? In other words, the message can be 100MB but a single field can be no more than 32766b?
- Is there a way to increase this number? if so what kind of implications are there?

**Comment by joschi** [comment] 2016-02-17 08:38
Duplicate of #873.

**Closed by joschi** 2016-02-17 08:38 UTC
