### ISSUE TITLE
multiple amqp connection to same host and different user - messages lost

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#2451] opened 2016-07-04 14:01 UTC
### Problem description
If you use the same amqp host with multiple users / vhosts in the same instance of graylog only the first input will work. 

messages will be fetched (and deleted) from all other inputs, but no error is given in graylog server log and the messages are lost. 

### Steps to reproduce the problem

1. create an input with username / vhost over amqp (on the same amqp server/cluster)
2. create a second input with other username / vhost over amqp (on the same amqp server/cluster)
3. send test messages over both inputs 

### Environment

* Graylog Version: 2.0.3

used cloudamp cluster to test this.

**Comment by bernd** [comment] 2016-07-14 09:35
I am unable to reproduce this problem.

This is the RabbitMQ setup I use:

![image](https://cloud.githubusercontent.com/assets/461/16834937/6c918404-49b6-11e6-9cc9-1b288d22a9d9.png)

And the inputs:

![image](https://cloud.githubusercontent.com/assets/461/16835010/c2e57392-49b6-11e6-9b8c-95900aeef40a.png)

I have two scripts running which send GELF messages to the AMQP broker. All messages on boths vhosts show up in Graylog.

Can you post your setup details? Thanks!

**Comment by jalogisch** [comment] 2016-07-15 13:09
Did the same test with a fresh OVA (2.1 Alpha 2) using 3 AMQP Inputs from the same host and it is working with out issues.

Did the same test on my "default" hosts (OVA 2.1 Alpha 2 updated OVA from 2. GA) run into the issue that not more than 3 AMQP Inputs are working. 

I guess that this is more a "local" and no global issue.

**Comment by bernd** [comment] 2016-07-19 08:38
I am closing this now because it seems to be a local issue. Please re-open it if you find another issue. Thanks! :smiley:

**Closed by bernd** 2016-07-19 08:38 UTC
Labels: bug, P3, S1
