### ISSUE TITLE
Syslog TCP RST send by Graylog

### ISSUE THREAD

**Issue by lboue** [Graylog2/graylog2-server#1105] opened 2015-04-10 10:05 UTC
Hello,

I send syslogs message from a firewall over TCP to Graylog. I received those messages well but after a while, Graylog closes the TCP session with a RST packet. I do not understand this behavior

Could'you help me please ?

Here is versions I use:
<pre>rpm -qa | grep graylog
graylog-1.0-repository-el6-1.2.0-1.noarch
graylog-web-1.0.1-1.noarch
graylog-server-1.0.1-1.noarch

Kernel 2.6.32-358.el6.x86_64</pre>

And Input in Cluster
<pre>Syslog TCP 1514 (Syslog TCP) running
Network IO:  16,9kiB  0B (total:  13,0GiB  0B )
Total connections: 11512 (2 active)
recv_buffer_size: 1048576
port: 1514
tls_key_file:
tls_key_password: *******
max_message_size: 2097152
override_source:
allow_override_date: true
bind_address: 0.0.0.0
tls_cert_file:
</pre>

![graylog syslog](https://cloud.githubusercontent.com/assets/938089/7085892/8d5ab44a-df7b-11e4-9d7c-ea15075c4b13.png)

Regards,

**Comment by lboue** [comment] 2015-04-27 09:13
Hello,

Does anyone can help me?

**Comment by bernd** [comment] 2015-07-29 07:03
Another report from the mailing list that seems to be related:

--

I'm using syslog-ng to feed in data via a syslog/TCP channel and it's continually (every 10 seconds) dropping the TCP channel - forcing syslog-ng to restart it

```
2015-07-29T02:26:31+00:00 syslog.server syslog notice syslog-ng[30512]: Syslog connection broken; fd='408', server='AF_INET(192.168.6.3:1514)', time_reopen='10'
2015-07-29T02:26:41+00:00 syslog.server syslog notice syslog-ng[30512]: Syslog connection established; fd='465', server='AF_INET(192.168.6.3:1514)', local='AF_INET(0.0.0.0:0)'
2015-07-29T02:26:41+00:00 syslog.server syslog notice syslog-ng[30512]: Syslog connection broken; fd='465', server='AF_INET(192.168.6.3:1514)', time_reopen='10'
2015-07-29T02:26:51+00:00 syslog.server syslog notice syslog-ng[30512]: Syslog connection established; fd='379', server='AF_INET(192.168.6.3:1514)', local='AF_INET(0.0.0.0:0)'
2015-07-29T02:26:51+00:00 syslog.server syslog notice syslog-ng[30512]: Syslog connection broken; fd='379', server='AF_INET(192.168.6.3:1514)', time_reopen='10'
2015-07-29T02:27:01+00:00 syslog.server syslog notice syslog-ng[30512]: Syslog connection established; fd='476', server='AF_INET(192.168.6.3:1514)', local='AF_INET(0.0.0.0:0)'
2015-07-29T02:27:02+00:00 syslog.server syslog notice syslog-ng[30512]: Syslog connection broken; fd='476', server='AF_INET(192.168.6.3:1514)', time_reopen='10'
```

tcpdump shows normal data flow followed by two TCP resets coming back from the graylog-1.1.5 server - so it's definitely graylog that's borking. 

BTW, this system *is working*: I'm seeing these syslogs flowing in - can do searches/etc - but I assume I'm losing some records due to this issue. I even created a xinetd.d based tcp service on the graylog server that just logged what it received to a file, configured the syslog server to send to both tcp channels - and it's running fine with no restarts (ie tcpdump of both ports only shows TCP resets on the graylog port not the xinetd port). So I think that implies it isn't the OS (CentOS-7)

*Source:* https://groups.google.com/forum/?hl=en#!topic/graylog2/YQ0MYvdp4G0

**Comment by jhaar** [comment] 2015-07-29 07:21
My syslog-ng.conf contains the following

-----------------------
destination d_graylog {
        tcp("192.168.66.3" port(9876));
        syslog("192.168.66.3" port(1514));
};
log { source(s_local);  destination(d_graylog);};
---------------------------

I have the tcp channel aimed at an xinetd service that just writes the content to disk - it doesn't crash/TCP-reset. The "syslog" channel goes to the TCP syslog Input channel in graylog and shows the TCP-reset issue

The reason I'm using "syslog" is because graylog didn't like the "tcp" option - the content just blackholes all together. Graylog documentation about syslog-ng referred to using "syslog" (which I didn't even know existed as an option in syslog-ng) and that works - except for the TCP-reset issue

ngrep shows the traffic looking as follows - you can see the difference between the "tcp" (9876) and "syslog" (1514) channel formats

T 192.168.66.3.13:59786 -> 192.168.66.3.13:9876 [AP] <164>Jul 29 01:54:50 192.168.66.3.1 %ASA-4-106023: Deny udp src inside:192.168.66.3.185/6185 dst outside:192.168.66.3.111/3478 by access-group "acl_in" [0x0, 0x0].
T 192.168.66.3.13:43365 -> 192.168.66.3.13:1514 [AP] 168 
T 192.168.66.3.13:43365 -> 192.168.66.3.13:1514 [AP] <164>1 2015-07-29T01:54:50+00:00 192.168.66.3.1 %ASA-4-106023 - - - Deny udp src inside:192.168.66.3.185/6185 dst outside:192.168.66.3.111/3478 by access-group "acl_in" [0x0, 0x0].111 <22>1 2015-07-29T01:54:50+00:00 mailsrv .........

**Comment by bernd** [comment] 2015-07-29 07:35
@jhaar Awesome, thank you for the configs.

**Comment by bernd** [comment] 2015-07-29 11:07
@jhaar How many messages per second are you sending to that syslog input?

**Comment by jhaar** [comment] 2015-07-29 19:45
The syslog server sees bursts up to a 1000/sec - but with such repeated startup/shutdown of the graylog syslog input channel, I don't think it would reach those actual peaks (but it could reach 90% of course)

**Comment by jhaar** [comment] 2015-07-31 01:23
FYI I just replaced syslog-ng with rsyslog and still have the problem. It works - but is continually experiencing tcp-resets - once every few seconds

**Comment by bernd** [comment] 2015-07-31 10:22
@jhaar Thanks for the update. I saw the issue as well but wasn't able to easily reproduce it yet. I only saw it every few minutes. I will let you know once I have more information.

**Comment by jhaar** [comment] 2015-08-04 09:13
FYI I just moved off using syslog/TCP to syslog/UDP and immediately saw graylog messages/sec leap for a factor of 4 times!! We were losing 75% of all TCP syslogs due to this issue

Thankfully the central syslog server is in the same rack as the graylog server - so using UDP is OK - but that certainly wouldn't be possible over WANs/etc

**Comment by lboue** [comment] 2015-08-04 09:25
In my case I had to setup rsyslog between syslog sender and graylog:
firewall ==>  rsyslog (syslog TCP/514) ==> graylog (syslog TCP/1514)

I using syslog/TCP to ensure message integrity and reading the last post I understand that I could lose messages.

**Comment by bernd** [comment] 2015-08-04 09:33
> FYI I just moved off using syslog/TCP to syslog/UDP and immediately saw graylog messages/sec leap for a factor of 4 times!! We were losing 75% of all TCP syslogs due to this issue

That's really bad. Thanks for the update again. I am on it.

**Comment by lboue** [comment] 2015-08-04 09:39
Could TCP keepalive solve this issue? 
Add TCP keepalive configuration option for TCP transport: https://github.com/Graylog2/graylog2-server/issues/1287

**Comment by bernd** [comment] 2015-08-04 16:25
@jhaar @lboue I found the problem in our Syslog handling.

The TCP RST was sent because Graylog closed the connection after an exception has been thrown. This just wasn't logged because we were missing a exception logger for the Netty pipeline. (will be fixed in #1340)

See https://github.com/Graylog2/graylog2-server/pull/1339 for a fix. This will be released in Graylog 1.2.0.

Thank you very much for all the debugging information!

**Closed** 2015-08-05 08:01 UTC
Labels: bug

**Comment by bernd** [comment] 2015-08-06 12:54
@jhaar @lboue We just released Graylog 1.1.6 which contains the fix! https://www.graylog.org/graylog-1-1-6-released/

**Comment by lboue** [comment] 2015-08-07 12:40
Thanks a lot for this fix ! I will try it soon

**Comment by jhaar** [comment] 2015-08-12 07:28
looking good. No more TCP resets :-)

**Comment by bernd** [comment] 2015-08-12 08:11
> looking good. No more TCP resets :-)

Great! Thanks for the feedback!
