### ISSUE TITLE
Autocompletion stopped working

### ISSUE THREAD

**Issue by paasi6666** [Graylog2/graylog2-server#18719] opened 2024-03-20 14:56 UTC
## Expected Behavior
Suggestion of fields in search-query. Strangely enough, this only happens on one of our two graylog servers (identical versions, different pipelines / streams, etc.). The Autocompletion worked perfectly fine about one week prior. Tried multiple browsers and multiple users, but same behaviour.

## Current Behavior
No fields are suggested:
![2024-03-20_150513](https://github.com/Graylog2/graylog2-server/assets/26493612/68bc3462-2f63-4e19-adad-429b22b9daa3)

Applications throws following error:
![2024-03-20_150447](https://github.com/Graylog2/graylog2-server/assets/26493612/6b54da4c-ac49-4f92-a575-1885856c58ef)

## Steps to Reproduce
Go to any stream or search and type anything into the search-query field.

The User-Option `Enable autocompletion` is enabled.
* Graylog Version: 5.2.5+7eaa89d
* Java Version: java 17 2021-09-14 LTS
* OpenSearch Version: 2.9.0
* MongoDB Version: 5.0.17

**Comment by dennisoelkers** [comment] 2024-03-27 14:01
Maybe related to #13883?

**Comment by dennisoelkers** [comment] 2024-03-27 14:03
Hey @paasi6666, thanks for reporting this! Which browser are you using? Does it happen all the time? I cannot reproduce it locally, so anything helping us to narrow it down would be great.

**Comment by luk-kaminski** [comment] 2024-07-17 09:20
@Emy-01 - our questions from March have not been answered, no similar issues appeared, I'd suggest closing it.

**Comment by luk-kaminski** [comment] 2024-09-20 09:27
Reproducing impossible, original reporter has not answered questions, we are closing the issue.

FYI: @kmerz

**Closed by luk-kaminski** 2024-09-20 09:27 UTC
Labels: bug, triaged, to-verify, Medium Prio
