### ISSUE TITLE
UTF-8 characters in large record sets are not exported correctly when exporting as csv

### ISSUE THREAD

**Issue by cheokjiade** [Graylog2/graylog2-server#9801] opened 2020-12-15 11:38 UTC
When exporting a large search (over 100,000 rows) as CSV, non english (e.g. Chinese/Tamil/Japanese) UTF8 characters are not exported properly and instead get exported as characters like "¶DÑ	lí_;¨ eô". The characters are displayed correctly in the graylog web interface.

## Expected Behavior
When exporting as CSV, UTF8 characters should be exported instead of being converted. Regardless of CSV file size.

## Current Behavior
When exporting a large search (over 100,000 rows) as CSV, non english (e.g. Chinese/Tamil/Japanese) UTF8 characters are not exported properly and instead get exported as characters like "¶DÑ	lí_;¨ eô".

## Steps to Reproduce (for bugs)
1. Log over 100,000 lines containing non-english characters
2. Export to csv

## Context
We are trying to export logs for analysis. However, the logs contain non-english characters which are not exported properly

## Your Environment

* Graylog Version: Graylog 3.3.5+6436f1b
* Java Version: OpenJDK 8
* Elasticsearch Version: 6.8
* MongoDB Version: 4.0
* Operating System: AWS Linux 2
* Browser version: Chrome  87.0.4280.88

**Comment by radykal-com** [comment] 2021-01-14 14:08
Does the encoding problem appears when exporting just a few rows?

**Comment by cheokjiade** [comment] 2021-01-22 02:47
Nope, we have exported around 60,000 rows with no issues.

**Comment by kmerz** [comment] 2023-11-24 10:02
This is a duplicate of [#9399](https://github.com/Graylog2/graylog2-server/issues/9399)

**Closed by kmerz** 2023-11-24 10:02 UTC
Labels: bug
