### ISSUE TITLE
stream_url no longer works in email notifications | hotlink removed from alert - 3.1

### ISSUE THREAD

**Issue by ahuxtable** [Graylog2/graylog2-server#6373] opened 2019-09-02 00:26 UTC
## Expected Behavior
When using code in an email notification like
`${if stream_url}More Info: ${stream_url}${end}`
I should get a link in an email notification to the stream generating the alert

A hotlink to the event used to also be in the alert itself (in the web interface), however this  appears to have been removed.

The 'ID' in the alert is not the ID of the log event generating the alert, but for the notification event itself, so can't just copy that and paste into search under streams to get the event details.

This means that locating the exact event generating the alert is awkward as you have to search the exact timestamp

## Current Behavior
stream_url does not contain a value, therefore does not appear

## Possible Solution
Both fine in 3.0, only since upgrade to 3.1 have this issue

## Steps to Reproduce (for bugs)
Create an email notification with the stream_url attribute and test.   stream_url is not populated.

## Context
Trying to have a simple way for semi-technical staff to further investigate events.

## Your Environment
Running version 3.1

**Comment by mpfz0r** [comment] 2019-09-02 07:53
Thank you for you report.
This is already on our todo-list
Duplicate of #6203

**Closed by mpfz0r** 2019-09-02 07:53 UTC
