### ISSUE TITLE
Posthog cookie with suboptimal domain

### ISSUE THREAD

**Issue by ed-graylog** [Graylog2/graylog2-server#17977] opened 2024-01-18 05:37 UTC
## What?
Currently when using graylog we see large 4k size cookies being set for domains such as example.com when in reality we have gl hosted on internal.example.com. This means this cookie is sent to all internal websites when telemetry is enabled which can be problematic.

Either this should be set to the actual domain internal.example.com or be configurable perhaps in the server.conf file.

## Why?

It is too large (3851 byte with telemetry enabled) and contains rather detailed information about the graylog installation. It doesn’t make any sense to share this information with any arbitrary website in our organization. 

## Your Environment

* Graylog Version: 5.2.3

This is tied to HS - 2253423458

**Comment by dennisoelkers** [comment] 2024-01-18 07:07
This is a duplicate of #17745, so I am closing this issue. If you have any additional information, please add it to the original issue.

**Closed by dennisoelkers** 2024-01-18 07:07 UTC
Labels: feature
