### ISSUE TITLE
Sidecar "Can not validate configuration path" log message is not specific enough

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#5049] opened 2018-09-02 23:25 UTC
Configuring rsyslog with this configuration file path:

```
/etc/rsyslog.d/51-graylog.conf
```

Sidecar cannot start process and fails with:

```
time="2018-09-02T18:21:06-05:00" level=error msg="Can not validate configuration path" 
```

1. It's confusing that the process is reported as "running" and shows as green
1. I'm not sure what that message means. Is the path malformed? Are there missing write permissions?

It works after I `sudo touch /etc/rsyslog.d/51-graylog.conf `.

## Your Environment

* Graylog Version: `3.0.0-alpha.2-SNAPSHOT+73c96fa`

**Comment by bernd** [comment] 2018-09-03 06:27
@lennartkoopmann I think this is the problem I described in https://github.com/Graylog2/collector-sidecar/issues/279.

**Comment by lennartkoopmann** [comment] 2018-09-03 17:27
Yes, that looks good. Thanks!

**Comment by mpfz0r** [comment] 2018-09-12 12:27
I'm closing this as a duplicate of Graylog2/collector-sidecar#279

**Closed by mpfz0r** 2018-09-12 12:27 UTC
Labels: bug, sidecar, triaged
