### ISSUE TITLE
LDAP settings service does not create collection

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#1117] opened 2015-04-16 10:21 UTC
When the collection is missing, the UI shows LDAP to be enabled, but actually saving any changes fails due to a 404 on loading the settings.

**Comment by joschi** [comment] 2015-06-02 10:54
I can't reproduce this. Opening the LDAP configuration dialog and saving the configuration works for me even if the `ldap_settings` collection didn't exist before in MongoDB.

MongoDB Collections are automatically created on first access and do not need to be created explicitly (unless special settings should be used, e. g. for capped collections).

@kroepke Could you please elaborate on the problem?

**Comment by joschi** [comment] 2015-06-02 11:59
Closed as issue can't be reproduced.

**Closed by joschi** 2015-06-02 11:59 UTC
Labels: bug
