### ISSUE TITLE
Support for multiple plugin directories

### ISSUE THREAD

**Issue by mribichich** [Graylog2/graylog2-server#4811] opened 2018-05-28 20:24 UTC
## Expected Behavior
Graylog should have two different folders for plugins. One for the ones that graylog ships with, managed by graylog project, and another one for volume mounting in docker for users that want to install a new plugin or several

## Current Behavior
In order to mount a plugins volume the User has to override the whole folder. And it makes it very difficult to manage, since every time a new version is pulled, we have to copy the new plugins first and then remount the volume. 

I know the docs say that we could mount each plugin file separately, but if you are using several its kind of unmanaged. Mounting a whole folder would be much easier

## Possible Solution
Have a second folder, for user plugins to install. That way we dont mess with graylog plugin folder, and we could mount a whole folder full of plugins without overriding graylogs

For situations where the same plugin its in both folders, graylog could choose the one from the user.

Graylog could merge both folders without a problem

Thanks

**Comment by jalogisch** [comment] 2018-05-30 07:14
Duplicate of https://github.com/Graylog2/graylog2-server/issues/2854

**Closed by jalogisch** 2018-05-30 07:14 UTC
Labels: feature, triaged

**Comment by mribichich** [comment] 2018-05-30 19:06
sorry tried to look for it, but didnt find it. thanks
