### ISSUE TITLE
Lowercase LDAP login name to avoid account duplicates

### ISSUE THREAD

**Issue by maxkochubey** [Graylog2/graylog2-server#4325] opened 2017-11-08 04:47 UTC
## Expected Behavior

Enter to web UI with my old good account.

## Current Behavior

When I logged on into Graylog web UI using my LDAP account, I have entered first capital in my login name by mistake ("M.kochubey" instead of "m.kochubey"). So Graylog created new account with same name, but without any permissions and connections to my roles.

## Possible Solution

It would make sense to lowercase username in login form field, when user account mapped from Active Directory - as far as I know, there's no difference in upper and lower case letters for AD.

## Steps to Reproduce (for bugs)

1. Setup LDAP/AD mapping for user authentication (my user search filter is "(&(objectClass=user)(sAMAccountName={0})(mail={0}@example.com))")
2. Add some roles to one of accounts from AD (e.g. admin role)
3. Log out and log in using this AD account and password, but first capital letter in login name

## Your Environment

* Graylog Version: 2.3.2+3df951e with user accounts mapped from LDAP (Active Directory)
* Elasticsearch Version: 5.6.3
* MongoDB Version: 3.4.9
* Operating System: Ubuntu 16.04, kernel 4.11.0-14-generic
* Browser version: Google Chrome 62.0.3202.62

**Comment by jalogisch** [comment] 2017-11-08 08:16
Duplicate of https://github.com/Graylog2/graylog2-server/issues/3946

similar to https://github.com/Graylog2/graylog2-server/issues/1361

**Closed by jalogisch** 2017-11-08 08:16 UTC
