### ISSUE TITLE
hn.a.setWidgetsToSearch is not a function

### ISSUE THREAD

**Issue by edward-marrufo** [Graylog2/graylog2-server#11107] opened 2021-08-03 16:14 UTC
When upgrading from Graylog 4.0 to any other version I am seeing the above message in the GUI
## Expected Behavior

Immediately upon upgrading from 4.0 to 4.1.2 (or any version) we should be greeted with either the standard search bar or the guide to help.
## Current Behavior

What happens in the upgrade going from 4.0.6 to 4.1.2 we see the above error in the GUI along with the monkey and banana screen. This does happen on both Firefox and Safari that I tested.

See HS-506579305
## Possible Solution

I'm not sure how to fix the code however the work around solution  I have discovered is to delete ALL the files in the plugins directory. In my CentOS7 environment this is located at /usr/share/graylog/plugin. Once I delete all of the plugins, I force a reinstall of the entire ecosystem including plugins. A reinstall of the plugins or the server alone will NOT resolve the issue. You must delete the plugin files and **_then_** reinstall everything. Here is a list of the exact commands I use.

(in plugins directory)
systemctl stop graylog-server
rm -f *
yum reinstall graylog-server graylog-enterprise graylog-enterprise-integrations-plugins graylog-enterprise-plugins 
graylog-integrations-plugins -y
systemctl start graylog-server

## Steps to Reproduce (for bugs)

I was able to reproduce this bug in my lab using an image, however I was not able to reproduce it otherwise.

Immediately upon staring up my instance using systemctl start graylog-server I direct my work computer browser (Firefox) to the following url

http://192.168.1.100:9000/gettingstarted

I hit the dismiss guide button and then am directed to the following url

http://192.168.1.100:9000/search?q=&rangetype=relative&relative=300

No matter if I hit the Graylog icon button on upper left side or the search button, I get the same error.

## Context

I am getting this error on the upgrade. Even after a reboot and a hard refresh the issue persists.

## Your Environment

* Graylog Version: Graylog 4.0.6 initial install upgrading to 4.1.2
* Java Version: OpenJDK Runtime Environment (build 1.8.0_282-b08)
* Elasticsearch Version: 7.10.0-1
* MongoDB Version: 4.0.23-1.el7
* Operating System: CentOS 7
* Browser version: Firefox 90.0.2 (64-bit)

Full stack trace

```
TypeError: hn.a.setWidgetsToSearch is not a function
    nm WidgetFocusProvider.tsx:86
    cs vendor.53480e037b0a599cf54a.js:2
    Oc vendor.53480e037b0a599cf54a.js:2
    unstable_runWithPriority vendor.53480e037b0a599cf54a.js:2
    Ua vendor.53480e037b0a599cf54a.js:2
    Ac vendor.53480e037b0a599cf54a.js:2
    sc vendor.53480e037b0a599cf54a.js:2
    Qa vendor.53480e037b0a599cf54a.js:2
    unstable_runWithPriority vendor.53480e037b0a599cf54a.js:2
    Ua vendor.53480e037b0a599cf54a.js:2
    Qa vendor.53480e037b0a599cf54a.js:2
    Va vendor.53480e037b0a599cf54a.js:2
    nc vendor.53480e037b0a599cf54a.js:2
    yo vendor.53480e037b0a599cf54a.js:2
    a UseLoadView.ts:38
    promise callback*e ViewLoader.ts:45
    d ViewLoader.ts:57
    s bluebird.js:5370
    _settlePromiseFromHandler bluebird.js:3366
    _settlePromise bluebird.js:3423
    _settlePromise0 bluebird.js:3468
    _settlePromises bluebird.js:3548
    l bluebird.js:145
    c bluebird.js:138
    _drainQueues bluebird.js:154
    drainQueues bluebird.js:67
    promise callback*i bluebird.js:4593
    _queueTick bluebird.js:163
    settlePromises bluebird.js:128
    _fulfill bluebird.js:3494
    _resolveCallback bluebird.js:3285
    r bluebird.js:3338
    o vendor.53480e037b0a599cf54a.js:2
    n vendor.53480e037b0a599cf54a.js:2
    emit vendor.53480e037b0a599cf54a.js:2
    trigger vendor.53480e037b0a599cf54a.js:2
    triggerAsync vendor.53480e037b0a599cf54a.js:2
    <anonymous> task.js:52
    b task.js:25
    A task.js:36
vendor.53480e037b0a599cf54a.js:2:299786
```

Screenshot.

<img width="1781" alt="image" src="https://user-images.githubusercontent.com/73505502/128240488-2dac0109-6d59-4c2a-ac3b-6a80cd76b287.png">

**Comment by edward-marrufo** [comment] 2021-08-04 19:11
Upgrade log mentions 4.1.3 but this also happens with 4.1.2 as mentioned yesterdau

Resolving Dependencies
--> Running transaction check
---> Package graylog-enterprise-integrations-plugins.noarch 0:4.0.6-1 will be updated
---> Package graylog-enterprise-integrations-plugins.noarch 0:4.1.3-1 will be an update
---> Package graylog-enterprise-plugins.noarch 0:4.0.6-1 will be updated
---> Package graylog-enterprise-plugins.noarch 0:4.1.3-1 will be an update
---> Package graylog-integrations-plugins.noarch 0:4.0.6-1 will be updated
---> Package graylog-integrations-plugins.noarch 0:4.1.3-1 will be an update
---> Package graylog-server.noarch 0:4.0.6-1 will be updated
---> Package graylog-server.noarch 0:4.1.3-1 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

**Comment by edmundoa** [comment] 2021-08-05 10:52
@edward-marrufo I have been trying to reproduce the issue in a VM and using tarballs, to have more control of the system. So far I have been able to reproduce the issue only when I leave an outdated enterprise plugin in there:

```
$ java -jar graylog.jar server -l -f ../graylog.conf
2021-08-05 10:47:12,929 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Enterprise Integrations 4.1.3 [org.graylog.enterprise.integrations.EnterpriseIntegrationsPlugin]
2021-08-05 10:47:12,933 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Integrations 4.1.3 [org.graylog.integrations.IntegrationsPlugin]
2021-08-05 10:47:12,934 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Graylog Enterprise 4.0.11 [org.graylog.plugins.enterprise.EnterprisePlugin]
2021-08-05 10:47:12,935 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Elasticsearch 6 Support 4.1.3+9d79c05 [org.graylog.storage.elasticsearch6.Elasticsearch6Plugin]
2021-08-05 10:47:12,936 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Elasticsearch 7 Support 4.1.3+9d79c05 [org.graylog.storage.elasticsearch7.Elasticsearch7Plugin]
(...)
```

```
$ ls -l ./graylog/test-graylog/plugin
total 150000
-rw-r--r-- 1 vagrant vagrant 31779847 Aug  5 10:40 graylog-plugin-enterprise-4.0.11.jar
-rw-r--r-- 1 vagrant vagrant 35816703 Aug  5 10:41 graylog-plugin-enterprise-integrations-4.1.3.jar
-rw-r--r-- 1 vagrant vagrant 32868952 Aug  5 10:44 graylog-plugin-integrations-4.1.3.jar
-rw-r--r-- 1 vagrant vagrant 23280154 Aug  5 10:47 graylog-storage-elasticsearch6-4.1.3.jar
-rw-r--r-- 1 vagrant vagrant 29843669 Aug  5 10:47 graylog-storage-elasticsearch7-4.1.3.jar
```

Replacing that `graylog-plugin-enterprise-4.0.11.jar` with the 4.1.3 version and adding both `graylog-plugin-enterprise-es7-4.1.3.jar` and `graylog-plugin-enterprise-es6-4.1.3.jar`, makes the problem disappear. Could you please verify that the packages are updating the plugins in your system?

**Comment by edmundoa** [comment] 2021-08-05 13:31
@edward-marrufo since I was wondering if our rpm packages were doing something wrong, I spun up a CentOS VM and tried doing the upgrade. Other than my own ignorance about yum and how it works, I could successfully upgrade Graylog 4.0.11 to 4.1.3 and everything seems to be working. Here is the gist of how I did the upgrade:

```
$ sudo systemctl stop graylog-server.service
$ ls /usr/share/graylog-server/plugin/
graylog-plugin-aws-4.0.11.jar        graylog-plugin-enterprise-4.0.11.jar               graylog-plugin-integrations-4.0.11.jar  graylog-storage-elasticsearch6-4.0.11.jar  LICENSE-ENTERPRISE
graylog-plugin-collector-4.0.11.jar  graylog-plugin-enterprise-integrations-4.0.11.jar  graylog-plugin-threatintel-4.0.11.jar   graylog-storage-elasticsearch7-4.0.11.jar
$ sudo rpm -Uvh https://packages.graylog2.org/repo/packages/graylog-4.1-repository_latest.rpm
$ sudo yum clean all
$ sudo yum update
$ ls /usr/share/graylog-server/plugin/
graylog-plugin-aws-4.1.3.jar         graylog-plugin-enterprise-es6-4.1.3.jar           graylog-plugin-integrations-4.1.3.jar     graylog-storage-elasticsearch7-4.1.3.jar
graylog-plugin-collector-4.1.3.jar   graylog-plugin-enterprise-es7-4.1.3.jar           graylog-plugin-threatintel-4.1.3.jar      LICENSE-ENTERPRISE
graylog-plugin-enterprise-4.1.3.jar  graylog-plugin-enterprise-integrations-4.1.3.jar  graylog-storage-elasticsearch6-4.1.3.jar
$ sudo systemctl start graylog-server.service
```

So far I haven't seen the mentioned error, so I will need more information on your end to continue investigating.

**Comment by edward-marrufo** [comment] 2021-08-05 16:07
@edmundoa I figured out exactly what was causing it. I don't recall how I upgraded this particular instance earlier however it appears there is a "fake" plugin (old) in the plugin directory with a .bak extension. I don't recall if this .bak plugin was created by GL during an upgrade from 3.3 or if it came from somewhere else. Here is a directory listing before the upgrade

`-rw-r--r--. 1 root root 20239834 Apr  7 09:58 graylog-plugin-aws-4.0.6.jar
-rw-r--r--. 1 root root  6463542 Apr  7 09:58 graylog-plugin-collector-4.0.6.jar
-rw-r--r--. 1 root root 31779416 Apr  7 09:59 graylog-plugin-enterprise-4.0.6.jar
-rw-r--r--. 1 root root 31779416 Apr 22 11:07 graylog-plugin-enterprise-4.0.6.jar.bak
-rw-r--r--. 1 root root 23319834 Apr  7 09:59 graylog-plugin-enterprise-integrations-4.0.6.jar
-rw-r--r--. 1 root root 32429185 Apr  7 09:59 graylog-plugin-integrations-4.0.6.jar
-rw-r--r--. 1 root root  7997116 Apr  7 09:58 graylog-plugin-threatintel-4.0.6.jar
-rw-r--r--. 1 root root 23274748 Apr  7 09:58 graylog-storage-elasticsearch6-4.0.6.jar
-rw-r--r--. 1 root root 29840232 Apr  7 09:58 graylog-storage-elasticsearch7-4.0.6.jar
-rw-r--r--. 1 root root       48 Apr  7 09:59 LICENSE-ENTERPRISE`

After the upgrade here is the same directory listing.

`-rw-r--r--. 1 root root 22822077 Aug  4 11:02 graylog-plugin-aws-4.1.3.jar
-rw-r--r--. 1 root root  7050134 Aug  4 11:02 graylog-plugin-collector-4.1.3.jar
-rw-r--r--. 1 root root 31779416 Apr 22 11:07 graylog-plugin-enterprise-4.0.6.jar.bak
-rw-r--r--. 1 root root 55930399 Aug  4 11:03 graylog-plugin-enterprise-4.1.3.jar
-rw-r--r--. 1 root root    16580 Aug  4 11:03 graylog-plugin-enterprise-es6-4.1.3.jar
-rw-r--r--. 1 root root    16568 Aug  4 11:03 graylog-plugin-enterprise-es7-4.1.3.jar
-rw-r--r--. 1 root root 35816703 Aug  4 11:04 graylog-plugin-enterprise-integrations-4.1.3.jar
-rw-r--r--. 1 root root 32868952 Aug  4 11:03 graylog-plugin-integrations-4.1.3.jar
-rw-r--r--. 1 root root  8581100 Aug  4 11:02 graylog-plugin-threatintel-4.1.3.jar
-rw-r--r--. 1 root root 23280154 Aug  4 11:02 graylog-storage-elasticsearch6-4.1.3.jar
-rw-r--r--. 1 root root 29843669 Aug  4 11:02 graylog-storage-elasticsearch7-4.1.3.jar
-rw-r--r--. 1 root root       48 Aug  4 11:03 LICENSE-ENTERPRISE`

After the upgrade is still when I am getting the error if that .bak plugin is there.

GL server log if we leave the .bak plugin in there.

`2021-08-05T09:27:35.503-05:00 INFO  [CmdLineTool] Loaded plugin: AWS plugins 4.1.3 [org.graylog.aws.AWSPlugin]
2021-08-05T09:27:35.505-05:00 INFO  [CmdLineTool] Loaded plugin: Enterprise Integrations 4.1.3 [org.graylog.enterprise.integrations.EnterpriseIntegrationsPlugin]
2021-08-05T09:27:35.506-05:00 INFO  [CmdLineTool] Loaded plugin: Integrations 4.1.3 [org.graylog.integrations.IntegrationsPlugin]
2021-08-05T09:27:35.507-05:00 INFO  [CmdLineTool] Loaded plugin: Collector 4.1.3 [org.graylog.plugins.collector.CollectorPlugin]
2021-08-05T09:27:35.507-05:00 INFO  [CmdLineTool] Loaded plugin: Graylog Enterprise 4.0.6 [org.graylog.plugins.enterprise.EnterprisePlugin]
2021-08-05T09:27:35.508-05:00 INFO  [CmdLineTool] Loaded plugin: Graylog Enterprise (ES6 Support) 4.1.3 [org.graylog.plugins.enterprise.org.graylog.plugins.enterprise.es6.EnterpriseES6Plugin]
2021-08-05T09:27:35.508-05:00 INFO  [CmdLineTool] Loaded plugin: Graylog Enterprise (ES7 Support) 4.1.3 [org.graylog.plugins.enterprise.org.graylog.plugins.enterprise.es7.EnterpriseES7Plugin]
2021-08-05T09:27:35.512-05:00 INFO  [CmdLineTool] Loaded plugin: Threat Intelligence Plugin 4.1.3 [org.graylog.plugins.threatintel.ThreatIntelPlugin]
2021-08-05T09:27:35.512-05:00 INFO  [CmdLineTool] Loaded plugin: Elasticsearch 6 Support 4.1.3+9d79c05 [org.graylog.storage.elasticsearch6.Elasticsearch6Plugin]
2021-08-05T09:27:35.512-05:00 INFO  [CmdLineTool] Loaded plugin: Elasticsearch 7 Support 4.1.3+9d79c05 [org.graylog.storage.elasticsearch7.Elasticsearch7Plugin]`


here is the GL server log if we remove that .bak plugin entirely

`2021-08-05T09:40:39.711-05:00 INFO  [CmdLineTool] Loaded plugin: AWS plugins 4.1.3 [org.graylog.aws.AWSPlugin]
2021-08-05T09:40:39.716-05:00 INFO  [CmdLineTool] Loaded plugin: Enterprise Integrations 4.1.3 [org.graylog.enterprise.integrations.EnterpriseIntegrationsPlugin]
2021-08-05T09:40:39.717-05:00 INFO  [CmdLineTool] Loaded plugin: Integrations 4.1.3 [org.graylog.integrations.IntegrationsPlugin]
2021-08-05T09:40:39.717-05:00 INFO  [CmdLineTool] Loaded plugin: Collector 4.1.3 [org.graylog.plugins.collector.CollectorPlugin]
2021-08-05T09:40:39.717-05:00 INFO  [CmdLineTool] Loaded plugin: Graylog Enterprise 4.1.3 [org.graylog.plugins.enterprise.EnterprisePlugin]
2021-08-05T09:40:39.718-05:00 INFO  [CmdLineTool] Loaded plugin: Graylog Enterprise (ES6 Support) 4.1.3 [org.graylog.plugins.enterprise.org.graylog.plugins.enterprise.es6.EnterpriseES6Plugin]
2021-08-05T09:40:39.718-05:00 INFO  [CmdLineTool] Loaded plugin: Graylog Enterprise (ES7 Support) 4.1.3 [org.graylog.plugins.enterprise.org.graylog.plugins.enterprise.es7.EnterpriseES7Plugin]
2021-08-05T09:40:39.719-05:00 INFO  [CmdLineTool] Loaded plugin: Threat Intelligence Plugin 4.1.3 [org.graylog.plugins.threatintel.ThreatIntelPlugin]
2021-08-05T09:40:39.719-05:00 INFO  [CmdLineTool] Loaded plugin: Elasticsearch 6 Support 4.1.3+9d79c05 [org.graylog.storage.elasticsearch6.Elasticsearch6Plugin]
2021-08-05T09:40:39.719-05:00 INFO  [CmdLineTool] Loaded plugin: Elasticsearch 7 Support 4.1.3+9d79c05 [org.graylog.storage.elasticsearch7.Elasticsearch7Plugin]`

**Comment by edmundoa** [comment] 2021-08-06 09:41
@edward-marrufo thank you for the details!

Looking at the version (4.0.6) and date the file was accessed (Apr 22), my wild guess is that it was done by hand while testing something and then forgot in there. Anyway, I wasn't expecting Graylog loading `.bak` files as plugins, so I opened https://github.com/Graylog2/graylog2-server/issues/11122 for that.

By the way, does removing the `.bak` plugin fix the issue for you? If so, I think the cause of this issue was found and it can be closed.

**Comment by edward-marrufo** [comment] 2021-08-06 15:08
@edmundoa yes removing the file completely resolves the issue. You do need to do a hard refresh  (command shift r on firefox mac) in order to avoid reloading from cache however.

**Comment by edmundoa** [comment] 2021-08-06 15:14
@edward-marrufo Thank you for information!

That is true, I'm so used to do that when restarting Graylog that I missed that :D

Then I'll close the issue, please reopen if you see the issue again or can reproduce it in another way.

**Closed by edmundoa** 2021-08-06 15:14 UTC
Labels: bug
