### ISSUE TITLE
enable dots in field names / remove auto replace `.` to `_` in field names

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#8539] opened 2020-07-14 10:03 UTC
## Expected Behavior
It should be possible to configure that you can have the current behaviour of replacing `.` in field names with a `_` or that you want to keep them.

## Current Behavior
The dot is replaced and you need to access the field name during processing with the dot, but when stored the dot is replaced by underscore. 

## Possible Solution
Make it possible to configure this would be the best to not break older setups but give new setups the ability to work consistent. 

## Context
In the past Elasticsearch did not allowed dots in field names for some versions and as a fix we have implemented a replacement during the serialisation of the data that is written to elasticsearch. 

https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/plugin/Message.java#L364

This was the fix to avoid message lost with ingestion errors - at the next version Elasticsearch allowed dots in field names again but we where not able to simple switch back. 

As our current supported elasticsearch version all allow dots in field names, but removing this replacement might create issues with dashboards and reporting (and searches at all) for existing setups it should be configuration option if the replacement should be done or not.

## Your Environment

* Graylog Version: 3

**Comment by kroepke** [comment] 2020-07-14 12:04
Duplicate of https://github.com/Graylog2/graylog2-server/issues/4583
Also see https://github.com/Graylog2/graylog2-server/pull/5983 for discussion.

**Closed by kroepke** 2020-07-14 12:04 UTC
Labels: bug
