### ISSUE TITLE
Add possibility to stop Inputs, if journal utilization too high

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2334] opened 2016-06-06 07:51 UTC
### Problem description
If there is some problem with ES and messages could not be flushed from journal, current behaviour is to drop old messages from journal and write new ones.
In that case old messages are lost forever.

It will be good to be able to just stop inputs. In that case log collectiors will stop crawling logs until ES repaired and Inputs started again. So no logs will be lost.

### Environment
* Graylog Version: 2.0.2

**Comment by joschi** [comment] 2016-06-06 08:14
Basically a duplicate of #2312.

**Closed by joschi** 2016-06-06 08:14 UTC
