### ISSUE TITLE
Problem loading notification config from Content Pack for Plugin

### ISSUE THREAD

**Issue by cablespaghetti** [Graylog2/graylog2-server#7801] opened 2020-04-01 09:41 UTC
## Expected Behavior
When I load the content pack it installs correctly with my notification config for this slack notification plugin: https://github.com/sportalliance/graylog-plugin-slack-notification

The reason I'm raising here is because I've been unable to see any problems with the code in the plugin so am hoping someone more familiar with this part of the source code might be able to point me in the right direction.

I've already tried updating everything to the latest v3.2.4 parent poms etc.

## Current Behavior
This stack trace happens where slack-notification-v1 isn't present in the POJO:
```
2020-04-01 08:39:08,341 ERROR   [ContentPackLoaderPeriodical] - Uncaught exception in periodical - {}
org.graylog2.contentpacks.exceptions.ContentPackException: Failed to install content pack <f671636f-126d-4ea8-ae60-332fa1b80b47/1>
        at org.graylog2.contentpacks.ContentPackService.installContentPack(ContentPackService.java:158) ~[graylog.jar:?]
        at org.graylog2.contentpacks.ContentPackService.installContentPack(ContentPackService.java:99) ~[graylog.jar:?]
        at org.graylog2.periodical.ContentPackLoaderPeriodical.doRun(ContentPackLoaderPeriodical.java:182) ~[graylog.jar:?]
        at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.IllegalArgumentException: Could not resolve type id 'slack-notification-v1' as a subtype of [simple type, class org.graylog.events.contentpack.entities.EventNotificationConfigEntity]: known type ids = [email-notification-v1, http-notification-v1, legacy-alarm-callback-notification-v1] (for POJO property 'config')
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.graylog.events.contentpack.entities.AutoValue_NotificationEntity$Builder["config"])
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3751) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3669) ~[graylog.jar:?]
        at org.graylog.events.contentpack.facade.NotificationFacade.decode(NotificationFacade.java:93) ~[graylog.jar:?]
        at org.graylog.events.contentpack.facade.NotificationFacade.createNativeEntity(NotificationFacade.java:84) ~[graylog.jar:?]
        at org.graylog2.contentpacks.ContentPackService.installContentPack(ContentPackService.java:149) ~[graylog.jar:?]
        ... 4 more
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'slack-notification-v1' as a subtype of [simple type, class org.graylog.events.contentpack.entities.EventNotificationConfigEntity]: known type ids = [email-notification-v1, http-notification-v1, legacy-alarm-callback-notification-v1] (for POJO property 'config')
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.graylog.events.contentpack.entities.AutoValue_NotificationEntity$Builder["config"])
        at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.DeserializationContext.invalidTypeIdException(DeserializationContext.java:1635) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownTypeId(DeserializationContext.java:1187) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleUnknownTypeId(TypeDeserializerBase.java:291) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:162) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:113) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:167) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:269) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:193) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3746) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3669) ~[graylog.jar:?]
        at org.graylog.events.contentpack.facade.NotificationFacade.decode(NotificationFacade.java:93) ~[graylog.jar:?]
        at org.graylog.events.contentpack.facade.NotificationFacade.createNativeEntity(NotificationFacade.java:84) ~[graylog.jar:?]
        at org.graylog2.contentpacks.ContentPackService.installContentPack(ContentPackService.java:149) ~[graylog.jar:?]
        ... 4 more
```

## Possible Solution
Guide me to where in the plugin or graylog source code the addition to this list is missing and I'm happy to raise PRs etc.

## Steps to Reproduce (for bugs)
Create a content pack and download the JSON from Graylog 3.2.4 and then try and install it in another Graylog 3.2.4 instance.

## Context
Trying to automate rolling out a content pack to a number of graylog instances with this slack notification configuration.

## Your Environment
Kubernetes using Graylog in Docker loading content packs from JSON in a ConfigMap. Although I don't think for this particular bug it matters.

* Graylog Version: 3.2.4

**Comment by will-graylog** [comment] 2022-06-04 01:11
I can confirm this still occurs in v4.2.6. Steps to reproduce:

1. Brand new 4.2.6 install.
2. Create Notification named "test", type "Slack notification"
3. Fill in "Webhook URL" and "Channel" fields accordingly, then Create the Notification.
4. Create new Content Pack named "test", add only the Notification you just made. Create and Download.
5. Open Content Pack in word processor and inspect the JSON. You will see the `data.type` field says "slack-notification-v1", so presumably this is an acceptable Notification Type option.
6. Delete All Versions of the Content Pack in the Web UI, then upload (this part succeeds).
7. Install the new Content Pack and error appears in Web UI indicating failure to install.

Server.log shows exactly the error OP reported. It appears the system believes the only acceptable Notification Types are `email-notification-v1, http-notification-v1, legacy-alarm-callback-notification-v1`.

The impact is that people cannot install any content packs that include a Slack Notification in their Alerting config.

**Comment by danotorrey** [comment] 2022-08-02 16:26
Thanks for the report @cablespaghetti. Thanks also for the additional investigation @will-graylog.

This was indeed an issue in the Graylog core for several notification types. A fix for those types is available here: https://github.com/Graylog2/graylog2-server/pull/13171 and https://github.com/Graylog2/graylog-plugin-enterprise-integrations/pull/859. This will be included in an upcoming Graylog release.

Note that the original issue reported by @cablespaghetti is for a third-party Slack notification (https://github.com/sportalliance/graylog-plugin-slack-notification), which Graylog does not support. But, since the cause of the issue is clear, I have filed a PR there (https://github.com/sportalliance/graylog-plugin-slack-notification/pull/64) to hopefully contribute a fix there too.

**Closed** 2022-08-05 16:09 UTC
Labels: bug, triaged, content-packs
