### ISSUE TITLE
Duplicate accounts created for LDAP users when user-provided username case varies

### ISSUE THREAD

**Issue by supahgreg** [Graylog2/graylog2-server#2259] opened 2016-05-19 04:19 UTC
### Problem description
Duplicate accounts get created for LDAP users when the letter casing of the username provided during authentication varies (e.g. "tester" vs "Tester" vs "TeStEr").  Among other things, this results in the user having a unique set of profile values per username version.

### Steps to reproduce the problem
1. Import "graylog-2.0.1-1.ova"
2. Verify you can log into Graylog after startup
3. Install OpenLDAP
4. Create a LDAP user "tester" and group, and add the user to the group
4. Configure Graylog to use the LDAP server and its users and groups
5. Assign the LDAP group to a role
6. Using a clean browser session, log in as "tester".  Edit the profile to use an arbitrary timezone.
6. Using another clean browser session, log in as "TESTER".  Note that "tester" and "TESTER" are now listed in the Username column on "/system/users", and the "TESTER" user does not have the timezone you set for "tester".

### Environment
* Graylog Version:  2.0.1  ("graylog-2.0.1-1.ova")
* Elasticsearch Version:  2.3.1
* MongoDB Version:  3.2.5
* Operating System:  Ubuntu 14.04.4 (x86_64)
* Browser version:  Firefox 46

This has also been observed in an Active Directory / Chef-installed environment with the same versions.

**Comment by joschi** [comment] 2016-05-19 08:49
@supahgreg Thanks for reporting this! I'll close this issue as a duplicate of #1361.

**Closed by joschi** 2016-05-19 08:49 UTC

**Comment by supahgreg** [comment] 2016-05-19 11:34
Oops, sorry I missed that!
