### ISSUE TITLE
Input Extractors not displayed with correct order

### ISSUE THREAD

**Issue by ap-wtioit** [Graylog2/graylog2-server#15101] opened 2023-03-30 07:51 UTC
The input extractors in System/Inputs are sorted in string order of the order attribute when the order attribute is actually an integer and therefore it should be sorted as an integer

## Expected Behavior
When rendering the json:
```json
{
	
	"extractors": [
		{
			"title": "First",
			"order": 1,
		},
		{
			"title": "Second",
			"order": 2,
		},
		{
			"title": "Ninth",
			"order": 9,
		}
		{
			"title": "Eleventh",
			"order": 11,
		}
	]
}
```
The display order should be:
* First
* Second
* Ninth
* Eleventh

## Current Behavior
The display order is:
* First
* Second
* Eleventh
* Ninth

## Steps to Reproduce (for bugs)

1. Create an input
2. Add Extractors like in the above json (or just more than 10)
3. Make sure you have unique orders
4. Extractor with numerical order 9 is string sorted at the end of the list

## Context
It's really hard to get the correct order for extractors when extractors are not displayed in the order they are used.

## Your Environment

* Graylog Version: Graylog 5.0.5
* Java Version:
  ```
  openjdk version "17.0.6" 2023-01-17
  OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
  OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)
  ```
* Opensearch Version: Version: 2.6.0, Build: tar/7203a5af21a8a009aece1474446b437a3c674db6/2023-02-24T18:57:04.388618985Z, JVM: 17.0.6
* MongoDB Version:
  ```
  MongoDB shell version v5.0.15
  Build Info: {
      "version": "5.0.15",
      "gitVersion": "935639beed3d0c19c2551c93854b831107c0b118",
      "openSSLVersion": "OpenSSL 1.1.1f  31 Mar 2020",
      "modules": [],
      "allocator": "tcmalloc",
      "environment": {
          "distmod": "ubuntu2004",
          "distarch": "x86_64",
          "target_arch": "x86_64"
      }
  }
  ```
* Operating System: Debian GNU/Linux 10 (buster), Docker, Docker-Compose
* Browser version: Firefox 111.0.1 (64-bit)

**Comment by patrickmann** [comment] 2023-04-25 09:01
This is a duplicate of #15165 which was addressed for 5.1 by PR #14757.
We'll also use the original issue to track the backport.

**Closed as not planned** 2023-04-25 09:01 UTC
Labels: bug, triaged
