### ISSUE TITLE
Yellow ES cluster leads to graylog-server not starting

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#1196] opened 2015-05-30 18:43 UTC
On current `master` my `graylog-server` refuses to start if my Elasticsearch cluster state is yellow. I think it should only refuse to start if the state is red.

> ERROR: The Elasticsearch cluster state is RED which means shards are unassigned. This usually indicates a crashed and corrupt cluster and needs to be investigated. Graylog will shut down.

![screen shot 2015-05-30 at 1 43 21 pm](https://cloud.githubusercontent.com/assets/35022/7898797/e20d38d2-06d1-11e5-8ff4-59d6ead7ba08.png)

**Comment by lennartkoopmann** [comment] 2015-05-30 18:44
For reference the full output:

```
~/workspace/graylog2/graylog2-server(branch:master) » java -Djava.library.path=${GRAYLOGCTL_DIR}/../lib/sigar -Xms1g -Xmx1g -XX:NewRatio=1 -XX:PermSize=128m -XX:MaxPermSize=256m -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow -jar graylog2-bootstrap/target/graylog2.jar server
2015-05-30 13:39:14,605 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugins: [MongoDB profiler input 0.1.0 [c8237800-825b-11e4-b4a9-0800200c9a66], Librato Metrics 1.0.0 [5ea51750-8d08-11e4-b4a9-0800200c9a66], SplunkOutput 0.1.0 [com.graylog.SplunkOutputPlugin]]
2015-05-30 13:39:14,707 INFO : org.graylog2.bootstrap.CmdLineTool - Running with JVM arguments: -Djava.library.path=/../lib/sigar -Xms1g -Xmx1g -XX:NewRatio=1 -XX:PermSize=128m -XX:MaxPermSize=256m -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow
2015-05-30 13:39:15,452 INFO : org.graylog2.shared.system.stats.SigarService - Failed to load SIGAR. Falling back to JMX implementations.
2015-05-30 13:39:17,759 INFO : org.graylog2.shared.buffers.InputBufferImpl - Message journal is enabled.
2015-05-30 13:39:18,033 INFO : kafka.log.LogManager - Found clean shutdown file. Skipping recovery for all logs in data directory '/Users/lennart/workspace/graylog2/graylog2-server/data/journal'
2015-05-30 13:39:18,034 INFO : kafka.log.LogManager - Loading log 'messagejournal-0'
2015-05-30 13:39:18,078 INFO : kafka.log.Log - Completed load of log messagejournal-0 with log end offset 47902455
2015-05-30 13:39:18,090 INFO : org.graylog2.shared.journal.KafkaJournal - Initialized Kafka based journal at data/journal
2015-05-30 13:39:18,097 INFO : org.graylog2.shared.buffers.InputBufferImpl - Initialized InputBufferImpl with ring size <65536> and wait strategy <BlockingWaitStrategy>, running 2 parallel message handlers.
2015-05-30 13:39:18,277 INFO : org.graylog2.plugin.system.NodeId - Node ID: 4cfdad2d-c566-4876-910a-f6244ad177b0
2015-05-30 13:39:18,448 INFO : org.elasticsearch.node - [graylog2-server] version[1.5.2], pid[35418], build[62ff986/2015-04-27T09:21:06Z]
2015-05-30 13:39:18,448 INFO : org.elasticsearch.node - [graylog2-server] initializing ...
2015-05-30 13:39:18,457 INFO : org.elasticsearch.plugins - [graylog2-server] loaded [graylog2-monitor], sites []
2015-05-30 13:39:20,220 INFO : org.elasticsearch.node - [graylog2-server] initialized
2015-05-30 13:39:20,231 INFO : org.graylog2.shared.buffers.ProcessBuffer - Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2015-05-30 13:39:22,091 INFO : org.graylog2.bindings.providers.RulesEngineProvider - No static rules file loaded.
2015-05-30 13:39:22,144 INFO : org.graylog2.buffers.OutputBuffer - Initialized OutputBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2015-05-30 13:39:22,457 INFO : org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 5.1.3.Final
2015-05-30 13:39:22,864 INFO : org.graylog2.bootstrap.ServerBootstrap - Graylog server 1.1.0-rc.2-SNAPSHOT (3cde0f0) starting up. (JRE: Oracle Corporation 1.7.0_51 on Mac OS X 10.10.3)
2015-05-30 13:39:22,889 INFO : org.graylog2.shared.initializers.PeriodicalsService - Starting 19 periodicals ...
2015-05-30 13:39:22,889 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.ThroughputCounterManagerThread] periodical in [0s], polling every [1s].
2015-05-30 13:39:22,892 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.ThroughputCalculator] periodical in [0s], polling every [1s].
2015-05-30 13:39:22,892 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.AlertScannerThread] periodical in [10s], polling every [60s].
2015-05-30 13:39:22,893 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.BatchedElasticSearchOutputFlushThread] periodical in [0s], polling every [1s].
2015-05-30 13:39:22,893 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.ClusterHealthCheckThread] periodical in [0s], polling every [20s].
2015-05-30 13:39:22,895 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.ContentPackLoaderPeriodical] periodical, running forever.
2015-05-30 13:39:22,900 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.DeadLetterThread] periodical, running forever.
2015-05-30 13:39:22,901 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.GarbageCollectionWarningThread] periodical, running forever.
2015-05-30 13:39:22,903 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.IndexerClusterCheckerThread] periodical in [0s], polling every [30s].
2015-05-30 13:39:22,906 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.IndexRetentionThread] periodical in [0s], polling every [300s].
2015-05-30 13:39:22,907 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.IndexRotationThread] periodical in [0s], polling every [10s].
2015-05-30 13:39:22,908 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.NodePingThread] periodical in [0s], polling every [1s].
2015-05-30 13:39:22,908 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.StreamThroughputCounterManagerThread] periodical in [0s], polling every [1s].
2015-05-30 13:39:22,914 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.VersionCheckThread] periodical in [0s], polling every [1800s].
2015-05-30 13:39:22,915 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.ThrottleStateUpdaterThread] periodical in [1s], polling every [1s].
2015-05-30 13:39:22,916 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.events.ClusterEventPeriodical] periodical in [0s], polling every [1s].
2015-05-30 13:39:22,918 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.events.ClusterEventCleanupPeriodical] periodical in [0s], polling every [300s].
2015-05-30 13:39:22,920 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.ClusterIdGeneratorPeriodical] periodical, running forever.
2015-05-30 13:39:22,924 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.PurgeExpiredCollectorsThread] periodical in [0s], polling every [3600s].
2015-05-30 13:39:22,931 INFO : org.graylog2.periodical.IndexRetentionThread - Elasticsearch cluster not available, skipping index retention checks.
2015-05-30 13:39:23,058 INFO : org.elasticsearch.node - [graylog2-server] starting ...
2015-05-30 13:39:23,251 INFO : org.elasticsearch.transport - [graylog2-server] bound_address {inet[/0:0:0:0:0:0:0:0:9350]}, publish_address {inet[/172.31.99.206:9350]}
2015-05-30 13:39:23,276 INFO : org.elasticsearch.discovery - [graylog2-server] graylog-dev-lennart/DDDrc1VmQ42HhaE9nwnS9g
2015-05-30 13:39:23,534 INFO : org.reflections.Reflections - Reflections took 567 ms to scan 1 urls, producing 2 keys and 2 values 
2015-05-30 13:39:26,421 WARN : org.elasticsearch.discovery - [graylog2-server] waited for 3s and no initial state was set by the discovery
2015-05-30 13:39:26,421 INFO : org.elasticsearch.node - [graylog2-server] started
2015-05-30 13:39:26,573 INFO : org.elasticsearch.cluster.service - [graylog2-server] detected_master [Martha Johansson][uK1xY2ynSfiiJTlJ7Cg0yA][sundaysister.local][inet[/172.31.99.206:9300]], added {[Martha Johansson][uK1xY2ynSfiiJTlJ7Cg0yA][sundaysister.local][inet[/172.31.99.206:9300]],}, reason: zen-disco-receive(from master [[Martha Johansson][uK1xY2ynSfiiJTlJ7Cg0yA][sundaysister.local][inet[/172.31.99.206:9300]]])
2015-05-30 13:39:26,594 ERROR: org.graylog2.UI - 

################################################################################

ERROR: The Elasticsearch cluster state is RED which means shards are unassigned. This usually indicates a crashed and corrupt cluster and needs to be investigated. Graylog will shut down.

Need help?

* Official documentation: http://docs.graylog.org/
* Community support: https://www.graylog.org/community-support/
* Commercial support: https://www.graylog.com/support/

But we also got some specific help pages that might help you in this case:

* http://docs.graylog.org/en/1.0/pages/configuring_es.html

Terminating. :(

################################################################################

2015-05-30 13:39:26,596 ERROR: com.google.common.util.concurrent.ServiceManager - Service IndexerSetupService [FAILED] has failed in the STARTING state.
java.lang.IllegalStateException
	at org.graylog2.UI.exitHardWithWall(UI.java:36)
	at org.graylog2.initializers.IndexerSetupService.startUp(IndexerSetupService.java:137)
	at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:54)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
	at java.lang.Thread.run(Thread.java:744)
2015-05-30 13:39:26,598 ERROR: org.graylog2.shared.initializers.InputSetupService - Not starting any inputs because lifecycle is: Uninitialized [LB:DEAD]
2015-05-30 13:39:26,603 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.periodical.AlertScannerThread].
2015-05-30 13:39:26,603 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.periodical.AlertScannerThread] complete, took <0ms>.
2015-05-30 13:39:26,603 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.periodical.BatchedElasticSearchOutputFlushThread].
2015-05-30 13:39:26,603 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.periodical.BatchedElasticSearchOutputFlushThread] complete, took <0ms>.
2015-05-30 13:39:26,603 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.periodical.ClusterHealthCheckThread].
2015-05-30 13:39:26,603 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.periodical.ClusterHealthCheckThread] complete, took <0ms>.
2015-05-30 13:39:26,603 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.periodical.IndexerClusterCheckerThread].
2015-05-30 13:39:26,604 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.periodical.IndexerClusterCheckerThread] complete, took <0ms>.
2015-05-30 13:39:26,604 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.periodical.IndexRetentionThread].
2015-05-30 13:39:26,604 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.periodical.IndexRetentionThread] complete, took <0ms>.
2015-05-30 13:39:26,604 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.periodical.IndexRotationThread].
2015-05-30 13:39:26,604 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.periodical.IndexRotationThread] complete, took <0ms>.
2015-05-30 13:39:26,604 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.periodical.VersionCheckThread].
2015-05-30 13:39:26,604 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.periodical.VersionCheckThread] complete, took <0ms>.
2015-05-30 13:39:26,604 WARN : org.graylog2.initializers.BufferSynchronizerService - Elasticsearch is unavailable. Not waiting to clear buffers and caches, as we have no healthy cluster.
2015-05-30 13:39:26,604 INFO : org.elasticsearch.node - [graylog2-server] stopping ...
2015-05-30 13:39:26,604 INFO : org.graylog2.initializers.OutputSetupService - Stopping output org.graylog2.outputs.BlockingBatchedESOutput
2015-05-30 13:39:26,604 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.periodical.ThrottleStateUpdaterThread].
2015-05-30 13:39:26,604 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.periodical.ThrottleStateUpdaterThread] complete, took <0ms>.
2015-05-30 13:39:26,605 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.events.ClusterEventPeriodical].
2015-05-30 13:39:26,605 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.events.ClusterEventPeriodical] complete, took <0ms>.
2015-05-30 13:39:26,605 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.events.ClusterEventCleanupPeriodical].
2015-05-30 13:39:26,605 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.events.ClusterEventCleanupPeriodical] complete, took <0ms>.
2015-05-30 13:39:26,605 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutting down periodical [org.graylog2.periodical.PurgeExpiredCollectorsThread].
2015-05-30 13:39:26,605 INFO : org.graylog2.shared.initializers.PeriodicalsService - Shutdown of periodical [org.graylog2.periodical.PurgeExpiredCollectorsThread] complete, took <0ms>.
2015-05-30 13:39:26,629 INFO : org.elasticsearch.node - [graylog2-server] stopped
2015-05-30 13:39:26,629 INFO : org.elasticsearch.node - [graylog2-server] closing ...
2015-05-30 13:39:26,634 INFO : org.graylog2.shared.journal.JournalReader - Stopping.
2015-05-30 13:39:26,635 INFO : org.elasticsearch.node - [graylog2-server] closed
2015-05-30 13:39:30,533 INFO : org.graylog2.shared.initializers.RestApiService - Adding security context factory: <org.graylog2.security.ShiroSecurityContextFactory@65dd47b0>
2015-05-30 13:39:30,572 INFO : org.graylog2.shared.initializers.RestApiService - Started REST API at <http://0.0.0.0:12900/>
2015-05-30 13:39:30,573 INFO : org.graylog2.shared.initializers.RestApiService - Shutting down REST API at <http://0.0.0.0:12900/>
2015-05-30 13:39:30,590 INFO : org.graylog2.shared.initializers.ServiceManagerListener - Services are now stopped.
2015-05-30 13:39:30,590 ERROR: org.graylog2.bootstrap.ServerBootstrap - Graylog startup failed. Exiting. Exception was:
java.lang.IllegalStateException: Expected to be healthy after starting. The following services are not running: {STARTING=[RestApiService [STARTING]], FAILED=[IndexerSetupService [FAILED]]}
	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.checkHealthy(ServiceManager.java:710)
	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.awaitHealthy(ServiceManager.java:535)
	at com.google.common.util.concurrent.ServiceManager.awaitHealthy(ServiceManager.java:301)
	at org.graylog2.bootstrap.ServerBootstrap.startCommand(ServerBootstrap.java:114)
	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:196)
	at org.graylog2.bootstrap.Main.main(Main.java:58)
2015-05-30 13:39:30,591 INFO : org.graylog2.bootstrap.commands.Server - SIGNAL received. Shutting down.
2015-05-30 13:39:30,595 INFO : org.graylog2.system.shutdown.GracefulShutdown - Graceful shutdown initiated.
2015-05-30 13:39:30,595 INFO : org.graylog2.system.shutdown.GracefulShutdown - Node status: [Halting [LB:DEAD]]. Waiting <3sec> for possible load balancers to recognize state change.
2015-05-30 13:39:34,601 INFO : org.graylog2.system.shutdown.GracefulShutdown - Goodbye.
```

**Comment by lennartkoopmann** [comment] 2015-05-30 18:45
Getting the cluster back into green state with any other changes made the server start flawlessly.

**Comment by kroepke** [comment] 2015-05-30 21:07
But the cluster state for the graylog indices is actually red, not yellow. Not all shards of the index graylog2_0 are assigned.

The initial check when connecting is to check "at least RED" to verify we can connect. Compare IndexerSetupService.

The output of head is misleading at best, even if we started you could not actually search. In fact I think the output of head is wrong here, at least according to Elasticsearch docs. To me this works as intended.

**Comment by joschi** [comment] 2015-06-01 15:50
I'm closing this issue as Graylog is working as intended.

Changing this behavior was already requested in #1136.

**Closed** 2015-06-01 16:23 UTC
Labels: bug
