### ISSUE TITLE
Syslog timestamp timezone set wrong

### ISSUE THREAD

**Issue by profhase** [Graylog2/graylog2-server#3091] opened 2016-11-16 13:26 UTC
As of rfc3164, the timestamp provided in the syslog message is in system's local time. Graylog interprets it as `UTC` which leads to the following issue:

## Steps to reproduce

1. Send message with rsyslog from system with local GMT+1 at 13:00 (means 12:00 Z)
2. In graylog you will see that the `timestamp` field is populated with 13:00 Z 
3. The message cannot be found by normal means as it is in the future

## Possible Solution
1. At the syslog input there should be a way to setup source's timezone
OR
2. One should be able to set the option that the timestamp is set to the receiving date

## Context
Our Tomcat sends messages via rsyslog

## Your Environment

* Graylog Version: 2.1.2
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Docker Container
* Browser version:

**Comment by ckozler** [comment] 2016-11-16 17:19
I'm having a bit of the same issue except my syslog sender is already sending UTC so being able to "rewrite" dynamically what the *real* source time is would be ideal. I'm trying to see if its possible with syslog-ng rather than graylog https://github.com/Graylog2/graylog2-server/issues/3093

**Comment by mikkolehtisalo** [comment] 2016-11-25 17:16
Relevant [RFC-5224 The Syslog Protocol, 6.2.3 TIMESTAMP](https://tools.ietf.org/html/rfc5424#section-6.2.3).

**Comment by profhase** [comment] 2016-11-27 21:26
@mikkolehtisalo on many systems syslog still uses rfc 3164:

https://www.ietf.org/rfc/rfc3164.txt

>    The TIMESTAMP field is the local time and is in the format of "Mmm dd
>    hh:mm:ss" (without the quote marks) [...]

**Comment by profhase** [comment] 2016-12-01 14:14
@kroepke For our setup it's unfortunately a bug (we cannot aggregate messages). Is there a workaround for that? I tried to rewrite the timestamp field but did not succeed.

**Comment by kroepke** [comment] 2016-12-01 14:19
@profhase The timestamp field is settable, so a pipeline rule or a custom plugin should be able to set the correct timezone.
The "feature" label is regarding the ability to override timezones based on inputs, which won't happen in 2.x (mainly because we currently don't have enough time to do it, not because we don't want to).

**Comment by profhase** [comment] 2016-12-01 14:26
@kroepke thanks, I did not try pipelines, i tried to do with standard extractor for field copying.

**Comment by kroepke** [comment] 2016-12-01 16:42
@profhase Actually I've just tried it and it might be a little tricky with 2.1 (basically you would have to stringify the timestamp and then parse it into a date again with string madness).

The upcoming 2.2 beta ("soonish") will have date arithmetic in pipelines, making this much easier. If you require something ad hoc I would suggest either looking at Drools (although I personally don't recommend it because it's much slower than necessary) or writing a small plugin.
Sorry for the incovenience.

**Comment by joschi** [comment] 2018-03-17 12:29
Duplicate of #3853.

**Closed by joschi** 2018-03-17 12:29 UTC
Labels: feature, triaged
