### ISSUE TITLE
idea怎么运行graylog

### ISSUE THREAD

**Issue by gddai** [Graylog2/graylog2-server#16890] opened 2023-10-11 02:44 UTC
## Why?

您好有相关idea运行graylog的教程吗

## Your Environment

* Graylog Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment] 2023-10-11 07:36
Hey @gddai,

please have a look at our documentation for instructions how to set up/run Graylog: https://go2docs.graylog.org/5-1/downloading_and_installing_graylog/installing_graylog.html

As this is not a bug or feature request, I am closing this issue.

**Closed by dennisoelkers** 2023-10-11 07:36 UTC
Labels: feature

**Comment by gddai** [comment] 2023-10-11 08:21
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project graylog2-server: Fatal error compiling: Error while executing the compiler. InvocationTargetException: class com.google.errorprone.BaseErrorProneJavaCompiler (in unnamed module @0x15bb8ed5) cannot access class com.sun.tools.javac.api.BasicJavacTask (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.api to unnamed module @0x15bb8ed5 -> [Help 1]
您好，这个错误怎么解决

**Comment by gddai** [comment] 2023-10-11 08:22
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project graylog2-server: Fatal error compiling: Error while executing the compiler. InvocationTargetException: class com.google.errorprone.BaseErrorProneJavaCompiler (in unnamed module @0x15bb8ed5) cannot access class com.sun.tools.javac.api.BasicJavacTask (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.api to unnamed module @0x15bb8ed5 -> [Help 1]
您好，这个错误怎么解决

**Comment by dennisoelkers** [comment] 2023-11-09 10:02
Hey @gddai, 
what exactly are you trying to achieve? If you are unfamiliar with Java development, you can still use our OS packages or docker images to get started with Graylog.
