### ISSUE TITLE
Graylog behind a proxy and src parameter

### ISSUE THREAD

**Issue by zoulja** [Graylog2/graylog2-server#10632] opened 2021-05-13 12:59 UTC
I have Graylog behind NAT and proxy
It listens on 127.0.0.1 and requests are routed to this IP:port from public IP
It’s pretty much the same as described in https://docs.graylog.org/en/4.0/pages/configuration/web_interface.html?highlight=proxy#making-the-web-interface-work-with-load-balancers-proxies

The problem is that absolute path is used inside of index page of Graylog, like

```
<link rel="shortcut icon" href="http://127.0.0.1:9000/assets/favicon.png">
<script src="http://127.0.0.1:9000/config.js">
<script src="http://127.0.0.1:9000/assets/vendor.594b2a39cb22b445205e.js">
```
Browser obviously fails to load resources from 127.0.0.1
What’s the reason of using absolute path and how to correct it?
## Expected Behavior
Graylog web UI is accessible behind a proxy

## Current Behavior
Absolute path in the index page body blocks scripts load
## Possible Solution  
Replace links like    
`<script src="http://127.0.0.1:9000/config.js">   ` 
to    
`<script src="/config.js">    `
## Your Environment

* Graylog Version: 4.0.7
* Java Version: 1.8
* Elasticsearch Version:7.10
* MongoDB Version: 4
* Operating System: Centos 7
* Browser version: Chrome 90

**Comment by dennisoelkers** [comment] 2021-05-14 07:41
Hey @zoulja,

we are generating absolute URLs to support configurations where the API and the frontend assets are served from different endpoints. As we already default to do this from a single port for a while now, we plan to remove this in a future version and change it to generate relative URLs to make use cases like yours easier.

Your situation can be fixed quite easily though by _either_ adding the `X-Graylog-Server-URL` header in the proxy _or_ setting the `http_external_uri` setting in the Graylog configuration file.

As this is not a bug in Graylog, I am closing this issue. If you have further information, feel free to reopen it.

**Closed by dennisoelkers** 2021-05-14 07:41 UTC
Labels: bug

**Comment by zoulja** [comment] 2021-05-14 07:48
@dennisoelkers please note current behaviour contradicts Graylog documentation.
I was not precise enough, actually I'm referring to https://docs.graylog.org/en/4.0/pages/configuration/web_interface.html?highlight=proxy#using-a-layer-3-load-balancer-forwarding-tcp-ports
So I don't have anything on L7 which can operate headers, but only port forwarding(what is s actually L4)
Please reopen the issue

**Comment by dennisoelkers** [comment] 2021-05-17 07:42
@zoulja: Besides the now potentially unneeded absolute qualification of web interface assets, what you mean is that the docs for an L4 proxy do not mention setting the `http_external_uri` configuration setting?

That is true and extending the docs here could help. Feel free to open a PR for the docs. I am not seeing your point though when you say that `current behaviour contradicts Graylog documentation`?

**Comment by komodin** [comment] 2021-05-18 11:30
@dennisoelkers hi, I'm facing the same issue. I'm running Graylog and nginx in Docker containers.
The frontend works well, but not the `/api/api-browser` page.

This are the Graylog container env vars:

```
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI=https://graylog.mycompany.com/
      - GRAYLOG_REST_TRANSPORT_URI=https://graylog.mycompany.com/
      - GRAYLOG_TRUSTED_PROXIES=172.16.0.0/12
```

And this is the nginx server block with all the required proxy_set_headers as in the documentation:

```
server {
    listen 443 ssl; # managed by Certbot
    server_name graylog.mycompany.com;

    ssl_certificate /etc/nginx/cert/fullchain.pem;
    ssl_certificate_key /etc/nginx/cert/privkey.pem; # managed by Certbot

    location / {
        proxy_pass http://graylog:9000/;
        proxy_set_header           Host  $host;
        proxy_set_header           X-Forwarded-Host  $host;
        proxy_set_header           X-Forwarded-Server  $host;
        proxy_set_header           X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header           X-Forwarded-Proto  $scheme;
        proxy_set_header           X-Graylog-Server-URL https://$server_name/;
    }
}
```

This is the source of the Graylog frontend that works well. You can see it uses https, the custom domain and no explicit port:

```
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="robots" content="noindex, nofollow">
    <meta charset="UTF-8">
    <title>Graylog Web Interface</title>
    <link rel="shortcut icon" href="https://graylog.mycompany.com/assets/favicon.png">
    
  </head>
  <body>
    <script src="https://graylog.mycompany.com/config.js"></script>
    
    <script src="https://graylog.mycompany.com/assets/vendor.594b2a39cb22b445205e.js"></script>
    
    <script src="https://graylog.mycompany.com/assets/polyfill.3433c0ea0395e9c3a16a.js"></script>
    
    <script src="https://graylog.mycompany.com/assets/builtins.3433c0ea0395e9c3a16a.js"></script>
    
    <script src="https://graylog.mycompany.com/assets/plugin/org.graylog.plugins.threatintel.ThreatIntelPlugin/plugin.org.graylog.plugins.threatintel.ThreatIntelPlugin.520f039c4bf8ec3f02a8.js"></script>
    
    <script src="https://graylog.mycompany.com/assets/plugin/org.graylog.plugins.collector.CollectorPlugin/plugin.org.graylog.plugins.collector.CollectorPlugin.28b11d390db6141c043a.js"></script>
    
    <script src="https://graylog.mycompany.com/assets/plugin/org.graylog.integrations.IntegrationsPlugin/plugin.org.graylog.integrations.IntegrationsPlugin.aef3a02ae9bca2792cce.js"></script>
    
    <script src="https://graylog.mycompany.com/assets/plugin/org.graylog.aws.AWSPlugin/plugin.org.graylog.aws.AWSPlugin.e5715e00b46c0f1983ce.js"></script>
    
    <script src="https://graylog.mycompany.com/assets/app.3433c0ea0395e9c3a16a.js"></script>
    
  </body>
</html>
```

But when I access the `/api/api-browser` page, it tries to connect using the internal proto, address and port:

```
<!DOCTYPE html>
<html>
<head>
  <title>Graylog REST API browser</title>
... some other assets ...
  <script type="text/javascript">
    var apiTarget = "http://172.18.0.4:9000/api/";
... rest of the file ...
```

I hope this help you to reproduce it. Please let me know if I can give you any additional details or if I can try anything.

Thank you so much for your help!
