### ISSUE TITLE
Dashboard Edit Mode

### ISSUE THREAD

**Issue by chalfling** [Graylog2/graylog2-server#11475] opened 2021-10-14 17:30 UTC
## What?

A button to stop Dashboard from updating after a widget change.

## Why?

If someone has to edit several widget on a Dashboard, this will take several minutes or hours. Each widget update run a search update on entire Dashboard. I think a "stop updating"/"edit mode" button will save a lot of time.

## Your Environment

* Graylog Version: 4.2.0
* Elasticsearch Version: 7.10.1
* MongoDB Version: 4.2
* Operating System: FreeBSD 12.2

**Comment by kmerz** [comment] 2023-11-15 12:35
Duplicate of #10295

**Closed by kmerz** 2023-11-15 12:35 UTC
Labels: feature, triaged, ux
