### ISSUE TITLE
WARN  [SearchResource] Unable to execute search: [reduce]

### ISSUE THREAD

**Issue by Alekc** [Graylog2/graylog2-server#4061] opened 2017-08-07 10:13 UTC
Trying to get quick values from 38k of messages. 

## Expected Behavior
Getting values

## Current Behavior
Getting popup on graylog ui

Loading quick values failed with status: Error: cannot GET http://xxx.xxx.xxx.xxx:9000/api/search/universal/relative/terms?query=ip%3A2605%5C%3Aa000%5C%3Ad3d3%5C%3A5a00%5C%3A84a3%5C%3A3cd8%5C%3A3d16%5C%3Adf55&range=28800&filter=streams%3A5896f5de463b38d28d08bd99&field=idx (500)

In server error log I can see
2017-08-07T11:06:42.238+01:00 WARN  [SearchResource] Unable to execute search: [reduce]

Nothing relevant shows in elastic search logs 

## Steps to Reproduce (for bugs)
Not sure, its a random bug

## Your Environment
Debian Jessie, 

* Graylog Version: Graylog 2.2.3+7adc951
* Elasticsearch Version: 2.4.6
* MongoDB Version: 1:2.4.10-5+deb8u1

**Comment by joschi** [comment] 2017-08-07 10:30
@Alekc Please post the complete logs of your Graylog and Elasticsearch nodes.

**Comment by Alekc** [comment] 2017-08-07 10:33
Do I need to increase verbosity level somewhere? Otherwise I am seeing only reported data in my logs.

**Comment by joschi** [comment] 2017-08-07 10:36
@Alekc You could increase log levels by either starting Graylog with the `--debug` parameter or by editing the [`log4j2.xml`](https://github.com/Graylog2/graylog2-server/blob/2.2.3/graylog2-server/src/main/resources/log4j2.xml) file.

You can also increase the log levels to DEBUG during runtime using the `/system/loggers` resource of the Graylog REST API (check the API browser for details).

**Comment by Alekc** [comment] 2017-08-07 11:00
@joschi Ok, looks like graylog is still mystic about the error even with debug log enabled. 


[graylog-debug.zip](https://github.com/Graylog2/graylog2-server/files/1204597/graylog-debug.zip)

Any hint for producing proper debug message on elasticsearch?

Also it's worth mentioning that other fields are working fine with the same data, but only the idx field is producing error.

**Comment by joschi** [comment] 2017-08-07 11:10
@Alekc I'm not sure how you've configured the logging levels now, but the file you've uploaded contains *only* DEBUG messages, none of the other interesting log levels (INFO, WARN, ERROR, FATAL).

**Comment by Alekc** [comment] 2017-08-07 11:20
@joschi 
My bad, instead of /system/loggers I used /cluster/system/loggers/subsystems
Although even using /api/system/loggers produce the same result  in log (only warn message and the rest is all debug). 

```
GET /api/system/loggers
{
  "total": 11,
  "loggers": {
    "": {
      "level": "info",
      "level_syslog": 400
    },
    "org.graylog2": {
      "level": "debug",
      "level_syslog": 500
    },
    "org.apache.directory.api.ldap.model.message.BindRequestImpl": {
      "level": "error",
      "level_syslog": 200
    },
    "com.joestelmach.natty.Parser": {
      "level": "warn",
      "level_syslog": 300
    },
    "kafka.log.Log": {
      "level": "warn",
      "level_syslog": 300
    },
    "com.github.joschi.jadconfig": {
      "level": "warn",
      "level_syslog": 300
    },
    "org.elasticsearch.script": {
      "level": "warn",
      "level_syslog": 300
    },
    "org.apache.shiro.session.mgt.AbstractValidatingSessionManager": {
      "level": "warn",
      "level_syslog": 300
    },
    "org.graylog2.periodical.VersionCheckThread": {
      "level": "off",
      "level_syslog": 0
    },
    "org.drools.compiler.kie.builder.impl.KieRepositoryImpl": {
      "level": "warn",
      "level_syslog": 300
    },
    "kafka.log.OffsetIndex": {
      "level": "warn",
      "level_syslog": 300
    }
  }
}
```
Am I missing something obvious? 

Thanks

**Comment by Alekc** [comment] 2017-08-07 11:35
Error persists on 2.3.0 as well

**Comment by Alekc** [comment] 2017-08-07 11:50
Turns out that it's not a Graylog but ElasticSearch issue. 

After enabling proper logging, following came up:

```
2017-08-07T12:39:09.512+01:00 DEBUG [wire] http-outgoing-1 << "{"error":{"root_cause":[],"type":"reduce_search_phase_exception","reason":"[reduce] ","phase":"fetch","grouped":true,"failed_shards":[],"caused_by":{"type":"aggregation_execution_exception","reason":"Merging/Reducing the aggregations failed when computing the aggregation [ Name: gl2_terms, Type: terms ] because: the field you gave in the aggregation query existed as two different types in two different indices"}},"status":503}"
```
Not sure if that's something fixed in ES 5.x (I am using 2.x now). 

Still: for the Graylog part, I think it can be better if we show some meaningful error instead of generic 500 in red box.

**Comment by joschi** [comment] 2017-08-07 12:09
Duplicate of #3603.

**Closed by joschi** 2017-08-07 12:09 UTC

**Comment by joschi** [comment] 2017-08-07 12:12
@Alekc Please attach the index mappings of your Elasticsearch indices to issue #3603.

You can fetch the mappings via the Elasticsearch HTTP API, for example:
```
# curl 'http://127.0.0.1:9200/_mapping?pretty'
```

Please also tell us for which field the quick values specifically fail.
