### ISSUE TITLE
Bar chart does not correctly render results

### ISSUE THREAD

**Issue by moafrancky** [Graylog2/graylog2-server#8141] opened 2020-05-15 13:43 UTC
## Expected Behavior

Bar chart should display all data
## Current Behavior

Bar chart is sometimes blank
## Possible Solution

Similar to issues 8095 and 7167 ?
## Steps to Reproduce (for bugs)

1- I go to the search tab. I filter to have only one result in the last 5 minutes. I have 1 message in 'All Messages' but 'Message Count' bar chart is blank (Y-Scale is 0 to 1). --> NOK
2- I generate one new event. I've now 2 results. Bar chart shows 2 results (Y-Scale is 0 to 1). --> OK
3- I switch to last 7 days. I've 2 results in 'All messages' but bar chart is again blank (Y-Scale is 0 to 2). --> NOK

## Context

Clean install. Database nearly empty. Some pipelines and rules are defined. Events used in 'steps to reproduce' are from 'all messages' stream.
## Your Environment

* Graylog Version: 3.2.4
* Elasticsearch Version: OSS 6.8.8
* MongoDB Version: 3.6.17
* Operating System: Official docker 3.2.4-1
* Browser version: Chrome 72

**Comment by dennisoelkers** [comment] 2020-05-15 13:49
Hey @moafrancky,

thanks for reporting this! We are already tracking this issue in #7167, therefore I am closing this issue. If you feel that this issue does not cover your problem, please reopen this issue with further information.

Duplicate of #7167.

**Closed by dennisoelkers** 2020-05-15 13:49 UTC
Labels: bug
