### ISSUE TITLE
graylog views   Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by dio99** [Graylog2/graylog2-server#6466] opened 2019-09-20 06:40 UTC
not every time i get this in views when i load a query. and next time i load it it works..

Cannot read property 'title' of undefined

Stack Trace:

TypeError: Cannot read property 'title' of undefined
    at t._isNewView (https://10.246.12.228/assets/ExtendedSearchPage.a26cc2d110296629aea2.js:1:132926)
    at t.render (https://10.246.12.228/assets/ExtendedSearchPage.a26cc2d110296629aea2.js:1:133229)
    at ka (https://10.246.12.228/assets/vendor.91c91d4a31d54d96392a.js:18:63009)
    at Sa (https://10.246.12.228/assets/vendor.91c91d4a31d54d96392a.js:18:62804)
    at Da (https://10.246.12.228/assets/vendor.91c91d4a31d54d96392a.js:18:66638)
    at Fo (https://10.246.12.228/assets/vendor.91c91d4a31d54d96392a.js:18:90682)
    at Vo (https://10.246.12.228/assets/vendor.91c91d4a31d54d96392a.js:18:91066)
    at Ys (https://10.246.12.228/assets/vendor.91c91d4a31d54d96392a.js:18:97953)
    at Ss (https://10.246.12.228/assets/vendor.91c91d4a31d54d96392a.js:18:97333)
    at Ls (https://10.246.12.228/assets/vendor.91c91d4a31d54d96392a.js:18:96354)
    at Zo (https://10.246.12.228/assets/vendor.91c91d4a31d54d96392a.js:18:95228)
    at Object.enqueueSetState (https://10.246.12.228/assets/vendor.91c91d4a31d54d96392a.js:18:44755)
    at t.b.setState (https://10.246.12.228/assets/vendor.91c91d4a31d54d96392a.js:26:1665)
    at https://10.246.12.228/assets/ShowViewPage.a26cc2d110296629aea2.js:1:2235
    at s (https://10.246.12.228/assets/app.a26cc2d110296629aea2.js:102:224951)
    at P._settlePromiseFromHandler (https://10.246.12.228/assets/app.a26cc2d110296629aea2.js:102:198233)
    at P._settlePromise (https://10.246.12.228/assets/app.a26cc2d110296629aea2.js:102:199033)
    at P._settlePromise0 (https://10.246.12.228/assets/app.a26cc2d110296629aea2.js:102:199732)
    at P._settlePromises (https://10.246.12.228/assets/app.a26cc2d110296629aea2.js:102:201059)
    at https://10.246.12.228/assets/app.a26cc2d110296629aea2.js:102:154681
    at u (https://10.246.12.228/assets/polyfill.a26cc2d110296629aea2.js:1:33700)
    at https://10.246.12.228/assets/polyfill.a26cc2d110296629aea2.js:1:33845
    at MutationObserver.f (https://10.246.12.228/assets/polyfill.a26cc2d110296629aea2.js:1:20081)

Component Stack:

    in ViewActionsMenu
    in ConnectStoresWrapper[ViewActionsMenu] stores=metadata,view,currentUser
    in span
    in span
    in u
    in w
    in ConnectStoresWrapper[w] stores=queries,queryTitles,viewMetadata
    in withRouter(ConnectStoresWrapper[w] stores=queries,queryTitles,viewMetadata)
    in div
    in t
    in ExtendedSearchPage
    in ConnectStoresWrapper[ExtendedSearchPage] stores=executionState
    in Unknown
    in t
    in ConnectStoresWrapper[t] stores=executionState
    in Unknown
    in n
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in t
    in withRouter(t)
    in div
    in App
    in RouterContext
    in Router
    in h
    in t
    in n
    in AppFacade

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment] 2019-09-20 10:14
Duplicate of #6346.

**Closed by dennisoelkers** 2019-09-20 10:14 UTC
