### ISSUE TITLE
Pipelines not working

### ISSUE THREAD

**Issue by arturluizbr** [Graylog2/graylog2-server#4324] opened 2017-11-07 14:39 UTC
Any changes on messages are not persisted.
- When I drop a message it is not removed;
- When i remove or set fields the message don't change a bit;

## Expected Behavior
- what i did on rule should be persisted on messages after pipeline (since it is not a decorator)

## Current Behavior
- Messages don't change after a pipeline

## Steps to Reproduce (for bugs)
I'm using Docker Compose yml file the way it is shown in docs, but with these images:
- docker.elastic.co/elasticsearch/elasticsearch:5.6.0
- mongo:3
- graylog/graylog:2.4 (I was on 2.3, changed but the problem persists)

1. Create a rule with:
```
rule "drop message"
when
  true
then
  drop_message();
end
```
2. Attach to Default Stream

PS.: My Message Conf. Order is:

1 | Message Filter Chain | active
2 | Pipeline Processor | active
3 | GeoIP Resolver | disabled

I tried to put pipeline first but no success...

## Context
In Graylog Debug logs i saw that everytime i edit a rule this Warning shows up:
```
WARN : org.graylog2.shared.events.DeadEventLoggingListener - Received unhandled event of type <org.graylog.plugins.pipelineprocessor.processors.PipelineInterpreter.State> from event bus <AsyncEventBus{graylog-eventbus}>
```

**Comment by jalogisch** [comment] 2017-11-07 14:49
I can't reproduce that - could you please check the `pipeline_processor_rules` collection in the MongoDB if those rules are actually written to Database?

Thank you

**Comment by arturluizbr** [comment] 2017-11-07 14:55
In mongodb:
```
> db.pipeline_processor_rules.find()
{ "_id" : ObjectId("5a01b15c2ab79c0001f66e9b"), "title" : "remove keep alive on UDP", "description" : "Remove as mensagens de Keep Alive", "source" : "rule \"remove keep alive on UDP\"\nwhen\n    contains(to_string($message.message), \"Keep Alive sent on UDP\", true)\nthen\nend", "created_at" : ISODate("2017-11-07T13:13:00.995Z"), "modified_at" : ISODate("2017-11-07T14:19:12.466Z") }
{ "_id" : ObjectId("5a01b3d82ab79c0001f67158"), "title" : "drop message", "description" : "Remove as mensagens", "source" : "rule \"drop message\"\nwhen\n  true\nthen\n  drop_message();\nend", "created_at" : ISODate("2017-11-07T13:23:36.177Z"), "modified_at" : ISODate("2017-11-07T14:49:49.847Z") }
```

**Comment by joschi** [comment] 2017-11-08 08:26
@arturluizbr Which plugins are you using in your Graylog cluster? What files are in the plugin directory (see `plugin_dir`)?

You can see the loaded plugins in the web interface on the System/Nodes/Details page.

**Comment by arturluizbr** [comment] 2017-11-08 18:17
Today i checked and it was working as expected. (At least the dropped messages)

I'll keep monitoring to see any changes on this behavior, because i did nothing and it is working fine now.

Is there any possibility that the pipeline won't affect the current Index until the rotation occurs?

**Comment by joschi** [comment] 2017-11-09 07:19
> Is there any possibility that the pipeline won't affect the current Index until the rotation occurs?

No, but the pipeline will only modify newly ingested messages. Existing messages won't be modified or reindexed.

**Comment by arturluizbr** [comment] 2017-11-09 12:17
Too bad =/

I excluded the drop rule from pipeline but messages won't shows up anymore (even when throughput number keeps showing messages flowing), i guess changes I do on pipelines are delayed somehow, tomorrow i'll see if messages shows up again.

**Comment by arturluizbr** [comment] 2017-11-09 12:27
> i guess changes I do on pipelines are delayed somehow, tomorrow i'll see if messages shows up again.

I'd put a debug on pipeline and it worked, but commands to change or drop messages still don't work as expected.

**Comment by arturluizbr** [comment] 2017-11-09 12:42
> @arturluizbr Which plugins are you using in your Graylog cluster? What files are in the plugin directory (see plugin_dir)?

These ones on 2.4 and for 2.3 all that are not version 2.4.0-beta.1:

Anonymous Usage Statistics | 2.4.0-beta.1
AWS plugins | 2.4.0-beta.1
CEF Input | 2.4.0-beta.1
Collector | 2.4.0-beta.1
Elastic Beats Input | 2.4.0-beta.1
Enterprise Integration Plugin | 2.4.0-beta.1
MapWidgetPlugin | 2.4.0-beta.1
NetFlow Plugin | 2.4.0-beta.1
Pipeline Processor Plugin | 2.4.0-beta.1
Stream Lookup pipeline function | 1.1.0
Threat Intelligence Plugin | 2.4.0-beta.1

**Comment by joschi** [comment] 2017-11-09 13:01
@arturluizbr Please only use plugins that are compatible with your Graylog version.

For example the Stream Lookup pipeline function plugin is not compatible with Graylog 2.4.x and probably also not with Graylog 2.3.x.

**Comment by arturluizbr** [comment] 2017-11-09 13:12
I disabled the plugin, nothing changed.

**Comment by arturluizbr** [comment] 2017-11-09 14:03
I still didn't find the reason it wasn't working, i delete all containers and volumes to restart over the setup and now it looks like its working fine, i'll notify if that problem occurs again.

**Comment by joschi** [comment] 2017-11-09 14:58
@arturluizbr Okay, I'll close this issue until you add another comment regarding the problem.

**Closed by joschi** 2017-11-09 14:58 UTC
Labels: needs-input
