### ISSUE TITLE
Pipeline rule editor cursor is invisible on the light theme

### ISSUE THREAD

**Issue by damianharouff** [Graylog2/graylog2-server#18717] opened 2024-03-20 13:54 UTC
In Graylog 6.0.0-beta.2+8b77fdb, the pipeline rule source code editor text box cursor is nearly invisible on the light theme. It's visible on the dark theme. This may be happening in other text boxes too. 

https://github.com/Graylog2/graylog2-server/assets/2953243/58ae065a-fa5e-41bd-b950-c4010362fbe7

## Your Environment

- Graylog Version: Graylog 6.0.0-beta.2+8b77fdb
- Java Version: Embedded
- OpenSearch Version: 2.12.0
- MongoDB Version: 7.0.6
- Operating System: Debian 12
- Browser version: Version 122.0.6261.129 (Official Build) (arm64)

**Comment by bernd** [comment] 2024-03-26 17:17
Duplicate of https://github.com/Graylog2/graylog2-server/issues/14190

**Comment by gally47** [comment] 2024-03-28 14:41
I tested it on the current master on both Chrome and Firefox couldn't reproduce it. It works just fine for me.

**Comment by grotlue** [comment] 2024-04-02 08:40
Follow up issue https://github.com/Graylog2/graylog2-server/issues/18847

**Closed by grotlue** 2024-04-02 08:40 UTC
Labels: bug, triaged, blocker, test-day
