### ISSUE TITLE
2.0b2 Messagecount on /system/indices is multiplied by number of nodes

### ISSUE THREAD

**Issue by SjonHortensius** [Graylog2/graylog2-server#1823] opened 2016-02-16 10:49 UTC
I have a couple of indices with 6M messages in it. They reside on multiple nodes, and `/system/indices` multiplies these incorrectly, showing:

> Contains messages from 1 years ago up to 9 months ago (9.3GB/ 18,011,076 messages)

Both the size and number of messages are incorrect (they should be divided by 3)

**Comment by dennisoelkers** [comment] 2016-02-16 10:50
Which version are you using? 2.0-alpha.2 I guess?

**Comment by SjonHortensius** [comment] 2016-02-16 10:51
This is alpha1, I didn't notice alpha2 yet.

**Comment by kroepke** [comment] 2016-02-19 11:36
Is it multiplied by nodes or replicas?

**Comment by dennisoelkers** [comment] 2016-04-11 13:23
@SjonHortensius: Is it still the case with the latest beta?

**Comment by SjonHortensius** [comment] 2016-04-11 14:01
Yes, here is some more example output, these settings have always been like this. This cluster has 2 graylog & e/s nodes; and it's the 20M messages are reported as being 40M incorrectly

>Index rotation strategy:
>    Message Count
>Max docs per index:
>    20000000
>
> 5 indices with a total of 48,832,347 messages under management, current write-active index is graylog2_4.
> graylog2_4 Contains messages up to a few seconds ago (6.5GB/ 12,018,269 messages)
> graylog2_3 Contains messages from 6 months ago up to 2 months ago (4.4GB/ 10,194,380 messages)
> graylog2_2 Contains messages from 7 months ago up to 6 months ago (2.1GB/ 4,828,782 messages)
> graylog2_1 Contains messages from a year ago up to 7 months ago (12.2GB/ 40,000,054 messages)
> graylog2_0 Contains messages from 3 years ago up to a year ago (12.6GB/ 30,623,208 messages)

The total `5 indices with a total of 48,832,347` seems to be correct

**Comment by kroepke** [comment] 2016-04-12 14:02
I cannot reproduce this issue.

When I test this with multiple elasticsearch nodes and lots of shards and replicas, I always get the correct number from the primary shards.

Could you please provide the output of `/_cat/indices?v` as well as a screenshot of an index where the numbers are wrong for you?

Thanks!

**Comment by kroepke** [comment] 2016-04-12 14:24
It still works when having multiple graylog nodes as well.

**Comment by SjonHortensius** [comment] 2016-04-12 14:45
That's just weird, anything else I can provide you to help debug this? Do you agree that the output I posted is incorrect?

**Comment by kroepke** [comment] 2016-04-12 16:09
From the output you pasted I can't tell which version is correct. I'd need to take a look at what elasticsearch reports. for each of these indices.
Just to be very clear, these are indices that were written with various older elasticsearch versions and opened with 2.3.1, right?

**Comment by kroepke** [comment] 2016-04-12 16:11
@SjonHortensius Could you please try with the most recent beta.3 snapshot from http://packages.graylog2.org/_/snapshots?q=2.0.0-beta.3 ?
We've recently reorganized some of the API we use to speed things up. The data path should be the same though. Just to make sure we haven't "accidentally" fixed this already.

**Comment by SjonHortensius** [comment] 2016-04-13 07:31
>  Just to be very clear, these are indices that were written with various older elasticsearch versions and opened with 2.3.1, right?

This is exactly correct. Fwiw; this is what `_cat/indices?v` outputs:

```
health status index      pri rep docs.count docs.deleted store.size pri.store.size 
green  open   graylog2_1   4   1   20000027            0     12.1gb            6gb 
green  open   graylog2_0   4   1   15311604            0     12.6gb          6.3gb 
green  open   graylog2_3   4   1    5097190            0      4.3gb          2.1gb 
green  open   graylog2_2   4   1    2414391            0        2gb            1gb 
green  open   graylog2_4   4   1    6097850            0      6.6gb          3.3gb 
```

Not sure what the screenshot adds (since I already posted the numbers) but here it is:
![screenshot-3868](https://cloud.githubusercontent.com/assets/1684987/14485919/675c9a54-015a-11e6-8c60-3288f3f2d36b.png)

**Comment by kroepke** [comment] 2016-04-13 10:08
The screenshot is just simpler for me to visually compare what's actually on the screen and can't be misinterpreted like a copy'n'paste from HTML, that's all :smile: 

I'll look into it.

**Comment by kroepke** [comment] 2016-04-13 12:11
With the latest beta.3-snapshot, two ES nodes, two graylog nodes and after an upgrade from 1.3.4 -> 2.0.0-beta.3-snapshot, I still cannot reproduce this issue.

Either we are missing something obvious or something else is severely broken. Which exact version of Graylog are you using?
`Graylog 2.0.0-beta.3-SNAPSHOT (37cf61c)` display correct numbers for me.

**Comment by kroepke** [comment] 2016-04-13 12:22
Ok, finally reproduced it in beta.2.

This is then fixed in the upcoming beta.3 which uses a different endpoint to get the data.

I'll close the issue for now, please reopen it if beta.3 (due today or tomorrow) does not fix the problem.

Thank you for your contribution and patience :smile:

**Closed by kroepke** 2016-04-13 12:22 UTC
Labels: bug, P2, S3

**Comment by kroepke** [comment] 2016-04-13 12:25
For completeness' sake: this was the change that fixed the problem https://github.com/Graylog2/graylog2-server/pull/2017

**Comment by SjonHortensius** [comment] 2016-04-15 11:22
Thanks for the update and link to fix. I can confirm b3 fixes this behavior
