### ISSUE TITLE
"Field content value condition" unable to trigger alerts

### ISSUE THREAD

**Issue by sumit-sngpt** [Graylog2/graylog2-server#2239] opened 2016-05-16 13:47 UTC
### Problem description
We are trying to configure alert based on "Field content value condition" but its failing to trigger any alert despite similar events getting into that stream. How to debug the issue?

### Steps to reproduce the problem

**Field content value condition**

> Alert is triggered when messages matching <-----> are received. Grace period: 0 minutes. Including last message in alert notification.

### Environment

* Graylog Version: 2.0.1

**Comment by dennisoelkers** [comment] 2016-05-17 08:45
Do you see any errors in your Graylog server log? Is there anything special with the value you are matching against?

**Comment by sumit-sngpt** [comment] 2016-05-17 10:10
Nothing that is evident at server logs. The values are just string against which its matching like <eventName:"xyz">

**Comment by jalogisch** [comment] 2016-07-20 09:36
@sumit-sngpt did still have the issue?

did you check if the message maybe contain leading whitespace?

I will close this issue - if the problem is still present, please reopen and provide us details how we can reproduce.

thank you

**Closed by jalogisch** 2016-07-20 09:36 UTC
Labels: needs-input
