### ISSUE TITLE
auth: secondary ldap as backup 

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#2924] opened 2016-10-06 07:51 UTC
## Expected Behavior
In HA Environments you will have more than one LDAP Server, and it should be possible to add additional Server that serves the same tree.

## Current Behavior
Only one LDAP Server is possible

## Your Environment

* Graylog Version: 2.1.1

**Comment by joschi** [comment] 2016-10-06 07:53
Duplicate of #1046.

**Closed by joschi** 2016-10-06 07:53 UTC
