### ISSUE TITLE
I'm searching key words in all fileds and some exceptions happend.

### ISSUE THREAD

**Issue by Balley2** [Graylog2/graylog2-server#1945] opened 2016-03-18 07:39 UTC
### Problem description
1.when I search keyword 22:52 it'll return "Nothing found." in console page.
and search 22:52:12 returns an exception page "Loading..." and it'll keep on. at the same time it takes "org.graylog2.rest.resources.search.SearchResource - Unable to execute search: all shards failed' in graylog-server.log.

2.when I search keyword "22:52" (increased double quotation marks), it word well,and result contains message contained keyword 22:52:12. but I'm trying serach "22:52:12"(the same increased double quotation marks) it returns "Nothing found".

### Steps to reproduce the problem
![g5](https://cloud.githubusercontent.com/assets/17921572/13871720/64d92dd2-ed1f-11e5-921a-13f8d39dbb76.PNG)
![g1](https://cloud.githubusercontent.com/assets/17921572/13871686/3acb0cd6-ed1f-11e5-98dc-fac5003fff1a.PNG)
![g2](https://cloud.githubusercontent.com/assets/17921572/13871690/424c24c2-ed1f-11e5-8da2-221ece4c6ca8.PNG)
![g3](https://cloud.githubusercontent.com/assets/17921572/13871693/49372fc0-ed1f-11e5-8de8-6c610901cacb.PNG)
![g4](https://cloud.githubusercontent.com/assets/17921572/13871710/5e96e9aa-ed1f-11e5-9d5f-97667e51daf7.PNG)

### Environment

* Graylog Version: graylog-2.0.0-alpha.5
* Elasticsearch Version:elasticsearch-2.2.0
* MongoDB Version:mongodb-linux-x86_64-ubuntu1404-3.2.4
* Operating System:ubuntu1404
* Browser version:Chrome 48.0.2564.82 m

**Comment by joschi** [comment] 2016-03-18 09:40
@Balley2 Thanks for reporting this!

I could reproduce that on Graylog 2.0.0-alpha.6-SNAPSHOT. The problem is, that an invalid Lucene query like `22:52:12` doesn't trigger proper error handling and doesn't show the user that the query was invalid.

In this specific case, the colon character (`:`) is a reserved character and would need to be escaped if the query wasn't quoted, e. g. `22\:52\:12` or `"22:52:12"`. See https://www.elastic.co/guide/en/elasticsearch/reference/2.2/query-dsl-query-string-query.html#_reserved_characters for details.

**Comment by kroepke** [comment] 2016-03-30 13:43
Closing because it duplicates #1896

**Closed by kroepke** 2016-03-30 13:43 UTC
Labels: bug, P2, S2
