### ISSUE TITLE
web interface shows error page on refreshes

### ISSUE THREAD

**Issue by dumpwhanau** [Graylog2/graylog2-server#2071] opened 2016-04-13 10:39 UTC
### Problem description

Under Firefox if I hit ENTER in the URL bar (to refresh a page), I see this error popup appear for a seconds before disappearing. This doesn't seem to occur under Chrome - but I can also say it didn't occur under Firefox on graylog-1.3.4 either - so it's specific to v2

The popup is saying "Server Currently Unavailable. We are experiencing problems connecting to the graylog server..."

So there is no problem, but I'm continually going "ah! there's a problem - wait - no there isn't" ;-)

### Steps to reproduce the problem

1. ...

### Environment

* Graylog Version: graylog-server-2.0.0-3.beta.2.noarch and 2.0.0-3.beta.3
* Elasticsearch Version: elasticsearch-2.3.1-1.noarch
* MongoDB Version:  2.6.11-1.el7
* Operating System: CentOS-7
* Browser version: Firefox-45

**Comment by dennisoelkers** [comment] 2016-04-13 11:46
Hey @dumpwhanau, I cannot reproduce this problem at all. Do you see anything in the browser console when doing this? Does it happen when you just do a full page refresh in your browser (using the os-specific shortcut) too?

**Comment by dumpwhanau** [comment] 2016-04-13 19:24
Our server is in the USA east coast and my browser (along with me) is in Christchurch New Zealand - so there's a long way between us - I wonder if that latency is why I'm seeing it and you're not?

If I click the "reload" icon I see it too (note: the warning message pops up ~80% of the time on reloads - not all of the time). If I don't reload but instead am clicking my way through graylog "properly", that web popup box doesn't appear

I've done some more testing and I don't see this "popup" on the Search page or the "Sources" page - but I do see it on the Streams, Dashboard, System pages. That might be real or just dumb luck - but it might be a useful comment :-)

I got the firefox console up but frankly I don't know what to look for. There are always a bunch of comments in the console. One that looks interesting says 

There was an error fetching a resource: Bad request." Additional information: Not available"
FetchError() plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.6a9dfb56109359d2018f.js:13385
json/this.request<() plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.6a9dfb56109359d2018f.js:13446
tryCatcher() plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.6a9dfb56109359d2018f.js:18175
[23]</module.exports/Promise.prototype._settlePromiseFromHandler() plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.6a9dfb56109359d2018f.js:16281
[23]</module.exports/Promise.prototype._settlePromiseAt() plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.6a9dfb56109359d2018f.js:16355
[23]</module.exports/Promise.prototype._settlePromises() plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.6a9dfb56109359d2018f.js:16471
[2]</Async.prototype._drainQueue()

**Comment by dumpwhanau** [comment] 2016-04-14 10:28
More data... I got a sniffer up and when I did a refresh and saw that "currently unavailable" page, that did NOT come from the server. I can see tonnes of requests for "GET /system/cluster/nodes" - but none containing the string "unavailable". So this does sound like Firefox showing me something out of cache?

Also, the "unavailable" popup mentions the problem is with http://graylog.server:12900/ - whereas the web server I perceive myself as using is port  http://graylog.server:9000

BTW this is Firefox/45 on Ubuntu. As I mentioned earlier - Chrome on Ubuntu is fine. I have just tried Firefox/45 on Win10 and got the same effect - so it's definitely Firefox-related

**Comment by kroepke** [comment] 2016-04-18 09:27
This sounds like it is caused by the high latency connection. The page is displayed from within the client side application, so you will not find it in the traffic.

We'll look at making the timeout customizable for the connections that trigger the "unavailable" page.

**Comment by jhaar** [comment] 2016-04-28 21:01
This issue appears to have changed with the official v2.0.0 release. Now I see the login page flash up! It's still just a cosmetic problem - if I was doing a search, I'd hit ENTER, see the flash of an inappropriate page and then the search results come back. So it's all working - just with this "noise" in between. I also reconfirmed I only see this with Firefox. Chrome on the same Ubuntu laptop doesn't show this "flash"

BTW I've also had comments from a co-worker in the same office as our server who is also seeing this - so my theory about latency being behind this may be incorrect

**Comment by aminkhodamoradi** [comment] 2016-06-09 01:00
I download last version of graylog2.0.0 beta . I import it in virtual machine (vmware)  then I use that url in browser but this error apears <This site can’t be reached...>
the older version didn't has this problem

**Comment by joschi** [comment] 2016-06-09 08:48
@dumpwhanau Please download and use the latest stable version of Graylog (version 2.0.2 at the time of writing).

**Comment by jhaar** [comment] 2016-06-09 09:24
Yup - I'm running 2.0.2 and it's still happening. Works fine under Chrome, but shows this transitory flash of the login and/or "server unavailable" screens inside Firefox

**Comment by aminkhodamoradi** [comment] 2016-06-13 21:28
I have downloaded  last version  but doesn't fixed.
sometimes it's load but now graylog2 cann't connect to elasticsearch.

**Comment by dennisoelkers** [comment] 2016-06-28 13:37
@jhaar: The transitory flash of the login page is kinda "intended". It happens every time when you are doing a full page load of the Graylog web interface. Unfortunately we still rely on full page refreshes for search in some places in 2.0.x. This will most probably be gone in 2.1.x though. As this is not a bug, I am closing this issue now.

@aminkhodamoradi: It seems like your problem is not related to the original issue. Please open a new issue if it still persists and provide as much context as possible.

**Closed by dennisoelkers** 2016-06-28 13:37 UTC
Labels: improvement

**Comment by jhaar** [comment] 2016-08-19 08:34
Well I've just got 2.1.beta4 up and the issue is still there. I am trying to demo graylog to others and they're all going "why are you continually logged out"? It's annoying as hell

I appreciate using Chrome works just fine - but I like Firefox :-)

**Comment by vaizki** [comment] 2016-08-31 13:32
well with 2.1rc1 installed yesterday this still keeps popping up every time I search..  and it's not just Firefox, same thing with Chrome 52 on Win10 here.

**Comment by edmundoa** [comment] 2016-09-06 13:09
Let's continue the discussion under #2770.
