### ISSUE TITLE
Unable to load histogram data

### ISSUE THREAD

**Issue by jacobpmani** [Graylog2/graylog2-server#2983] opened 2016-10-25 03:56 UTC
Hi,

I recently upgraded the Graylog to version 2.1, and am unable to load the histogram data, on the Sources page.
I see the below error message.
"Could not load histogram data
Loading of histogram data has failed with status: Error:cannot GET http://x.x.x.x:9000/api/search/universal/relative/histogram?query-%2A&range=3600&interval=minute(400)

Thanks in advance
![image](https://cloud.githubusercontent.com/assets/23045577/19672555/4665550e-9aaa-11e6-9c1e-c8a942d1f5d7.png)

**Comment by edmundoa** [comment] 2016-10-25 08:51
Hi @jacobpmani,

Would you be so kind as to share with us any error messages in your Graylog server logs?

**Comment by jacobpmani** [comment] 2016-10-26 01:46
Hi Edmundo,

Thank you for replying.
Is there any log in particular you are looking for?

root@graylog:/var/log# ls
alternatives.log    auth.log       auth.log.3.gz  bootstrap.log  dmesg.0     dmesg.3.gz  dpkg.log.1  graylog    kern.log.1     kern.log.4.gz  syslog       syslog.3.gz  syslog.6.gz  upstart
alternatives.log.1  auth.log.1     auth.log.4.gz  dist-upgrade   dmesg.1.gz  dmesg.4.gz  faillog     installer  kern.log.2.gz  lastlog        syslog.1     syslog.4.gz  syslog.7.gz
apt                 auth.log.2.gz  boot.log       dmesg          dmesg.2.gz  dpkg.log    fsck        kern.log   kern.log.3.gz  ntpstats       syslog.2.gz  syslog.5.gz  udev

Also, on the nodes i see the below output. There are unprocessed messages in the journal and the buffers wouldn't empty. Could this be a memory leak issue? A bug maybe?
![capture](https://cloud.githubusercontent.com/assets/23045577/19710444/e27a939e-9b60-11e6-861e-066e23906e6b.PNG)

Thank you kindly.
Jacob

**Comment by joschi** [comment] 2016-10-26 07:23
@jacobpmani We need the logs of your Graylog node(s), see http://docs.graylog.org/en/2.1/pages/configuration/file_location.html for their default locations.

**Comment by jacobpmani** [comment] 2016-10-27 03:12
[Graylog-log2.txt](https://github.com/Graylog2/graylog2-server/files/554887/Graylog-log2.txt)
@joschi PFA the logs....There are more, Please tell me if you need them too, or if you have a FTP, kindly share the details.

thanks.

**Comment by joschi** [comment] 2016-10-27 09:28
@jacobpmani There are pretty obvious hints in your logs, such as:
```
2016-10-20_11:32:51.94116 Caused by: java.io.IOException: No space left on device
```

**Comment by joschi** [comment] 2016-10-27 09:29
I'm closing this issue.

If you have any questions regarding freeing some disk space, please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Closed by joschi** 2016-10-27 09:29 UTC

**Comment by Radhakrishnan95** [comment] 2017-09-19 16:54
Hi Guys,
   For me Same issue but different error .
[DEBUG][action.search            ] [Hit-Maker] All shards failed for phase: [query]
RemoteTransportException[[Hit-Maker][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: IllegalArgumentException[Expected numeric type on field [timestam$
Caused by: java.lang.IllegalArgumentException: Expected numeric type on field [timestamp], but got [string]

Please give me some suggestion to solve this issue .i'm Very new to this graylog.
