### ISSUE TITLE
illegal repetition creating timestamp using grok

### ISSUE THREAD

**Issue by whitty69** [Graylog2/graylog2-server#1725] opened 2016-01-26 15:05 UTC
--- graylog-web-interface v1.3.2 (e7c49b6) (Oracle Corporation 1.7.0_55 / Linux 3.12.48-52.27-default) on 

We are trying to parse the following message with a grok extractor and we are getting an illegal repetition exception when we use this pattern. We believe that it's due to the comma in the timestamp extraction. 

**Pattern**
%{DATA:timestamp;date;MMM dd, yyyy HH:mm:ss a}%{SPACE}%{DATA:pxc_logger}%{WORD:pxc_log_level}:%{SPACE}%{GREEDYDATA:pxc_log_msg}

**Message**
Jan 26, 2016 4:39:40 AM com.phoenixcontact.integration.customer.service.jpa.CustomerDBAccessor getCustomer FINE: Found ERPCustomers: [ERPCustomer [blocked=false, organization=99999999, customerId=88888988, companyName=null]]

We have tried escaping the comma with no success.

**Comment by joschi** [comment] 2016-01-26 15:12
Duplicate of #905.

As a workaround, try replacing the comma in your date pattern with another character.

**Closed by joschi** 2016-01-26 15:12 UTC

**Comment by whitty69** [comment] 2016-01-26 17:33
thanks.. that is what we#re gonna do, but thought I'd log an issue anyway. :-)

**Comment by joschi** [comment] 2016-01-27 09:10
@whitty69 No worries. We'd rather have duplicate issues than no bug reports at all. :smile:
