### ISSUE TITLE
Grouping Dashboards in Folders or Categories

### ISSUE THREAD

**Issue by H2Cyber** [Graylog2/graylog2-server#13155] opened 2022-07-28 17:47 UTC
## What?

Users should have the ability to group Dashboards in categories or folders.

## Why?

Dashboards are frequently numerous and can be related to different use cases (e.g. security dashboards, operational dashboards, etc.). It would be great to be able to group them into categories or folders.

## Your Environment

* Graylog Version: 4.3.3

**Comment by supahgreg** [comment] 2022-07-30 14:25
#4654 (but +1 either way)

**Comment by bernd** [comment] 2022-08-03 14:14
Duplicate of #4654.

**Closed by bernd** 2022-08-03 14:14 UTC
Labels: feature
