### ISSUE TITLE
Logs not showing up in web UI after reindexing logs from old cluster (Graylog: 3.1, elastic search:6.8.18, Mongo: 4.0) to new cluster (Graylog: 4.1, elastic search:6.8.18, Mongo: 4.0).

### ISSUE THREAD

**Issue by ravichandra452** [Graylog2/graylog2-server#11821] opened 2021-12-14 19:16 UTC
The below snapshot shows that the graylog_0 index in the new cluster has 135,759 messages (Messages migrated from the old cluster). 
Search all messages doesn’t return any messages in the web UI as shown in another snapshot. Recalculate the index range didn’t help

![image](https://user-images.githubusercontent.com/91612078/146063390-b3fa750a-1150-4550-95dd-6d222a903359.png)
![image](https://user-images.githubusercontent.com/91612078/146063633-f1887911-6ba9-4cb3-a455-1c5748791426.png)

I can view the same logs (135,759 messages) in the old cluster WebUI without any problem as shown below
![image](https://user-images.githubusercontent.com/91612078/146063972-c3982d26-5a2c-44a3-bf02-ee7125fec91f.png)
![image](https://user-images.githubusercontent.com/91612078/146064558-40ce18e2-be14-4c6a-8e9b-fca6277f5fe0.png)

Could someone please guide why the messages are not showing up in the web UI of the new cluster in spite of messages present in the index?

**Comment by ravichandra452** [comment] 2021-12-14 20:58
I can pull the messages from the index (graylog_0) through elastic search query API call but am not able to load the same through the Graylog WebUI search bar.

**Comment by janheise** [comment] 2024-06-07 07:48
Closing this, I could not reproduce the problem with current versions in different upgrade scenarios.

**Closed by janheise** 2024-06-07 07:48 UTC
Labels: bug, triaged, High Prio
