### ISSUE TITLE
content packs should include pipelines

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#2554] opened 2016-07-27 11:28 UTC
### Problem description

if you step into and take advantage of the new pipeline features you have no possibility to share/save them.

This would be needed if you develop new pipelines in your lab and want to copy them over to your production. Or simple just want to share with someone else.

At this given point you can only copy over the rules (one by one) but everything other need to be applied again. To be more user friendly and to raise the adoption rate for pipelines this is needed.

**Comment by bernd** [comment] 2016-07-27 11:33
Duplicate of https://github.com/Graylog2/graylog2-server/issues/2507 :wink:

**Closed by bernd** 2016-07-27 11:33 UTC
