### ISSUE TITLE
Timestamp problem with Graylog 2 alpha 4

### ISSUE THREAD

**Issue by pszafer** [Graylog2/graylog2-server#1890] opened 2016-03-03 13:49 UTC
### Problem description

Since updateg Elasticsearch and Graylog to the newest versions I have problem with timestamp from syslog pfsense.

Current time: **Thu Mar  3 14:43:17 CET 2016**
This is what I can see in wireshark, what pfsense sends to me:

> <15>Mar  3 14:33:56 apinger: Polling, timeout: 0.999s
> <15>Mar  3 14:33:56 apinger: #4145509 from WANFIBERGW(77.65.14.53) delay: 0.690ms/0.597ms/6.330ms received = 1092723 
> <15>Mar  3 14:33:56 apinger: (avg: 0.633ms)<15>

After update I have a lot in logs:

- Graylog:
```
2016-03-03 14:46:18,662 ERROR: org.graylog2.indexer.messages.Messages - Failed to index [14] messages. Please check the index error log in your web interface for the reason. Error: failure in bulk execution:
[0]: index [graylog2_18], type [message], id [4d143b41-e146-11e5-acd4-323166623665], message [MapperParsingException[failed to parse [timestamp]]; nested: IllegalArgumentException[Invalid format: "16777216" is too short];]
[1]: index [graylog2_18], type [message], id [4d143b44-e146-11e5-acd4-323166623665], message [MapperParsingException[failed to parse [timestamp]]; nested: IllegalArgumentException[Invalid format: "16777216" is too short];]
[2]: index [graylog2_18], type [message], id [4d143b43-e146-11e5-acd4-323166623665], message [MapperParsingException[failed to parse [timestamp]]; nested: IllegalArgumentException[Invalid format: "16777216" is too short];]
```

- Elasticsearch:

```
 [2016-03-03 14:43:15,118][DEBUG][action.bulk              ] [Worm] [graylog2_18][1] failed to execute bulk item (index) index {[graylog2_deflector][message][e12353d2-e145-11e5-acd4-323166623665], source[{"gl2_remote_ip":"10.8.0.2","gl2_remote_port":514,"BASE10NUM":"1000000003","rule":"1000000003","source":"router.poznan.tbhydro.net","gl2_source_input":"5649a63ce4b084ea31b7be59","dst_ip":"ff02::1:2","src_ip":"fe80::687b:9152:4a51:ccd9","ip_version":"6","action":"block","gl2_source_node":"6d693aff-1450-40b8-9aa2-de2a71317189","mix":"113","timestamp":"16777216","direction":"in","level":6,"IPV6":"ff02::1:2","streams":["5649c894e4b009a774a8b596"],"match":"match","message":"filterlog: 5,16777216,,1000000003,lagg0_vlan30,match,block,in,6,0x00,0x00000,1,UDP,17,113,fe80::687b:9152:4a51:ccd9,ff02::1:2,546,547,113","src_port":"546","iface":"lagg0_vlan30","service":"filterlog","proto":"UDP","dst_port":"547","evtid":"5","facility":"local0"}]}
 MapperParsingException[failed to parse [timestamp]]; nested: IllegalArgumentException[Invalid format: "16777216" is too short];
         at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:343)
         at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:318)
         at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:445)
         at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:271)
         at org.elasticsearch.index.mapper.DocumentParser.innerParseDocument(DocumentParser.java:131)
         at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:79)
         at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:304)
         at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:547)
         at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:529)
         at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOperationOnPrimary(TransportIndexAction.java:211)
         at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:223)
         at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:326)
         at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:119)
         at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:68)
         at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:595)
         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
         at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:263)
         at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:260)
         at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
         at java.lang.Thread.run(Thread.java:745)
 Caused by: java.lang.IllegalArgumentException: Invalid format: "16777216" is too short
         at org.joda.time.format.DateTimeParserBucket.doParseMillis(DateTimeParserBucket.java:187)
         at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:780)
         at org.elasticsearch.index.mapper.core.DateFieldMapper$DateFieldType.parseStringValue(DateFieldMapper.java:362)
         at org.elasticsearch.index.mapper.core.DateFieldMapper.innerParseCreateField(DateFieldMapper.java:528)
         at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:241)
         at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:335)
         ... 22 more
```

Is this a bug in my config? Or graylog bug? or elasticsearch bug?

### Environment

* Graylog Version: 2.0-alpha4
* Elasticsearch Version: 2.2.0
* MongoDB Version:
* Operating System: Debian 8

**Comment by kroepke** [comment] 2016-03-04 13:39
This looks like either the source sending the message changed (the timestamp is indexed as: `16777216`) or a change in the extractors/converters.

We recently had a change applied to the syslog parser, but I couldn't reproduce this issue.

Looking at the raw message, this looks suspicious: `filterlog: 5,16777216`

Are you maybe using grok to extract fields and it mistakenly overrides the timestamp?

Since this does not look like a bug I'll close the issue. Please reopen it if you feel that there is in fact a bug in Graylog.

Thanks!

**Closed by kroepke** 2016-03-04 13:39 UTC

**Comment by pszafer** [comment] 2016-03-07 08:08
you're right!

I don't even rembered that I changed this.
Thanks for help :). Topic can be closed.
