### ISSUE TITLE
Grok Pattern 400 error

### ISSUE THREAD

**Issue by viperfx** [Graylog2/graylog2-server#3139] opened 2016-11-30 17:24 UTC
## Expected Behavior
I have tested a grok pattern in the grok debugger and from other github issues I have read, this should mean it would work in graylog

## Current Behavior
Log lines to match
```
Connect: 25 ms, Pretransfer: 25 ms, StartTransfer: 89 ms, ContentTransfer: 0 ms, NameLookup: 0 ms, Total: 89 ms, DNSLookup: 0 ms, TCPConnection: 25 ms, TLSHandshake: 0 ms, ServerProcessing: 89 ms
TLSHandshake: 0 ms, ContentTransfer: 0 ms, StartTransfer: 88 ms, Total: 88 ms, DNSLookup: 0 ms, TCPConnection: 76 ms, ServerProcessing: 88 ms, NameLookup: 0 ms, Connect: 76 ms, Pretransfer: 76 ms
TLSHandshake: 0 ms, ServerProcessing: 95 ms, ContentTransfer: 0 ms, DNSLookup: 0 ms, TCPConnection: 72 ms, NameLookup: 0 ms, Connect: 72 ms, Pretransfer: 72 ms, StartTransfer: 95 ms, Total: 95 ms
TCPConnection: 0 ms, TLSHandshake: 0 ms, ContentTransfer: 0 ms, Pretransfer: 0 ms, Total: 91 ms, DNSLookup: 0 ms, ServerProcessing: 91 ms, NameLookup: 0 ms, Connect: 0 ms, StartTransfer: 91 ms
StartTransfer: 329 ms, DNSLookup: 0 ms, TCPConnection: 76 ms, TLSHandshake: 156 ms, NameLookup: 0 ms, Pretransfer: 76 ms, ServerProcessing: 96 ms, ContentTransfer: 0 ms, Connect: 76 ms, Total: 329 ms
```

Pattern 
```
%{WORD}[:] %{INT:Connect} ms, %{WORD}[:] %{INT:Pretransfer} ms, %{WORD}[:] %{INT:StartTransfer} ms, %{WORD}[:] %{INT:ContentTransfer} ms, %{WORD}[:] %{INT:NameLookup} ms, %{WORD}[:] %{INT:Total} ms, %{WORD}[:] %{INT:DNSLookup} ms, %{WORD}[:] %{INT:TCPConnection} ms, %{WORD}[:] %{INT:TLSHandshake} ms, %{WORD}[:] %{INT:ServerProcessing} ms
```

## Steps to Reproduce (for bugs)

1. Use default graylog2 installation
2. Add grok pattern at URL/system/grokpatterns
3. 400 Error message show at bottom

## Context

I am trying to match these messages from syslog and index the metrics as fields, to eventually send to graphna 
## Your Environment

* Graylog Version:2.1.2+50e449a, codename Smuttynose

**Comment by joschi** [comment] 2016-12-07 16:04
@viperfx I've looked into this issue but couldn't reproduce it on Graylog 2.2.0-beta.1.

I'll close this issue as fixed, although we won't fix it in the Graylog 2.1.x series.

**Closed by joschi** 2016-12-07 16:04 UTC
Labels: to-verify
