### ISSUE TITLE
Username case sensitivity

### ISSUE THREAD

**Issue by pdepaepe** [Graylog2/graylog2-server#1361] opened 2015-08-19 13:43 UTC
Hello,

With ldap support (not tested without), on authentication, varying the case sensitivity of your username will create a new graylog account (and so new permission context).

Example:

jsmith
Jsmith
JSmith ....

**Comment by joschi** [comment] 2015-08-19 14:07
(Semi-) duplicate of Graylog2/graylog2-web-interface#1007. I'm keeping this issue open because the other one is in the wrong repository.

**Comment by kroepke** [comment] 2015-08-24 10:18
We will reconsider this for 2.0 because it needs a few incompatible API changes.

We would either need to treat user names as case insensitive in the entire application or map LDAP/AD names to lowercase.
In either case we have hit problems in the past which is why we haven't addressed it yet.

**Comment by sharique** [comment] 2016-12-22 09:54
Any update of this issue?

**Comment by joschi** [comment] 2016-12-22 09:57
@sharique No.

**Comment by drewmmiranda** [comment] 2017-06-29 02:38
Any update? :)

**Comment by martinbydefault** [comment] 2017-09-23 14:03
Is this planned to be implemented in some future?  
I support @kroepke idea about creating a mapping, but maybe another way is to add a boolean field to the UserImpl, named CASE_INSENSITIVE that is`true` if case insensitive and `false` if not, and the getName method of the user is the one that handles the conversion to lower case.  
I haven't yet inspected the whole code to see if this alternative breaks less things but I think at least require less changes.  
What do you think about this?

**Comment by omniton** [comment] 2020-03-31 17:32
any plan about fixing this issue?

**Comment by jalogisch** [comment] 2020-06-09 12:08
[z#843562]

**Comment by tellistone** [comment] 2022-07-05 10:01
We should super fix this, it's real annoying!

**Comment by boosty** [comment] 2022-08-17 13:27
Might be something for 5.0.

**Comment by boosty** [comment] 2022-10-12 14:59
I suggest to add a new config option (only for AD/LDAP for now) to lowercase the username on creation and sign in.
The change should come with a documentation on how to convert existing usernames in MongoDB to lowercase.

Opinions?

**Comment by drewmiranda-gl** [comment] 2022-10-12 16:12
That could work. Is there a practical reason why one would need case sensitivity for usernames? I'm not familiar with open ldap but Active Directory treats usernames as case insensitive so doing a `toLower` on the username would work. Is the issue that mongo is storing it in a case sensitive way and graylog has to reconcile with mongo?

For usability, i'm a fan of "expected behavior" being the default. In this case, new installs could default to usernames always being lower (or even a cosmetic/display username and the forced lower username).

**Comment by jalogisch** [comment] 2022-10-12 16:18
The problem is that login will work with any - at least in the past - but as the account is stored in Mongo the way you type in you are able to create multiple accounts just by changing cases for letters ...

**Comment by bernd** [comment] 2022-10-12 16:42
> The problem is that login will work with any - at least in the past - but as the account is stored in Mongo the way you type in you are able to create multiple accounts just by changing cases for letters ...

This is not the case anymore. For LDAP/AD Graylog is using the username that is returned from the LDAP/AD server instead of using the value that has been entered by the user in the login form. So whatever format the user is using, we always use the format from the LDAP/AD server. We also don't use the username as the primary key for user accounts from LDAP/AD anymore but use the `entryUUID` (or equivalent), so even changes in the username don't lead to the creation of a new user account in Graylog.

**Comment by drewmiranda-gl** [comment] 2022-10-12 16:48
I didn't realize the dup user thing was fixed. Looks like the remaining issue is an `Invalid Credentials` error even though the username (which should be case insensitive) is correct:
![image](https://user-images.githubusercontent.com/107503402/195401633-2780c80c-d95b-4c10-92ec-757dee7ac3b3.png)

**Comment by bernd** [comment] 2022-10-12 16:56
> I didn't realize the dup user thing was fixed. Looks like the remaining issue is an `Invalid Credentials` error even though the username (which should be case insensitive) is correct: ![image](https://user-images.githubusercontent.com/107503402/195401633-2780c80c-d95b-4c10-92ec-757dee7ac3b3.png)

@drewmiranda-gl The user `Drew` is a user in LDAP/AD or a local Graylog user?

**Comment by drewmiranda-gl** [comment] 2022-10-12 17:01
My mistake, that was a local user 🤦‍♂️, LDAP user does appear to work correctly regardless of case.

Local users appear to have an issue with casing.

**Comment by bernd** [comment] 2022-10-13 08:57
For reference:

We fixed the creation of duplicate accounts due to the case sensitivity of usernames as part of the new authentication implementation in https://github.com/Graylog2/graylog2-server/pull/9007.

**Comment by boosty** [comment] 2022-11-10 08:48
I am closing this for now. Should there be more demand to change the behaviour for local users, we can reopen this issue (or create a new, more specific one).

**Closed by boosty** 2022-11-10 08:48 UTC
Labels: feature, triaged
