### ISSUE TITLE
Add-To-Dashboard menu empty for Histogram on search page

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#4995] opened 2018-08-14 10:29 UTC
There are reports that under currently unknown circumstances the add-to-dashboard menu for the histogram on the search page can come up empty, while all other menus are properly populated (e.g. quick values or count).

The user in question is both `Reader` and `Admin` and has write access to all dashboards, according to API responses and screenshots.

This issue is consistently reproducable for the reporting user (as well as other users at that site) and cross-browser.
Occurring in 2.4.5.

Please contact me for access to the confidential screenshots and other data.

**Comment by edmundoa** [comment] 2018-08-21 13:02
Closing, turned out to be somehow caused by outdated web plugins.

**Closed by edmundoa** 2018-08-21 13:02 UTC
Labels: bug, triaged, web

**Comment by Sophie-de-Lalalie** [comment] 2018-09-12 10:26
Hi. We have the same problem in a Rancher/Docker Setup with image: graylog/graylog:2.4.6-1
Could you please tell me, what "somehow caused by outdated web plugins" means exactly? Thank you.

**Comment by edmundoa** [comment] 2018-09-12 10:38
@Sophie-de-Lalalie it means that old plugins may run some old common code under certain situations, and the best way to avoid those problems is to ensure all official Graylog plugins are exactly the same version as the Graylog version you are using. Unofficial plugins must be compatible with that Graylog version as well.

In case you doubt which plugin versions a Graylog setup has installed, check the _Installed plugins_ section under _System -> Nodes -> \<Node\>_. Please note that you should ensure all nodes are running the same plugins, to avoid any issues.

**Comment by Sophie-de-Lalalie** [comment] 2018-09-12 11:05
Thank you. graylog/graylog:2.4.6-1 ships with 2.4.0 plugins:

> Installed plugins 10 plugins installed
Name	Version	Author	Description
AWS plugins	2.4.0	Graylog, Inc.	Collection of plugins to read data from or interact with the Amazon Web Services (AWS).  Website 
CEF Input	2.4.0	Graylog, Inc.	Input plugin to receive CEF (Common Event Format) messages.  Website 
Collector	2.4.0	Graylog, Inc.	Collectors plugin  Website 
Elastic Beats Input	2.4.0	Graylog, Inc.	Input plugin for Elastic Beats (Beats/Lumberjack protocol).  Website 
Enterprise Integration Plugin	2.4.0	Graylog, Inc	Provides basic integration with Graylog Enterprise  Website 
MapWidgetPlugin	2.4.0	Graylog, Inc.	Map widget for Graylog  Website 
NetFlow Plugin	2.4.0	Graylog, Inc.	Provides NetFlow inputs  Website 
Pipeline Processor Plugin	2.4.0	Graylog, Inc.	Pluggable pipeline processing framework  Website 
Slack	3.0.0	Graylog, Inc.	Slack plugin to forward messages or write alarms to Slack chat rooms.  Website 
Threat Intelligence Plugin	2.4.0	Graylog, Inc.	

I tested using graylog/graylog:2.4 and cant reproduce the problem there. So either at least one of these pre-shipped plugins or the Slack 3.0.0 plugin is not compatible with 2.4.6-1.

**Comment by edmundoa** [comment] 2018-09-12 11:40
No, Graylog 2.4.6 ships with 2.4.6 plugins, so please install those and try again. The Slack plugin does not have any web components, so it should not cause any problems in this case. If you need further assistance, please write in the [discussion forum](https://community.graylog.org/) or the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by Sophie-de-Lalalie** [comment] 2018-09-12 11:47
Then sorry for my misstake there. Your are right: the slack plugin is not the problem, i tested it. So the  volume we use for the plugin directory contained outdated plugins then. Anyway. Problem solved. Thank you very much.
