### ISSUE TITLE
Indices disappear in graylog 1.0.0

### ISSUE THREAD

**Issue by pcmodem** [Graylog2/graylog2-server#1114] opened 2015-04-14 21:23 UTC
Much the same as previous reported incident https://github.com/Graylog2/graylog2-server/issues/427 except without obvious memory errors

I am able to see the indexes that are missing on disk and are even seeing them be re-indexed in the log, however graylog-web interface does not see them even after both a manual re-index and a manual deflector cycle.

I do not see any error messages related to memory in the graylog server logs or in the elasticsearch logs.  I have increased ES_HEAP_SIZE from the default to 3g in /etc/init.d/elasticsearch with no results

![screen shot 2015-04-14 at 5 12 00 pm](https://cloud.githubusercontent.com/assets/6361870/7147579/e7921f4c-e2c9-11e4-8c1d-0fbed64a04a1.png)

![screen shot 2015-04-14 at 5 16 15 pm](https://cloud.githubusercontent.com/assets/6361870/7147592/fbe17240-e2c9-11e4-8484-309689d2ba1d.png)

root@util42:/etc/init.d# tail /var/log/elasticsearch/graylog2.log
[2015-04-14 17:01:26,927][INFO ][http                     ] [Blood Brothers] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/10.14.x.x:9200]}
[2015-04-14 17:01:26,928][INFO ][node                     ] [Blood Brothers] started
[2015-04-14 17:01:28,218][INFO ][gateway                  ] [Blood Brothers] recovered [5] indices into cluster_state
[2015-04-14 17:01:39,552][INFO ][cluster.service          ] [Blood Brothers] added {[graylog2-server][uwp90wZOR4uWUbYryr6hGQ][util42][inet[/10.14.x.x:9350]]{client=true, data=false, master=false},}, reason: zen-disco-receive(join from node[[graylog2-server][uwp90wZOR4uWUbYryr6hGQ][util42][inet[/10.14.x.x:9350]]{client=true, data=false, master=false}])
[2015-04-14 17:01:39,750][INFO ][cluster.service          ] [Blood Brothers] removed {[graylog2-server][uwp90wZOR4uWUbYryr6hGQ][util42][inet[/10.14.x.x:9350]]{client=true, data=false, master=false},}, reason: zen-disco-node_left([graylog2-server][uwp90wZOR4uWUbYryr6hGQ][util42][inet[/10.14.190.96:9350]]{client=true, data=false, master=false})
[2015-04-14 17:02:20,961][INFO ][cluster.service          ] [Blood Brothers] added {[graylog2-server][LJKVXw0NSLqEMSvGMnZKjg][util42][inet[/10.14.x.x:9350]]{client=true, data=false, master=false},}, reason: zen-disco-receive(join from node[[graylog2-server][LJKVXw0NSLqEMSvGMnZKjg][util42][inet[/10.14.190.96:9350]]{client=true, data=false, master=false}])
[2015-04-14 17:08:31,011][INFO ][cluster.metadata         ] [Blood Brothers] [graylog2_6] creating index, cause [api], shards [1]/[0], mappings []
[2015-04-14 17:08:31,116][INFO ][cluster.metadata         ] [Blood Brothers] [graylog2_6] create_mapping [message]
[2015-04-14 17:08:32,526][INFO ][cluster.metadata         ] [Blood Brothers] [graylog2_6] update_mapping [message] (dynamic)
[2015-04-14 17:08:34,519][INFO ][cluster.metadata         ] [Blood Brothers] [graylog2_6] update_mapping [message] (dynamic)
root@util42:/etc/init.d#

root@util42:/data/elasticsearch/graylog2/nodes/0/indices# ls -lh
total 24K
drwxr-xr-x 4 elasticsearch elasticsearch 4.0K Mar 18 20:14 graylog2_1
drwxr-xr-x 4 elasticsearch elasticsearch 4.0K Mar 22 21:43 graylog2_2
drwxr-xr-x 4 elasticsearch elasticsearch 4.0K Mar 28 21:56 graylog2_3
drwxr-xr-x 4 elasticsearch elasticsearch 4.0K Apr  4 21:00 graylog2_4
drwxr-xr-x 4 elasticsearch elasticsearch 4.0K Apr  9 21:48 graylog2_5
drwxr-xr-x 4 elasticsearch elasticsearch 4.0K Apr 14 17:08 graylog2_6

**Comment by joschi** [comment] 2015-04-15 08:21
Please check if all indices are shown in the output of the following curl command (replace the admin user credentials and the hostname where Graylog server is running):
```
curl -u admin:PASSWORD http://localhost:12900/system/indices/ranges?pretty=true
```

**Comment by pcmodem** [comment] 2015-04-15 17:18
This output does not see the two missing indices:

#@util42:~$ curl -u http://localhost:12900/system/indices/ranges?pretty=true
{
  "total" : 4,
  "ranges" : [ {
    "index" : "graylog2_6",
    "starts" : "2015-04-14T21:09:05.000Z",
    "calculation_took_ms" : 4,
    "calculated_at" : "2015-04-14T21:09:08.000Z"
  }, {
    "index" : "graylog2_5",
    "starts" : "2015-04-14T21:08:29.000Z",
    "calculation_took_ms" : 764,
    "calculated_at" : "2015-04-14T21:09:10.000Z"
  }, {
    "index" : "graylog2_2",
    "starts" : "2015-03-29T01:56:55.000Z",
    "calculation_took_ms" : 883,
    "calculated_at" : "2015-04-14T21:09:10.000Z"
  }, {
    "index" : "graylog2_1",
    "starts" : "2015-03-23T01:43:34.000Z",
    "calculation_took_ms" : 905,
    "calculated_at" : "2015-04-14T21:09:12.000Z"
  } ]

**Comment by pcmodem** [comment] 2015-04-15 17:41
Looking through the graylog server logs, it looks like it had issues connecting to the elasticsearch instance while cycling, possibly due to memory - however its not very well detailed.  maybe this is related?  

 cat /var/log/graylog-server.log | grep "graylog2_3"
2015-03-28 21:56:51,404 INFO : org.graylog2.indexer.Deflector - Cycling from <graylog2_2> to <graylog2_3>
2015-03-28 21:56:51,404 INFO : org.graylog2.indexer.Deflector - Creating index target <graylog2_3>...
2015-03-28 21:56:54,113 INFO : org.graylog2.indexer.ranges.RebuildIndexRangesJob - Calculated range of [graylog2_3] in [3ms].
2015-03-30 17:26:44,005 WARN : org.graylog2.rest.resources.search.SearchResource - Unable to execute search: Failed to execute phase [query_fetch], all shards failed; shardFailures {[vTlx0xbzRKimrnRfKyWvIA][graylog2_3][0]: RemoteTransportException[[Morlun][inet[/10.14.x:9300]][search/phase/query+fetch]]; nested: SearchParseException[[graylog2_3][0]: from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"query":{"query_string":{"query":"NOT message:.xml HTTP/1.1","allow_leading_wildcard":false}},"post_filter":{"bool":{"must":[{"range":{"timestamp":{"from":"2015-03-30 20:26:43.910","to":"2015-03-30 21:26:43.910","include_lower":true,"include_upper":true}}},{"query":{"query_string":{"query":"streams:55074dcbe4b0b61688312bcb"}}}]}},"sort":[{"timestamp":{"order":"desc"}}]}]]]; nested: QueryParsingException[[graylog2_3] Failed to parse query [NOT message:.xml HTTP/1.1]]; nested: ParseException[Cannot parse 'NOT message:.xml HTTP/1.1': Lexical error at line 1, column 26.  Encountered: <EOF> after : "/1.1"]; nested: TokenMgrError[Lexical error at line 1, column 26.  Encountered: <EOF> after : "/1.1"]; }
---many different errors ----
[23]: index [graylog2_3], type [message], id [759fdb01-db98-11e4-a772-005056853cf4], message [ClusterBlockException[blocked by: [FORBIDDEN/8/index write (api)];]]
[24]: index [graylog2_3], type [message], id [75a6dfe0-db98-11e4-a772-005056853cf4], message [ClusterBlockException[blocked by: [FORBIDDEN/8/index write (api)];]]
[0]: index [graylog2_3], type [message], id [b28685f0-db98-11e4-a772-005056853cf4], message [ClusterBlockException[blocked by: [FORBIDDEN/8/index write (api)];]]
2015-04-05 09:36:00,513 WARN : org.graylog2.periodical.IndexRotationThread - Deflector is pointing to [graylog2_3], not the newest one: [graylog2_4]. Re-pointing.


 cat /var/log/graylog-server.log | grep "graylog2_4"
2015-04-04 21:00:28,531 INFO : org.graylog2.indexer.Deflector - Cycling from <graylog2_3> to <graylog2_4>
2015-04-04 21:00:28,531 INFO : org.graylog2.indexer.Deflector - Creating index target <graylog2_4>...
2015-04-04 21:00:28,867 INFO : org.graylog2.indexer.ranges.RebuildIndexRangesJob - Index [graylog2_4] is empty, inserting dummy index range.
2015-04-04 21:00:28,868 INFO : org.graylog2.indexer.ranges.RebuildIndexRangesJob - Index [graylog2_4] is empty but it is the current deflector target. Inserting dummy index range.
org.elasticsearch.action.search.SearchPhaseExecutionException: Failed to execute phase [query], all shards failed; shardFailures {[vTlx0xbzRKimrnRfKyWvIA][graylog2_4][0]: NodeDisconnectedException[[Morlun][inet[/10.x:9300]][search/phase/query] disconnected]}
2015-04-05 06:02:01,855 WARN : org.graylog2.periodical.IndexRotationThread - Deflector is pointing to [graylog2_4], not the newest one: [graylog2_3]. Re-pointing.
2015-04-05 06:02:04,939 WARN : org.graylog2.periodical.IndexRotationThread - Deflector is pointing to [graylog2_3], not the newest one: [graylog2_4]. Re-pointing.
2015-04-05 09:34:12,667 WARN : org.graylog2.periodical.IndexRotationThread - Deflector is pointing to [graylog2_4], not the newest one: [graylog2_3]. Re-pointing.
org.elasticsearch.action.search.SearchPhaseExecutionException: Failed to execute phase [query], all shards failed; shardFailures {[vTlx0xbzRKimrnRfKyWvIA][graylog2_4][0]: NodeDisconnectedException[[Morlun][inet[/10x9300]][search/phase/query] disconnected]}
[0]: index [graylog2_4], type [message], id [279c1590-db98-11e4-a772-005056853cf4], message [UnavailableShardsException[[graylog2_4][0] [1] shardIt, [1] active : Timeout waiting for [1m], request: org.elasticsearch.action.bulk.BulkShardRequest@69a8f6ee]]
[1]: index [graylog2_4],
[499]: index [graylog2_4], type [message], id [2f5d67c1-db98-11e4-a772-005056853cf4], message [UnavailableShardsException[[graylog2_4][0] [1] shardIt, [1] active : Timeout waiting for [1m], request: org.elasticsearch.action.bulk.BulkShardRequest@4b26dee6]]
2015-04-05 09:36:00,513 WARN : org.graylog2.periodical.IndexRotationThread - Deflector is pointing to [graylog2_3], not the newest one: [graylog2_4]. Re-pointing.
org.elasticsearch.action.search.SearchPhaseExecutionException: Failed to execute phase [query], all shards failed; shardFailures {[vTlx0xbzRKimrnRfKyWvIA][graylog2_4][0]: NodeDisconnectedException[[Morlun][inet[/10.:9300]][search/phase/query] disconnected]}
org.elasticsearch.action.search.SearchPhaseExecutionException: Failed to execute phase [query], all shards failed; shardFailures {[vTlx0xbzRKimrnRfKyWvIA][graylog2_4][0]: NodeDisconnectedException[[Morlun][inet[/10.:9300]][search/phase/query] disconnected]}
———many like above -----
2015-04-09 21:48:01,791 INFO : org.graylog2.periodical.IndexRotationThread - Deflector index <graylog2_4> should be rotated, Pointing deflector to new index now!
2015-04-09 21:48:01,811 INFO : org.graylog2.indexer.Deflector - Cycling from <graylog2_4> to <graylog2_5>
2015-04-09 21:48:05,122 INFO : org.graylog2.indexer.ranges.RebuildIndexRangesJob - Calculated range of [graylog2_4] in [2824ms].
2015-04-09 21:48:32,121 INFO : org.graylog2.indexer.SetIndexReadOnlyJob - Flushing old index <graylog2_4>.
2015-04-09 21:48:32,160 INFO : org.graylog2.indexer.SetIndexReadOnlyJob - Setting old index <graylog2_4> to read-only.
2015-04-09 21:48:32,221 INFO : org.graylog2.indexer.indices.jobs.OptimizeIndexJob - Optimizing index <graylog2_4>.

Looks like maybe ran out of memory during index cycle?

[2015-04-03 17:28:17,829][ERROR][indices.fielddata.breaker] [Morlun] New used memory 959764824 [915.3mb] from field [message] would be larger than configured breaker: 623326003 [594.4mb], breaking
graylog2.log.2015-03-28:1:[2015-03-28 21:56:51,659][INFO ][cluster.metadata         ] [Morlun] [graylog2_3] creating index, cause [api], shards [1]/[0], mappings []
graylog2.log.2015-03-28:2:[2015-03-28 21:56:51,868][INFO ][cluster.metadata         ] [Morlun] [graylog2_3] create_mapp[2015-04-03 17:28:11,203][ERROR][indices.fielddata.breaker] [Morlun] New used memory 959781642 [915.3mb] from field [message] would be larger than configured breaker: 623326003 [594.4mb], breaking

**Comment by pugnacity** [comment] 2015-06-19 11:18
i have the same problem here, but i don't have any thing in the graylog2 log file.  the indices are still in elastic search. how can i read add the missing indices?

**Comment by drothenberger** [comment] 2015-06-19 18:27
I had the same problem and ultimately discovered the cause was some bad timestamps being sent by one of my devices. The year was 2050 for the timestamps. This caused the start time calculated by Graylog2 to be negative for the index, so Graylog2 did not include the index.

I solved the problem by fixing the time on the device. I got the missing indices back into Graylog2 by manually removing the bad documents from ElasticSearch and then telling Graylog2 to recalculate the time ranges for the indices.

**Comment by pugnacity** [comment] 2015-06-19 19:35
How did you delete the records? I always get only the error:
```
curl -XDELETE 'http://localhost:9200/graylog-elasticsearch-live/graylog2_204/_query?pretty' -d '{
    "query" : {
        "term" : { "_id" : "a77512dc-163a-11e5-bb5b-005056a7e5cd" }
    }
}
'
{
  "error" : "IndexMissingException[[graylog-elasticsearch-live] missing]",
  "status" : 404
}
```

**Comment by drothenberger** [comment] 2015-06-19 19:52
I used the ESClient ElasticSearch front-end.

https://github.com/rdpatil4/ESClient

**Comment by bernd** [comment] 2015-08-06 18:24
The upcoming Graylog 1.2.0 has a new index range calculator which does not have that problem anymore.

Closing this issue.

**Closed by bernd** 2015-08-06 18:24 UTC
