### ISSUE TITLE
Sidecar: Restart after configuration update of rsyslog fails, but manual restart works

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#5050] opened 2018-09-02 23:36 UTC
Changed the configuration of my rsyslog daemon and the sidecar initiated a restart as expected. It did, however, fail. Initiating a manual restart through the Sidecar web interface page succeeded without problems.

Maybe there is some kind of a race condition, where the starting of the process doesn't wait until it's fully shut down? Looks like rsyslog complains about an existing PID file, that, I suspect, had not been deleted yet.

```
time="2018-09-02T18:33:02-05:00" level=info msg="[rsyslog] Configuration change detected, rewriting configuration file." 
time="2018-09-02T18:33:03-05:00" level=error msg="[rsyslog] Error during configuration validation: Starting parse\nEntering state 0\nReducing stack by rule 1 (line 132):\n-> $$ = nterm conf ()\nStack now 0\nEntering state 1\nReading a token: Next token is token BEGINOBJ ()\nShifting token BEGINOBJ ()\nEntering state 3\nReading a token: Next token is token NAME ()\nReducing stack by rule 17 (line 157):\n-> $$ = nterm nvlst ()\nStack now 0 1 3\nEntering state 27\nNext token is token NAME ()\nShifting token NAME ()\nEntering state 55\nReading a token: Next token is token '=' ()\nShifting token '=' ()\nEntering state 97\nReading a token: Next token is token STRING ()\nShifting token STRING ()\nEntering state 132\nReducing stack by rule 20 (line 160):\n   $1 = token STRING ()\n-> $$ = nterm value ()\nStack now 0 1 3 27 55 97\nEntering state 133\nReducing stack by rule 19 (line 159):\n   $1 = token NAME ()\n   $2 = token '=' ()\n   $3 = nterm value ()\n-> $$ = nterm nv ()\nStack now 0 1 3 27\nEntering state 57\nReducing stack by rule 18 (line 158):\n   $1 = nterm nvlst ()\n   $2 = nterm nv ()\n-> $$ = nterm nvlst ()\nStack now 0 1 3\nEntering state 27\nReading a token: Next token is token ENDOBJ ()\nShifting token ENDOBJ ()\nEntering state 56\nReducing stack by rule 7 (line 138):\n   $1 = token BEGINOBJ ()\n   $2 = nterm nvlst ()\n   $3 = token ENDOBJ ()\n-> $$ = nterm obj ()\nStack now 0 1\nEntering state 23\nReducing stack by rule 2 (line 133):\n   $1 = nterm conf ()\n   $2 = nterm obj ()\n-> $$ = nterm conf ()\nStack now 0\nEntering state 1\nReading a token: Next token is token BEGINOBJ ()\nShifting token BEGINOBJ ()\nEntering state 3\nReading a token: Next token is token NAME ()\nReducing stack by rule 17 (line 157):\n-> $$ = nterm nvlst ()\nStack now 0 1 3\nEntering state 27\nNext token is token NAME ()\nShifting token NAME ()\nEntering state 55\nReading a token: Next token is token '=' ()\nShifting token '=' ()\nEntering state 97\nReading a token: Next token is token STRING ()\nShifting token STRING ()\nEntering state 132\nReducing stack by rule 20 (line 160):\n   $1 = token STRING ()\n-> $$ = nterm value ()\nStack now 0 1 3 27 55 97\nEntering state 133\nReducing stack by rule 19 (line 159):\n   $1 = token NAME ()\n   $2 = token '=' ()\n   $3 = nterm value ()\n-> $$ = nterm nv ()\nStack now 0 1 3 27\nEntering state 57\nReducing stack by rule 18 (line 158):\n   $1 = nterm nvlst ()\n   $2 = nterm nv ()\n-> $$ = nterm nvlst ()\nStack now 0 1 3\nEntering state 27\nReading a token: Next token is token NAME ()\nShifting token NAME ()\nEntering state 55\nReading a token: Next token is token '=' ()\nShifting token '=' ()\nEntering state 97\nReading a token: Next token is token STRING ()\nShifting token STRING ()\nEntering state 132\nReducing stack by rule 20 (line 160):\n   $1 = token STRING ()\n-> $$ = nterm value ()\nStack now 0 1 3 27 55 97\nEntering state 133\nReducing stack by rule 19 (line 159):\n   $1 = token NAME ()\n   $2 = token '=' ()\n   $3 = nterm value ()\n-> $$ = nterm nv ()\nStack now 0 1 3 27\nEntering state 57\nReducing stack by rule 18 (line 158):\n   $1 = nterm nvlst ()\n   $2 = nterm nv ()\n-> $$ = nterm nvlst ()\nStack now 0 1 3\nEntering state 27\nReading a token: Next token is token ENDOBJ ()\nShifting token ENDOBJ ()\nEntering state 56\nReducing stack by rule 7 (line 138):\n   $1 = token BEGINOBJ ()\n   $2 = nterm nvlst ()\n   $3 = token ENDOBJ ()\n-> $$ = nterm obj ()\nStack now 0 1\nEntering state 23\nReducing stack by rule 2 (line 133):\n   $1 = nterm conf ()\n   $2 = nterm obj ()\n-> $$ = nterm conf ()\nStack now 0\nEntering state 1\nReading a token: Next token is token PROPFILT ()\nShifting token PROPFILT ()\nEntering state 17\nReading a token: Next token is token LEGACY_ACTION ()\nShifting token LEGACY_ACTION ()\nEntering state 14\nReducing stack by rule 40 (line 189):\n   $1 = token LEGACY_ACTION ()\n-> $$ = nterm s_act ()\nStack now 0 1 17\nEntering state 26\nReducing stack by rule 37 (line 185):\n   $1 = nterm s_act ()\n-> $$ = nterm actlst ()\nStack now 0 1 17\nEntering state 25\nReading a token: Next token is token PRIFILT ()\nReducing stack by rule 24 (line 164):\n   $1 = nterm actlst ()\n-> $$ = nterm stmt ()\nStack now 0 1 17\nEntering state 47\nReducing stack by rule 35 (line 183):\n   $1 = nterm stmt ()\n-> $$ = nterm block ()\nStack now 0 1 17\nEntering state 49\nReducing stack by rule 32 (line 180):\n   $1 = token PROPFILT ()\n   $2 = nterm block ()\n-> $$ = nterm stmt ()\nStack now 0 1\nEntering state 24\nReducing stack by rule 3 (line 134):\n   $1 = nterm conf ()\n   $2 = nterm stmt ()\n-> $$ = nterm conf ()\nStack now 0\nEntering state 1\nNext token is token PRIFILT ()\nShifting token PRIFILT ()\nEntering state 16\nReading a token: Next token is token LEGACY_ACTION ()\nShifting token LEGACY_ACTION ()\nEntering state 14\nReducing stack by rule 40 (line 189):\n   $1 = token LEGACY_ACTION ()\n-> $$ = nterm s_act ()\nStack now 0 1 16\nEntering state 26\nReducing stack by rule 37 (line 185):\n   $1 = nterm s_act ()\n-> $$ = nterm actlst ()\nStack now 0 1 16\nEntering state 25\nReading a token: Next token is token PRIFILT ()\nReducing stack by rule 24 (line 164):\n   $1 = nterm actlst ()\n-> $$ = nterm stmt ()\nStack now 0 1 16\nEntering state 47\nReducing stack by rule 35 (line 183):\n   $1 = nterm stmt ()\n-> $$ = nterm block ()\nStack now 0 1 16\nEntering state 48\nReducing stack by rule 31 (line 179):\n   $1 = token PRIFILT ()\n   $2 = nterm block ()\n-> $$ = nterm stmt ()\nStack now 0 1\nEntering state 24\nReducing stack by rule 3 (line 134):\n   $1 = nterm conf ()\n   $2 = nterm stmt ()\n-> $$ = nterm conf ()\nStack now 0\nEntering state 1\nNext token is token PRIFILT ()\nShifting token PRIFILT ()\nEntering state 16\nReading a token: Next token is token LEGACY_ACTION ()\nShifting token LEGACY_ACTION ()\nEntering state 14\nReducing stack by rule 40 (line 189):\n   $1 = token LEGACY_ACTION ()\n-> $$ = nterm s_act ()\nStack now 0 1 16\nEntering state 26\nReducing stack by rule 37 (line 185):\n   $1 = nterm s_act ()\n-> $$ = nterm actlst ()\nStack now 0 1 16\nEntering state 25\nReading a token: Next token is token PRIFILT ()\nReducing stack by rule 24 (line 164):\n   $1 = nterm actlst ()\n-> $$ = nterm stmt ()\nStack now 0 1 16\nEntering state 47\nReducing stack by rule 35 (line 183):\n   $1 = nterm stmt ()\n-> $$ = nterm block ()\nStack now 0 1 16\nEntering state 48\nReducing stack by rule 31 (line 179):\n   $1 = token PRIFILT ()\n   $2 = nterm block ()\n-> $$ = nterm stmt ()\nStack now 0 1\nEntering state 24\nReducing stack by rule 3 (line 134):\n   $1 = nterm conf ()\n   $2 = nterm stmt ()\n-> $$ = nterm conf ()\nStack now 0\nEntering state 1\nNext token is token PRIFILT ()\nShifting token PRIFILT ()\nEntering state 16\nReading a token: Next token is token LEGACY_ACTION ()\nShifting token LEGACY_ACTION ()\nEntering state 14\nReducing stack by rule 40 (line 189):\n   $1 = token LEGACY_ACTION ()\n-> $$ = nterm s_act ()\nStack now 0 1 16\nEntering state 26\nReducing stack by rule 37 (line 185):\n   $1 = nterm s_act ()\n-> $$ = nterm actlst ()\nStack now 0 1 16\nEntering state 25\nReading a token: Next token is token PRIFILT ()\nReducing stack by rule 24 (line 164):\n   $1 = nterm actlst ()\n-> $$ = nterm stmt ()\nStack now 0 1 16\nEntering state 47\nReducing stack by rule 35 (line 183):\n   $1 = nterm stmt ()\n-> $$ = nterm block ()\nStack now 0 1 16\nEntering state 48\nReducing stack by rule 31 (line 179):\n   $1 = token PRIFILT ()\n   $2 = nterm block ()\n-> $$ = nterm stmt ()\nStack now 0 1\nEntering state 24\nReducing stack by rule 3 (line 134):\n   $1 = nterm conf ()\n   $2 = nterm stmt ()\n-> $$ = nterm conf ()\nStack now 0\nEntering state 1\nNext token is token PRIFILT ()\nShifting token PRIFILT ()\nEntering state 16\nReading a token: Next token is token LEGACY_ACTION ()\nShifting token LEGACY_ACTION ()\nEntering state 14\nReducing stack by rule 40 (line 189):\n   $1 = token LEGACY_ACTION ()\n-> $$ = nterm s_act ()\nStack now 0 1 16\nEntering state 26\nReducing stack by rule 37 (line 185):\n   $1 = nterm s_act ()\n-> $$ = nterm actlst ()\nStack now 0 1 16\nEntering state 25\nReading a token: Next token is token PRIFILT ()\nReducing stack by rule 24 (line 164):\n   $1 = nterm actlst ()\n-> $$ = nterm stmt ()\nStack now 0 1 16\nEntering state 47\nReducing stack by rule 35 (line 183):\n   $1 = nterm stmt ()\n-> $$ = nterm block ()\nStack now 0 1 16\nEntering state 48\nReducing stack by rule 31 (line 179):\n   $1 = token PRIFILT ()\n   $2 = nterm block ()\n-> $$ = nterm stmt ()\nStack now 0 1\nEntering state 24\nReducing stack by rule 3 (line 134):\n   $1 = nterm conf ()\n   $2 = nterm stmt ()\n-> $$ = nterm conf ()\nStack now 0\nEntering state 1\nNext token is token PRIFILT ()\nShifting token PRIFILT ()\nEntering state 16\nReading a token: Next token is token LEGACY_ACTION ()\nShifting token LEGACY_ACTION ()\nEntering state 14\nReducing stack by rule 40 (line 189):\n   $1 = token LEGACY_ACTION ()\n-> $$ = nterm s_act ()\nStack now 0 1 16\nEntering state 26\nReducing stack by rule 37 (line 185):\n   $1 = nterm s_act ()\n-> $$ = nterm actlst ()\nStack now 0 1 16\nEntering state 25\nReading a token: Next token is token PRIFILT ()\nReducing stack by rule 24 (line 164):\n   $1 = nterm actlst ()\n-> $$ = nterm stmt ()\nStack now 0 1 16\nEntering state 47\nReducing stack by rule 35 (line 183):\n   $1 = nterm stmt ()\n-> $$ = nterm block ()\nStack now 0 1 16\nEntering state 48\nReducing stack by rule 31 (line 179):\n   $1 = token PRIFILT ()\n   $2 = nterm block ()\n-> $$ = nterm stmt ()\nStack now 0 1\nEntering state 24\nReducing stack by rule 3 (line 134):\n   $1 = nterm conf ()\n   $2 = nterm stmt ()\n-> $$ = nterm conf ()\nStack now 0\nEntering state 1\nNext token is token PRIFILT ()\nShifting token PRIFILT ()\nEntering state 16\nReading a token: Next token is token LEGACY_ACTION ()\nShifting token LEGACY_ACTION ()\nEntering state 14\nReducing stack by rule 40 (line 189):\n   $1 = token LEGACY_ACTION ()\n-> $$ = nterm s_act ()\nStack now 0 1 16\nEntering state 26\nReducing stack by rule 37 (line 185):\n   $1 = nterm s_act ()\n-> $$ = nterm actlst ()\nStack now 0 1 16\nEntering state 25\nReading a token: Next token is token PRIFILT ()\nReducing stack by rule 24 (line 164):\n   $1 = nterm actlst ()\n-> $$ = nterm stmt ()\nStack now 0 1 16\nEntering state 47\nReducing stack by rule 35 (line 183):\n   $1 = nterm stmt ()\n-> $$ = nterm block ()\nStack now 0 1 16\nEntering state 48\nReducing stack by rule 31 (line 179):\n   $1 = token PRIFILT ()\n   $2 = nterm block ()\n-> $$ = nterm stmt ()\nStack now 0 1\nEntering state 24\nReducing stack by rule 3 (line 134):\n   $1 = nterm conf ()\n   $2 = nterm stmt ()\n-> $$ = nterm conf ()\nStack now 0\nEntering state 1\nNext token is token PRIFILT ()\nShifting token PRIFILT ()\nEntering state 16\nReading a token: Next token is token LEGACY_ACTION ()\nShifting token LEGACY_ACTION ()\nEntering state 14\nReducing stack by rule 40 (line 189):\n   $1 = token LEGACY_ACTION ()\n-> $$ = nterm s_act ()\nStack now 0 1 16\nEntering state 26\nReducing stack by rule 37 (line 185):\n   $1 = nterm s_act ()\n-> $$ = nterm actlst ()\nStack now 0 1 16\nEntering state 25\nReading a token: Now at end of input.\nReducing stack by rule 24 (line 164):\n   $1 = nterm actlst ()\n-> $$ = nterm stmt ()\nStack now 0 1 16\nEntering state 47\nReducing stack by rule 35 (line 183):\n   $1 = nterm stmt ()\n-> $$ = nterm block ()\nStack now 0 1 16\nEntering state 48\nReducing stack by rule 31 (line 179):\n   $1 = token PRIFILT ()\n   $2 = nterm block ()\n-> $$ = nterm stmt ()\nStack now 0 1\nEntering state 24\nReducing stack by rule 3 (line 134):\n   $1 = nterm conf ()\n   $2 = nterm stmt ()\n-> $$ = nterm conf ()\nStack now 0\nEntering state 1\nNow at end of input.\nShifting token $end ()\nEntering state 2\nStack now 0 1 2\nCleanup: popping token $end ()\nCleanup: popping nterm conf ()\nrsyslogd: pidfile '/run/rsyslogd.pid' and pid 3320 already exist.\nIf you want to run multiple instances of rsyslog, you need to specify\ndifferent pid files for them (-i option).\nrsyslogd: run failed with error -3000 (see rsyslog.h or try http://www.rsyslog.com/e/3000 to learn what that number means)\n exit status 1" 
time="2018-09-02T18:33:03-05:00" level=error msg="[rsyslog] Collector configuration file is not valid, waiting for the next update. Starting parse\nEntering state 0\nReducing stack by rule 1 (line 132):\n-> $$ = nterm conf ()\nStack now 0\nEntering state 1\nReading a token: Next token is token BEGINOBJ ()\nShifting token BEGINOBJ ()\nEntering state 3\nReading a token: Next token is token NAME ()\nReducing stack by rule 17 (line 157):\n-> $$ = nterm nvlst ()\nStack now 0 1 3\nEntering state 27\nNext token is token NAME ()\nShifting token NAME ()\nEntering state 55\nReading a token: Next token is token '=' ()\nShifting token '=' ()\nEntering state 97\nReading a token: Next token is token STRING ()\nShifting token STRING ()\nEntering state 132\nReducing stack by rule 20 (line 160):\n   $1 = token STRING ()\n-> $$ = nterm value ()\nStack now 0 1 3 27 55 97\nEntering state 133\nReducing stack by rule 19 (line 159):\n   $1 = token NAME ()\n   $2 = token '=' ()\n   $3 = nterm value ()\n-> $$ = nterm nv ()\nStack now 0 1 3 27\nEntering state 57\nReducing stack by rule 18 (line 158):\n   $1 = nterm nvlst ()\n   $2 = nterm nv ()\n-> $$ = nterm nvlst ()\nStack now 0 1 3\nEntering state 27\nReading a token: Next token is token ENDOBJ ()\nShifting token ENDOBJ ()\nEntering state 56\nReducing stack by rule 7 (line 138):\n   $1 = token BEGINOBJ ()\n   $2 = nterm nvlst ()\n   $3 = token ENDOBJ ()\n-> $$ = nterm obj ()\nStack now 0 1\nEntering state 23\nReducing stack by rule 2 (line 133):\n   $1 = nterm conf ()\n   $2 = nterm obj ()\n-> $$ = nterm conf ()\nStack now 0\nEntering state 1\nReading a token: Next token is token BEGINOBJ ()\nShifting token BEGINOBJ ()\nEntering state 3\nReading a token: Next token is token NAME ()\nReducing stack by rule 17 (line 157):\n-> $$ = nterm nvlst ()\nStack now 0 1 3\nEntering state 27\nNext token is token NAME ()\nShifting token NAME ()\nEntering state 55\nReading a token: Next token is token '=' ()\nShifting token '=' ()\nEntering state 97\nReading a token: Next token is token STRING ()\nShifting token STRING ()\nEntering state 132\nReducing stack by rule 20 (line 160):\n   $1 = token STRING ()\n-> $$ = nterm value ()\nStack now 0 1 3 27 55 97\nEntering state 133\nReducing stack by rule 19 (line 159):\n   $1 = token NAME ()\n   $2 = token '=' ()\n   $3 = nterm value ()\n-> $$ = nterm nv ()\nStack now 0 1 3 27\nEntering state 57\nReducing stack by rule 18 (line 158):\n   $1 = nterm nvlst ()\n   $2 = nterm nv ()\n-> $$ = nterm nvlst ()\nStack now 0 1 3\nEntering state 27\nReading a token: Next token is token NAME ()\nShifting token NAME ()\nEntering state 55\nReading a token: Next token is token '=' ()\nShifting token '=' ()\nEntering state 97\nReading a token: Next token is token STRING ()\nShifting token STRING ()\nEntering state 132\nReducing stack by rule 20 (line 160):\n   $1 = token STRING ()\n-> $$ = nterm value ()\nStack now 0 1 3 27 55 97\nEntering state 133\nReducing stack by rule 19 (line 159):\n   $1 = token NAME ()\n   $2 = token '=' ()\n   $3 = nterm value ()\n-> $$ = nterm nv ()\nStack now 0 1 3 27\nEntering state 57\nReducing stack by rule 18 (line 158):\n   $1 = nterm nvlst ()\n   $2 = nterm nv ()\n-> $$ = nterm nvlst ()\nStack now 0 1 3\nEntering state 27\nReading a token: Next token is token ENDOBJ ()\nShifting token ENDOBJ ()\nEntering state 56\nReducing stack by rule 7 (line 138):\n   $1 = token BEGINOBJ ()\n   $2 = nterm nvlst ()\n   $3 = token ENDOBJ ()\n-> $$ = nterm obj ()\nStack now 0 1\nEntering state 23\nReducing stack by rule 2 (line 133):\n   $1 = nterm conf ()\n   $2 = nterm obj ()\n-> $$ = nterm conf ()\nStack now 0\nEntering state 1\nReading a token: Next token is token PROPFILT ()\nShifting token PROPFILT ()\nEntering state 17\nReading a token: Next token is token LEGACY_ACTION ()\nShifting token LEGACY_ACTION ()\nEntering state 14\nReducing stack by rule 40 (line 189):\n   $1 = token LEGACY_ACTION ()\n-> $$ = nterm s_act ()\nStack now 0 1 17\nEntering state 26\nReducing stack by rule 37 (line 185):\n   $1 = nterm s_act ()\n-> $$ = nterm actlst ()\nStack now 0 1 17\nEntering state 25\nReading a token: Next token is token PRIFILT ()\nReducing stack by rule 24 (line 164):\n   $1 = nterm actlst ()\n-> $$ = nterm stmt ()\nStack now 0 1 17\nEntering state 47\nReducing stack by rule 35 (line 183):\n   $1 = nterm stmt ()\n-> $$ = nterm block ()\nStack now 0 1 17\nEntering state 49\nReducing stack by rule 32 (line 180):\n   $1 = token PROPFILT ()\n   $2 = nterm block ()\n-> $$ = nterm stmt ()\nStack now 0 1\nEntering state 24\nReducing stack by rule 3 (line 134):\n   $1 = nterm conf ()\n   $2 = nterm stmt ()\n-> $$ = nterm conf ()\nStack now 0\nEntering state 1\nNext token is token PRIFILT ()\nShifting token PRIFILT ()\nEntering state 16\nReading a token: Next token is token LEGACY_ACTION ()\nShifting token LEGACY_ACTION ()\nEntering state 14\nReducing stack by rule 40 (line 189):\n   $1 = token LEGACY_ACTION ()\n-> $$ = nterm s_act ()\nStack now 0 1 16\nEntering state 26\nReducing stack by rule 37 (line 185):\n   $1 = nterm s_act ()\n-> $$ = nterm actlst ()\nStack now 0 1 16\nEntering state 25\nReading a token: Next token is token PRIFILT ()\nReducing stack by rule 24 (line 164):\n   $1 = nterm actlst ()\n-> $$ = nterm stmt ()\nStack now 0 1 16\nEntering state 47\nReducing stack by rule 35 (line 183):\n   $1 = nterm stmt ()\n-> $$ = nterm block ()\nStack now 0 1 16\nEntering state 48\nReducing stack by rule 31 (line 179):\n   $1 = token PRIFILT ()\n   $2 = nterm block ()\n-> $$ = nterm stmt ()\nStack now 0 1\nEntering state 24\nReducing stack by rule 3 (line 134):\n   $1 = nterm conf ()\n   $2 = nterm stmt ()\n-> $$ = nterm conf ()\nStack now 0\nEntering state 1\nNext token is token PRIFILT ()\nShifting token PRIFILT ()\nEntering state 16\nReading a token: Next token is token LEGACY_ACTION ()\nShifting token LEGACY_ACTION ()\nEntering state 14\nReducing stack by rule 40 (line 189):\n   $1 = token LEGACY_ACTION ()\n-> $$ = nterm s_act ()\nStack now 0 1 16\nEntering state 26\nReducing stack by rule 37 (line 185):\n   $1 = nterm s_act ()\n-> $$ = nterm actlst ()\nStack now 0 1 16\nEntering state 25\nReading a token: Next token is token PRIFILT ()\nReducing stack by rule 24 (line 164):\n   $1 = nterm actlst ()\n-> $$ = nterm stmt ()\nStack now 0 1 16\nEntering state 47\nReducing stack by rule 35 (line 183):\n   $1 = nterm stmt ()\n-> $$ = nterm block ()\nStack now 0 1 16\nEntering state 48\nReducing stack by rule 31 (line 179):\n   $1 = token PRIFILT ()\n   $2 = nterm block ()\n-> $$ = nterm stmt ()\nStack now 0 1\nEntering state 24\nReducing stack by rule 3 (line 134):\n   $1 = nterm conf ()\n   $2 = nterm stmt ()\n-> $$ = nterm conf ()\nStack now 0\nEntering state 1\nNext token is token PRIFILT ()\nShifting token PRIFILT ()\nEntering state 16\nReading a token: Next token is token LEGACY_ACTION ()\nShifting token LEGACY_ACTION ()\nEntering state 14\nReducing stack by rule 40 (line 189):\n   $1 = token LEGACY_ACTION ()\n-> $$ = nterm s_act ()\nStack now 0 1 16\nEntering state 26\nReducing stack by rule 37 (line 185):\n   $1 = nterm s_act ()\n-> $$ = nterm actlst ()\nStack now 0 1 16\nEntering state 25\nReading a token: Next token is token PRIFILT ()\nReducing stack by rule 24 (line 164):\n   $1 = nterm actlst ()\n-> $$ = nterm stmt ()\nStack now 0 1 16\nEntering state 47\nReducing stack by rule 35 (line 183):\n   $1 = nterm stmt ()\n-> $$ = nterm block ()\nStack now 0 1 16\nEntering state 48\nReducing stack by rule 31 (line 179):\n   $1 = token PRIFILT ()\n   $2 = nterm block ()\n-> $$ = nterm stmt ()\nStack now 0 1\nEntering state 24\nReducing stack by rule 3 (line 134):\n   $1 = nterm conf ()\n   $2 = nterm stmt ()\n-> $$ = nterm conf ()\nStack now 0\nEntering state 1\nNext token is token PRIFILT ()\nShifting token PRIFILT ()\nEntering state 16\nReading a token: Next token is token LEGACY_ACTION ()\nShifting token LEGACY_ACTION ()\nEntering state 14\nReducing stack by rule 40 (line 189):\n   $1 = token LEGACY_ACTION ()\n-> $$ = nterm s_act ()\nStack now 0 1 16\nEntering state 26\nReducing stack by rule 37 (line 185):\n   $1 = nterm s_act ()\n-> $$ = nterm actlst ()\nStack now 0 1 16\nEntering state 25\nReading a token: Next token is token PRIFILT ()\nReducing stack by rule 24 (line 164):\n   $1 = nterm actlst ()\n-> $$ = nterm stmt ()\nStack now 0 1 16\nEntering state 47\nReducing stack by rule 35 (line 183):\n   $1 = nterm stmt ()\n-> $$ = nterm block ()\nStack now 0 1 16\nEntering state 48\nReducing stack by rule 31 (line 179):\n   $1 = token PRIFILT ()\n   $2 = nterm block ()\n-> $$ = nterm stmt ()\nStack now 0 1\nEntering state 24\nReducing stack by rule 3 (line 134):\n   $1 = nterm conf ()\n   $2 = nterm stmt ()\n-> $$ = nterm conf ()\nStack now 0\nEntering state 1\nNext token is token PRIFILT ()\nShifting token PRIFILT ()\nEntering state 16\nReading a token: Next token is token LEGACY_ACTION ()\nShifting token LEGACY_ACTION ()\nEntering state 14\nReducing stack by rule 40 (line 189):\n   $1 = token LEGACY_ACTION ()\n-> $$ = nterm s_act ()\nStack now 0 1 16\nEntering state 26\nReducing stack by rule 37 (line 185):\n   $1 = nterm s_act ()\n-> $$ = nterm actlst ()\nStack now 0 1 16\nEntering state 25\nReading a token: Next token is token PRIFILT ()\nReducing stack by rule 24 (line 164):\n   $1 = nterm actlst ()\n-> $$ = nterm stmt ()\nStack now 0 1 16\nEntering state 47\nReducing stack by rule 35 (line 183):\n   $1 = nterm stmt ()\n-> $$ = nterm block ()\nStack now 0 1 16\nEntering state 48\nReducing stack by rule 31 (line 179):\n   $1 = token PRIFILT ()\n   $2 = nterm block ()\n-> $$ = nterm stmt ()\nStack now 0 1\nEntering state 24\nReducing stack by rule 3 (line 134):\n   $1 = nterm conf ()\n   $2 = nterm stmt ()\n-> $$ = nterm conf ()\nStack now 0\nEntering state 1\nNext token is token PRIFILT ()\nShifting token PRIFILT ()\nEntering state 16\nReading a token: Next token is token LEGACY_ACTION ()\nShifting token LEGACY_ACTION ()\nEntering state 14\nReducing stack by rule 40 (line 189):\n   $1 = token LEGACY_ACTION ()\n-> $$ = nterm s_act ()\nStack now 0 1 16\nEntering state 26\nReducing stack by rule 37 (line 185):\n   $1 = nterm s_act ()\n-> $$ = nterm actlst ()\nStack now 0 1 16\nEntering state 25\nReading a token: Next token is token PRIFILT ()\nReducing stack by rule 24 (line 164):\n   $1 = nterm actlst ()\n-> $$ = nterm stmt ()\nStack now 0 1 16\nEntering state 47\nReducing stack by rule 35 (line 183):\n   $1 = nterm stmt ()\n-> $$ = nterm block ()\nStack now 0 1 16\nEntering state 48\nReducing stack by rule 31 (line 179):\n   $1 = token PRIFILT ()\n   $2 = nterm block ()\n-> $$ = nterm stmt ()\nStack now 0 1\nEntering state 24\nReducing stack by rule 3 (line 134):\n   $1 = nterm conf ()\n   $2 = nterm stmt ()\n-> $$ = nterm conf ()\nStack now 0\nEntering state 1\nNext token is token PRIFILT ()\nShifting token PRIFILT ()\nEntering state 16\nReading a token: Next token is token LEGACY_ACTION ()\nShifting token LEGACY_ACTION ()\nEntering state 14\nReducing stack by rule 40 (line 189):\n   $1 = token LEGACY_ACTION ()\n-> $$ = nterm s_act ()\nStack now 0 1 16\nEntering state 26\nReducing stack by rule 37 (line 185):\n   $1 = nterm s_act ()\n-> $$ = nterm actlst ()\nStack now 0 1 16\nEntering state 25\nReading a token: Now at end of input.\nReducing stack by rule 24 (line 164):\n   $1 = nterm actlst ()\n-> $$ = nterm stmt ()\nStack now 0 1 16\nEntering state 47\nReducing stack by rule 35 (line 183):\n   $1 = nterm stmt ()\n-> $$ = nterm block ()\nStack now 0 1 16\nEntering state 48\nReducing stack by rule 31 (line 179):\n   $1 = token PRIFILT ()\n   $2 = nterm block ()\n-> $$ = nterm stmt ()\nStack now 0 1\nEntering state 24\nReducing stack by rule 3 (line 134):\n   $1 = nterm conf ()\n   $2 = nterm stmt ()\n-> $$ = nterm conf ()\nStack now 0\nEntering state 1\nNow at end of input.\nShifting token $end ()\nEntering state 2\nStack now 0 1 2\nCleanup: popping token $end ()\nCleanup: popping nterm conf ()\nrsyslogd: pidfile '/run/rsyslogd.pid' and pid 3320 already exist.\nIf you want to run multiple instances of rsyslog, you need to specify\ndifferent pid files for them (-i option).\nrsyslogd: run failed with error -3000 (see rsyslog.h or try http://www.rsyslog.com/e/3000 to learn what that number means)\n" 

----

time="2018-09-02T18:33:23-05:00" level=info msg="[rsyslog] Got remote restart command" 
time="2018-09-02T18:33:23-05:00" level=info msg="[rsyslog] Stopping" 
time="2018-09-02T18:33:26-05:00" level=info msg="[rsyslog] Starting (exec driver)" 
```

## Your Environment

* Graylog Version: 3.0.0-alpha.2-SNAPSHOT+73c96fa
* Sidecar Version: 1.0.0-alpha.6 (c544c7c) [go1.10.3/amd64]

**Comment by mpfz0r** [comment] 2018-10-12 13:16
Hmm, I cannot reproduce this.

@lennartkoopmann How did you configure the rsyslogd collector?
We need to start it with  `-n` otherwise it will daemonize itself and we loose track.

**Comment by bernd** [comment] 2019-01-07 11:09
Closing this. Please re-open if this is still a problem. Thank you!

**Closed by bernd** 2019-01-07 11:09 UTC
Labels: bug, needs-input, sidecar, triaged
