### ISSUE TITLE
Error starting input: Cannot assign requested address. 

### ISSUE THREAD

**Issue by midi-abdel** [Graylog2/graylog2-server#1078] opened 2015-03-25 20:10 UTC
Hi,

I keep getting "Error starting input: Cannot assign requested address. " every time i try to add an input, the only time when I don't get the message when the IP is local (Localhost or Graylog IP).

    recv_buffer_size: 1048576
    port: 10514
    tls_key_file:
    tls_key_password: *******
    max_message_size: 2097152
    override_source:
    allow_override_date: true
    bind_address: 192.168.1.1
    tls_cert_file:

I can ping the client, iptables disabled.
Could anyone help me figure out how can I fix this error.
Thanks

**Comment by edmundoa** [comment] 2015-03-26 09:50
Hi,

You can only bind to an IP address that belongs to the machine were Graylog (or any other program) is running. Please check that the IP you are trying to use is assigned to one of the network interfaces you see when you execute `ifconfig -a`.

It looks like this is a configuration issue and not a bug, so I'm closing the issue now. Please correct me if you think I'm wrong or refer to our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or [IRC channel](https://webchat.freenode.net/?channels=%23graylog2) for further questions.

**Closed by edmundoa** 2015-03-26 09:50 UTC

**Comment by midi-abdel** [comment] 2015-04-08 14:55
Thank you for your answer, it's a config issue and not a bug.
