### ISSUE TITLE
HTTP Streams Output or HTTP GELF Streams Output

### ISSUE THREAD

**Issue by rayterrill** [Graylog2/graylog2-server#4679] opened 2018-03-22 14:44 UTC
## Expected Behavior
It would be super useful to have a HTTP Streams Output or HTTP GELF Streams Output option available in Graylog core, to allow you to POST stream content to a web service for additional routing/alerting processing.

## Current Behavior
The Alert Notifications functionality has the ability to POST messages to a web service over HTTP, which is super useful. There appears to be no such capability with the built-in Streams Output functions, nor with any of the Marketplace items.

## Possible Solution
It would be beneficial to have the same capability at the Streams Output level so we don't necessarily have to fire alerts for messages, and can just output them for processing to another upstream service using HTTP or HTTP GELF.

## Context
We have a need to process and route messages coming into Graylog with complicated logic - things like sending certain messages to one team, others to another team, potentially using different contact mechanisms. That logic doesn't really need to live in Graylog itself, it could live in an upstream web service if Graylog could output the logs matching that stream to that upstream service.

## Your Environment
Graylog 2.4.3+2c41897

**Comment by dennisoelkers** [comment] 2018-03-22 15:03
Thanks for reporting this! This is a duplicate of #2187, closing this in favor of it.

**Closed by dennisoelkers** 2018-03-22 15:03 UTC
Labels: feature

**Comment by rayterrill** [comment] 2018-03-22 15:07
Crap! I swear I looked for duplicates. Sorry @dennisoelkers!
