### ISSUE TITLE
MaxBytesLengthExceededException -- too long field length

### ISSUE THREAD

**Issue by avarabyeu** [Graylog2/graylog2-server#745] opened 2014-10-23 08:07 UTC
IllegalArgumentException[Document contains at least one immense term in field="response_payload" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped. Please correct the analyzer to not produce such terms. The prefix of the first immense term is: '[60, 63, 120, 109, 108, 32, 118, 101, 114, 115, 105, 111, 110, 61, 34, 49, 46, 48, 34, 32, 101, 110, 99, 111, 100, 105, 110, 103, 61, 34]...', original message: bytes can be at most 32766 in length; got 90694]; nested: MaxBytesLengthExceededException[bytes can be at most 32766 in length; got 90694];

Looks like ElasticSearch cannot index such long field value. It will be pretty good to have possibility to configure indexing options via Graylog admin interface. I believe disabling indexing for such fields can prevent issue.

**Comment by joschi** [comment] 2015-01-14 17:09
Duplicate of #873.

**Closed by joschi** 2015-01-14 17:09 UTC
Labels: es-features
