### ISSUE TITLE
GROK not working on GL, working on grokdebugger

### ISSUE THREAD

**Issue by rafaelvittoruthes** [Graylog2/graylog2-server#1065] opened 2015-03-18 21:13 UTC
The follow patterns and input works fine in the grok debugger, but on the extractor (while trying to apply) it doesn't.
INPUT:
```
<14>0 2015-03-18T17:35:28-03:00 hostname.myhost.com 1,2015 - - - 17:35:27,007701000868,TRAFFIC,drop,1,2015/03/18 17:35:27,176.9.12.211,1.1.1.1,0.0.0.0,0.0.0.0,Deny_Web_Differ,,,not-applicable,vsys1,UNSTRUST,TRUST,ethernet1/13,,Syslog-Default,2015/03/18 17:35:27,0,1,49205,25,0,0,0x0,tcp,deny,74,74,0,1,2015/03/18 17:35:18,0,any,0,364500870,0x0,DE,BR,0,1,0,policy-deny
```
```
PA_EVENTLOG ^<%{POSINT:pa_syslog_pri}>%{INT:pa_syslogversion} %{TIMESTAMP_ISO8601:pa_timestamp} %{SYSLOGHOST:pa_source} %{PA_LOGMSG:pa_logmsg}
PA_LOGMSG %{INT:pa_domain},.*,%{INT:pa_serial},%{STRING:pa_type},%{STRING:pa_threatcontenttype},%{INT:pa_configversion},%{PA_TIME:pa_generatetime},%{IP:pa_sourceip},%{IP:pa_destinationip},%{IP:pa_natsourceip},%{IP:pa_natdestinationip},%{STRING:pa_rule},%{STRING:pa_sourceuser},%{STRING:pa_destinationuser},%{STRING:pa_application},%{STRING:pa_virtualsystem},%{STRING:pa_sourcezone},%{STRING:pa_destinationzone},%{STRING:pa_inboundinterface},%{STRING:pa_outboundinterface},%{STRING:pa_logaction},%{PA_TIME:pa_timelogged},%{INT:pa_sessionid},%{INT:pa_repeatcount},%{INT:pa_sourceport},%{INT:pa_destinationport},%{INT:pa_natsourceport},%{INT:pa_natdestinationport},%{STRING:pa_flags},%{STRING:pa_protocol},%{STRING:pa_action},%{INT:pa_bytes},%{INT:pa_bytessent},%{INT:pa_bytesreceived},%{INT:pa_packets},%{PA_TIME:pa_starttime},%{INT:pa_elapsedtime},%{STRING:pa_category},%{INT:pa_padding},%{INT:pa_seqno},%{STRING:pa_actionflags},%{STRING:pa_sourcecountry},%{STRING:pa_destinationcountry},%{INT:pa_cpadding},%{INT:pa_pktssent},%{INT:pa_pktsreceived},%{STRING:pa_other}
PA_TIME %{YEAR}/%{MONTHNUM}/%{MONTHDAY} %{TIME}
STRING [/\\-_.a-zA-Z0-9]+|\w?|.*
```

**Comment by kroepke** [comment] 2015-03-23 07:02
Did you import the general patterns first? Graylog by default does not ship with any patterns, because most people maintain a full set of their own patterns.

Is there any error message in the server log?

**Comment by rafaelvittoruthes** [comment] 2015-03-23 12:03
Hello Kay
Sure, I did import all default patterns.
I did not check for those messages, but will do.
It seems to be some misinterpretation of some characters.
For example: a numbered field identified as INT is not recognized on gl.
Changing to some string, it goes on.
On the debugger, this doesn't happen.
I'll get that error message and drop to you.

Enviado do meu iPad

**Comment by rafaelvittoruthes** [comment] 2015-03-24 20:47
Hello Kay,
Today I was able to run some tests. Some weird things happened:
1) Once, and only once, the test (TRY button) ran successfully. The
following tests, using the same values, went wrong.
2) I observed that, even putting any regex to match on grok, the input
stops processing messages. I have an average of 1.500 msgs/sec. After
applying that grok pattern, it drops to 1 or 2/msgs/sec. Its a TCP SYSLOG
INPUT. Messages received are in graylog format, as tutorial suggests.
3) no message is generated on the default log file, while trying the match
or when processing messages. what i noticed is that messages are received,
but not processed on grok, because the journal increases. After removing
the extractor and restarting the input, there's a burst of messages in
queue, like 10k or 20k, depending on how much time I left it 'stuck'.

is there anyway to enable a debug for those steps? creating the extractor
and grok parsing?

thanks,
rafael

**Comment by rafaelvittoruthes** [comment] 2015-03-25 19:57
Got an error message on the webinterface log.


2015-03-25 16:56:10,697 - [ERROR] - from
org.graylog2.restclient.lib.ApiClient in
play-akka.actor.default-dispatcher-22
REST call failed
java.util.concurrent.TimeoutException: No response received after 5000
        at
com.ning.http.client.providers.netty.NettyResponseFuture.get(NettyResponseFuture.java:260)
~[com.ning.async-http-client-1.8.14.jar:na]
        at
org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder.execute(ApiClientImpl.java:433)
~[org.graylog2.graylog2-rest-client-1.0.1.jar:na]
        at lib.extractors.testers.GrokTest.test(GrokTest.java:49)
[graylog-web-interface.graylog-web-interface-1.0.1.jar:1.0.1]
        at
controllers.api.ToolsApiController.grokTest(ToolsApiController.java:120)
[graylog-web-interface.graylog-web-interface-1.0.1.jar:1.0.1]
        at
Routes$$anonfun$routes$1$$anonfun$applyOrElse$159$$anonfun$apply$841.apply(routes_routing.scala:2611)
[graylog-web-interface.graylog-web-interface-1.0.1.jar:na]
        at
Routes$$anonfun$routes$1$$anonfun$applyOrElse$159$$anonfun$apply$841.apply(routes_routing.scala:2611)
[graylog-web-interface.graylog-web-interface-1.0.1.jar:na]
        at
play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264)
[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at
play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255)
[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55)
[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.GlobalSettings$1.call(GlobalSettings.java:67)
[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.mvc.Security$AuthenticatedAction.call(Security.java:44)
[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)
[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)
[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at
scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
[org.scala-lang.scala-library-2.10.4.jar:na]
        at
scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
[org.scala-lang.scala-library-2.10.4.jar:na]
        at
play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)
[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at
play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46)
[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at
play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32)
[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at scala.concurrent.impl.Future$.apply(Future.scala:31)
[org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.Future$.apply(Future.scala:485)
[org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.j.JavaAction$class.apply(JavaAction.scala:82)
[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at
play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252)
[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at
play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at
play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at
play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)
[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at
play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)
[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at scala.Option.map(Option.scala:145)
[org.scala-lang.scala-library-2.10.4.jar:na]
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)
[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)
[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at
play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at
play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at
play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at
play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at
play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at
play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at
scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
[org.scala-lang.scala-library-2.10.4.jar:na]
        at
scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
[org.scala-lang.scala-library-2.10.4.jar:na]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
[com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
        at
akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
[com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
        at
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[org.scala-lang.scala-library-2.10.4.jar:na]
        at
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[org.scala-lang.scala-library-2.10.4.jar:na]
        at
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[org.scala-lang.scala-library-2.10.4.jar:na]
        at
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[org.scala-lang.scala-library-2.10.4.jar:na]

**Comment by kroepke** [comment] 2015-03-26 08:49
That is a timeout error, it indicates that your graylog server is overwhelmed. That can have many reasons, but trying a grok pattern is not one of them.

We'll look at the pattern bug later, at least I do not have enough time right now, unfortunately.

**Comment by jfschneider** [comment] 2015-04-01 06:37
I too have problems with graylog 1.0.1 grok parser so i thought i add my findings to this thread.
Same thing: patterns work in grokdebug but not in GL. Example:
```
myhostname sudo: icinga : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/service tomcat status
```
Pattern that works (i imported patterns from grokdebug):
```
%{WORD} sudo: %{GREEDYDATA}
```

Pattern that doesn't work and produces a very generic warning after hitting "Try!":
```
%{WORD} sudo: icinga%{GREEDYDATA}
```
that is, any character i insert after `sudo: ` creates the warning, the 'i' of 'icinga' is enough. 
Definitions:
```
    WORD	\b\w+\b
    GREEDYDATA .*
```
Things I tried: quoting the `:`, trying to capture the word 'icinga' with a `%{WORD}`, inserting a direct regex. Nothing helps. No error messages in the server log.
I have tried this with several different messages and different patterns, when I build up the pattern, there's always a point where GL starts producing the warning, sometimes just when I add another letter of the original message. For testing purposes I kept the pattern very simple, more complex patterns i build in grokdebug never worked at all.

All patterns work flawlessley in grokdebug. Server is a test server with not much to do.
```
$ rpm -qa|egrep "elastic|mongo|gray"
graylog-server-1.0.1-1.noarch
graylog-1.0-repository-el6-1.2.0-1.noarch
elasticsearch-1.4.4-1.noarch
mongodb-server-2.4.6-1.el6.x86_64
graylog-web-1.0.1-1.noarch
```

**Comment by rafaelvittoruthes** [comment] 2015-04-01 10:28
On a previous reply from the team, it was mentioned the timeout as the cause, possibly due to server occupation.
I then ran one instance, in a 32core with 16g for the jvm and no work at all. Timeout.
I tried to change between Java versions but didn't help.


Enviado do meu iPad

**Comment by edmundoa** [comment] 2015-04-07 10:03
Do you only notice problems when using the "test" button provided in the extractor form? If so, this issue might be related to this one: https://github.com/Graylog2/graylog2-web-interface/issues/1190

To be sure it is not the same issue, it would be really helpful if you could save one of those patterns and see if the extractor is actually working when messages arrive.

**Comment by rafaelvittoruthes** [comment] 2015-04-08 00:12
Hello Edmundo,

This happens when hitting the test button.
But I also tried to save anyway the pattern, and the input stops processing messages. They are all retained in the journal.
After removing the grok from the input, I must restart the graylog to start processing again.
So, the input (tcp syslog, btw) accepts the messages, doesn't evaluate nor forwards to any stream, an freezes.

I tried to move from 1.0.0 to 1.0.1 but stayed the same.

Enviado do meu iPad

**Comment by kroepke** [comment] 2015-06-01 10:21
The problem with your pattern is that the STRING subpattern is greedy and thus forces excessive backtracking.

The grok debugger takes 8 seconds for me to process the input line you pasted, so there's no way this pattern can process more than a couple of messages per second even in Java (grok debugger is probably using JRuby) and even with many CPUs.

The code actually works fine, when I added a couple of ```?``` to the patterns, and cleaned up the STRING pattern (it simple matches everything: ```.*```) then it is many times faster.

I'll close it because it is not a bug, just a very expensive pattern which we cannot do anything about.

**Closed by kroepke** 2015-06-01 10:21 UTC
Labels: bug
