### ISSUE TITLE
World map don't handle longitude/latidude with a minus

### ISSUE THREAD

**Issue by goliwok** [Graylog2/graylog2-server#5419] opened 2018-12-17 22:13 UTC
## Expected Behavior
I create a stream that get latitude and longitude from messages and generate a world map with these messages. It works only when these data doesn't contain a minus.

## Current Behavior

When the longitude/latitude contains some minus, the map could’t be generated 
I try to generate the map by message -> world map.
The contains something like this : "54.68410,-25.31700"

## Steps to Reproduce (for bugs)

1. send latitude/longitude (with a minus inside) from your node server.
2. select one message with the data from above.
3. try to create a world map with the message field.

## Your Environment

* Graylog Version: 2.2.3
* Elasticsearch Version: 2.4.4
* MongoDB Version: 3.2.11
* Operating System: Debian 4.9.65
* Browser version: chrome 70.0.3538.110 

![capture d ecran 2018-12-17 a 23 01 39](https://user-images.githubusercontent.com/16302051/50119003-1ab6a380-025a-11e9-8b5b-1f068237eaa0.png)

**Comment by dennisoelkers** [comment] 2018-12-18 08:51
There are two problems here:

  1.) Your geodata is in your `message` field. This is not a good practice and will not work with Graylog. You need to store your geodata in a separate field in your documents.
  2.) It looks like you try to create a world map for your `source` field (guessing from the fact that in your screen shot the dropdown for the `source` field is expanded). You will need to create a world map from the dropdown of the field you stored your geodata in.

As it seems like this is not a bug in Graylog, I am closing this issue. If you have additional information and/or I misunderstood the issue, feel free to reopen it.

**Comment by jalogisch** [comment] 2018-12-18 09:01
actually, I can verify this issue on my current GL 2.5 and ES6.5.3 installation.

![grafik](https://user-images.githubusercontent.com/404238/50143040-d522c680-02ab-11e9-8530-a2d2bd8afaff.png)

The mapping of this field is the following:

```
  "dst_addr_geolocation": {
            "type": "geo_point"
          },
```

**Comment by jalogisch** [comment] 2018-12-18 09:17
after changing the mapping of the geolocation field to `keyword` it is possible to view the world map again.

**Closed by jalogisch** 2018-12-18 09:17 UTC
