### ISSUE TITLE
Warning popup about losing changes when saving event definitions

### ISSUE THREAD

**Issue by thll** [Graylog2/graylog2-server#18481] opened 2024-03-05 09:04 UTC
## Expected Behavior

Saving an event definition should not warn about losing changes on that page.

## Current Behavior

When I try to save a newly created event definition, I get a popup saying

```
Do you really want to abandon this page and lose your changes?
This action cannot be undone.
```

If I click `cancel`, the event definition is saved nonetheless. If I try to save it again, the popup doesn't appear again and I end up having created the event definition twice.

## Steps to Reproduce (for bugs)

https://github.com/Graylog2/graylog2-server/assets/886541/f65fec73-053a-4233-8bec-ded0e2e74a0f

## Your Environment

* Graylog Version: 6.0.0-SNAPSHOT
* Java Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by simonychuang** [comment] 2024-09-27 19:58
Looks like this was fixed with https://github.com/Graylog2/graylog2-server/issues/18771. I am not able to reproduce the issue anymore.

**Closed by simonychuang** 2024-09-27 19:58 UTC
Labels: bug, triaged, frontend
