### ISSUE TITLE
Double Field Names in Document View

### ISSUE THREAD

**Issue by xtruthx** [Graylog2/graylog2-server#8500] opened 2020-07-07 14:46 UTC
## Expected Behavior
If you open a document by click on his document id the view should show all field names one time.
## Current Behavior
The field names are displayed twice as you can see on the attached screenshot
## Steps to Reproduce (for bugs)

1. Open a document on its document id within a stream

## Your Environment

* Graylog Version: 3.3
![fieldname_bug](https://user-images.githubusercontent.com/2736347/86798689-5c43b500-c071-11ea-95a9-91af786d801d.png)

**Comment by linuspahl** [comment] 2020-07-07 15:07
Hello @xtruthx,

thanks for reporting this bug! We will provide a fix with the next patch release.
I am closing this issue, because we will take care of the problem with https://github.com/Graylog2/graylog2-server/issues/8483

Duplicate of https://github.com/Graylog2/graylog2-server/issues/8483

**Closed by linuspahl** 2020-07-07 15:07 UTC
Labels: bug

**Comment by xtruthx** [comment] 2020-07-07 15:09
Thx @linuspahl  i did not found the issue. Sorry for the noise

**Comment by linuspahl** [comment] 2020-07-07 15:13
@xtruthx No worries, it is very helpful to know that the problem can also occur in this case.
