### ISSUE TITLE
Unexpected exception. java.nio.channels.ClosedSelectorException

### ISSUE THREAD

**Issue by HSVK** [Graylog2/graylog2-server#2018] opened 2016-04-04 12:33 UTC
### Problem description

Seeing the "Unexpected exception" messages in graylog log, whenever this happens graylog slows down and the query time goes beyond 20 secs. 

2016-04-03T20:05:10.321-06:00 INFO  [AbstractValidatingSessionManager] Validating all active sessions...
2016-04-03T20:05:10.325-06:00 INFO  [AbstractValidatingSessionManager] Finished session validation.  No sessions were stopped.
2016-04-03T20:14:32.354-06:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
2016-04-03T21:05:10.321-06:00 INFO  [AbstractValidatingSessionManager] Validating all active sessions...
2016-04-03T21:05:10.325-06:00 INFO  [AbstractValidatingSessionManager] Finished session validation.  No sessions were stopped.
2016-04-03T21:27:45.245-06:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
2016-04-03T21:30:34.496-06:00 WARN  [DefaultExceptionMonitor] Unexpected exception.
java.nio.channels.ClosedSelectorException
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:83)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at org.apache.mina.transport.socket.nio.NioProcessor.select(NioProcessor.java:97)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1074)
        at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2016-04-03T22:05:10.321-06:00 INFO  [AbstractValidatingSessionManager] Validating all active sessions...
2016-04-03T22:05:10.325-06:00 INFO  [AbstractValidatingSessionManager] Finished session validation.  No sessions were stopped.
2016-04-03T23:05:10.321-06:00 INFO  [AbstractValidatingSessionManager] Validating all active sessions...
2016-04-03T23:05:10.325-06:00 INFO  [AbstractValidatingSessionManager] Finished session validation.  No sessions were stopped
### Steps to reproduce the problem
1. ... Happened when toggling between the web pages of users and roles. But i do not think that might be a problem.
### Environment
- Graylog Version: 1.3.3
- Elasticsearch Version: 1.7.5
- MongoDB Version: 3.2.3
- Operating System: CentOS release 6.6 (Final) 
- Browser version:

**Comment by kroepke** [comment] 2016-04-04 12:37
The exception is coming out of the LDAP subsystem. It seems that iterating the LDAP groups is very slow, which seems to be the cause of the slowdown.

**Comment by HSVK** [comment] 2016-04-04 12:43
Hi Kroepke, Thanks, how do we control this, when i see this error the graylog takes long time to return the search. 

Just a Note: We are not using the LDAP group to define the roles, we utilize the roles menu from the graylog web.

Thanks, Hema.

**Comment by kroepke** [comment] 2016-04-11 09:41
Can you please also check whether your graylog server is overloaded in general? The warning `Did not find meta info of this node. Re-registering.` usually indicates a server which is too slow.

**Comment by bernd** [comment] 2017-06-23 16:23
Closing this. Please re-open if this is still an issue with Graylog 2.2 or the upcoming 2.3. Thank you!

**Closed by bernd** 2017-06-23 16:23 UTC
Labels: bug, ldap, P3, S2, severe, triaged
