### ISSUE TITLE
Elasticsearch 7.8.1 upgrade

### ISSUE THREAD

**Issue by lingpri** [Graylog2/graylog2-server#8790] opened 2020-08-13 16:39 UTC
delete following mongo collection  `index_failures`, `index_sets`, `index_ranges`, `index_field_types` using the command below 

```
db.index_sets.remove( { } )

db.index_ranges.remove( {} )

db.index_field_types.remove( {} )

db.index_failures.remove({})
```
and when I start graylogserver i get error below,

```

2020-08-13 11:03:46,464 ERROR: org.graylog2.periodical.IndexerClusterCheckerThread - Uncaught exception in periodical
org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException: An error occurred: 
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.exceptionFrom(ElasticsearchClient.java:97) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:72) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:65) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ClusterAdapterES7.indicesExist(ClusterAdapterES7.java:270) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ClusterAdapterES7.clusterHealth(ClusterAdapterES7.java:249) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ClusterAdapterES7.health(ClusterAdapterES7.java:64) ~[classes/:?]
	at org.graylog2.indexer.cluster.Cluster.health(Cluster.java:70) ~[classes/:?]
	at org.graylog2.periodical.IndexerClusterCheckerThread.doRun(IndexerClusterCheckerThread.java:58) ~[classes/:?]
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_265]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_265]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_265]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.IllegalArgumentException: indices are mandatory
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.IndicesRequestConverters.indicesExist(IndicesRequestConverters.java:514) ~[elasticsearch7-7.6.2.jar:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1510) ~[elasticsearch7-7.6.2.jar:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1499) ~[elasticsearch7-7.6.2.jar:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.IndicesClient.exists(IndicesClient.java:827) ~[elasticsearch7-7.6.2.jar:?]
	at org.graylog.storage.elasticsearch7.ClusterAdapterES7.lambda$indicesExist$12(ClusterAdapterES7.java:270) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:70) ~[classes/:?]
	... 14 more
2020-08-13 11:03:46,503 ERROR: org.graylog2.periodical.IndexRetentionThread - Uncaught exception in periodical
org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException: An error occurred: 
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.exceptionFrom(ElasticsearchClient.java:97) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:72) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:65) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ClusterAdapterES7.indicesExist(ClusterAdapterES7.java:270) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ClusterAdapterES7.clusterHealth(ClusterAdapterES7.java:249) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ClusterAdapterES7.health(ClusterAdapterES7.java:64) ~[classes/:?]
	at org.graylog2.indexer.cluster.Cluster.health(Cluster.java:70) ~[classes/:?]
	at org.graylog2.indexer.cluster.Cluster.isHealthy(Cluster.java:125) ~[classes/:?]
	at org.graylog2.periodical.IndexRetentionThread.doRun(IndexRetentionThread.java:65) ~[classes/:?]
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_265]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_265]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_265]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.IllegalArgumentException: indices are mandatory
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.IndicesRequestConverters.indicesExist(IndicesRequestConverters.java:514) ~[elasticsearch7-7.6.2.jar:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1510) ~[elasticsearch7-7.6.2.jar:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1499) ~[elasticsearch7-7.6.2.jar:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.IndicesClient.exists(IndicesClient.java:827) ~[elasticsearch7-7.6.2.jar:?]
	at org.graylog.storage.elasticsearch7.ClusterAdapterES7.lambda$indicesExist$12(ClusterAdapterES7.java:270) ~[classes/:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:70) ~[classes/:?]
	... 15 more

```

## what is the expected Behavior ?
Should we do something about the stack trace or is it safe to ignore the bug.

## How to monitor ?
x@x-Precision-5540:~$ docker system df -v

## Context
I'm trying to test o365 input with elastic search 7.8.1 and am unable to see received messages. I do see messages in the disk journal.

## Your Environment
* Graylog Version: graylog-parent  4.0.0-SNAPSHOT (branch: master)
* Java Version:
* Elasticsearch Version: 7.8.1 
* MongoDB Version: db.version() in mongo shell 4.2.3
* Operating System: Ubuntu 18.04.4 LTS
* Browser version:FireFox

**Comment by dennisoelkers** [comment] 2020-08-17 08:42
@lingpri: did you try this for 6.x? removing needed collections is not a scenario that we would automatically recover from in earlier versions as well, the user would need to trigger an index range recalculation manually.

**Comment by lingpri** [comment] 2020-08-17 14:29
> @lingpri: did you try this for 6.x? removing needed collections is not a scenario that we would automatically recover from in earlier versions as well, the user would need to trigger an index range recalculation manually.

@dennisoelkers - I start `elasticSearch6.x ` in my local using docker-compose.yml  .
 which image should I use for elasticsearch7.8 ? (Below is an example for 6.8.3)
 Is it possible to run both 7.8.x and 6.8 in the same development machine ?
 
I'm speculating , i didn't configure elasticsearch7.8.x right in my machine. Hence ended up in this scenario. if you need any further details, please keep me posted.




`

**Comment by dennisoelkers** [comment] 2020-08-18 11:33
@lingpri: the docker image is unrelated to this. In my opinion the issue is removing crucial collections in the database manually. This is not supposed to be recoverable automatically, neither for Elasticsearch 6.x or 7.x. Therefore I am closing this issue, as it does not look like a bug right now. If you have additional information indicating that it is, please reopen it.

**Closed by dennisoelkers** 2020-08-18 11:33 UTC
Labels: bug
