### ISSUE TITLE
Add filter to Sidecar Administration

### ISSUE THREAD

**Issue by cmiscloni** [Graylog2/graylog2-server#8987] opened 2020-09-17 09:20 UTC
It will be great if the Administration menu in Sidecar could have an option to list Sidecar with **no configuration assigned**.

Thanks.

**Comment by boosty** [comment] 2022-04-12 08:23
Closing as duplicate of https://github.com/Graylog2/graylog2-server/issues/8688

**Closed by boosty** 2022-04-12 08:23 UTC
Labels: feature, triaged, ux
