### ISSUE TITLE
Permission Management: Error in Event-Definition visibility

### ISSUE THREAD

**Issue by ihe-nu** [Graylog2/graylog2-server#15478] opened 2023-05-11 10:58 UTC
## Expected Behavior
A User has the roles 
* Event Definition Creator (Allows creation of Event Definitions (built-in))
* Event Notification Creator (Allows creation of Event Notifications (built-in))

When this user clicks on "Alerts" in the top Menu. Three sub menus should be visable, as there might be shared Event Definitions or Event Notifications.

## Current Behavior
When this user clicks on "Alerts" in the top Menu, only the sub-menu for "Alerts & Events" is visible. The submenu for "Event Definitions" and "Notifications" are not visible. 

## Possible Solution
Make both menu items visible if the rights for  Event Definition Creator and Event Notification Creator are granted.

## Steps to Reproduce (for bugs)

1. create a new user
2. grant the roles  Event Definition Creator and Event Notification Creator
3. click on alerts on the top
4. search the buttons in the sub menu

If the deeplink is accessed by those users, the pages are shown as they should.

## Context
Customer asked for more granular permission management

## Your Environment
Graylog 5.0 and 5.1 RC2 are affected.

**Comment by patrickmann** [comment] 2023-06-23 10:57
This issue is a duplicate of #14940 
Fixed in 5.1 by #15052 
Fixed in 5.0.6 by #15055

**Closed by patrickmann** 2023-06-23 10:57 UTC
Labels: bug, triaged
