### ISSUE TITLE
Setting timestamp field in GELF HTTP Input causes messages to hang in Journal

### ISSUE THREAD

**Issue by hkelley** [Graylog2/graylog2-server#5501] opened 2019-01-14 12:34 UTC
Per [http://docs.graylog.org/en/2.5/pages/gelf.html#gelf-payload-specification](url), the timestamp attribute is part of a valid GELF message.

Currently, when one POSTs a message via the HTTP input using a specified timestamp,  the message is accepted (HTTP 202) but remains in the Journal and is never indexed.

The message should be accepted with a timestamp.

To Reproduce:
1. Define an HTTP Input
2. Post a message including a timestamp value
`curl -X POST -H 'Content-Type: application/json' -d '{ "version": "1.1", "timestamp":1545401488441,"host": "example.org", "short_message": "A short message", "level": 5, "_some_info": "foo" }' 'http://localhost:12201/gelf'`
3. Post the same message without a timestamp value
`curl -X POST -H 'Content-Type: application/json' -d '{ "version": "1.1", "timestamp":1545401488441,"host": "example.org", "short_message": "A short message", "level": 5, "_some_info": "foo" }' 'http://localhost:12201/gelf'`

* Graylog Version:  2.5.1+34194da, codename Trippy Trampoline
* JVM:  Oracle Corporation 1.8.0_191 on Linux 4.4.0-131-generic
* Elasticsearch Version:  6.5.4
* MongoDB Version:  db version v3.6.9
* Operating System:  Ubuntu 16.04.5 LTS

**Comment by kmerz** [comment] 2019-01-14 12:37
I could reproduce that on my development instance.

**Comment by dennisoelkers** [comment] 2019-01-14 15:46
@hkelley, @kmerz: Do you see anything in the server los?

**Comment by dennisoelkers** [comment] 2019-01-14 15:52
@hkelley: The problem is the following: You are specifying the timestamp in millisecond resolution, while Graylog expects a float with second resolution. So the following would work:

```
curl -X POST -H 'Content-Type: application/json' -d '{ "version": "1.1", "timestamp":1545401488.441,"host": "example.org", "short_message": "A short message", "level": 5, "_some_info": "foo" }' 'http://localhost:12201/gelf'
```

Also, I think that the message with the millisecond timestamp does not stay in the journal, but is processed. You just do not find it in the web interface, as its timestamp is in the future.

As this is the intended behavior of Graylog, I am closing this issue. If you have any additional information or think this is unjustified, please reopen the issue.

**Closed by dennisoelkers** 2019-01-14 15:52 UTC
Labels: blocker, bug
