### ISSUE TITLE
Message order inconsistent with equal timestamp

### ISSUE THREAD

**Issue by pschichtel** [Graylog2/graylog2-server#6923] opened 2019-12-04 10:05 UTC
## Expected Behavior
Messages should be consistently ordered based on order of arrival and the order should be consistent when switch between newest-to-oldest and oldest-to-newest ordering. 

## Current Behavior
When messages have the same timestamp, they are in reverse order when viewed in newest-to-oldest ordering, but are ordered correctly when viewed in oldest-to-newest.

## Possible Solution
Consistently apply a second field (maybe "created"?) to improve the ordering

## Steps to Reproduce (for bugs)
1. Ingest a few messages with the exact same timestamp, but temporally spaced apart
2. Change to order in the search view

## Context
This makes it strange to analyse event flows in applications, especially in a distributed setup.

## Your Environment

* Graylog Version: 3.1.3 with PR #6873 merged
* Elasticsearch Version: 6.8.4 (docker image)
* MongoDB Version: 4.0 (docker image)
* Operating System: Fedora 28
* Browser version: Firefox ??

**Comment by mpfz0r** [comment] 2019-12-04 10:08
Thanks for your report. This however is a
Duplicate of #2741

**Closed by mpfz0r** 2019-12-04 10:08 UTC
Labels: bug
