### ISSUE TITLE
Double scroll in Graylog 3.2 streams

### ISSUE THREAD

**Issue by prcdpr** [Graylog2/graylog2-server#8024] opened 2020-05-04 01:36 UTC
## Expected Behavior
When you go to stream there is All messages widget. This widget shouldn't have internal scrolling but instead it should expand to full height.

## Current Behavior
Currently there is internal scroll in All messages widget and the widget takes around half of page height by default which is not enough to conveniently browse logs. And if i expand the height it creates another scrollbar on body element.

## Possible Solution
Remove fixed CSS height from `.react-grid-item` on "All messages" widget

## Steps to Reproduce (for bugs)
Go to any stream

## Context
This is another regression of Graylog 3.2 UX that I encountered and significantly reduces my productivity.

**Comment by dennisoelkers** [comment] 2020-05-07 11:32
Thanks for the feedback, @prcdpr!

This is a duplicate of #7681, therefore I am closing it. If you have additional information, please add it to that issue. If you think it is not identical and you are describing a different issue, please reopen this one with more information.

**Closed by dennisoelkers** 2020-05-07 11:32 UTC
Labels: improvement, search, triaged
