### ISSUE TITLE
Unable to edit/delete saved search

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2184] opened 2016-05-04 11:18 UTC
### Problem description
1. It is impossible to delete saved search, if it doesn't return result. Button just don't appears.
2. If I modify search query and click "Update search criteria" - it says that criteria was updated, but actualy nothing happend. And if I click "search" after query modification, Update button disapears, and there is only button "Save" like for first search. And I can't save new query with old name.

### Environment

* Graylog Version: 2.0 GA

**Comment by joschi** [comment] 2016-05-04 11:49
@hc4 Thank you very much for reporting this! I'll close this issue as a duplicate of Graylog2/graylog2-web-interface#1639.

**Closed by joschi** 2016-05-04 11:49 UTC
