### ISSUE TITLE
Graylog show error when going to search page

### ISSUE THREAD

**Issue by qarmin** [Graylog2/graylog2-server#7495] opened 2020-02-19 07:50 UTC
This error shows me only 2 times, today and half month ago, and always after login to Graylog.

```
t is undefined

Stack Trace:

r9fe9hsd/P<@https://graylog.bth.lan/assets/app.752d67533720db23bce4.js:208:159590
value@https://graylog.bth.lan/assets/app.752d67533720db23bce4.js:82:508406
go@https://graylog.bth.lan/assets/vendor.5452e7a2fdfb6282da0a.js:18:65535
yo@https://graylog.bth.lan/assets/vendor.5452e7a2fdfb6282da0a.js:18:65330
Qs@https://graylog.bth.lan/assets/vendor.5452e7a2fdfb6282da0a.js:18:99620
Is@https://graylog.bth.lan/assets/vendor.5452e7a2fdfb6282da0a.js:18:83908
Rs@https://graylog.bth.lan/assets/vendor.5452e7a2fdfb6282da0a.js:18:80933
Ps@https://graylog.bth.lan/assets/vendor.5452e7a2fdfb6282da0a.js:18:79506
_i/<@https://graylog.bth.lan/assets/vendor.5452e7a2fdfb6282da0a.js:18:41771
29/exports.unstable_runWithPriority@https://graylog.bth.lan/assets/vendor.5452e7a2fdfb6282da0a.js:42:3998
fi@https://graylog.bth.lan/assets/vendor.5452e7a2fdfb6282da0a.js:18:41500
_i@https://graylog.bth.lan/assets/vendor.5452e7a2fdfb6282da0a.js:18:41719
mi@https://graylog.bth.lan/assets/vendor.5452e7a2fdfb6282da0a.js:18:41652
Ds@https://graylog.bth.lan/assets/vendor.5452e7a2fdfb6282da0a.js:18:78497
enqueueSetState@https://graylog.bth.lan/assets/vendor.5452e7a2fdfb6282da0a.js:18:46463
24/b.prototype.setState@https://graylog.bth.lan/assets/vendor.5452e7a2fdfb6282da0a.js:26:1438
vkns48ms/t.default/y</n.prototype.safeSetState@https://graylog.bth.lan/assets/app.752d67533720db23bce4.js:208:633720
n/r.loadingPromise<@https://graylog.bth.lan/assets/app.752d67533720db23bce4.js:208:633160


Component Stack:

    in ConnectStoresWrapper[C] stores=currentQuery,availableStreams,queryFilters
    in Unknown
    in ConnectStoresWrapper[Unknown/Anonymous] stores=searchMetadata,executionState,configurations
    in i
    in a
    in div
    in t
    in t
    in ExtendedSearchPage__SearchGrid
    in div
    in t
    in ExtendedSearchPage__SearchArea
    in div
    in t
    in ExtendedSearchPage__GridContainer
    in Unknown
    in ConnectStoresWrapper[Unknown/Anonymous] stores=view
    in Q
    in withRouter(Q)
    in Unknown
    in n
    in t
    in withRouter(t)
    in Unknown
    in n
    in Unknown
    in n
    in div
    in a
    in div
    in i
    in t
    in withRouter(t)
    in c
    in d
    in ConnectStoresWrapper[d] stores=currentUser
    in t
    in withRouter(t)
    in RouterContext
    in Router
    in m
    in t
    in n
    in t
    in c
    in AppFacade

```

## Possible steps to reproduce (This happens to me only 2 times, so I'm not sure if this is corrent)
1. Login to Graylog
2. Close Firefox
3. Reboot Computer
4. Open Firefox
5. Login to Graylog
6. Go to search page

I think, that something is wrong with Firefox/Graylog cache, but I'm not sure about it.

## Your Environment

* Graylog Version: 3.2.1-1
* Elasticsearch Version: 6.8.6-1
* MongoDB Version: v4.0.16
* Operating System: CentOS 7
* Browser version: Firefox 72.0.2 Windows 10

**Comment by dennisoelkers** [comment] 2020-02-19 08:54
Thanks for reporting this! It is a duplicate of #7365, already fixed for the upcoming release of `3.2.2`.

**Closed by dennisoelkers** 2020-02-19 08:54 UTC
Labels: bug
