### ISSUE TITLE
Geo IP feature shows only one city

### ISSUE THREAD

**Issue by rooty123** [Graylog2/graylog2-server#2060] opened 2016-04-12 11:04 UTC
### Problem description

Perhaps it's not the issue, but it doesn't work well for me.
All I see on map is my own city, maybe it's due to wrong configuration.
### Steps to reproduce the problem
1. I have special field remote_addr, that is populated from nginx log by graylog extractor. This field contains only IP address.
2. I have enabled Geo-location processor with correct path to Maxmind DB
3. I only see strange field gl2_remote_ip_geolocation, while the it should be named remote_addr_geolocation
4. I also see this field in records that do not have IP address field at all.
### Environment
- Graylog Version: 2.0-beta2
- Elasticsearch Version:
- MongoDB Version:
- Operating System:
- Browser version:

**Comment by edmundoa** [comment] 2016-04-12 11:35
Hi,

I think the problem is the sorting of message processors. Would you be so kind as to share with us the message processor list in your System -> Configurations page?

I would try setting the GeoIP resolver as last processor to run, and then see if that solves the issues with the extraction of geo location information.

**Comment by rooty123** [comment] 2016-04-12 12:28
![screenshot from 2016-04-12 15 27 33](https://cloud.githubusercontent.com/assets/371690/14459859/21b69140-00c3-11e6-97b9-ea9854a6765f.png)

**Comment by rooty123** [comment] 2016-04-12 12:30
Oh, I moved geo ip processor lower and it works! Thanks

**Comment by edmundoa** [comment] 2016-04-12 13:49
Good to hear! We need to place the processor last by default, then.

The `gl2_remote_ip` field is an internal field indicating the sender of messages. As it is an IP in your case, Graylog is extracting the location information as well.

**Comment by kroepke** [comment] 2016-05-02 09:43
We need to either change the default order of the processors, or allow a GeoIP lookup function for the rules.

**Comment by edmundoa** [comment] 2016-05-10 09:50
I think changing the default processor order would be the way to go atm. Having a GeoIP lookup function would also be helpful, of course 😄

**Comment by bernd** [comment] 2017-06-23 17:00
This will be fixed with the upcoming Graylog 2.3 which includes a new lookup table feature and a data adapter for the maxmind database.

**Closed by bernd** 2017-06-23 17:00 UTC
Labels: improvement
