### ISSUE TITLE
The item about 'time_zone' does not work

### ISSUE THREAD

**Issue by loveyang2012** [Graylog2/graylog2-server#19043] opened 2024-04-13 13:54 UTC
version: graylog 5.0
api: Search/Messages : Simple search returning (matching) messages only, as CSV.

when I learning the apis of graylog,I have some troubles, I have been set time_zone filed,but it does not work,like this
I want Asia/Shanghai time,but i got USA time,somebody can help me,please?

![ad13f9c88236e1acaf228929245700b](https://github.com/Graylog2/graylog2-server/assets/24237714/1b4dc4c8-40f7-4168-9a69-121a3687df21)

if I want to use the absolute time,how to ? someone can give me a example,please ?

**Comment by kmerz** [comment] 2024-05-03 09:18
@luk-kaminski if you have time could you verify this issue?

**Comment by luk-kaminski** [comment] 2024-05-20 09:37
@kmerz - sure!

@loveyang2012 - I was testing the same API on 6.0 and I was not able to reproduce this error.

![Screenshot 2024-05-20 at 11-34-22 Graylog REST API browser](https://github.com/Graylog2/graylog2-server/assets/100699120/aeda8f9d-80fb-4b5d-9c42-d9414cf30629)

![Screenshot 2024-05-20 at 11-33-48 Graylog REST API browser](https://github.com/Graylog2/graylog2-server/assets/100699120/c7c82ed9-9f9a-4f87-bae0-c8525a4bedc5)

**Comment by luk-kaminski** [comment] 2024-07-23 10:04
@Emy-01 @kmerz 
The reporter has not responded, we have not been able to reproduce, I'd consider closing this one.

**Closed** 2024-07-23 15:43 UTC
Labels: bug, triaged, cannot reproduce, to-verify
