### ISSUE TITLE
Uncaught exception appears to stop further processing.

### ISSUE THREAD

**Issue by aimdev** [Graylog2/graylog2-server#3273] opened 2016-12-31 16:06 UTC
## Expected Behavior

I have the following setup using graylog installed on debian jessie, from the repository
deb https://packages.graylog2.org/repo/debian/ stable 2.1.

The input is udp on port 1514 taking syslog from a modem. 

The input has an key value extractor

The details are 

Configured extractors
Syslog-KV Copy input
Trying to extract data from message into message_copy, leaving the original intact.
DetailsEditDelete
Condition
Will only attempt to run if the message includes the string always->Any(All)IN=pppoa0
Configuration
No configuration options
Converters
tokenizer

## Current Behavior

All is well for a while till the following uncaught exception, then it apears no more 
traffic is read or processed. 

## Steps to Reproduce (for bugs)

1. Suggest this may be dependant on the router syslog output.
2 .
3.
4.

## Context

Stops further processing
## Your Environment

* Graylog Version: graylog-2.1-repository               1-3 
 graylog-server                       2.1.2-1   
* Elasticsearch Version: elasticsearch                        2.4.3                       all  
* MongoDB Version: 1:2.4.10-5                  amd64  
* Operating System: Debian Jessie amd64 updated
* Browser version: Safari 10.0.2

2016-12-31T14:14:10.544Z ERROR [Extractor] Could not apply converter [tokenizer] of extractor [822b3fa0-cf29-11e6-8def-22712d50c340].
java.lang.IllegalArgumentException: Multiple entries with same key: LEN=415 and LEN=435
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:136) ~[graylog.jar:?]
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:98) ~[graylog.jar:?]
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:84) ~[graylog.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:295) ~[graylog.jar:?]
	at org.graylog2.inputs.converters.TokenizerConverter.convert(TokenizerConverter.java:55) ~[graylog.jar:?]
	at org.graylog2.plugin.inputs.Extractor.runConverters(Extractor.java:242) [graylog.jar:?]
	at org.graylog2.plugin.inputs.Extractor.runExtractor(Extractor.java:228) [graylog.jar:?]
	at org.graylog2.filters.ExtractorFilter.filter(ExtractorFilter.java:73) [graylog.jar:?]
	at org.graylog2.messageprocessors.MessageFilterChainProcessor.process(MessageFilterChainProcessor.java:100) [graylog.jar:?]
	at org.graylog2.buffers.processors.ServerProcessBufferProcessor.handleMessage(ServerProcessBufferProcessor.java:56) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.dispatchMessage(ProcessBufferProcessor.java:82) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:61) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:35) [graylog.jar:?]
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by joschi** [comment] 2017-01-02 08:48
Duplicate of #1663.

**Closed by joschi** 2017-01-02 08:48 UTC
