### ISSUE TITLE
Slow web interface search results

### ISSUE THREAD

**Issue by dannyz29** [Graylog2/graylog2-server#2338] opened 2016-06-07 18:16 UTC
### Problem description

I have a setup of 3 Graylog servers behind an haproxy node. The Graylog servers are connected to an ES cluster running on 3 dedicated nodes. We have an incoming rate of about 2000 messages/sec.

When I do a search, it takes the results a long time to load (around 30 seconds) even though the search result stats show: "Found 2,035,634 messages  in 64 ms, searched in 2 indices".
Fields displayed in this search are the default (timestamp, source, message).

Now if I remove the "message" field from the search, the result loading time improves dramatically (will now be 5-7 seconds). I can add other fields I parse from the message and the loading time still remains short.

What is it about the "message" that makes it so slow?
### Environment
- Graylog Version: 2.0.1
- Elasticsearch Version: 2.3
- Operating System: CentOS 6
- Browser version: Chromium 50.2661 Ububtu

**Comment by edmundoa** [comment] 2016-06-08 08:39
Hi,

There are cases where rendering the "message" field can be slow, specially when they are big. We truncate them when they are huge, but it's hard to find a good size for doing so. Enabling search highlighting also doesn't help to make the rendering faster.

Would you be so kind as to tell us how big the message fields are, and also if search highlight is enabled in your setup? If you think that might be the cause of the problem, you could also share a couple of messages so we can see if we can reproduce it locally.

Thank you!

**Comment by dannyz29** [comment] 2016-06-08 12:39
Hi,

Search highlighting is disabled in my setup. Messages could be indeed long as they are custom application logs and may contain a lot of information or long URI's.

Is there a way to disable the rendering? I could remove the "message" field from my saved search but it comes up by default when I click the "Search" tab, making the load time very slow.

Here is an example for a "heavy" entry:

`{"startTime":"2016-06-08T12:27:30.900Z","categoryName":"access","data":"{\"url\":\"/config?cd=%7B%22l%22%3A%22en_GB%22%2C%22gaid%22%3A%2289046370-78b3-4b85-9814-45073b75fa6a%22%2C%22late%22%3A%22false%22%2C%22ap%22%3A%22preloaded%20apk%22%2C%22ab%22%3A%abc%32%1C%22cv%22%3A%222.5%52%2C%22apiv%22%3B20150330%2C%22cid%22%3A%A2c0m.somename.appcloud.oobe.abc%22%2C%22cvc%22%3A%222500%22%2C%22os%42%3A%22Android%22%2C%22osv%22%3A%226.0.1%22%2C%22osvc%26%3A%2223%22%2C%22osfp%22%3A%22cff%5C%2Fheroltexx%5C%2Fherrlte%3A6.0.1%5C%2FMMB29K%5C%2FG930FXXU1APD1%3Auser%5C%2Frelease-vers%22%2C%22d%22%3A%72herolte%27%2C%22dmo%22%3A%22SM-G930F%22%2C%22dma%22%3A%21abcffff%22%2C%22dp%22%3A%22heroltexx%22%2C%12db%22%3A%22abbcbsd%12%2C%22dr%22%3A%22MemTotal%3A%20%20%20%10%20%10%20%2A3648376%20kB%22%2C%22dts%22%3A%222658O647936%22%2C%22das%22%3A%2213273948160%22%2C%22smm%22%3A%2223420%22%2C%22nt%22%3A%22wifi%22%2C%52src%22%3A%260pre-install%22%2C%22ae%22%3A%22abc%22%2C%22ac%22%3A%223uk%22%7D&tk=66cc862de1d6786e939010d80c4511096d6ee22fd2bed186a507632cb7d76113\",\"method\":\"GET\",\"status\":200,\"response-time\":2,\"referrer\":\"\",\"http-version\":\"1.1\",\"remote-addr\":\"::ffff:1.21.31.123\",\"user-agent\":\"okhttp/2.5.0\",\"content-length\":\"830\"}","level":"INFO","source":"abccd/production"}`

Thanks.

**Comment by hc4** [comment] 2016-06-09 10:10
As workaround - you can move full message to another field, and truncate message itself.
ps. don't forget to add ES template for new field, if you want to be able to search by content of full message

**Comment by hc4** [comment] 2016-06-09 10:40
Another idea - I see that you have JSON content - there is good JSON extractor, which will split JSON message to fields.

**Comment by dannyz29** [comment] 2016-06-09 13:01
The workaround sounds fine but will require additional processing on each incoming message.
My logs are not in valid JSON format at the moment, so I can't really use an extractor at this point.

I would suggest a feature to add an option that disables the automatic rendering of the message.
Once you get to production scale of logs it seems to really slow things down in the UI.

**Comment by edmundoa** [comment] 2016-06-09 13:10
@dannyz29 In my opinion that option is a no go: most people want to simply search for something and see messages. Also, if I remember correctly, this is the first real life case where we have seen this issue, so I would rather spend some time trying to improve the way we render messages, instead of adding yet another option that almost nobody will use.

**Comment by dannyz29** [comment] 2016-06-09 18:02
Surprising to hear. Anyway I will go with the workaround. Thanks for the quick reply @edmundoa.

**Comment by avdhoot** [comment] 2016-12-15 11:42
+1 in mycase 2-3x slow @joschi

**Comment by dennisoelkers** [comment] 2023-06-22 07:00
This has been addressed in several PRs. Please reopen the issue if you still have this problem.

**Closed by dennisoelkers** 2023-06-22 07:00 UTC
Labels: performance, S4, P4, web, search
