### ISSUE TITLE
Editing/Deleting things on webinterface not possible

### ISSUE THREAD

**Issue by unamuno** [Graylog2/graylog2-server#1800] opened 2016-02-11 10:39 UTC
Hey,
when I tried to delete/edit dashboards, users or streams this ends in the error:
> Deleting dashboard "test" failed with status:

I can still delete widgets inside of a dashboard.

There are no log entries in the graylog-server, graylog-web application and mongodb log
The only error message I found was generated in the browser console:

> Failed to load resource: net::ERR_EMPTY_RESPONSE

After I deleted a test user from the mongodb directly, its still visible in the web-gui.

**Comment by edmundoa** [comment] 2016-02-11 11:25
Hi,

Which Graylog version are you using?

**Comment by unamuno** [comment] 2016-02-11 12:30
I am using graylog-web-interface v1.3.3 (0fda9dc) as well as graylog-server 1.3.3
The last update in January didn't fixed this issue.

**Comment by danlsgiga** [comment] 2016-03-18 21:32
I'm also facing the same issue. I have 3 graylog-web interfaces and 3 graylog-server nodes.

**Comment by danlsgiga** [comment] 2016-03-18 22:37
Ok, never mind, I figured out. I have an Nginx proxy in front of the graylog-web nodes. I have an explicit configuration not allowing DELETE commands, only POST/GET/HEAD. That's what was causing my issue. After allowing DELETE everything is working fine.
Sorry for the misunderstanding.

**Comment by unamuno** [comment] 2016-03-21 10:21
@danlsgiga same here. Thanks for your help.

@edmundoa:Please close this issue.

**Comment by edmundoa** [comment] 2016-03-21 10:25
Closing as requested, happy to hear the issue is gone!

**Closed by edmundoa** 2016-03-21 10:25 UTC
Labels: bug, P4, S3
