### ISSUE TITLE
Cannot query: Graylog repeating the characters in search box

### ISSUE THREAD

**Issue by ortizleo** [Graylog2/graylog2-server#8332] opened 2020-06-11 19:13 UTC
Hello.

Graylog ´s repeating the caracthers that we input in search box, because of it we cannot query correctly. 
Tested with Firefox, Chrome and Edge, all with cache+history+cookies cleaned.

Graylog 3.3.1
Centos 7

- To reproduce
Try query something in search box.

Attached prints show the problem, when I press a single key graylog insert multiple words in the box...

Virtual Keyboard
![query problem2](https://user-images.githubusercontent.com/17042298/84429697-fe9d8380-abfe-11ea-87b4-3f18809afebd.gif)

Keyboard
![query problem](https://user-images.githubusercontent.com/17042298/84429210-28a27600-abfe-11ea-9088-354dfcd5a589.gif)

**Comment by dennisoelkers** [comment] 2020-06-12 08:26
Hey @ortizleo,

thanks for reporting this. Is this related to your on screen keyboard? I.e., can you check if using a physical keyboard changes the behavior for you?

**Comment by ortizleo** [comment] 2020-06-12 14:41
Hello.

Physical and virtual keyboard....

**Comment by valleyman07** [comment] 2020-06-15 12:01
Hello.

he same has happened to me after updating version from 3.2.5 to 3.3.1 and change has also changed the witges' queries symbols.
It's possible to make a downgrade to the version i had before?

**Comment by ortizleo** [comment] 2020-06-17 14:58
Hello.
Any news? We cant query in Graylog 3.3.1...

**Comment by franz82** [comment] 2020-06-19 07:51
Hello,
same issue here, Graylog 3.3.0 and Firefox 76.0.1, OS Arch Linux.
-f

**Comment by valleyman07** [comment] 2020-06-19 09:52
you have planned to remove any patch?
is there any chance of doing a downgrade? because no new or defined query works in the dashboard.
And my company we need so it works.

**Comment by ortizleo** [comment] 2020-06-24 12:56
Please we need a fix.
@dennisoelkers

**Comment by dennisoelkers** [comment] 2020-06-24 13:29
Since this issue was opened, I tried several times to reproduce it, with different browsers and versions. Unfortunately I was not successful. Does anyone of you see an error in your browser's JS console?

**Comment by ortizleo** [comment] 2020-06-24 14:32
Hello.

Here show this in console:

```
6ace.js:4113 Uncaught Error: Unknown config key: sharedPopups
    at a.exports.get (ace.js:4113)
    at Function.ace.define.c.for (ext-language_tools.js:1811)
    at Array.g (ext-language_tools.js:2085)
    at i.t._signal (ace.js:3876)
    at i.exec (ace.js:11866)
    at r.$callKeyboardHandlers (ace.js:4631)
    at r.onTextInput (ace.js:4646)
    at y.onTextInput (ace.js:13548)
    at A (ace.js:2461)
    at HTMLTextAreaElement.T (ace.js:2482)

```

Attached another example, here I pressed 12345a on physical  keyboard..
![query problem3](https://user-images.githubusercontent.com/17042298/85575962-5fb95400-b60e-11ea-998c-dffaa9d476be.gif)

**Comment by dennisoelkers** [comment] 2020-06-25 12:24
Thanks for the information, @ortizleo! Which plugins (and which versions of them) do you have installed?

**Comment by franz82** [comment] 2020-06-25 18:45
@dennisoelkers,
some info from my env.
I had installed [graylog-plugin-telegram-notification-2.3.0.jar](https://github.com/irgendwr/TelegramAlert/releases/tag/v2.3.0) before upgrade graylog from v3.2.5-1 to v3.3.0-5 (graylog deb packages).
Now I deleted the telegram plugin and... search tab started working again!
In fact, I can see a [new version of telegram plugin](https://github.com/irgendwr/TelegramAlert/releases/tag/v2.3.1) specifically for Graylog 3.3.0 or later.
Do you think this can cause the issue?
-f

**Comment by franz82** [comment] 2020-06-25 18:52
Just a little update:
I installed latest telegram plugin ([v2.3.1](https://github.com/irgendwr/TelegramAlert/releases/tag/v2.3.1)), telegram notifications are working.
Search console is still working, too.
-f

**Comment by ortizleo** [comment] 2020-06-26 02:28
> Just a little update:
> I installed latest telegram plugin ([v2.3.1](https://github.com/irgendwr/TelegramAlert/releases/tag/v2.3.1)), telegram notifications are working.
> Search console is still working, too.
> -f

Ok you found it.
Updated graylog-plugin-telegram-notification to [2.3.1](https://github.com/irgendwr/TelegramAlert/releases/tag/v2.3.1) and is fixed :).

Good Work and thanks!

**Comment by irgendwr** [comment] 2020-06-26 15:49
This issue is a duplicate of #8183 .

As @ortizleo already discovered: this is fixed in the [latest release of TelegramAlert](https://github.com/irgendwr/TelegramAlert/releases/latest). So the solution is to upgrade the plugin, restart graylog and optionally clear the browsers cache.

The issue is/was an unfortunate side-effect of how graylog's frontend plugin system works. If a plugin's frotend depends on graylog assets, it has to contain them and therefore will also override them which causes issues when these assets are out of sync.

@ortizleo / @dennisoelkers please close this, as it is solved.

**Comment by dennisoelkers** [comment] 2020-06-29 07:50
Thanks @franz82, @ortizleo and @irgendwr!

This issue is resolved. Nevertheless we should prevent hard to find issues like this by making our plugin system more robust, which is in  my backlog for a while now anyway.

**Closed by dennisoelkers** 2020-06-29 07:50 UTC
Labels: bug, to-verify, triaged
