### ISSUE TITLE
Strange Dashboard Behavior in 3.2.x

### ISSUE THREAD

**Issue by yoke88** [Graylog2/graylog2-server#7701] opened 2020-03-18 03:28 UTC
After upgraded from graylog 3.1 to 3.2, the UI changed a lot ,especially the dashboard behivor.

## Expected Behavior

I have created a dashboard to overview all windows event logs to troubleshooting. so i created four tabs (view) and using different query to get a summary.
- All Errors and warnings with query `winlogbeat_level:(错误 OR Error OR 警告 OR Warning)`
- All Errors  with query `winlogbeat_level:(错误 OR Error)`
- All Warnings with query `winlogbeat_level:(警告 OR Warning)`
- NetLog Failed with query `winlogbeat_event_id:(5719 OR 4266)`

![捕获](https://user-images.githubusercontent.com/3146226/76920987-d35d0e00-6907-11ea-9b35-9978ab10d9b6.JPG)

when in graylog 3.1 every tab (the view show the search bar for every tab, and show the query i used, and i can change the query and using Drill-down to quick change the query ),after 3.2 ,the query bar for each tab disappeared and the search become global filter,the global filter will replace the search query for each widget in the dashboard.

for example:
The widget with query `winlogbeat_level:(错误 OR Error OR 警告 OR Warning)` , if i want to drill-down a host with name xxxx ,i using drill-down to add a quick query `winlogbeat_beat_name:xxxx` and i want to combine the search like this `winlogbeat_level:(错误 OR Error OR 警告 OR Warning) AND winlogbeat_beat_name:xxxx` , but the behaivor in graylog 3.2 will replace all the query with `winlogbeat_beat_name:xxxx`

so now in graylog 3.2 i have two options:
1. rewrite the whole query , but i need to know the original query,but i can not see the query of the widget.( I can see the query from chrom development tools ,but can not see it in the GUI)

> you will see in the screenshot below ,the widget shows the correct query result (with only error events) but does not show the query in the search bar
![Annotation 2020-03-18 111525](https://user-images.githubusercontent.com/3146226/76922004-64cd7f80-690a-11ea-87c9-9c81d46b9058.jpg)

2. do not using drill-down and the global-filter, boring life ,and i want to migrate to kibana

 
## Current Behavior
- widget query does not show in the GUI ,but i can capture it using chrome development tools
- dashboard global filter will replace all the widget query .which i want is "global filter is actually a filter but not a query search", or "global filter will combine the widget query"

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by bernd** [comment] 2020-03-23 10:26
@Graylog2/frontend Can you please check if there is a bug with the dashboard filter replacing the widget queries? Thank you!

**Comment by linuspahl** [comment] 2020-03-23 13:30
@yoke88 Thank you for reporting this issue! We have a theory regarding the cause, but it would be good to know how and when you've created the dashboard / tabs and the widgets:
1. Did the dashboard already existed in 3.1?
2. Or did you used the "Export to Dashboard" functionality on the main search page (3.2)
3. You've mentioned you are still seeing the query string, using the Chrome Dev Tools. Could you explain where you are still seeing query string?

My guess:
When you are opening the dashboard, you should see a request for the dashboard: 
`http://[your.domain]/api/views/[dashboard-id]`
followed by one for the related search data:
`http://[your.domain]/api/views/search[search-id]`
The second one returns an object, with the key `queries` (you will see one entry for each dashboard tab)
An entry in the `queries` array has `query` attribute, does the query string still exists here?
An entry in the `queries` array also has a `search_type` attribute with an entry for every widget on the specific dashboard tab. A `search_type` also has a query attribute. It would be great to know what this attribute contains, if you are able to relate this `search_type` with a problematic widget.

Thanks in advance for you help!

**Comment by yoke88** [comment] 2020-03-26 07:15
the dashboard was created at 3.1 and upgraded to 3.2

![捕获](https://user-images.githubusercontent.com/3146226/77620111-9a124700-6f74-11ea-81e1-e84d7fd751bb.JPG)

**Comment by yoke88** [comment] 2020-03-26 07:17
The dashboard was created at 3.1 and upgraded to 3.2
![捕获](https://user-images.githubusercontent.com/3146226/77620222-d645a780-6f74-11ea-8015-3656577aae75.JPG)

**Comment by linuspahl** [comment] 2020-04-06 09:50
@yoke88 Thanks again for your feedback! We will release a fix for this problem with graylog 3.3.
If you have not done it already, one workaround is creating a dashboard from scratch with the desired widgets. The dashboard and widget search query relation will work as described in "Expected behaviour -> for example"

**Comment by dennisoelkers** [comment] 2020-05-14 11:51
Fixed in #7750.

**Closed by dennisoelkers** 2020-05-14 11:51 UTC
Labels: bug, search, triaged
