### ISSUE TITLE
Stacktrace when opening license page

### ISSUE THREAD

**Issue by rkmbaxed** [Graylog2/graylog2-server#13940] opened 2022-11-10 13:12 UTC
I get a Stack Trace on the license page in Graylog 5 beta 3. This error wasn't in Graylog 5 beta 2.

## Expected Behavior
Open the license page

## Current Behavior
I get a stack trace when I try to open the license page.
Something went wrong.

Stack trace from the UI.
````
e[r].localeCompare is not a function

Stack Trace:

TypeError: e[r].localeCompare is not a function
    at https://graylog-test.someone.de/assets/plugin/org.graylog.plugins.enterprise.EnterprisePlugin/plugin.org.graylog.plugins.enterprise.EnterprisePlugin.bb4a02a2e80fb5b1c06f.js:2:1361498
    at Array.sort (<anonymous>)
    at a.getFormattedDataRows (https://graylog-test.someone.de/assets/plugin/org.graylog.plugins.enterprise.EnterprisePlugin/plugin.org.graylog.plugins.enterprise.EnterprisePlugin.bb4a02a2e80fb5b1c06f.js:2:1361466)
    at a.value (https://graylog-test.someone.de/assets/plugin/org.graylog.plugins.enterprise.EnterprisePlugin/plugin.org.graylog.plugins.enterprise.EnterprisePlugin.bb4a02a2e80fb5b1c06f.js:2:1362631)
    at ji (https://graylog-test.someone.de/assets/vendor.1e79e27aeb952fbe940b.js:2:822174)
    at Pi (https://graylog-test.someone.de/assets/vendor.1e79e27aeb952fbe940b.js:2:821969)
    at _a (https://graylog-test.someone.de/assets/vendor.1e79e27aeb952fbe940b.js:2:857467)
    at fb (https://graylog-test.someone.de/assets/vendor.1e79e27aeb952fbe940b.js:2:848941)
    at lb (https://graylog-test.someone.de/assets/vendor.1e79e27aeb952fbe940b.js:2:848866)
    at ab (https://graylog-test.someone.de/assets/vendor.1e79e27aeb952fbe940b.js:2:845896)
    at https://graylog-test.someone.de/assets/vendor.1e79e27aeb952fbe940b.js:2:797644
    at exports.unstable_runWithPriority (https://graylog-test.someone.de/assets/vendor.1e79e27aeb952fbe940b.js:2:872944)
    at Up (https://graylog-test.someone.de/assets/vendor.1e79e27aeb952fbe940b.js:2:797353)
    at $p (https://graylog-test.someone.de/assets/vendor.1e79e27aeb952fbe940b.js:2:797589)
    at Kp (https://graylog-test.someone.de/assets/vendor.1e79e27aeb952fbe940b.js:2:797524)
    at nb (https://graylog-test.someone.de/assets/vendor.1e79e27aeb952fbe940b.js:2:842681)
    at Object.enqueueSetState (https://graylog-test.someone.de/assets/vendor.1e79e27aeb952fbe940b.js:2:801309)
    at h.setState (https://graylog-test.someone.de/assets/vendor.1e79e27aeb952fbe940b.js:2:903650)
    at p.n (https://graylog-test.someone.de/assets/vendor.1e79e27aeb952fbe940b.js:2:911149)
    at p.emit (https://graylog-test.someone.de/assets/vendor.1e79e27aeb952fbe940b.js:2:56458)
    at z.trigger (https://graylog-test.someone.de/assets/vendor.1e79e27aeb952fbe940b.js:2:912030)
    at https://graylog-test.someone.de/assets/plugin/org.graylog.plugins.enterprise.EnterprisePlugin/plugin.org.graylog.plugins.enterprise.EnterprisePlugin.bb4a02a2e80fb5b1c06f.js:2:1000521
Component Stack:

    in a
    in div
    in t
    in div
    in t
    in Row
    in span
    in a
    in LicensesPage
    in t
    in t
    in div
    in t
    in PageContentLayout__StyledGrid
    in s
    in div
    in PageContentLayout__Container
    in E
    in t
    in t
    in div
    in App__PageContent
    in i
    in Nt
    in div
    in App__AppLayout
    in m
    in fn
    in t
    in t
    in i
    in t
    in et
    in Unknown
    in ConnectStoresWrapper[Unknown/Anonymous] stores=streams
    in Qg
    in t
    in At
    in we
    in z
    in at
    in dt
    in St
    in Pt
    in Et
    in vt
    in b
    in xt
    in Mt
    in Suspense
    in t
    in Unknown
    in ee
    in we
    in z
    in me````

## Possible Solution


## Steps to Reproduce (for bugs)

1. Click on Enterprise -> Licenses

## Context
Try to insert a valid license and to open the license page

## Your Environment

* Graylog Version: 5.0 beta 3 (Graylog 5.0.0-beta.3+19ce29b)
* Java Version: 17
* Opensearch Version: 2.3
* MongoDB Version: 6.0
* Operating System: SLES15
* Browser version: Edge / Chrome / Firefox current version

**Comment by bernd** [comment] 2022-11-10 20:42
Thanks for the report. The issue is fixed in 5.0.0-beta.4 we released today.

**Closed by bernd** 2022-11-10 20:42 UTC
Labels: bug
