### ISSUE TITLE
Bar Chart display no data (Default Aggregat) with few data

### ISSUE THREAD

**Issue by LeDOC666** [Graylog2/graylog2-server#8095] opened 2020-05-12 07:25 UTC
I just update to 3.2.4, and have seen problem with my Streams, and some dashboards.
Here is a sample:
I have a Stream with 25 messages on timestamp: 00:00
On **Message Count** widget, I see the auto level Y bar, but I don't see the data bar to 25.

## Expected Behavior
See the real data in **Bar Chart**

## Current Behavior
Level is right (set to 40 on Y bar), but no data at 00:00
BUT **Line chart** display the data

## Steps to Reproduce (for bugs)

1. Have few message (25 per day) at 00:00 for me
2. Display Default **Message Count** 

## Your Environment

* Graylog Version: 3.2.4
* Elasticsearch Version: 5
* MongoDB Version: 4.0.6
* Operating System: OL 7.4
* Browser version: Chrome

**Comment by LeDOC666** [comment] 2020-05-12 07:29
Row = timestamp
Metric = count()

**Comment by dennisoelkers** [comment] 2020-05-12 08:16
Hey @LeDOC666!

Thanks for getting in touch with us! Can you edit the widget and change the visualization to "Data Table" and check if there is only a single data point? If that is the case, it would indicate that this is really related to #7167.

**Comment by LeDOC666** [comment] 2020-05-12 09:30
Yes, I have only a single point

**Comment by dennisoelkers** [comment] 2020-05-15 13:48
Duplicate of #7167.

**Closed by dennisoelkers** 2020-05-15 13:48 UTC
Labels: bug
