### ISSUE TITLE
3.2 search field's are not filtered to the current search context

### ISSUE THREAD

**Issue by asmodianx** [Graylog2/graylog2-server#7535] opened 2020-02-24 13:28 UTC
3.2 search field's are not filtered to the current search context

## Expected Behavior
In 3.1 after executing a search it only displays the the fields in the current search

## Current Behavior
In 3.2 the search screen no longer exists and what is called the search screen is the views screen in 3.1 which displays all possible fields which is not the intended behavior
## Possible Solution
return 3.1 search screen

bring view/search screen to feature parity with old 3.1 search screen (also missing lookups beautifiers and other key features)

## Steps to Reproduce (for bugs)

1.populate graylog with sufficiently diverse fields and data types
2.search for a specific event type
3.the left hand dock will display all fields in the system

## Context

As the left hand field doc is missing features and functionality and is clogged with out of context fields the view/search is unusable
## Your Environment
Graylog 3.2.2+2f9a628 on aux-graylog1 (Private Build 1.8.0_242 on Linux 4.15.0-88-generic)

Graylog Version:
Graylog 3.2.2+2f9a628

Elasticsearch Version:
6.8.6

MongoDB Version:
v4.0.16

Operating System:
ubuntu 18.04 x64

Browser version:
Firefox

**Comment by dennisoelkers** [comment] 2020-02-24 13:31
Hey @asmodianx, thanks for reporting this!

We are already tracking this issue and plan to fix it in the next non-patch release of Graylog (`3.3`). Therefore I am closing this issue.

Duplicate of #7517.

**Closed by dennisoelkers** 2020-02-24 13:31 UTC
Labels: bug

**Comment by asmodianx** [comment] 2020-02-24 14:40
Thank you!
