### ISSUE TITLE
User Details should show all shared entities, even ones done by teams.

### ISSUE THREAD

**Issue by bud1979** [Graylog2/graylog2-server#9248] opened 2020-10-22 16:34 UTC
Shared Entities only shows directly shared objects.  Could we get a way to get a Summary view, of ones shared directly, and via teams on the same page?  Right now, I would expect to come to my user and see all things shared in one spot, similar to the dark screen, but one is shared direct and on via teams.  On the teams page it is shown, but you have to map the team to the user every time.  Thinking of a "Summary Shared Entities" at the bottom of all stuff this user has access.  

<img width="1394" alt="Screen Shot 2020-10-22 at 10 31 05 AM" src="https://user-images.githubusercontent.com/26657656/96902678-0e04c700-1452-11eb-8212-e912a39f1737.png">

## Your Environment

* Graylog Version: 4.0b1

**Comment by bernd** [comment] 2020-10-23 14:23
Refs: https://github.com/Graylog2/graylog-plugin-enterprise/issues/1718

**Comment by bernd** [comment] 2020-10-26 14:38
Duplicate of https://github.com/Graylog2/graylog-plugin-enterprise/issues/1718

**Closed by bernd** 2020-10-26 14:38 UTC
Labels: bug, triaged
