### ISSUE TITLE
Keep AD group mapping in GL 4 OS

### ISSUE THREAD

**Issue by aim4r** [Graylog2/graylog2-server#9392] opened 2020-11-06 21:59 UTC
## What?

AD group mapping simplifies access management in GL. Please keep the AD group mapping feature in GL 4 OS

## Why?

Because we love GL and we know the team will listen to our feedback :)

## Your Environment

* Graylog Version: 4 beta

**Comment by rosaLux161** [comment] 2020-11-19 10:56
Thoughts about it:

LDAP group mapping is an essential feature that was already available in the free version. To remove an already existing feature, which is probably used in many setups and replace it with a new one, but which is only available in the Enterprise version, will break and lead to huge problems in many setups

Of course, Graylog is financed by donations and especially by the Enterprise version and a larger range of functions, but I ask the responsible persons to think about whether the role system and role mapping feature should really be outsourced to the Enterprise version.

**Comment by riskersen** [comment] 2020-11-21 06:42
+1 important feature

**Comment by mayrstefan** [comment] 2020-11-21 10:45
I'm confused. From the 4.0 Release post

Open Source:
> Simplified Access Control removes the complexities of group permissions, enabling the management of users directly for a much simpler experience. Open Source users will also be able to manage access for larger teams of users through integration with AD/LDAP.

Enterprise:
> Team Management enables enterprise-sized organizations to efficiently control access to content creation at a Team level. This significantly reduces the time required to manage access and provides a greater degree of flexibility to share dashboards and search templates within a team and across the organization. 

Also from the docs:
> Both LDAP and Active Directory now support the synchronization of teams. Because teams are only available in Graylog Enterprise, the Open Source product no longer has Group Mapping.

From the Enterprise Release notes:
>Add support for managing access to streams, searches and dashboards through teams.

So teams are the successor to roles. Before Graylog 4 we used LDAP-Mappings to fill roles and used the roles for permission management of streams and dashboards. How can we replace that in the Open Source Edition when the answer is not teams? What happens with existing role mappings?

**Comment by sbaygithub** [comment] 2020-11-23 08:31
> I'm confused. From the 4.0 Release post
> 
> Open Source:
> 
> > Simplified Access Control removes the complexities of group permissions, enabling the management of users directly for a much simpler experience. Open Source users will also be able to manage access for larger teams of users through integration with AD/LDAP.
> 
> Enterprise:
> 
> > Team Management enables enterprise-sized organizations to efficiently control access to content creation at a Team level. This significantly reduces the time required to manage access and provides a greater degree of flexibility to share dashboards and search templates within a team and across the organization.
> 
> Also from the docs:
> 
> > Both LDAP and Active Directory now support the synchronization of teams. Because teams are only available in Graylog Enterprise, the Open Source product no longer has Group Mapping.
> 
> From the Enterprise Release notes:
> 
> > Add support for managing access to streams, searches and dashboards through teams.
> 
> So teams are the successor to roles. Before Graylog 4 we used LDAP-Mappings to fill roles and used the roles for permission management of streams and dashboards. How can we replace that in the Open Source Edition when the answer is not teams? What happens with existing role mappings?

From the docs: "Existing custom roles will be migrated to the new entity sharing system on the first server startup." 
See: https://docs.graylog.org/en/4.0/pages/upgrade/graylog-4.0.html#ldap-and-active-directory-group-mapping-removed

I totally agree with the previous comments above and hope that Graylog listen to their customers as the feature is essential for the Open source version and it would break a lot of installations. So please bring that feature back.

**Comment by macko003** [comment] 2020-11-23 12:52
+1
We also use Graylog free version, and based on the docs I can't imagine how can we use rights based on LDAP, and LDAP groups

**Comment by mayrstefan** [comment] 2020-11-24 16:25
@sbaygithub I was not brave enough to test it in our production environment with a real ldap server but I did some local tests with the Graylog docker containers, local users and roles with different permissions. There is no visible migration. Not in the logs nor in the GUI. The API browser shows that permissions are still present in roles. But the web UI doesn't show those permissions any more. Also I cannot see any teams or shares assigned to streams or dashboards.

### To reproduce
1. start graylog:3.3
2. create some streams, dashboards, users and roles and assign some permissions
3. stop graylog:3.3 and start graylog:4.0
4. permissions are still as expected but not visible anywhere in the gui

**Comment by dphilpot** [comment] 2020-11-25 10:44
Hey,

we are using graylog for some time now and where grateful for the LDAP Group and User mapping feature. This is some thing not every competitor supports and was one of the main features for us to migrate to graylog.

We will not upgrade to 4.x until we are sure that this feature is working and back in the community version.

We totally understand that a company needs to make money, but we can not understand that a given feature is taken away with profit in mind.

So please bring back this as a free working feature for the community.

**Comment by rcny** [comment] 2020-11-25 15:11
Just passed by and wanted to note, [AWS's Open Distro for Elasticsearch Security](https://github.com/opendistro-for-elasticsearch/security) has LDAP authn and authz with the group mapping as a totally free and open source feature. You can have all authn/authz features without any paywall (not like with vanilla X-Pack, Search Guard or nowaday Graylog) which are even totally ES native. As for me, I'll stick with 3.x and probably consider migrating users to the Open Distro Security powered Kibana if Graylog's group mapping won't return to the community tier. 
Furthermore, fully getting rid of Graylog will be absolute pain for me. I have quite a massive amount of pipelines running in my Graylog cluster, but, well, I can't stick with ES6 forever too. With great respect, I ask Graylog management to reconsider their group mapping removal from the community tier. At very least, there is the totally viable alternative for authn/authz here, which will possibly trigger migration of your potentially paying userbase to the Open Distro charged ELK. Well, Open Distro has substitutes for almost all essential Graylog features (e.x. you can replace Graylog's index sets with Open Distro's ISM), but I still think that Graylog is the very well-designed solution for log aggregation, processing and retrieval.

**Comment by kroepke** [comment] 2020-11-25 18:56
Hi all,

First of all, thank you for your patience and the friendly tone in this issue!

I'd like to explain the background of this decision, not because I want to avoid the conversation, but because I think it's important for understanding why we made this choice.

The goal of this project was to allow better management of permissions in Graylog. As several people noted, we also need to make money, and for Graylog that means selling software.
Thus it was clear from the beginning that some of the new features need to be available only to Enterprise customers.
We also did not want to cripple the Open Source version in some arbitrary manner, especially not take away Users or Permissions like other products do it.

When we talked to users and customers during the design phase of this, some common themes emerged: 
 * all wanted more self-service management of permissions
 * roles combined two things that don't belong together: what can be done (read/edit) and which things they can be done on (specific streams/dashboards)
 * larger environments tend to have teams with varying members and think about permission management through that concept

We drew three conclusions from this:
 * we need to support teams of users in Graylog, and as a completely new concept which provides little benefit for smaller deployments, it was an obvious candidate for an Enterprise feature
 * roles are not the right abstraction, because they require high privileges (editing the role itself) to grant more access to them
 * the share dialog used in Search was popular with and well-understood by users, so we wanted to adopt that style of access management in more places

So, Teams were an Enterprise feature, and Sharing was going to be basis of permission management. This meant taking the "to which thing" out of the roles, effectively turning roles into "capabilities" like "Can create dashboards", "Can use Archiving", but not "Can see the HTTP server stream". The latter is done via Shares.

However, this created a problem: If roles no longer say what specific things you can access, what good is it to map LDAP/AD groups to them? There's nothing you can manage through group-to-role mapping anymore.
Since your directory service does not know anything about Graylog dashboards and streams, there's no sensible group mapping that you can do.
Instead we said that groups will map to Teams, and in Enterprise you can share things with entire Teams, and thus with the users that happen to be members of them.

We had very long and heated discussions about this and essentially it boiled down to one of the following options:
 * remove all permissions from the product and make it all Enterprise
 * make everything Open Source and not be able to make money from the new feature at all
 * go with the approach I described above, with the consequence that a previous feature would be "removed"

I said "removed" in quotes, because there really is no direct equivalent for group mapping in Graylog 4.0 as it was done before.
We took care to migrate all existing permissions assigned through the supported features (custom roles still remain as they were, and you can still manage them through the API) to the new Share system, so no information leakage should occur. If something is not properly migrated, then that is a bug and should be fixed. Please report it and we'll get to it.

The message here is: We believe that making it easier to manage permissions for a large number of users is a typical Enterprise requirement and given the options we had in front of us, we picked the one that, we believe, balances implementation effort, Open Source community, and our Enterprise customers.

For these reasons we will not make this capability available in open source and we hope this helps illustrate our actions a bit better.

**Comment by dphilpot** [comment] 2020-11-26 06:48
Hey @kroepke,
first of all thank you very much for this detailed information and your will to speak open with the community. I can somehow understand your decision but somehow i'm asking myself if this is really the best way?

I put some thought into it and i was thinking of the following solution, which might be a good way for graylog itself since i can see that you will loose some people who cannot or are not willing to afford the enterprise version.

In my opinion you made a good decision to refactor this whole process and try to make it better! But what most people around me disturbs about graylog enterprise is its cost factor for features which they do not need.

So why not thinking about making this LDAP / SAML as a Module which has a "good" price for the community version of graylog. You can still keep it bundled with the enterprise version, if there is a nice price around this featured as a module i think many people who are using this will be able and willing to afford this?

With this in mind, you might even be able to package more feature in a module an offer them the enterprise as well as the community.

What do you think about this?

**Comment by LexaNz** [comment] 2020-11-26 20:17
> So why not thinking about making this LDAP / SAML as a Module which has a "good" price for the community version of graylog. You can still keep it bundled with the enterprise version, if there is a nice price around this featured as a module i think many people who are using this will be able and willing to afford this?
> 
> With this in mind, you might even be able to package more feature in a module an offer them the enterprise as well as the community.
> 
> What do you think about this?

I had exactly the same thought, there is only one pricing scheme, and we simply can't afford it. So we are looking now for another tool. Look Bacula systems for example, you can pay for volume, or for functionalities.

**Comment by aim4r** [comment] 2020-11-30 21:03
Thanks everyone for the comments, suggestions and feedback on this feature request. 
I think the Graylog team, [including the founder](https://community.graylog.org/t/graylog-4-0-ldap-group-changes/17866/4), made it clear that the decision is to remove the feature, with ample information backing this decision as detailed [here](https://github.com/Graylog2/graylog2-server/issues/9392#issuecomment-733892973). The reasoning and outcome might come as confusing or disappointing for some of us, but they have their reasons which we shall respect. 
As such, I will be closing this feature request soon.

**Closed** 2020-12-02 19:47 UTC
Labels: feature, triaged

**Comment by zez3** [comment] 2020-12-19 18:30
> The message here is: We believe that making it easier to manage permissions for a large number of users is a typical Enterprise requirement and given the options we had in front of us, we picked the one that, we believe, balances implementation effort, Open Source community, and our Enterprise customers.

The message here is pretty clear for me. It's a f off to all your past contributors and comunity!
I actually wanted to buy this new Enterprise Teams option but since you don't have such a license model, I can't. 
I am at an tipping point now where I am definitely consider moving to Elastic stack all of my infrastructure.
They have much more flexibility at licensing what I need and the new still beta pending release are now more attractive than ever.
https://www.elastic.co/subscriptions
Perhaps you should get inspired by them.

**Comment by hulkk** [comment] 2021-01-18 09:33
We need to start planning moving to ELK due to this change. Graylog is too buggy and expensive for its capabilities.
