### ISSUE TITLE
Increasing number of values in widgets seems broken after 3.3.6 upgrade

### ISSUE THREAD

**Issue by aim4r** [Graylog2/graylog2-server#9103] opened 2020-10-07 10:28 UTC
I have recently upgraded from 3.3.5 to 3.3.6 using APT packages on Ubuntu 20.04.

Just after upgrading, increasing the number of values in ANY widget became broken (results in a blank message table). 

## Steps to Reproduce (for bugs)
Full screesnhots aand steps to reproduce [here](https://community.graylog.org/t/increasing-number-of-values-is-broken-after-3-3-6-upgrade/17423)

## Context
I have recently upgraded from 3.3.5 to 3.3.6 using APT packages on Ubuntu 20.04.

## Your Environment
* Graylog Version: 3.3.6
* Operating System: Ubuntu 20.04

**Comment by dennisoelkers** [comment] 2020-10-07 10:55
Hey @aim4r!

Thanks for reporthing this. The issue is known already and fixed in fixed in #9085, which will be part of `3.3.7`.

Duplicate of #9087.

**Closed by dennisoelkers** 2020-10-07 10:55 UTC
Labels: bug
