### ISSUE TITLE
JSON extractor import not respecting 'flatten' option

### ISSUE THREAD

**Issue by rikatz** [Graylog2/graylog2-server#1600] opened 2015-12-02 16:30 UTC
While testing the JSON extractor, I did some changes on that and needed to export and import them.

Exporting the extractors where sucessfuly (as represented on the following code):

```json
{
  "extractors": [
    {
      "condition_type": "none",
      "condition_value": "",
      "converters": [],
      "cursor_strategy": "copy",
      "extractor_config": {
        "flatten": false,
        "key_separator": ".",
        "list_separator": ", ",
        "kv_separator": "="
      },
      "extractor_type": "json",
      "order": 0,
      "source_field": "message",
      "target_field": "message",
      "title": "JSONMessage"
    }
  ],
  "version": "1.2.2 (91c7822)"
}
```

But when importing this, Graylog changes the option of 'flatten' (from extractor config) to true.

**Comment by joschi** [comment] 2015-12-02 16:51
Duplicate of Graylog2/graylog2-web-interface#1702.

**Closed by joschi** 2015-12-02 16:51 UTC
