### ISSUE TITLE
Icons sometimes replaced with squares

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2568] opened 2016-07-29 16:35 UTC
### Problem description
Sometimes icons replaced with squares.
![image](https://cloud.githubusercontent.com/assets/17475270/17255743/2add4bce-55c3-11e6-95e8-eb8aefdc842a.png)

One way to reproduce (I not sure if it is stable)
1. Open Graylog
2. Open Pipelines tab
3. Refresh page (F5)

Some icons are broken.
For example Search tab:
![image](https://cloud.githubusercontent.com/assets/17475270/17255888/bffc14d8-55c3-11e6-8602-79958fb06463.png)
![image](https://cloud.githubusercontent.com/assets/17475270/17255897/ca5b5506-55c3-11e6-9bfa-8156fe1a60db.png)

If page refreshed (F5) on Search tab -normal icons returned.

### Environment
* Graylog Version: 2.1.0-beta1

**Comment by edmundoa** [comment] 2016-07-30 09:20
This issue is caused by #2564.

**Comment by kroepke** [comment] 2016-07-30 09:20
@hc4 This is a known issue which is in progress over at https://github.com/Graylog2/graylog2-server/pull/2564

The gist is that when the initial page load happens in a plugin the new app prefix screws up loading the webfonts.

**Comment by bernd** [comment] 2016-08-01 15:13
@hc4 Thank you for the report, this will be fixed in the next beta.

**Closed** 2016-08-01 15:13 UTC
Labels: bug, P1, S1, web
