### ISSUE TITLE
Graylog2 on IPv6 only with dual-stack front-end

### ISSUE THREAD

**Issue by valentin2105** [Graylog2/graylog2-server#4005] opened 2017-07-17 05:51 UTC
Hello,

I'm trying to deploy Graylog on IPv6 VMs with IPv4/6 reverse-proxy but I can't access it correctly behind Nginx. (it work directly via IPv6 port 9000).

## Expected Behavior
Can access to Graylog with my reverse-proxies

## Current Behavior
Accessing Graylog directly in IPv6 work fine, (port 9000 http)
But using my v4/v6 Nginx proxy, I got this error :

`{"type":"ApiError","message":"This IPv6 address cannot be used in IPv4 context"}`

## Steps to Reproduce (for bugs)
1. Install graylog in IPv6 only
2. Serve him using Nginx on IPv4/6

## Environment :
Latest graylog for Debian. 
(ES and Mongo are useless because it work fine)

```
rest_listen_uri = http://[2405:f124::43]:9001
rest_transport_uri = https://api.graylog.domain.com
trusted_proxies = 127.0.0.1/32, 0:0:0:0:0:0:0:1/128, 2405:f124::/32
web_listen_uri = http://[2405:f124::43]:9000/
```
( I try to expose api with **api.graylog.domain.com** and Graylog with **graylog.domain.com** )

Any idea what happend ? 

logs : 

```

2017-07-17T16:49:32.157+11:00 ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
java.lang.IllegalArgumentException: This IPv6 address cannot be used in IPv4 context
	at org.jboss.netty.handler.ipfilter.CIDR.getIpV4FromIpV6(CIDR.java:213) ~[graylog.jar:?]
	at org.jboss.netty.handler.ipfilter.CIDR4.ipv4AddressToInt(CIDR4.java:144) ~[graylog.jar:?]
	at org.jboss.netty.handler.ipfilter.CIDR4.contains(CIDR4.java:100) ~[graylog.jar:?]
	at org.jboss.netty.handler.ipfilter.IpSubnet.contains(IpSubnet.java:119) ~[graylog.jar:?]
	at org.jboss.netty.handler.ipfilter.IpSubnet.contains(IpSubnet.java:104) ~[graylog.jar:?]
	at org.graylog2.rest.RestTools.getRemoteAddrFromRequest(RestTools.java:70) ~[graylog.jar:?]
	at org.graylog2.shared.security.ShiroSecurityContextFilter.filter(ShiroSecurityContextFilter.java:68) ~[graylog.jar:?]
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132) ~[graylog.jar:?]
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68) ~[graylog.jar:?]
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197) ~[graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:318) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

```

(For information, I use the same configuration in IPv4/6 VM, and it work at glances). 

Thanks.

**Comment by joschi** [comment] 2017-07-17 07:44
@valentin2105 This is a duplicate of #3870 and has been fixed in #3926.

**Closed by joschi** 2017-07-17 07:44 UTC
