### ISSUE TITLE
(Histogram on) Search page breaks when removing search term from query that lead to 0 results before

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#5252] opened 2018-10-31 08:54 UTC
## Expected Behavior

Histogram on Search Page is shown whenever there are result messages

## Current Behavior

After 2.4, but before `3.0-alpha.3` (current state of `master`) the histogram breaks under certain conditions (see "Steps to Reproduce"), after #5154 the error boundary catches the exception thrown and displays an error page instead.

Pre #5154:
![screen shot 2018-10-31 at 09 53 34](https://user-images.githubusercontent.com/41929/47776529-e6f7dc80-dcf2-11e8-80cb-dfd34ee5a594.png)

Post #5154:
![screen shot 2018-10-31 at 09 53 44](https://user-images.githubusercontent.com/41929/47776544-ecedbd80-dcf2-11e8-87c4-81e2b46d585b.png)

## Steps to Reproduce (for bugs)

1. Go to "Search"
2. Switch relative time range to "All Messages"
3. Enter a search query that returns no results
4. Change the search query so that it returns results

**Comment by bernd** [comment] 2020-11-14 23:24
I am unable to reproduce that with the new search page. Closing the issue.

**Closed by bernd** 2020-11-14 23:24 UTC
Labels: #S, bug, triaged
