### ISSUE TITLE
Certain stream alerts (less than 1 in recent index) cause false positives when cycling indexes

### ISSUE THREAD

**Issue by spruchnik** [Graylog2/graylog2-server#602] opened 2014-06-30 19:28 UTC
```
15:08:58,959 INFO  [Deflector] Pointing deflector to new target index....
15:08:59,194 INFO  [Deflector] Flushing old index <graylog2_219>.
15:08:59,568 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_163] in [552ms].
15:08:59,716 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_164] in [148ms].
15:08:59,804 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_165] in [87ms].
15:08:59,896 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_166] in [91ms].
15:08:59,983 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_167] in [86ms].
15:09:00,071 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_168] in [87ms].
15:09:00,148 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_169] in [77ms].
15:09:00,152 INFO  [RebuildIndexRangesJob] Index [graylog2_220] is empty. Not calculating ranges.
15:09:00,241 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_171] in [88ms].
15:09:00,338 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_170] in [97ms].
15:09:00,440 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_173] in [101ms].
15:09:00,553 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_172] in [113ms].
15:09:00,643 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_197] in [89ms].
15:09:00,732 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_196] in [88ms].
15:09:00,814 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_199] in [82ms].
15:09:00,907 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_198] in [93ms].
15:09:01,003 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_190] in [95ms].
15:09:01,089 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_191] in [85ms].
15:09:01,168 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_194] in [79ms].
15:09:01,259 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_195] in [90ms].
15:09:01,392 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_192] in [132ms].
15:09:01,482 INFO  [Deflector] Setting old index <graylog2_219> to read-only.
15:09:01,493 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_193] in [101ms].
15:09:01,543 INFO  [SystemJobManager] Submitted SystemJob <feed1f70-0089-11e4-a31d-028925f19857> [org.graylog2.indexer.indices.jobs.OptimizeIndexJob]
15:09:01,543 INFO  [Deflector] Done!
15:09:01,546 INFO  [OptimizeIndexJob] Optimizing index <graylog2_219>.
15:09:01,643 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_176] in [149ms].
15:09:01,744 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_177] in [100ms].
15:09:01,864 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_174] in [120ms].
15:09:01,972 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_175] in [107ms].
15:09:02,113 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_178] in [140ms].
15:09:02,263 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_179] in [150ms].
15:09:03,145 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_180] in [882ms].
15:09:03,353 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_184] in [208ms].
15:09:03,451 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_183] in [97ms].
15:09:03,568 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_182] in [116ms].
15:09:03,684 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_181] in [115ms].
15:09:03,814 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_188] in [130ms].
15:09:03,955 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_187] in [140ms].
15:09:04,112 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_186] in [157ms].
15:09:04,340 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_185] in [227ms].
15:09:04,453 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_140] in [112ms].
15:09:04,580 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_189] in [126ms].
15:09:04,738 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_149] in [157ms].
15:09:04,867 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_145] in [128ms].
15:09:05,012 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_146] in [144ms].
15:09:05,253 INFO  [AlertScannerThread] Alert condition [01f5f408-e4e6-46db-a4aa-53e4ac64deb4:MESSAGE_COUNT={time: 30, threshold_type: less, threshold: 1, grace: 5}, stream:={539d7eb4e4b0c901febebccd: "Pingback Watching"}] is triggered. Sending alerts.
15:09:07,993 INFO  [RebuildIndexRangesJob] Calculated range of [graylog2_147] in [2981ms].
```

**Comment by bryanhelmig** [comment] 2015-02-12 23:12
We too run into this on occassion.

**Comment by brandongalbraith** [comment] 2015-07-14 00:56
Has this been fixed in Graylog 1.1?

**Comment by zexxon** [comment] 2015-08-08 18:59
Brandon can you please test on 1.1? We haven't been able to reproduce the issue and none of our supported customers have run into this particular defect on 1.0+ that I am aware of.

**Comment by brandongalbraith** [comment] 2015-08-08 19:15
@zexxon Yep! I'll test on 1.1.6 and return with results. Thanks!

**Comment by bernd** [comment] 2016-02-26 11:55
Closing this. Please re-open if the issue still exists in Graylog 1.3.x or the upcoming 2.0. Thank you.

**Closed by bernd** 2016-02-26 11:55 UTC
Labels: bug

**Comment by bryanhelmig** [comment] 2016-02-26 15:22
We've not seen the issue with 1.3 since upgrading. 

-bryan

**Comment by bernd** [comment] 2016-02-26 15:51
@bryanhelmig Great, thank you for the feedback! :smiley:
