### ISSUE TITLE
JSON extractor does not work

### ISSUE THREAD

**Issue by flashfm** [Graylog2/graylog2-server#1489] opened 2015-10-15 18:36 UTC
It works when I click "Try" in the editor.
But it does not add new fields to events.
I tried to delete old indexes (in case there is conflict in data types of fields) - does not help.
Can it be a reason that my extracted JSON fields also has "Message" field (however starting with capital M)?
Just FYI, I also have "empty" fields when clicking "Try".

**Comment by bernd** [comment] 2015-10-22 10:12
I am unable to reproduce the problem with the following JSON message.

```json
{"hello":"world 3", "Message": "new message"}
```
![p8mkyw42nmucgaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/461/10662584/087c41a6-78b6-11e5-8e40-3d9d28a48946.png)

Can you show us an example message that does not work for you? Also please show us the configuration of your extractor. (maybe a screenshot)

Thank you!

**Comment by bernd** [comment] 2015-10-23 12:35
This might be related to #1475. Maybe you have fields with `null` values in your JSON payload. That would explain your problem.

Please test with the upcoming Graylog 1.2.2 where the `null` value problem will be fixed and re-open this issue if you still have problems. Thank you!

**Closed by bernd** 2015-10-23 12:35 UTC
