### ISSUE TITLE
Deflector exists as an index and is not an alias.

### ISSUE THREAD

**Issue by Cryptophobia** [Graylog2/graylog2-server#4355] opened 2017-11-15 21:40 UTC
## Expected Behavior
No errors

## Current Behavior
I get the error above when deploying `graylog2/server:2.3.2-2` with off-cluster AWS Elasticsearch to our Kubernetes cluster. 

## Possible Solution
I have searched every issue out there. Most say to stop graylog and delete the `graylog_deflector` index and start graylog back up. I have done this multiple times but the `graylog_deflector` index is recreated by graylog when it starts back up.

I have tried other solutions like setting a variable:
```
        - name: GRAYLOG_ELASTICSEARCH_DISCOVERY_ENABLED
          value: "false
```
as per issues that say that discovery_enabled needs to be set to false for aws elasticsearch.

This also does not work.

## Your Environment

* Graylog Version:  graylog2/server:2.3.2-2
* Elasticsearch Version: AWS elasticsearch 5.3
* MongoDB Version: mongo:3 image - 3.4.10
* Operating System: debian containers
* Browser version: any

Any help would be greatly appreciated.

**Comment by joschi** [comment] 2017-11-16 08:26
Duplicate of #4167.

**Closed by joschi** 2017-11-16 08:26 UTC
