### ISSUE TITLE
collector 0.4.2 exception in thread "ChunkProcessor" java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by frjhong** [Graylog2/graylog2-server#1909] opened 2016-03-08 04:04 UTC
### Problem description
When we use graylog collector 0.4.2 on Red Hat Enterprise 6.4, we sometimes meet exception in thread "ChunkProcessor" as below , then graylog collector can't send log to server util restarting collector.
### Steps to reproduce the problem
[collectorlog.txt](https://github.com/Graylog2/graylog2-server/files/162534/collectorlog.txt)
1. Start collector 0.4.2 , bin/graylog-collector run -f collector.conf
2.After a few hours , exception in thread "ChunkProcessor" occurs , such as below .Then graylog collector can't send log to server util restarting collector.(detail exception in attachment collectorlog.txt)

Exception in thread "ChunkProcessor" java.lang.IndexOutOfBoundsException: readerIndex(164) + length(1) exceeds writerIndex(164): CompositeByteBuf(ridx: 164, widx: 164, cap: 164, components=1)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1166)
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:570)
        at org.graylog.collector.file.splitters.NewlineChunkSplitter$1$1.computeNext(NewlineChunkSplitter.java:53)

### Environment

* Graylog Version:1.3.3
* Elasticsearch Version:1.7.3
* MongoDB Version:v2.4.9-rc0
* Operating System:Red Hat Enterprise Linux Server release 7.1 (Maipo)

**Comment by renapu** [comment] 2016-03-08 15:32
Graylog2/collector#78

**Comment by joschi** [comment] 2016-03-08 15:39
@frjhong Thanks for reporting this!
@renapu Good catch, thanks!

Closing this issue as duplicate of Graylog2/collector#78.

**Closed by joschi** 2016-03-08 15:39 UTC
