### ISSUE TITLE
Can graylog2 dashboard widget support embedded mode?

### ISSUE THREAD

**Issue by linkmancheng** [Graylog2/graylog2-server#3324] opened 2017-01-10 03:12 UTC
## Expected Behavior

We want to integrate graylog2 to our own portal, and doing the technical evaluation.
It will be great if the graylog2 widget in dashboard can have its own URL to embedded to our portal.

**Comment by dennisoelkers** [comment] 2021-08-23 08:17
Duplicate of #4313. Technical, this issue is older, but the other one contains more context.

**Closed by dennisoelkers** 2021-08-23 08:17 UTC
Labels: feature, triaged
