### ISSUE TITLE
Timerange Selector in Search should close when clicking outside of the selector

### ISSUE THREAD

**Issue by kmerz** [Graylog2/graylog2-server#17306] opened 2023-11-15 08:50 UTC
## Expected Behavior
After opening the timerange selector in a search:
<img width="944" alt="Bildschirmfoto 2023-11-15 um 09 45 52" src="https://github.com/Graylog2/graylog2-server/assets/448763/2b573fcd-6f30-4b95-8a72-3d5b5b554512">

Clicking outside of the pop up of the timerange selector for example on the search query field, should close the pop up.

## Current Behavior
The timerange selector stays open.

## Possible Solution
When registering a click outside of the pop up the timerange selector should close.

## Steps to Reproduce (for bugs)
1. Open the timerange selector on the search page.
2. Click out side of the timerange selector.

## Your Environment
* Graylog Version: 5.1 and 5.2

**Comment by Dev79844** [comment] 2024-01-29 14:55
Hello @kmerz! can you please assign me this task?

**Comment by vpathish** [comment] 2024-02-13 02:04
Hello @kmerz 
A Uni Student Here, Can I Work on this issue.

**Comment by Emy-01** [comment] 2024-03-13 19:34
@dennisoelkers has this been worked on?

**Comment by monrax** [comment] 2024-10-17 11:29
Hello! I was looking for a good first issue to contribute to, and I saw that this one was the only one tagged with `good-first-issue`. Front end is not my area of expertise, but I know the basics of React so I think this will be a good way to practice.

**Comment by monrax** [comment] 2024-10-17 11:46
Last week, together with @linuspahl we found out the solution was to assign the corresponding toggle function to the `onChange` prop of the Mantine Popover in `TimeRangePicker.tsx`, as the behavior for this component is [to close when clicked outside by default](https://mantine.dev/core/popover/#click-outside) -- the missing piece was a function to call whenever the state changed.

However, now when the "Save as preset" nested popover is clicked, the entire thing closes which is not the expected behavior. Attached you will find a short screen recording of this.

https://github.com/user-attachments/assets/cc7c217a-46b8-4d6c-b120-4df21c40843b

**Comment by monrax** [comment] 2024-10-17 12:08
After going through the docs a bit further, we realized [nested popovers require children to be rendered without portal](https://mantine.dev/core/popover/#nested-popovers). Thus, by adding `withinPortal={false}` to the Popover returned in `SaveTimeRangeAsPresetButton.tsx`, we should be able to prevent the parent popover from closing when the nested one is clicked.

It works, but for some reason the style changes when any part of the content of the nested popover is clicked, except for the input box and the submit and cancel buttons. Attached is a screen recording of this, as well.

https://github.com/user-attachments/assets/c93e2de9-163c-4660-bcea-d348dffa4b59

**Comment by monrax** [comment] 2024-10-18 08:37
I appears the style change is due to the button group overriding the declared property `position:absolute;` of the mantine popover. A workaround is to add the property to the nested popover.Dropdown through `style={{position: 'absolute'}}` in order for it to override it back.

This might not be the ideal solution, however. As @linuspahl noticed, this is a bug that is currently present in other places with a similar behavior. [An issue](https://github.com/mantinedev/mantine/issues/6992) has been opened in the mantine repo.

https://github.com/user-attachments/assets/283d0e42-3e1b-445c-888d-9382e0fb0f89

Same problem, elsewhere:

![Image](https://github.com/user-attachments/assets/fc95d0ea-b6ba-486f-a251-975cf2bbaff0)

**Comment by monrax** [comment] 2024-10-18 10:05
btw dear reader, if you, or anyone else would like to checkout the workaround -- here's the corresponding branch: [issue-17306-timerangepicker-popover](https://github.com/Graylog2/graylog2-server/tree/issue-17306-timerangepicker-popover)

**Comment by monrax** [comment] 2024-11-13 14:11
It ended up being a bug with [mantine](https://github.com/mantinedev/mantine/issues/6992). Thanks, @linuspahl !

**Closed** 2024-11-18 15:52 UTC
Labels: bug, triaged, to-verify, low hanging fruit, good first issue, User Experience
