### ISSUE TITLE
Migrate from High-Level to OpenSearch Java Client

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#17272] opened 2023-11-14 07:45 UTC
Starting with 3.0.0, the High-Level Client will be deprecated and not be supported anymore, so we need to migrate to the [new Java Client](https://opensearch.org/docs/latest/clients/java/) before.

**Comment by bernd** [comment] 2023-11-14 08:02
Duplicate of https://github.com/Graylog2/graylog2-server/issues/14788.

**Closed by bernd** 2023-11-14 08:02 UTC
