### ISSUE TITLE
CSV export fails with 404

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#2111] opened 2016-04-20 09:19 UTC
### Problem description
Apparently there are some issues exporting search results as CSV, from #1898: 

> FYI, I see this too, but with different symptoms
> 
> Under Firefox I get a warning
> 
> You are about to log in to the site "graylog2.trimble.com" with the username "e482ce63-0f1b-4d62-add3-c9acba4472ae", but the website does not require authentication. This may be an attempt to trick you.
> 
> Under Chrome I get no warning, but in both cases it returns a 404 and fails. I noticed the query begins with "//search", which I assume should have been "/search" - so maybe that's related
> 
> Jason

**Comment by bernd** [comment] 2016-04-21 12:21
I tried to reproduce this in Chrome and Firefox with Graylog 2.0.0-beta.4-SNAPSHOT (3c68141) without success. I also get the "You are about to log in to the site..." warning in Firefox, but the export works.

**Comment by bernd** [comment] 2016-04-21 12:37
I can see this error in the console when LDAP is enabled:

```
2016-04-21 12:27:19,686 ERROR: org.graylog2.security.realm.LdapUserAuthenticator - Error during LDAP user account sync. Cannot log in user null
java.lang.NullPointerException
        at java.lang.String.<init>(String.java:166) ~[?:1.8.0_74]
        at java.lang.String.valueOf(String.java:3008) ~[?:1.8.0_74]
        at org.graylog2.security.realm.LdapUserAuthenticator.doGetAuthenticationInfo(LdapUserAuthenticator.java:91) [graylog.jar:?]
        at org.apache.shiro.realm.AuthenticatingRealm.getAuthenticationInfo(AuthenticatingRealm.java:568) [graylog.jar:?]
        at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doMultiRealmAuthentication(ModularRealmAuthenticator.java:219) [graylog.jar:?]
        at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthenticate(ModularRealmAuthenticator.java:269) [graylog.jar:?]
        at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:198) [graylog.jar:?]
        at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106) [graylog.jar:?]
        at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:270) [graylog.jar:?]
        at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:256) [graylog.jar:?]
        at org.graylog2.shared.security.ShiroSecurityContext.loginSubject(ShiroSecurityContext.java:98) [graylog.jar:?]
        at org.graylog2.shared.security.ShiroAuthenticationFilter.filter(ShiroAuthenticationFilter.java:48) [graylog.jar:?]
        at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132) [graylog.jar:?]
        at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:318) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_74]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_74]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
```

The export still works though.

**Comment by bernd** [comment] 2016-04-21 13:26
The exception will be fixed in https://github.com/Graylog2/graylog2-server/pull/2123

The warning in Firefox is because the CSV export puts the username and password into the URL of the request.

**Closed** 2016-04-21 13:42 UTC
