### ISSUE TITLE
Unclear behaviour of search buttons

### ISSUE THREAD

**Issue by pirona** [Graylog2/graylog2-server#6717] opened 2019-11-04 13:54 UTC
I'm not sure how to put it because it is surely not a bug. I'm unsure of the use initially intended for the search button, next to graylog logo in the interface, which is only available to admin users.
I developed a workflow which is ok for me :
- graylog logo (start page)  sends a dashboard
- search button goes to all messages

## Expected Behavior
Search button should be accessible to everyone, or at least it should be possible to make it accessible to everyone.

## Current Behavior
Search is only accessible to admins. There are two urls to access the same data and I'm not sure why.
https://example.com/search
https://example.com/streams/000000000000000000000001/search

Consequence is : if I spot something interesting by searching via search button, I cannot send the url to non-privileged users because they can't access the search url.

## Possible Solution
Make the search available to everyone ? 

## Steps to Reproduce (for bugs)
not relevant

## Context
By developing a workflow for my company.

## Your Environment
not relevant as it is not really a technical issue.

Thanks for all the work you're doing.

**Comment by dennisoelkers** [comment] 2020-02-20 13:31
@pirona: thanks for getting in touch with us! I have a couple of questions to understand your request, it would be great if you could get back to us:

  * What do you mean when you say `graylog logo (start page) sends a dashboard`?
  * What are the roles/permissions of your non-admin user which is not able to access search?

**Comment by pirona** [comment] 2020-02-20 13:45
Hello,

Thanks for your interest in this.

>     * What do you mean when you say `graylog logo (start page) sends a dashboard`?
Sorry, I'll rephrase this : my default startpage is a dashboard, so when I click on the graylog logo in upperleft corner, I'm sent to this dashboard's page
>     * What are the roles/permissions of your non-admin user which is not able to access search?
- Views User, 
- Reader, 
- lecture_all is a role I created which allows reading permissions on all streams and dashboards
- Archive Viewer

**Comment by dennisoelkers** [comment] 2020-02-25 13:50
Thanks for getting back to us, @pirona!

So the issue is that this user does not see the `Search` link in the top navigation bar? If yes, which Graylog version are you using?

**Comment by pirona** [comment] 2020-02-25 13:53
Yes, non-admin users do not see the search link in the top navigation bar.
I'm using 3.1.4 and I'm not planning to update right now.

**Comment by dennisoelkers** [comment] 2020-02-26 09:45
Do your user have the `searches:absolute`, `searches:relative`, `searches:keyword` permissions? These are required to see and use the `Search` navigation link.

**Comment by pirona** [comment] 2020-02-26 09:49
Hello, I checked the documentation (maybe poorly) and I really have no idea where to check nor set those values.

**Comment by pirona** [comment] 2020-02-26 10:30
Maybe through the API, the one thing I didn't check :)

**Comment by dennisoelkers** [comment] 2020-02-26 12:13
You are welcome! If this issue has been solved for you, please close it, thanks! :)

**Comment by pirona** [comment] 2020-02-26 12:28
Solved by using API and values searches:absolute, searches:relative, searches:keyword

**Closed** 2020-02-26 12:28 UTC
Labels: feature, search, triaged
