### ISSUE TITLE
Confusing behaviour when opening a stream without having reader permissions

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#2082] opened 2016-04-14 21:17 UTC
When you have a user that has `read` permission on a stream but does not have the `reader` role, then that user can click on the stream in the streams list but will immediately be redirected back to the streams list instead of seeing the messages in the stream. I guess the reason is that the `reader` role brings the required `search:relative` etc permissions.

This is technically correct but still confusing for the user. It took me a while to figure out what was going wrong.

Maybe we can display an error message that points the user to the cause of this?

**Comment by kroepke** [comment] 2016-04-18 09:19
@lennartkoopmann How can a user not have at least the reader role?

If that happened there is a pretty serious bug somewhere.

**Comment by bernd** [comment] 2016-07-05 12:29
@lennartkoopmann ping

**Comment by kroepke** [comment] 2016-07-27 14:51
@lennartkoopmann ping again, otherwise I'd close this issue during next bug triage

**Comment by bernd** [comment] 2016-08-03 09:23
Closing this because no feedback has been received, please re-open if this is still a problem. Thank you!

**Comment by kkamkou** [comment] 2016-11-02 13:35
Confirmed, the same (`2.1.1`). `Reader` permission is required. Reproduce:
- create a new role, assign one stream to it
- create a new user, assign only this role
- log-in as this user. Go to streams and try to open it. Or just look at your own profile.

```
https://xxx/api/system/cluster_config/org.graylog2.indexer.searches.SearchesClusterConfig Failed to load resource: the server responded with a status of 403 (Forbidden)
FetchProvider.js:17There was an error fetching a resource: cannot GET https://xxx/api/system/cluster_config/org.graylog2.indexer.searches.SearchesClusterConfig (403). Additional information: User [xxx] not authorized. (GET api/system/cluster_config/org.graylog2.indexer.searches.SearchesClusterConfig)t @ FetchProvider.js:17
vendor.js:36 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the AppWithSearchBar component.r @ vendor.js:36
bluebird.js:953Unhandled rejection Error: cannot GET https://xxx/api/system/cluster_config/org.graylog2.indexer.searches.SearchesClusterConfig (403)
```

And so on. Also there is a lot of `unhandled rejections`. hence, another ticket might be created about: "to handle 403 response".

**Comment by kroepke** [comment] 2016-11-02 13:37
The server should refuse to remove the reader role from users that don't have the admin role.
It is essential for things to work.

**Comment by kroepke** [comment] 2017-01-12 13:33
This has been fixed in https://github.com/Graylog2/graylog2-server/pull/3337, please see  https://github.com/Graylog2/graylog2-server/issues/2116

**Closed by kroepke** 2017-01-12 13:33 UTC
Labels: bug, triaged
