### ISSUE TITLE
Time Stamps Reporting Wrong

### ISSUE THREAD

**Issue by nilator83** [Graylog2/graylog2-server#3706] opened 2017-04-15 00:07 UTC
## Expected Behavior
Timestamps are not reflected with the desired timezone.

## Current Behavior
User, Browser, Graylog server all are set to America/Denver time zone. But I have one particular stream where to timestamps are coming in correct  on the message but graylog timestamps it as 6 hours behind. Yes I have tried the force override option in the input section.

## Steps to Reproduce (for bugs)
Here is a screenshot of the time setting referenced above.

<img width="376" alt="screen shot 2017-04-14 at 5 45 59 pm" src="https://cloud.githubusercontent.com/assets/17769644/25058818/d84dd056-213a-11e7-9ff9-f848da61821d.png">

Here you can see it comes in the message with the correct time. You can also hover over the graylog timestamp and is shows it as the same as the message, however it is not being interpreted correctly. 

<img width="1471" alt="screen shot 2017-04-14 at 5 56 16 pm" src="https://cloud.githubusercontent.com/assets/17769644/25058889/cd45f458-213b-11e7-9763-d97f9eaa2a65.png">

## Context
Its putting the graphs and charts all logs for that matter off by 6 hours.

## Your Environment

* Graylog Version: Graylog 2.2.3+7adc951
* Elasticsearch Version: 2.4.4
* MongoDB Version:3.2.12
* Operating System: Ubuntu Server 16.04LTS (Linux 4.4.0-62-generic)
* Browser version: Firefox, Chrome, Safari

**Comment by joschi** [comment] 2017-04-16 11:04
Duplicate of #2689.

**Closed by joschi** 2017-04-16 11:04 UTC

**Comment by nilator83** [comment] 2017-04-19 18:39
Well since this is not considered to be a bug. How would one go about ensuring that when setting user, web browsers and graylog server to mountain time that graylog does not think it 6 hours behind?

**Comment by gnu08** [comment] 2017-04-20 07:11
Well it look really a bug 
Graylog Version: Graylog  2.2.3+7adc951
Elasticsearch Version: 2.4.4
MongoDB Version:3.2.12
Operating System: Debian Linux 8

Tried on 3 systems running 2.2.2 without issues. Upgraded to 2.2.3, rebooted > wrong timestamps (as we can see on my screenshot (upgraded at 09:42:00 then I get 2 hour off)
![bug-graylog](https://cloud.githubusercontent.com/assets/27802041/25217965/47aabcf8-25a9-11e7-8b3c-5457e7f5da5b.PNG)
