### ISSUE TITLE
Outputs do not work with "All messages" stream

### ISSUE THREAD

**Issue by dbernaci** [Graylog2/graylog2-server#3919] opened 2017-06-16 10:08 UTC
I have configured output plugin (for example GELF or Syslog Output Plugin). I'm trying to associate default stream "All messages" with this Output, but it does not work. If I create another stream that includes all messages and configure Manage output with this configured Output it works correctly.

## Expected Behavior

Stream "All messages" output  should go to syslog server

## Current Behavior

I don't receive any messages from graylog on configured syslog server

## Steps to Reproduce (for bugs)

1. Configure Manage Outputs for Stream "All messages" with Syslog output 
2. Verify log received on syslog server 

## Your Environment

* Graylog Version: Graylog v2.2.3

**Comment by bernd** [comment] 2017-06-21 13:29
I was able to reproduce this. The problem is that the default "all message stream" gets loaded in the `DefaultStreamProvider` when Graylog starts. If the users adds an output to the default stream, the instance in the `DefaultStreamProvider` does not get updated.

We could fix this by adjusting the `OutputRouter` and `OutputRegistry` to lookup the actual output for a stream instead of relying on the stream instance inside the message to have the correct list of outputs.

**Comment by jalogisch** [comment] 2017-06-26 09:16
we could verify that and the current workaround would be to restart the Graylog server.

**Comment by bernd** [comment] 2017-06-28 11:49
I am moving this out of the 2.3 milestone, it will not make it.

**Comment by kiview** [comment] 2017-09-07 15:31
I'm not sure if this bug is related, but if the configured output of the `All messages` stream does not work correctly, Graylog won't process any messages received. 

I.e. when getting this error:
```
2017-09-07T17:26:08.647+02:00 ERROR [GelfTcpTransport] Connection failed: Connection refused: XXXXX
```

the journal will fill up without processing the messages.

**Comment by joschi** [comment] 2017-09-08 06:47
@kiview This is a different issue.

Make sure that the configured receiver in the GELF output is available.
Messages will only be deleted from the journal if all outputs were successful.

**Comment by kiview** [comment] 2017-09-08 08:44
I see, is this desired behavior or an issue? In our case, this would mean the All messages stream would effectively stop working if the the external resource we are outputting the stream to is not available. 
I could understand having kind of a transactional boundary around this, just wondering if this is an intentional design choice.

**Comment by joschi** [comment] 2017-09-08 08:48
@kiview See #966

**Comment by thll** [comment] 2022-03-02 16:32
This is working now. I think it was resolved with https://github.com/Graylog2/graylog2-server/pull/4752.

**Closed by thll** 2022-03-02 16:32 UTC
Labels: bug, triaged
