### ISSUE TITLE
Message window is duplicating labels

### ISSUE THREAD

**Issue by samupr** [Graylog2/graylog2-server#8463] opened 2020-07-01 15:43 UTC
When I open a Graylog message, I see the labels all duplicated. This started happening immediately after I upgraded to this version.

![image](https://user-images.githubusercontent.com/52700349/86264073-f7dcad80-bbb9-11ea-924f-32d2d7d01aa1.png)

* Graylog Version: Graylog 3.3.2+ade4779
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Centos 7 X86/64
* Browser version: Chrome 83.0.4103.116

**Comment by dennisoelkers** [comment] 2020-07-02 07:31
Hey @samupr, thanks for reporting this!

Can you please do the following:

1.) Clear your browser's cache and try again
2.) While trying to reproduce this issue, could you please check your browser's JS console to check for potential errors?

**Comment by samupr** [comment] 2020-07-03 14:57
1) Tried that and didn't help
2) No errors in console
I have also reproduced it in New Edge and IE browsers

**Comment by dennisoelkers** [comment] 2020-07-08 12:48
It looks like we are already tracking this issue. We are already working on a fix, which will land in one of the next versions.

Duplicate of #8483.

**Closed by dennisoelkers** 2020-07-08 12:48 UTC
Labels: bug
