### ISSUE TITLE
Using extractor causes data to no longer be viewable/searchable.

### ISSUE THREAD

**Issue by juliovalcarcel** [Graylog2/graylog2-server#1915] opened 2016-03-08 17:17 UTC
### Problem description

When adding an extractor to a GELF TCP input stream the data disappears. I have tried sending valid JSON objects using graylog-collector which are received ok if there are no extractors but when I try to apply the JSON extractor and use the try button it successfully matches but then when I save it my logs do not show up at all in the search. The same thing with Grok patterns. 

### Environment

* Graylog Version: 1.3.3
* Elasticsearch Version: 1.7.5
* MongoDB Version: 2.6.11
* Operating System: Centos 7

**Comment by joschi** [comment] 2016-03-08 17:27
@juliovalcarcel Please add some example messages and the exact extractor configuration you're using.

**Comment by juliovalcarcel** [comment] 2016-03-08 18:20
@joschi 

**Example Apache Access Log:**
```192.168.1.1 - - [08/Mar/2016:13:10:42 -0500] "GET / HTTP/1.1" 200 21620 "-" "check_http/v2.0.3 (nagios-plugins 2.0.3)"```

Using the %{COMMONAPACHELOG} grok pattern with copy setting (note i have tried the cut setting with no success). 

%{COMMONAPACHELOG} is from https://grokdebug.herokuapp.com/patterns#

I also have it set to "always try to extract"

**Comment by joschi** [comment] 2016-03-09 08:17
Try replacing the field name in `%{HTTPDATE:timestamp}` in the `COMMONAPACHELOG` grok pattern with another name. The `timestamp` field is required to have a very specific format.

Closing as duplicate of #1647.

**Closed by joschi** 2016-03-09 08:17 UTC

**Comment by juliovalcarcel** [comment] 2016-03-09 14:53
@joschi Following the solution on #1647 solves the problem with Grok, but when trying to use the JSON extractor on 
```{ "version": "1.1", "host": "192.168.1.1", "short_message": "GET / HTTP/1.1", "timestamp": 1457535036, "level": 6, "_user_agent": "check_http/v2.0.3 (nagios-plugins 2.0.3)", "_source_ip": "1.2.3.4", "_duration_usec": 114392, "_duration_sec": 0, "_request_size_byte": 23891, "_http_status": 200, "_http_request_path": "/", "_http_request": "/?path=/", "_http_method": "GET", "_http_referer": "-" }```

matches when testing but does not show up. Is that because of the timestamp field again?

**Comment by joschi** [comment] 2016-03-10 10:12
> matches when testing but does not show up. Is that because of the timestamp field again?

Yes. Please refer to http://docs.graylog.org/en/2.0/pages/gelf.html for a specification of the GELF protocol which also describes how the `timestamp` field has to look like.
