### ISSUE TITLE
Aggregation Metrics Function 'Latest Value' returns no value or N/A

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#13596] opened 2022-10-03 18:32 UTC
I'm not sure if this is user error, but when attempting to configure a widget with a metric function 'Latest Value', i get no results from the aggregation. All other functions return values.

Average:
![image](https://user-images.githubusercontent.com/107503402/193651772-9a9f1eb7-da47-4292-9d6a-54cf29fbdbb0.png)

Latest Value:
![image](https://user-images.githubusercontent.com/107503402/193651818-a8d41156-080d-42a3-831d-e6d776dae526.png)

## Expected Behavior

Latest value returns the most recent value available in the search time range.

## Current Behavior

No results are returned.

## Steps to Reproduce (for bugs)

1. Create a widget
2. Add a metric for a field that has values
3. Set function to `Latest Value`
4. Observe the result says `N/A`

## Context

My understanding is this is meant to solve the issue where you may want a dashboard in graylog that shows the latest/current value of a given metric. Without this its required to set a small time range (adjusted by how often there are new values logged to graylog) and use something like the average function.

## Your Environment

* Graylog Version: Graylog 4.3.7+05bccc7
* Java Version: 11.0.16
* Elasticsearch Version: Opensearch 1.3.4
* MongoDB Version: 4.4.15
* Operating System: Ubuntu Server 20.04 LTS
* Browser version: Chrome 106.0.5249.61

**Comment by drewmiranda-gl** [comment] 2022-10-03 18:33
Possibly related https://github.com/Graylog2/graylog2-server/issues/13593

**Comment by dennisoelkers** [comment] 2022-10-10 11:46
Hey @drewmiranda-gl,

I am unable to reproduce this issue. Maybe we can narrow down the root cause if you create a messages widget for the same time range and check the values of the field in the messages?

**Comment by drewmiranda-gl** [comment] 2022-10-12 16:26
Looks like the issue is if the search query for the widget is empty, you get `NA` but you specify a search query it works as expected.

![image](https://user-images.githubusercontent.com/107503402/195397289-577afcaf-37fd-4d7f-8111-b23c96eace11.png)

![image](https://user-images.githubusercontent.com/107503402/195397324-2d8ebea0-6413-4da9-b815-a51a3492c7b3.png)

My guess is this is working as designed. My guess is widgets should always have a search query defined as a best practice.

**Comment by luk-kaminski** [comment] 2022-11-10 10:43
Hi @drewmiranda-gl ,

It seems that in the first case the latest value does not have "aq_co2" field present. That's why you get N/A.
If you use "_exists_:aq_co2" query, all messages, including the lastest message, will have a value and you will never receive N/A.

I'd vote for closing this issue, I cannot see any bug here.

**Closed** 2023-03-01 09:42 UTC
Labels: bug, triaged
