### ISSUE TITLE
Graylog 2 Beta - Add to search query button not working

### ISSUE THREAD

**Issue by tbmay** [Graylog2/graylog2-server#2075] opened 2016-04-13 22:22 UTC
### Problem description
I just spent a few minutes looking at the ova appliance for the beta and the button for "Add to search query" didn't work.  Nothing was added and the up arrow that shows up in 1.3 doesn't show up.
### Steps to reproduce the problem

1. Import the version 2 beta 2.1 into virtual box.
2. Click the "Add to search button" on anything.

### Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by jhaar** [comment] 2016-04-14 01:49
Me too. This is a problem with v2.0 in general - not the OVA

I am assuming this refers to the little magnifying glass button that you used to be able to click on under graylog-1.3 to make it show up as a search term at the top. That is no longer working with at least 2.0.0-3.beta.2 and today's 2.0.0-3.beta.3-SNAPSHOT

**Comment by tbmay** [comment] 2016-04-14 02:28
Yes it is the little magnifying glass.  I doubted it was specific to the
OVA but since that's all looked at with version 2 I wanted to mention it.
I have 1.3 installed in production and that feature works fine.

On Wed, Apr 13, 2016 at 9:49 PM, Jason Haar <notifications@github.com>
wrote:

> Me too. This is a problem with v2.0 in general - not the OVA
>
> I am assuming this refers to the little magnifying glass button that you
> used to be able to click on under graylog-1.3 to make it show up as a
> search term at the top. That is no longer working with at least
> 2.0.0-3.beta.2 and today's 2.0.0-3.beta.3-SNAPSHOT
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Graylog2/graylog2-server/issues/2075#issuecomment-209718912>
>



-- 
Tim May
Laurens County School District 55
e.  tbmay@laurens55.org
o.  864.681.3627
c.  864.939.8292

-- 
*Confidentiality Notice* | This e-mail message, including any attachments, 
is for the sole use of the intended recipient(s) and may contain 
confidential information. Any unauthorized review, use, disclosure or 
distribution is prohibited. If you are not the intended recipient, 
immediately contact the sender by reply e-mail and destroy all copies of 
the original message.

**Comment by bernd** [comment] 2016-04-14 07:46
@tbmay @jhaar The issue has been fixed in 2.0.0-beta.3. Please try with 2.0.0-beta.3 which has been released yesterday (but not announced yet).

* OVA - https://packages.graylog2.org/releases/graylog-omnibus/ova/graylog-beta-2.0.0-beta.3-1.ova
* TGZ - https://packages.graylog2.org/releases/graylog/graylog-2.0.0-beta.3.tgz

 Duplicate of #2040 and #2067.

Closing this, please re-open if you still have problems with beta.3.

**Closed by bernd** 2016-04-14 07:46 UTC
