### ISSUE TITLE
Filebeat input causes continuous errors

### ISSUE THREAD

**Issue by mortrom** [Graylog2/graylog2-server#4562] opened 2018-02-05 01:42 UTC
With a fresh instance of the docker based graylog server, and having done nothing else than login, the launching of a new Beats input (shipped with the image) immediately triggers a never ending flow of repeated Java exceptions.  No Beats forwarder is required for this issue to occur.

In short the main error is one of the two following;

```
java.lang.Exception: Unknown beats protocol version: 69
java.lang.Exception: Unknown beats protocol version: 71
```

Attached a file with the full stack trace of the above...

[graylog-error.log](https://github.com/Graylog2/graylog2-server/files/1693573/graylog-error.log)

There appears to be no impact on functionality - a Flebeat forwarder is able to communicate and the logs appear correctly.

However, when looking at the detail portion of the input screen for the filebeat plugin the active connection count is followed by a total which keeps increasing. 

![screen shot 2018-02-05 at 11 47 51 am](https://user-images.githubusercontent.com/26054156/35785061-902d69c8-0a71-11e8-94d8-6bf02018b1a4.png)

## Expected Behavior
Launching the included filebeat input should not result in a flood of Java exceptions.

## Current Behavior
Continuous Java exceptions.  See file attachment.

## Possible Solution
None to suggest. 

## Steps to Reproduce (for bugs)

1. Run the graylog container for the first time.
2. Login in the normal way
3. Go to top menu bar > System/Inputs > Inputs
4. Select Input Beats
5. Launch New Input
6. Watch the active connections total climb continuously, or goto the graylog server logs to see the Java exceptions.

## Context
There is currently no obvious  impact other than the overhead to produce the errors.
The concern is that this will cause problems in the future, particularly under load, and require regular restarts.

## Your Environment
* Graylog Version: 2.4.3-1
* Elasticsearch Version: 5.6.6
* MongoDB Version: 3.6.2
* Operating System: Ubuntu 16.04 LTS
* Docker: 17.06.2-ce
* Browser version: Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by dennisoelkers** [comment] 2018-02-05 08:32
Thanks for reporting this. This probably happens because something is connecting to the filebeats port sending something else than the beats protocol. The error you are seeing occurs when the first byte of a connection to that port does not equal to the character '2', which is the current beats protocol version.

As this is not a bug, I am closing this issue. if you are conviced that I am mistaken, please reopen the issue.

**Closed by dennisoelkers** 2018-02-05 08:32 UTC

**Comment by admover** [comment] 2018-03-06 02:28
Hi,
I have the issue too, please help me.

**Comment by joschi** [comment] 2018-03-06 08:38
@admover Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
