### ISSUE TITLE
"NaN" in index set field type refresh interval setting

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#4965] opened 2018-07-31 02:33 UTC
When creating a new index set, the field type refresh interval setting shows `NaN`:

![screenshot from 2018-07-30 21-31-04](https://user-images.githubusercontent.com/35022/43434143-17928b0c-9440-11e8-8b99-3a243edb89ef.png)

* Graylog Version: 3.0.0-alpha.2-SNAPSHOT+07766b9

**Comment by bernd** [comment] 2018-07-31 09:27
Duplicate of https://github.com/Graylog2/graylog2-server/issues/4724

**Closed by bernd** 2018-07-31 09:27 UTC
Labels: bug
