### ISSUE TITLE
Possible regression in 5.2 due to migration V20230629140000_RenameFieldTypeOfEventDefinitionSeries

### ISSUE THREAD

**Issue by patrickmann** [Graylog2/graylog2-server#17551] opened 2023-12-01 16:15 UTC
A user [encountered](https://community.graylog.org/t/welcome-page-ioexception-encountered-while-reading-from-a-byte-array-input-stream/30834) a jackson error when upgrading from 5.1 to 5.2, due to a missing field.

> Caused by: com.fasterxml.jackson.databind.JsonMappingException: Null field
>  at [Source: de.undercouch.bson4jackson.io.LittleEndianInputStream@7731d550; pos: 390] (through reference chain: org.graylog.events.processor.$AutoValue_EventDefinitionDto$Builder["config"]->org.graylog.events.processor.aggregation.AutoValue_AggregationEventProcessorConfig$Builder["series"]->java.util.ArrayList[0]->org.graylog.plugins.views.search.searchtypes.pivot.series.AutoValue_Cardinality$Builder["field"])

Looks like the field was renamed in https://github.com/Graylog2/graylog2-server/pull/15863 and the migration does not cover all instances.

**Comment by thll** [comment] 2023-12-01 16:28
@patrickmann: is that a duplicate of https://github.com/Graylog2/graylog2-server/issues/17367 or a separate issue?

**Comment by patrickmann** [comment] 2023-12-05 08:30
Closing as dupe of #17367
Problem turned out to be a function that used `card()` instead of `count()`.

**Closed** 2023-12-11 09:25 UTC
Labels: bug, triaged, needs-backport
