### ISSUE TITLE
Is there a plan to support elasticsearch 7.x?

### ISSUE THREAD

**Issue by happyyangyuan** [Graylog2/graylog2-server#7649] opened 2020-03-09 09:24 UTC
## Why?

To match our existing elasticsearch 7.x

## Your Environment

* Graylog Version: 3.x
* Elasticsearch Version: 7.x

**Comment by florianvolle** [comment] 2020-03-09 10:02
Duplicate of #5933

**Closed by florianvolle** 2020-03-09 10:02 UTC
Labels: feature
