### ISSUE TITLE
Java 11 + Graylog 3.1 + TLS = No web interface

### ISSUE THREAD

**Issue by chris-y** [Graylog2/graylog2-server#6306] opened 2019-08-16 14:58 UTC
## Expected Behavior
Web interface works the same when running under Java 11 as it does under Java 8

## Current Behavior
Web interface doesn't load.  The furthest I can get is:
![image](https://user-images.githubusercontent.com/1818803/63176207-69ad1680-c03d-11e9-9e27-86d2d2eea3d3.png)
although I think it is only getting this far due to an old cached page.  If I open in a new browser it just fails to load anything.
As far as I can tell the backend is working fine and there are no obvious errors in the logs beyond the warnings mentioned in #5909 

## Steps to Reproduce (for bugs)

1. Install JRE 11
2.  update-alternatives --config java
3. Select  /usr/lib/jvm/java-11-openjdk-amd64/bin/java
4. systemctl restart graylog-server
5. Open web interface

## Context

Wanting to upgrade the server to Java 11 LTS as Elasticsearch is already using this version.

## Your Environment

* Graylog Version: 3.1
* Elasticsearch Version: 6.8.2
* MongoDB Version: 3.6.3
* Operating System: Ubuntu 18.04 LTS
* Browser version: Firefox 68 (although doesn't work in anything else either)

**Comment by mpfz0r** [comment] 2019-08-16 15:02
Are you sure the server is running at all?

I guess you need: https://github.com/Graylog2/fpm-recipes/pull/87

**Comment by chris-y** [comment] 2019-08-16 19:19
It seems to be running fine other than the web interface, I can see failed lookups appear in the logs but can't get on the interface. I already removed that option.

**Comment by mpfz0r** [comment] 2019-08-19 09:03
I can confirm this bug, but only if TLS is enabled. Do you have TLS enabled?

**Comment by chris-y** [comment] 2019-08-19 09:05
Yes, I do.

**Comment by mpfz0r** [comment] 2019-08-19 09:40
This seems to be related to: https://github.com/eclipse-ee4j/grizzly/issues/2075

If I downgrade to TLSv1.1 it works.

**Comment by mpfz0r** [comment] 2019-10-08 07:58
Since grizzly doesn't seem to care about the issue, I went and checked alternatives:

 - Using `jersey-container-netty-http` is not a viable option since it lacks support for Request injection.
- Next up would be Jetty

However, someone states that Java 12 doesn't have this issue, but that's not an LTS release, so :/

**Comment by chris-y** [comment] 2019-12-18 16:09
I noticed there was an update to JRE 11 - 11.0.5+10-0ubuntu1.1~18.04 - so I thought I'd give this another try, given that the reports suggest it might be a Java issue.
Additionally I'm now using Graylog 3.1.3

It worked... for about two minutes... before failing.
So this is still an issue unfortunately.

**Comment by strangedev** [comment] 2020-01-22 10:27
I can also confirm this bug on `Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux` using Graylog `3.1.0-1.beta.1` installed from the repository at `https://packages.graylog2.org/repo/debian/ stable 3.1`.
I am running OpenJDK build `11.0.6+10-post-Debian-1deb10u1` (Debian 10 does not include package sources for older versions of JDK by default).

**Comment by hulkk** [comment] 2020-06-17 12:51
Any updates regarding Java 11 support?

**Comment by mpfz0r** [comment] 2020-06-17 13:14
@hulkk not really. Grizzly seems to be a dead project, which we'd have to migrate away from.
As a workaround, you could terminate TLS on a web proxy and run graylog using http only.

**Comment by mpfz0r** [comment] 2020-11-09 17:32
This seems to finally have been fixed. opendk-11 `11.0.9+11-1~deb10u1` on Debian 10 works without Problems :partying_face: 

I haven't checked the changelog yet to spot the actual fix.

**Comment by chris-y** [comment] 2020-11-10 09:35
Ubuntu 20.04 version `11.0.9+11-Ubuntu-0ubuntu1.20.04` confirmed as working here too, nice spot!

**Comment by mpfz0r** [comment] 2020-11-10 10:32
Just confirmed that this got fixed in `11.0.8`  
https://bugs.openjdk.java.net/browse/JDK-8209333

**Comment by mpfz0r** [comment] 2020-11-11 13:52
Finally fixed with using `-Djdk.tls.acknowledgeCloseNotify=true`  (see #9445)

**Closed by mpfz0r** 2020-11-11 13:52 UTC
Labels: bug, infrastructure, java9, triaged
