### ISSUE TITLE
Hide dashboards that reference streams a user doesn't have access to 

### ISSUE THREAD

**Issue by asachs01** [Graylog2/graylog2-server#9867] opened 2021-01-05 14:48 UTC
## What?

Z-4466 references this issue, but it's best summed up in this:

```
In Graylog 4.0, I am trying to hide a dashboard if a user does not have access. Because you have to have the "Reader" role to access the web UI, all dashboards are showing up. I do know that the user cannot see anything in the dashboard if they do not have access to stream the dashboard is using but they still see the it. How do I change this behavior.
```

**Comment by matt-fairway** [comment] 2021-01-07 18:12
In Graylog 3.3.9, if you are a member of the "Reader" group only, by default, you cannot see anything. No streams, alerts, or dashboards. You have to create a new role, and add "Allow Reading" or "Allow Editing" to see the stream or dashboard. In Graylog 4.0.1, that behavior is different. If you are a member of the "Reader" group (the default), you do not see all streams but you can see all dashboards, you just cannot open them because you will get an error [Missing Stream Permissions]. That is the regression and will confusion for users who should not even see the dashboards.

**Comment by matt-fairway** [comment] 2021-01-13 20:58
For anyone coming here who is experiencing this issue, I think I understand why it is happening

Fix:
_If you have created a custom Graylog role with the ability to create new dashboards (this can be done with the API), remove those roles from the user._

Explanation:
Prior to Graylog 4, you were unable to create a dashboard unless you were an admin or had the create dashboard permission assigned to you or to a role you are in. The only way to do the latter was with the API. Depending on how you set up that permission, you could end up seeing everything.

Problem resolved.

**Closed** 2021-01-13 21:47 UTC
Labels: bug, triaged
