### ISSUE TITLE
Export to CSV is showing timestamp of GMT even though users changed their timezone to EST.

### ISSUE THREAD

**Issue by juesor** [Graylog2/graylog2-server#4786] opened 2018-05-11 15:39 UTC
## Expected Behavior

The timezone should export the users value based on timestamp of log message not GMT.

## Current Behavior

Currently if i search for logs and want to export to CSV i am stuck with GMT time.  This is not helpful.  I have a second option on the left to select timestamp and this will show a second time stamp on the right but this timestamp is in GMT.  Why is that being exported instead of the already viewable EST timestamp of the log?

## Possible Solution

I have no idea how graylog is doing the calculation on timestamp per log but since you give the users the ability to change their timezone please be persistent with that time.

## Steps to Reproduce (for bugs)

1. Search for messages
2. Export to CSV
3. Open CSV 
4.

## Context

My users are not happy with me that they cannot see log messages correctly.  Not everyone lives in one timezone so not providing that as an option to export to CSV doesn't make graylog useful.

## Your Environment

* Graylog Version: 2.4.4-1
* Elasticsearch Version: 2.4.6-1
* MongoDB Version: 3.2.9-1.el7
* Operating System: CentOS Linux release 7.4.1708 (Core)
* Browser version: Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by joschi** [comment] 2018-05-12 08:12
Duplicate of #4523

**Closed by joschi** 2018-05-12 08:12 UTC
