### ISSUE TITLE
"Show messages" button doesn't work for all collectors

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#5045] opened 2018-08-30 20:52 UTC
I'm running my own Metricbeat collector configuration and the "Show messages" button leads to an empty search result because there is no field `gl2_source_collector` set.

**Comment by bernd** [comment] 2018-08-31 06:51
With the old sidecar system, we had more control over the generated collector configurations and so we automatically added the `gl2_source_collector` field. In the new system, users write the config files on their own and we have basically no control over the generated config.

That means users have to add the `gl2_source_collector` field on their own. We should probably extend our default collectors with a usable default configuration template that includes the `gl2_source_collector` field and set it to `${nodeId}`.

**Comment by bernd** [comment] 2018-08-31 06:52
This issue is also a duplicate of https://github.com/Graylog2/graylog-plugin-collector/issues/88 :wink:

**Comment by edmundoa** [comment] 2018-08-31 08:58
I'll leave this one open, as this is in the end the new home of the sidecar :)

**Comment by mpfz0r** [comment] 2018-09-24 15:28
We did not configure our beats collectors with `fields_under_root`

cf https://www.elastic.co/guide/en/beats/filebeat/6.2/configuration-filebeat-options.html#configuration-fields

That's why it is prefixed with `fields_` by default. I suggest we change the "Show messages"
 link to  `fields_gl2_source_collector`.

As for the new sidecars, see https://github.com/Graylog2/collector-sidecar/issues/297

**Comment by mpfz0r** [comment] 2018-10-11 12:32
https://github.com/Graylog2/graylog2-server/pull/5197

We solve this with a 3-liner that can be included in any beats configuration.
We provide it via the default template.
I think that's all we can do for now. Closing this.

**Closed by mpfz0r** 2018-10-11 12:32 UTC
Labels: bug, needs-discussion, sidecar, triaged
