### ISSUE TITLE
EmailAlarmCallback fails to send, DummyAlert works

### ISSUE THREAD

**Issue by traviscosgrave** [Graylog2/graylog2-server#868] opened 2015-01-13 22:25 UTC
When an alert is triggered by a stream I get the following error message:

    2015-01-13 17:20:01,990 ERROR: org.graylog2.alarmcallbacks.EmailAlarmCallback - Stream [54b43f6ce4b0c6ea4d03cf4d: "Spotlight POC on JBoss7 - ERRORS"] has alert receivers and is triggered, but sending emails failed
    org.apache.commons.mail.EmailException: Sending the email to the following server failed : my.emailserver.com:25
            at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1410)
            at org.apache.commons.mail.Email.send(Email.java:1437)
            at org.graylog2.alerts.StaticEmailAlertSender.sendEmail(StaticEmailAlertSender.java:101)
            at org.graylog2.alerts.StaticEmailAlertSender.sendEmails(StaticEmailAlertSender.java:213)
            at org.graylog2.alarmcallbacks.EmailAlarmCallback.call(EmailAlarmCallback.java:80)
            at org.graylog2.periodical.AlertScannerThread.doRun(AlertScannerThread.java:105)
            at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:83)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
            at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
            at java.lang.Thread.run(Thread.java:745)
    Caused by: javax.mail.MessagingException: Exception reading response;
      nested exception is:
            java.net.SocketTimeoutException: Read timed out
            at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2210)
            at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2093)
            at com.sun.mail.smtp.SMTPTransport.finishData(SMTPTransport.java:1900)
            at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1122)
            at javax.mail.Transport.send0(Transport.java:195)
            at javax.mail.Transport.send(Transport.java:124)
            at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1400)
            ... 13 more
    Caused by: java.net.SocketTimeoutException: Read timed out
            at java.net.SocketInputStream.socketRead0(Native Method)
            at java.net.SocketInputStream.read(SocketInputStream.java:152)
            at java.net.SocketInputStream.read(SocketInputStream.java:122)
            at com.sun.mail.util.TraceInputStream.read(TraceInputStream.java:110)
            at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
            at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
            at com.sun.mail.util.LineInputStream.readLine(LineInputStream.java:89)
            at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2188)
            ... 19 more

Sending a DummyAlert works just fine via the web interface button or the API browser.

**Comment by joschi** [comment] 2015-01-14 09:11
> ```
    org.apache.commons.mail.EmailException: Sending the email to the following server failed : my.emailserver.com:25
    [...]
    Caused by: java.net.SocketTimeoutException: Read timed out
```

Make sure that `my.emailserver.com` on port 25/tcp is accessible from your Graylog2 Server (if you're running multiple Graylog2 Servers, it's the master).

**Comment by traviscosgrave** [comment] 2015-01-14 15:43
If it was inaccessible, the why would the DummyAlert work?

Just to be sure that it is accessible...

    admin@graylog2server1:~$ nmap -p 25 my.emailserver.com

    Starting Nmap 6.40 ( http://nmap.org ) at 2015-01-14 10:06 EST
    Nmap scan report for my.emailserver.com (10.0.10.61)
    Host is up (0.00058s latency).
    PORT   STATE SERVICE
    25/tcp open  smtp

When I send a dummy alert, this is what I see in the logs (@ the TRACE level).

    2015-01-14 10:27:07,507 DEBUG: org.graylog2.alerts.StaticEmailAlertSender - Sending mail to myalertemail@mydomain.com
    2015-01-14 10:27:07,649 DEBUG: org.graylog2.rest.accesslog - 10.0.10.11 admin [Wed Jan 14 10:27:07 EST 2015] "GET streams/54b43f6ce4b0c6ea4d03cf4d/alerts/sendDummyAlert" Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36 204 -1

When I trigger the alert via the rules (by sending messages from a cli) I see the following:

The logs have been grepped using:
`grep -Pi "(email|54b43f6ce4b0c6ea4d03cf4d|dummy|alert|alarmcallbacks|mail)"`

    2015-01-14 10:35:58,885 ERROR: org.graylog2.alarmcallbacks.EmailAlarmCallback - Stream [54b43f6ce4b0c6ea4d03cf4d: "Test ERROR Stream"] has alert receivers and is triggered, but sending emails failed
    org.apache.commons.mail.EmailException: Sending the email to the following server failed : 10.0.10.161:25
            at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1410)
            at org.apache.commons.mail.Email.send(Email.java:1437)
            at org.graylog2.alerts.StaticEmailAlertSender.sendEmail(StaticEmailAlertSender.java:101)
            at org.graylog2.alerts.StaticEmailAlertSender.sendEmails(StaticEmailAlertSender.java:213)
            at org.graylog2.alarmcallbacks.EmailAlarmCallback.call(EmailAlarmCallback.java:80)
            at org.graylog2.periodical.AlertScannerThread.doRun(AlertScannerThread.java:105)
    Caused by: javax.mail.MessagingException: Exception reading response;
            at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2210)
            at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2093)
            at com.sun.mail.smtp.SMTPTransport.finishData(SMTPTransport.java:1900)
            at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1122)
            at javax.mail.Transport.send0(Transport.java:195)
            at javax.mail.Transport.send(Transport.java:124)
            at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1400)
            at com.sun.mail.util.TraceInputStream.read(TraceInputStream.java:110)
            at com.sun.mail.util.LineInputStream.readLine(LineInputStream.java:89)
            at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2188)
    2015-01-14 10:35:58,886 DEBUG: org.graylog2.periodical.AlertScannerThread - Running alert checks.
    2015-01-14 10:35:58,890 DEBUG: org.graylog2.periodical.AlertScannerThread - There are 2 streams with configured alert conditions.
    2015-01-14 10:35:58,890 DEBUG: org.graylog2.periodical.AlertScannerThread - Stream [54b43db2e4b0c6ea4d03cd6f: "Test Stream"] has [0] configured alert conditions.
    2015-01-14 10:35:58,890 DEBUG: org.graylog2.periodical.AlertScannerThread - Stream [54b43f6ce4b0c6ea4d03cf4d: "Test ERROR Stream"] has [1] configured alert conditions.
    2015-01-14 10:35:58,891 DEBUG: org.graylog2.alerts.AlertServiceImpl - Checking alert condition [org.graylog2.alerts.AlertServiceImpl@1e3d3d92]
    2015-01-14 10:35:58,986 DEBUG: org.graylog2.alerts.types.MessageCountAlertCondition - Alert check <64e27895-4f08-4093-8b21-f06c4e7893a5> result: [26]
    2015-01-14 10:35:59,284 DEBUG: org.graylog2.periodical.AlertScannerThread - Alert condition [64e27895-4f08-4093-8b21-f06c4e7893a5:MESSAGE_COUNT={time: 30, threshold_type: more, threshold: 1, grace: 1}, stream:={54b43f6ce4b0c6ea4d03cf4d: "Test ERROR Stream - ERRORS"}] is triggered. Sending alerts.
    2015-01-14 10:35:59,286 DEBUG: org.graylog2.alerts.StaticEmailAlertSender - Sending mail to myalertemail@mydomain.com

**Comment by dennisoelkers** [comment] 2015-01-14 16:13
Could you please check the logs of your mail server? It seems like it responsed in an unexpected way when sending the actual alert. Maybe some content filter kicking in or something.

**Comment by traviscosgrave** [comment] 2015-01-14 20:39
I took a look at the logs in the mail server (hMailServer), and there is a clear difference between the dummy message and the alert message. I'm not an expert in mail servers or the process by which they manage messages, but it looks like the following is happening.

- graylog2 requests to send mail
- the mail server creates a session
- graylog2 sends EHLO and authenticates
- the mail server checks the FROM and TO
- graylog2 communicates parts of the message back and forth with the mail server
- the mail server logs "SENT: 221 goodbye" then ends the session
- the message is then written to disk and a session with the SMTP Deliverer is started relaying the message via gmail
- after being sent, the message is deleted from the disk

When a real message (non-DummyAlert) is sent, the session between the mail server and graylog2 gets interrupted. The "SENT: xxx goodbye" message is never logged. Below is the logging,although it isn't very revealing.

    "TCPIP"	1764	"2015-01-14 13:50:12.419"	"TCPConnection - Posting AcceptEx on 0.0.0.0:25"
    "DEBUG"	1764	"2015-01-14 13:50:12.419"	"Creating session 1737287"
    "SMTPD"	1764	1737287	"2015-01-14 13:50:12.419"	"10.0.10.84"	"SENT: 220 my.emailserver.com ESMTP"
    "SMTPD"	1844	1737287	"2015-01-14 13:50:12.434"	"10.0.10.84"	"RECEIVED: EHLO graylog2server1"
    "SMTPD"	1844	1737287	"2015-01-14 13:50:12.434"	"10.0.10.84"	"SENT: 250-my.emailserver.com[nl]250-SIZE 20480000[nl]250 AUTH LOGIN"
    "SMTPD"	1708	1737287	"2015-01-14 13:50:12.434"	"10.0.10.84"	"RECEIVED: AUTH LOGIN"
    "SMTPD"	1708	1737287	"2015-01-14 13:50:12.434"	"10.0.10.84"	"SENT: 334 LoginHASH"
    "SMTPD"	1480	1737287	"2015-01-14 13:50:12.434"	"10.0.10.84"	"RECEIVED: AuthHASH"
    "SMTPD"	1480	1737287	"2015-01-14 13:50:12.434"	"10.0.10.84"	"SENT: 334 AuthTokenHASH"
    "SMTPD"	1780	1737287	"2015-01-14 13:50:12.434"	"10.0.10.84"	"RECEIVED: ***"
    "SMTPD"	1780	1737287	"2015-01-14 13:50:12.450"	"10.0.10.84"	"SENT: 235 authenticated."
    "SMTPD"	1796	1737287	"2015-01-14 13:50:12.466"	"10.0.10.84"	"RECEIVED: MAIL FROM:<graylog2@mydomain.com>"
    "SMTPD"	1796	1737287	"2015-01-14 13:50:12.466"	"10.0.10.84"	"SENT: 250 OK"
    "SMTPD"	2052	1737287	"2015-01-14 13:50:12.466"	"10.0.10.84"	"RECEIVED: RCPT TO:<myalertemail@mydomain.com>"
    "SMTPD"	2052	1737287	"2015-01-14 13:50:12.466"	"10.0.10.84"	"SENT: 250 OK"
    "SMTPD"	1740	1737287	"2015-01-14 13:50:12.466"	"10.0.10.84"	"RECEIVED: DATA"
    "SMTPD"	1740	1737287	"2015-01-14 13:50:12.466"	"10.0.10.84"	"SENT: 354 OK, send."
    <<<< This is where the failed messaged stops working >>>>
    <<<< The following only happens with the dummy message >>>>
    "DEBUG"	1956	"2015-01-14 13:49:27.230"	"Saving message: C:\Program Files (x86)\hMailServer\Data\{12968B49-F5F5-4C6D-A022-A1364CCF3DFA}.eml"
    "DEBUG"	1956	"2015-01-14 13:49:27.230"	"Requesting SMTPDeliveryManager to start message delivery"
    "SMTPD"	1956	1737284	"2015-01-14 13:49:27.230"	"10.0.10.84"	"SENT: 250 Queued (0.000 seconds)"
    "SMTPD"	1740	1737284	"2015-01-14 13:49:27.230"	"10.0.10.84"	"RECEIVED: QUIT"
    "SMTPD"	1740	1737284	"2015-01-14 13:49:27.230"	"10.0.10.84"	"SENT: 221 goodbye"
    <<<< hMailServer then continues sending the message successfully >>>>

I have been able to line up the last `SENT: 354 OK, send.` message with the Java exception. There are no errors in the hMailServer log at all.

**Comment by kroepke** [comment] 2015-01-16 11:56
We'll need to analyze this further, but probably shouldn't hold up 1.0.0 for this until we have more information.

**Comment by traviscosgrave** [comment] 2015-01-16 12:10
What would be the best way to provide more information?

I am trying to kick off alerts to pagerduty, but there is a bug in the
pagerduty plugin. It doesn't respect the http_proxy_uri setting. So, email
would be the next obvious choice. This issue, however, is yet another
roadblock.

**Comment by wjanowiak** [comment] 2015-02-03 20:01
@traviscosgrave did you find a solution to this? I am seeing similar issues

**Comment by traviscosgrave** [comment] 2015-02-03 20:19
I haven't yet. I need to work with my ops team to get a better view of the
packets being passed back and forth. Hopefully, a Wireshark sessions will
give us a better idea of what HMailServer is sending back to Graylog2 that
makes it unhappy.

On Tue, Feb 3, 2015 at 3:01 PM, Waylon Janowiak <notifications@github.com>
wrote:

> @traviscosgrave <https://github.com/traviscosgrave> did you find a
> solution to this? I am seeing similar issues
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Graylog2/graylog2-server/issues/868#issuecomment-72722922>
> .
>



-- 
* Travis Cosgrave *
Technical Analyst
*d. *416.479.9564
*t. *877.781.0707 x 411
*e. *travis.cosgrave@thinkresearchgroup.com
<travis.cosgrave@patientordersets.com>

*thinkresearchgroup.com* <http://www.thinkresearchgroup.com>
 [image: think research] <http://www.thinkresearchgroup.com>

**Comment by bernd** [comment] 2015-03-02 15:58
Any news here? I just checked the code again and confirmed that the dummy alerts are using the same code for sending emails as the regular alerts. The only difference is that dummy alerts do not contain messages.

Maybe you run into some issues with maximum mail size if you include lots of messages in the emails? Just a guess.

**Comment by joschi** [comment] 2015-03-09 09:45
Closing this issue because the reporter didn't respond and it doesn't seem to be a bug.

**Closed by joschi** 2015-03-09 09:45 UTC
Labels: bug
