### ISSUE TITLE
Data adapter validation fails if no title is set

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#5072] opened 2018-09-05 15:50 UTC
When creating a new GeoIP data adapter, setting or changing a value before setting a title and name will fail the validation with a 400 error and no text message, since those fields are required by the backend. I'm not sure if this affects other data adapters or LUT entities, but we should check them, too.

<img width="1792" alt="screen shot 2018-09-05 at 17 43 33" src="https://user-images.githubusercontent.com/716185/45104956-776ed200-b133-11e8-878e-957f7a9c92c9.png">

## Expected Behavior
Data adapter validation should not run until all required fields are set, avoiding to show a confusing error message with little information.

## Current Behavior
Data adapter validation runs always, even if it can't be valid.

## Steps to Reproduce (for bugs)
1. Create a new data adapter in the lookup tables page
2. Select GeoIP type
3. Modify the refresh file input
4. See an error message and a 400 from the server appear on screen

## Your Environment
* Graylog Version: Graylog 3.0.0-SNAPSHOT (04d005f9976b36ebe348644812f5660318adfdbe), didn't verify on 2.4 yet

**Comment by danotorrey** [comment] 2019-10-10 21:44
I can't reproduce this on 3.1.2. Closing.

**Closed by danotorrey** 2019-10-10 21:44 UTC
Labels: bug, triaged
