### ISSUE TITLE
Disk journal and other node metrics do not load (3.2.2) with nginx as a reverse proxy

### ISSUE THREAD

**Issue by s1shed** [Graylog2/graylog2-server#7521] opened 2020-02-21 11:21 UTC
## Expected Behavior

There should not be an error when viewing the page for a node.

## Current Behavior

On two systems using Nginx as a reverse proxy (one using a subpath and the other using a subdomain), upon going to the page there's a red box with an error 400. "Getting journal information on node \*\* failed. 

![image](https://user-images.githubusercontent.com/8793762/75029306-7c9c1a00-54aa-11ea-84c2-4fa2468a69a0.png)

Additionally there is no sign of activity in the Buffers area. 

![image](https://user-images.githubusercontent.com/8793762/75029018-ff70a500-54a9-11ea-9a0e-41f1e2ccb0bb.png)

Messages are still being processed.

The behaviour is the same whether using a subpath or not. I do not know if this is a problem when not using a reverse proxy.

## Steps to Reproduce (for bugs)

1. Install graylog behind a reverse proxy.
2. Try to go to a node's page 
3.
4.

For example:
![journalinfo](https://user-images.githubusercontent.com/8793762/75029980-d3562380-54ab-11ea-87a4-66902e6f501b.gif)

## Your Environment

* Graylog Version: Graylog 3.2.2 (docker (tag graylog:3.2) and on another system I'm using the Debian package (3.2.2-1))
* Elasticsearch Version: docker tag elasticsearch-oss:6.8.2
* MongoDB Version: 3.6.17 (docker tag mongo:3)
* Operating System: Debian unstable
* Browser version: Firefox 73 & Chrome 80.0.3987.116

**Comment by mpfz0r** [comment] 2020-02-21 11:25
Maybe this could be helpful: https://github.com/Graylog2/graylog2-server/issues/7265#issuecomment-578724992

**Comment by s1shed** [comment] 2020-02-21 12:27
> Maybe this could be helpful: [#7265 (comment)](https://github.com/Graylog2/graylog2-server/issues/7265#issuecomment-578724992)

Thanks, I'll try. If it works I'll update the ticket while feeling like a jackass for wasting others' time.   

These configurations I'm using didn't have this problem with the previous version I was running (perhaps it was 3.2.1)

**Comment by s1shed** [comment] 2020-02-21 16:43
> > Maybe this could be helpful: [#7265 (comment)](https://github.com/Graylog2/graylog2-server/issues/7265#issuecomment-578724992)
> 
> Thanks, I'll try. If it works I'll update the ticket while feeling like a jackass for wasting others' time.
> 
> These configurations I'm using didn't have this problem with the previous version I was running (perhaps it was 3.2.1)

I tested with my graylog installation which is behind nginx with a subpath.

I set `http_external_uri=https://hostname.tld/gl/` , which is where graylog is accessible from.
I tried setting `http_publish_uri=http://127.0.0.1:9000`. This did not work. I  then set it to match the value I set `http_external_uri` to. This also did not work. I saw the same error.

I commented `http_external_uri` and  `http_publish_uri` and tried going to http://127.0.0.1:9000. The same behaviour persisted.

**Comment by vwbusguy** [comment] 2020-02-21 21:58
I'm seeing this as well since upgrading to 3.2.2.  We are not using nginx in our case, but we are proxying through an external load balancer service (Citrix NetScaler).

**Comment by vwbusguy** [comment] 2020-02-21 22:05
I think the proxy might be a red herring?  The net console in browser shows it tried to hit the correct proxied endpoint but the actual error response is:
`{"type":"ApiError","message":"Unable to map property native_lib_dir.\nKnown properties include: flush_interval, plugin_dir, segment_age, max_age, bin_dir, data_dir, max_size, directory, flush_age, segment_size"}`

**Comment by vwbusguy** [comment] 2020-02-21 22:07
There are several changes in this version related to Netty's NativeLibraryUtil, so I'm guessing that the regression might be caused by one of those changes based on the message.

**Comment by vwbusguy** [comment] 2020-02-21 22:14
It seems that the native lib directory was changed in 3.2.2 : https://github.com/Graylog2/graylog2-server/pull/7404

**Comment by vwbusguy** [comment] 2020-02-21 22:30
Doing a diff on the conf in the new version, it seems a new section was added:

```
# Set the bin directory here (relative or absolute)
# This directory contains binaries that are used by the Graylog server.
# Default: bin
bin_dir = /usr/share/graylog-server/bin
 
# Set the data directory here (relative or absolute)
# This directory is used to store Graylog server state.
# Default: data
data_dir = /var/lib/graylog-server
```
The native lib dir is based on the data_dir conf being set and is failing with an unhelpful message as a result.

Adding this back into the conf and restarting graylog creates the /var/lib/graylog-server/libnative path but the error about key mapping persists.  If I add `native_lib_dir = /var/lib/graylog-server/libnative` to the conf and restart, it still doesn't fix the problem.

**Comment by vwbusguy** [comment] 2020-02-21 22:46
It might just be a matter of adding native_lib_dir here: https://github.com/Graylog2/graylog2-server/blob/20ab7325eb82ec09c08ece0433e183412f32a05d/graylog2-server/src/main/java/org/graylog2/configuration/ExposedConfiguration.java#L58

**Comment by vwbusguy** [comment] 2020-02-21 23:20
Interestingly, if I go to Metrics, all of the journal endpoints appear to work fine.

**Comment by bernd** [comment] 2020-02-22 09:29
@s1shed @vwbusguy @mpfz0r I was able to reproduce the problem and am working on a fix.

As noted by @vwbusguy, this issue got introduced in #7404 (and #7359). It only happens on the node details page because that page is using a cluster wide API resource. That one has issues deserializing the journal response from all graylog nodes. (`/api/cluster/<node-id>/journal`) The nodes overview page is using another API resource (`/api/system/journal`) and is not affected.

This doesn't cause any processing issues, it's mainly a display issue in the UI.

We are working on a fix that will be in the next stable release. (3.2.3)

Thank you for the report!

**Comment by bernd** [comment] 2020-02-22 11:25
@s1shed @vwbusguy This is the fix: https://github.com/Graylog2/graylog2-server/pull/7526

**Comment by s1shed** [comment] 2020-02-22 11:32
> I think the proxy might be a red herring? 

Oops. I've run into a few problems that have been reverse proxy related. Sorry (to all) about the invalid assumption.

**Comment by bernd** [comment] 2020-02-22 11:39
> > I think the proxy might be a red herring?
> 
> Oops. I've run into a few problems that have been reverse proxy related. Sorry (to all) about the invalid assumption.

No worries! :smiley: Thank you for the report!

**Closed** 2020-02-24 11:24 UTC
Labels: bug
