### ISSUE TITLE
Dashboard: Widget edit URL is only directly opening edit mode if widget is part of the first dashboard page.

### ISSUE THREAD

**Issue by kyleknighted** [Graylog2/graylog2-server#10552] opened 2021-05-03 15:53 UTC
## Expected Behavior

While editing a Widget, the URL is appended with `/dashboards/<dash-id>?focusedId=<query-id>&editing=true` when I copy and paste this URL, it should load the edit screen for the focused widget.

## Current Behavior
While editing a Widget, the URL is appended with `/dashboards/<dash-id>?focusedId=<query-id>&editing=true` but if I copy the URL and attempt to share it with a colleague, the URL is redirected back to `/dashboards/<dash-id>`, when the widget is not part of the first dashboard page.

**Comment by kmerz** [comment] 2021-05-31 14:39
Unable to reproduce. Probably fixed by now.

**Comment by linuspahl** [comment] 2021-06-03 13:47
I am reopening this issue because this error still exists, when the related widget is not part of the first dashboard page.

**Closed** 2021-07-22 13:04 UTC
Labels: bug, dashboards, triaged, ux, widgets
