### ISSUE TITLE
Search Time Range Sanity Checks

### ISSUE THREAD

**Issue by ChristopherKB** [Graylog2/graylog2-server#8376] opened 2020-06-18 16:05 UTC
Search time range selector allows the user to set a From: time that is after the To: time. 
## Expected Behavior

When selecting a time range, we should check that the query is valid. It's fine to allow the To: setting to be in the future, to allow for time stamps that are malformed or other time related issues, but the query should always be executable. Alternately, we should show in the search results an error message that the time range was invalid.
## Current Behavior

Currently, you can set a search from June 6 12:00 to June 3 12:00. This returns nothing and gives no indication that the query was invalid.

## Possible Solution

Sanity checks on time range selections in the UI.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

No effect yet, but it could result in null search results and give the user the impression there is no data related to the query.
## Your Environment

* Graylog Version:3.3.1
* Elasticsearch Version: 6.8.x
* MongoDB Version:4.x
* Operating System: Unknown
* Browser version: Unknown

**Comment by dennisoelkers** [comment] 2020-06-19 07:08
Thanks for reporting this! We are already tracking this issue and have a PR that is addressing it: 
#8371.

Duplicate of #7191.

**Closed by dennisoelkers** 2020-06-19 07:08 UTC
Labels: bug
