### ISSUE TITLE
Indices not following rotation policy

### ISSUE THREAD

**Issue by freebsdsa** [Graylog2/graylog2-server#3268] opened 2016-12-28 23:38 UTC
I am testing Graylog 2.2 Beta and am using a stream to pull certain message types into its own ES indices so that we can have a different retention policy. I noticed that the new indices are not rotating per day as I have set it up to do, but the default ones rotate just fine.

Both indices show the same setup index time and P1D.

* Graylog Version: 2.2.0 beta 2
* Elasticsearch Version: 2.4.1
* MongoDB Version: 3.2.11
* Operating System: Centos 7.2

**Comment by bernd** [comment] 2016-12-30 08:16
Thanks for testing the beta release! We will take a look at this asap.

**Comment by bernd** [comment] 2017-01-02 10:51
@freebsdsa I am unable to reproduce this with the current beta.3 snapshot. Can you please send us your Graylog server log and the output of the following command executed on your server?

```
curl -u admin:<your-admin-password> 127.0.0.1:9000/api/system/indices/index_sets?pretty=true
```

Thanks!

**Comment by freebsdsa** [comment] 2017-01-03 15:50
Here is the output from that command.

{
  "total" : 2,
  "index_sets" : [ {
    "id" : "585195e6fbc89a3d0a58fed6",
    "title" : "Default index set",
    "description" : "The Graylog default index set",
    "index_prefix" : "graylog",
    "shards" : 18,
    "replicas" : 0,
    "rotation_strategy_class" : "org.graylog2.indexer.rotation.strategies.TimeBasedRotationStrategy",
    "rotation_strategy" : {
      "type" : "org.graylog2.indexer.rotation.strategies.AutoValue_TimeBasedRotationStrategyConfig",
      "type" : "org.graylog2.indexer.rotation.strategies.TimeBasedRotationStrategyConfig",
      "rotation_period" : "P1D"
    },
    "retention_strategy_class" : "org.graylog2.indexer.retention.strategies.DeletionRetentionStrategy",
    "retention_strategy" : {
      "type" : "org.graylog2.indexer.retention.strategies.AutoValue_DeletionRetentionStrategyConfig",
      "type" : "org.graylog2.indexer.retention.strategies.DeletionRetentionStrategyConfig",
      "max_number_of_indices" : 365
    },
    "creation_date" : "2016-12-14T18:56:38.916Z",
    "writable" : true,
    "default" : true
  }, {
    "id" : "58543f87fbc89a24547bf1ad",
    "title" : "Event Logs",
    "description" : "Gateway Event Logs",
    "index_prefix" : "eventlog",
    "shards" : 18,
    "replicas" : 0,
    "rotation_strategy_class" : "org.graylog2.indexer.rotation.strategies.TimeBasedRotationStrategy",
    "rotation_strategy" : {
      "type" : "org.graylog2.indexer.rotation.strategies.AutoValue_TimeBasedRotationStrategyConfig",
      "type" : "org.graylog2.indexer.rotation.strategies.TimeBasedRotationStrategyConfig",
      "rotation_period" : "P1D"
    },
    "retention_strategy_class" : "org.graylog2.indexer.retention.strategies.DeletionRetentionStrategy",
    "retention_strategy" : {
      "type" : "org.graylog2.indexer.retention.strategies.AutoValue_DeletionRetentionStrategyConfig",
      "type" : "org.graylog2.indexer.retention.strategies.DeletionRetentionStrategyConfig",
      "max_number_of_indices" : 300
    },
    "creation_date" : "2016-12-16T19:24:55.83Z",
    "writable" : true,
    "default" : false
  } ]
}

I also attached the full server log.
[server.log.zip](https://github.com/Graylog2/graylog2-server/files/682569/server.log.zip)

**Comment by bernd** [comment] 2017-01-04 09:49
@freebsdsa Thanks for the logs and the index set data!

The index set configuration looks good but I can't find anything in the logs that indicates an error with the index rotation. Since I am unable to reproduce this with the current master, please update to beta.3 or wait for beta.4 which will be release this week.

Please let us know if it works once you updated, thanks! I will leave this ticket open.

**Comment by tokred** [comment] 2017-01-04 14:56
I can confirm this issue on beta.3!

I have created two additional index sets which do not get rotated:
```
{
  "total" : 3,
  "index_sets" : [ {
    "id" : "586502faf4db16270516cdc5",
    "title" : "Default index set",
    "description" : "The Graylog default index set",
    "index_prefix" : "graylog",
    "shards" : 4,
    "replicas" : 1,
    "rotation_strategy_class" : "org.graylog2.indexer.rotation.strategies.TimeBasedRotationStrategy",
    "rotation_strategy" : {
      "type" : "org.graylog2.indexer.rotation.strategies.AutoValue_TimeBasedRotationStrategyConfig",
      "type" : "org.graylog2.indexer.rotation.strategies.TimeBasedRotationStrategyConfig",
      "rotation_period" : "P1D"
    },
    "retention_strategy_class" : "org.graylog2.indexer.retention.strategies.DeletionRetentionStrategy",
    "retention_strategy" : {
      "type" : "org.graylog2.indexer.retention.strategies.AutoValue_DeletionRetentionStrategyConfig",
      "type" : "org.graylog2.indexer.retention.strategies.DeletionRetentionStrategyConfig",
      "max_number_of_indices" : 30
    },
    "creation_date" : "2016-12-29T12:35:06.8Z",
    "index_analyzer" : "whitespace",
    "index_optimization_max_num_segments" : 1,
    "index_optimization_disabled" : false,
    "writable" : true,
    "default" : true
  }, {
    "id" : "58650bc7f4db16270516d76b",
    "title" : "Long Time Index Set",
    "description" : "Long Time Index Set",
    "index_prefix" : "gllong",
    "shards" : 4,
    "replicas" : 1,
    "rotation_strategy_class" : "org.graylog2.indexer.rotation.strategies.TimeBasedRotationStrategy",
    "rotation_strategy" : {
      "type" : "org.graylog2.indexer.rotation.strategies.AutoValue_TimeBasedRotationStrategyConfig",
      "type" : "org.graylog2.indexer.rotation.strategies.TimeBasedRotationStrategyConfig",
      "rotation_period" : "P1D"
    },
    "retention_strategy_class" : "org.graylog2.indexer.retention.strategies.DeletionRetentionStrategy",
    "retention_strategy" : {
      "type" : "org.graylog2.indexer.retention.strategies.AutoValue_DeletionRetentionStrategyConfig",
      "type" : "org.graylog2.indexer.retention.strategies.DeletionRetentionStrategyConfig",
      "max_number_of_indices" : 90
    },
    "creation_date" : "2016-12-29T13:12:39.765Z",
    "index_analyzer" : "standard",
    "index_optimization_max_num_segments" : 1,
    "index_optimization_disabled" : false,
    "writable" : true,
    "default" : false
  }, {
    "id" : "58650b01f4db16270516d695",
    "title" : "Short Time Index Set",
    "description" : "Short Time Index Set",
    "index_prefix" : "glshort",
    "shards" : 4,
    "replicas" : 1,
    "rotation_strategy_class" : "org.graylog2.indexer.rotation.strategies.TimeBasedRotationStrategy",
    "rotation_strategy" : {
      "type" : "org.graylog2.indexer.rotation.strategies.AutoValue_TimeBasedRotationStrategyConfig",
      "type" : "org.graylog2.indexer.rotation.strategies.TimeBasedRotationStrategyConfig",
      "rotation_period" : "P1D"
    },
    "retention_strategy_class" : "org.graylog2.indexer.retention.strategies.DeletionRetentionStrategy",
    "retention_strategy" : {
      "type" : "org.graylog2.indexer.retention.strategies.AutoValue_DeletionRetentionStrategyConfig",
      "type" : "org.graylog2.indexer.retention.strategies.DeletionRetentionStrategyConfig",
      "max_number_of_indices" : 7
    },
    "creation_date" : "2016-12-29T13:09:21.725Z",
    "index_analyzer" : "standard",
    "index_optimization_max_num_segments" : 1,
    "index_optimization_disabled" : false,
    "writable" : true,
    "default" : false
  } ]
}
```

Please advise on how I can provide additional info in order to support.

Best regards

**Comment by joschi** [comment] 2017-01-05 11:18
I couldn't reproduce this on current `master` either.

@freebsdsa @tokred Make sure that you've assigned the correct index sets to your streams and retry with the latest beta.

Graylog 2.2.0-beta.4 should be released today. If the problem still exists there for you, please add a comment in this issue. Until then, I'll close this as neither @bernd nor I could reproduce it.

**Comment by joschi** [comment] 2017-01-05 13:07
Aaand open again. Looks like this is a problem with `TimeBasedRotationStrategy` specifically.

We'll try to fix it for the next beta.

**Closed** 2017-01-05 15:38 UTC
Labels: bug, in progress, severe, triaged
