### ISSUE TITLE
Inactive graylog tabs in chrome 59 take up 100% CPU

### ISSUE THREAD

**Issue by glajchs** [Graylog2/graylog2-server#3814] opened 2017-05-11 19:14 UTC
Inactive graylog tabs in chrome 59 (currently beta) take up 100% CPU

## Expected Behavior
Graylog tabs shouldn't take up 100% CPU

## Current Behavior
When any graylog tab is active, it either takes up no or low CPU, however as soon as I make another tab in chrome active, the inactive graylog tab goes to 100% CPU and stays there indefinitely, or until I make that tab active again.

## Possible Solution
I have logged a bug with chrome as well.  This is either a chrome bug or a graylog bug, and if it's a chrome bug, it might still be worthwhile to know what API or use case you were hitting that caused this issue to happen, where all my other tabs don't have this issue.
[https://bugs.chromium.org/p/chromium/issues/detail?id=721491](https://bugs.chromium.org/p/chromium/issues/detail?id=721491)

## Steps to Reproduce (for bugs)
1.  Open any graylog tab in google-chrome-beta (version 59) (search page, config pages all show this issue).
2.  Open chrome's task manager (shift+esc, or right-click the title bar and click Task Manager)
3.  Open a new tab or switch to another existing tab in chrome
4.  After a second or two, the CPU goes to 100% and stays there
5.  Go back to the graylog tab
6.  After a second or two, the CPU goes back to normal

## Your Environment

* Graylog Version: Graylog 2.2.3+7adc951 on XXX (Oracle Corporation 1.8.0_101 on Linux 4.4.41-36.55.amzn1.x86_64)
* Elasticsearch Version: Version: 2.4.0, Build: ce9f0c7/2016-08-29T09:14:17Z, JVM: 1.8.0_101
* MongoDB Version: v3.2.12 ef3e1bc78e997f0d9f22f45aeb1d8e3b6ac14a14
* Operating System: amazon linux ef3e1bc78e997f0d9f22f45aeb1d8e3b6ac14a14 (for server), the client browser is Linux Mint 18.1 Serena
* Browser version: Version 59.0.3071.47 (Official Build) beta (64-bit)

**Comment by dennisoelkers** [comment] 2017-05-15 09:46
I have tried this with `58.0.3029.110` and `60.0.3088.3`. I was unable to reproduce it with either version, CPU usage ranged between 0 and 10% for the background tab. Can you check using the developer tools what is causing the CPU load?

**Comment by glajchs** [comment] 2017-05-15 17:52
Interesting, I would assume that chrome 60 would reproduce the issue.  I'm now starting to think that it is a chrome bug, because I did take a Performance trace via the chrome dev tools, and it showed most of the time spent (90%) in "idle".  This leads me to believe that it wasn't run-away client javascript that was taking up the tab's CPU, but rather something in the actual chrome process for the tab that is taking the CPU.

Do you happen to know of a public graylog server's UI I could link to?  I was trying to find some way of reproducing the environment that creates this for the bug description, but I didn't want to say "go download graylog and setup a whole new server" just in order to visit the UI.  It would also be great to be able to figure out if this is a problem with *our* graylog server, or with graylog servers in general.

**Comment by glajchs** [comment] 2017-05-15 18:55
OK so interestingly, I was able to get a new graylog server up in a VM, and in that VM I installed chrome 58, 59, and 60.  I was able to reproduce the problem only in chrome version 59.  So this seems like it must be a chrome 59 specific issue.

**Comment by joschi** [comment] 2017-05-16 07:32
@glajchs Thanks for your feedback!

We'll close this issue, as it seems to be a specific problem with Chrome 59, but if you find any other oddities regarding this issue, please don't hesitate to add a comment.

**Comment by dennisoelkers** [comment] 2017-05-16 08:07
@glajchs thanks for taking the time to deep dive into this!

**Comment by STRML** [comment] 2017-05-16 13:29
Just to add onto this with some visuals (in case this makes it to Chrome M59 Stable without a fix), this is what the profile looks like. The gray area is all "Other" and has no further information. The buffer fills up extremely quickly.

<img width="937" alt="screen shot 2017-05-16 at 8 22 36 am" src="https://cloud.githubusercontent.com/assets/1197375/26108045/e55abb1c-3a10-11e7-8f8a-ba4784a605d0.png">

A selection of this time in `chrome://tracing`:

<img width="1869" alt="screen shot 2017-05-16 at 8 27 33 am" src="https://cloud.githubusercontent.com/assets/1197375/26108249/8f678cb6-3a11-11e7-9af6-db2676c62022.png">

Digging through the trace, it appears to be in a Microtask loop. There may be a bug in 59 that executes microtasks synchronously, so if one is scheduled inside another it will busyloop all day.

This is OSX Sierra, `Version 59.0.3071.47 (Official Build) beta (64-bit)`.

**Comment by glajchs** [comment] 2017-06-06 15:16
Chrome 59 is live, and I can confirm that my team (which uses OSX) is also seeing the issue now.  Get ready for some upvotes on this! :-(  I'm still trying to work the chrome bug to get someone to fix it.

On a related note, is there a URL for a public graylog server I can point them at?

**Comment by STRML** [comment] 2017-06-06 16:07
This is now a rather critical issue, it would be best to reopen it to track the fix with the Chrome team. 

I've set up a test server at http://graylog.strml.net (`admin:admin`). You can view an [active stream here](search?q=gl2_source_input%3A5936d2532ab79c000120824c&relative=28800).

Strangely, it doesn't exhibit the issue on my machine.

**Comment by STRML** [comment] 2017-06-06 16:27
Okay, how's this for weird:

http://graylog.strml.net/dashboards does not exhibit the issue.

https://graylog.strml.net/dashboards does. It's the ssl that's the difference.

**Comment by bernd** [comment] 2017-06-07 09:13
@STRML Happens to me without HTTPS in my local dev environment as well.

I am reopening the issue.

**Comment by bernd** [comment] 2017-06-07 09:18
Link to issue on the Chrome bug tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=721491

**Comment by bernd** [comment] 2017-06-07 11:05
I added a comment to the Chrome bug for this issue with some more information: https://bugs.chromium.org/p/chromium/issues/detail?id=721491#c8

**Comment by jasonkeller** [comment] 2017-06-19 16:31
After hitting this bug myself, one "workaround" I've used now is to open each instance in a new window instead of a new tab, for anyone else afflicted similarly.

**Comment by bernd** [comment] 2017-06-21 08:57
I just updated to Chrome 59.0.3071.109 on Ubuntu 16.04 LTS and the problem does not show up anymore.

See https://bugs.chromium.org/p/chromium/issues/detail?id=721491#c18 for details on the issue that has been fixed in Chrome.

**Closed by bernd** 2017-06-21 08:57 UTC
Labels: known issue
