### ISSUE TITLE
LDAP settings disappearing in cluster env.

### ISSUE THREAD

**Issue by spamm8** [Graylog2/graylog2-server#1947] opened 2016-03-18 13:11 UTC
### Problem description
After saving LDAP settings, and several refreshing in browser on setting page it appears and disappears frequently. Probably thats why there are sometimes problems with login in using AD login and password (while password is 100% OK).
### Steps to reproduce the problem
Clustered (min. 2nodes) when setting LDAP after saving, click refresh several times, ldap settings appears again and after next few page refresh it disappears.
In logs I noticed that when it disappears it shows something like this:
```
[error] o.g.r.m.a.LdapSettingsService - Unable to load LDAP settings.
org.graylog2.restclient.lib.APIException: API call failed GET http://@10.x.x.202:12900/system/ldap/settings returned 500 Internal Server Error body: {"type":"ApiError","message":"Null systemPassword"}
```
Sometimes it refers to http://@10.x.x.201:12900.

It looks like settings were only written on first node with ip 10.x.x.200 and works only when server asks this API.
Browse API shows this error in /system/ldap/settings:
```
{"type":"ApiError","message":"Null systemPassword"}
```

### Environment
3 nodes 10.x.x.200, 10.x.x.201, 10.x.x.202
* Graylog Version: 1.3.4 (0d67a80) (Hansa)
* Elasticsearch Version: 1.7.5
* MongoDB Version:v3.0.6 (clustered)
* Operating System:ubuntu 14
* Browser version: firefox 45, cyberfox 45, chrome

Moreover when setting LDAP separately on single machine while others are down does not resolve issue. When later all 3 are up LDAP settings are just disappearing again.

**Comment by joschi** [comment] 2016-03-18 13:20
@spamm8 Please verify that all three Graylog server nodes are using the exactly same password secret (see https://github.com/Graylog2/graylog2-server/blob/0d67a80cf321982330e7b172629e9f1ee2797dac/misc/graylog2.conf#L9-L11) which is being used to encrypt the LDAP settings in MongoDB. Also verify that all three Graylog server nodes are using the same MongoDB database.

**Comment by spamm8** [comment] 2016-03-18 13:48
Wow! I'm impressed. It was really quick and gooood reply. I used the same secret on all nodes, reloaded and no more errors. LDAP Settings are now OK. Thanks a lot!

**Comment by joschi** [comment] 2016-03-18 14:05
@spamm8 You're welcome. I'm closing this issue now that it's not a bug in Graylog itself.

**Closed by joschi** 2016-03-18 14:05 UTC
