### ISSUE TITLE
TCP connections not closed

### ISSUE THREAD

**Issue by FlorentCoppint** [Graylog2/graylog2-server#1391] opened 2015-09-03 11:41 UTC
Hi,
On a 3 servers setup of Graylog server, I have an issue about TCP connections listed as "ESTABLISHED" by Graylog server, but that are not really true ones.

When I show ESTABLISHED connections with "lsof" tool, I got : 

 lsof | grep ESTABLISHED | awk '{print $2}' | sort | uniq -c | sort -n
      1 20285
      5 2125
     74 2395          <-- Graylog-web java process
    560 2069         <-- Mongodb process
 120288 2279      <-- Graylog-server java process

120288 ESTABLISHED connections seems very high ! That's not true.

When I show ESTABLISHED connections with "netstat" tools, I got something more realistic : 

 netstat -apn | grep ESTABLISHED | wc -l
730

Of course my clients never had 120 000 established connections simultaneously. It seems some closed connections are not really closed by Graylog.

I have multiple inputs on my graylog servers, but only one used by most clients : Syslog TCP Input on port 1514 (I had to set a port > 1024 to run Graylog as unprivileged user). This is this port having the 120 000 connections according to "lsof".
A load balancer in front of the 3 servers is listening on 514 TCP port and send it to my Graylog 1514 TCP port.

I don't know if I gave enough details about this bug. Please tell me if you need something else.

My 3 servers are running on Debian Wheezy (I updated recently 1 of the 3 to Jessie, problem is still there), with OpenJDK 7 and Graylog 1.1.6. I have this problem since multiple Graylog releases.

Thank you :)

Florent

**Comment by joschi** [comment] 2015-09-03 12:38
For completeness: Related mailing list thread at https://groups.google.com/d/msg/graylog2/GNW3Hcy5rU4/_pQOV5CYBgAJ

**Comment by bernd** [comment] 2015-09-03 12:51
@FlorentCoppint What kind of load balancer do you have in front of the Graylog servers? And can you show us the configuration if it's an open source one? Thanks!

**Comment by FlorentCoppint** [comment] 2015-09-03 13:23
I have IPVS+Keepalived in front. Here is the configuration used : 

virtual_server 10.111.12.111 514
{
	delay_loop 10
	lb_algo wlc
	lb_kind DR
	protocol TCP

	real_server 10.111.12.171 1514
	{
		weight 100
		HTTP_GET
		{
			url
			{
				path "/system/lbstatus"
				status_code 200
			}
			connect_timeout 2
			connect_port 12900
			nb_get_retry 3
			delay_before_retry 2
		}
	}
	real_server 10.111.12.172 1514
	{
		weight 100
		HTTP_GET
		{
			url
			{
				path "/system/lbstatus"
				status_code 200
			}
			connect_timeout 2
			connect_port 12900
			nb_get_retry 3
			delay_before_retry 2
		}
	}
	real_server 10.111.12.173 1514
	{
		weight 100
		HTTP_GET
		{
			url
			{
				path "/system/lbstatus"
				status_code 200
			}
			connect_timeout 2
			connect_port 12900
			nb_get_retry 3
			delay_before_retry 2
		}
	}
}


And on each backend (Graylog server):

iptables -t nat -A PREROUTING -p tcp -d 10.111.12.111 --dport 514 -j REDIRECT --to-port 1514
iptables -t nat -A OUTPUT -p tcp -d 10.111.12.111 --dport 514 -j REDIRECT --to-port 1514

A lot of services are running fine with this configuration.

**Comment by bernd** [comment] 2015-09-03 13:43
Thank you! Could you also show us your ipvsadm configuration? That would help reproducing your problem.

**Comment by FlorentCoppint** [comment] 2015-09-03 13:50
IPVS load balancer is configured through Keepalived. Here is the only thing I get : 

TCP  10.111.12.111:shell wlc
  -> 10.111.12.171:1514           Route   100    29         0         
  -> 10.111.12.172:1514           Route   100    22         1         
  -> 10.111.12.173:1514           Route   100    27         0

(as you can see, there is not 120 000 connections :) )

**Comment by bernd** [comment] 2015-09-03 14:01
Ah, thanks! I am not too familiar with keepalived yet. :wink:

**Comment by bernd** [comment] 2015-09-04 12:26
The problem is that lsof is kinda lying to you because it lists one `ESTABLISHED` for each thread that is running. The netstat program is correct.

I have one TCP connection on port 1514, see the different results.

```
# lsof -n | fgrep ESTABLISHED | fgrep -e 1514 | wc -l
186
# netstat -n | fgrep ESTABLISHED | fgrep 1514 | wc -l
1
#
```

I tested your load balancer setup and do not see a problem. I guess the lsof output was misguiding.

Can you please check this again with netstat?

**Comment by FlorentCoppint** [comment] 2015-09-04 13:17
Yes I understand, but I missed to say something important :D The root problem is that after few days, Graylog Server stops working with lots of "Too many opened files" errors... That's when I investigated this, that I saw the connections problem.
BTW, netstat is showing me more than 500 established connections on each server, which seems very high, I have 100 clients maximum.

**Comment by bernd** [comment] 2015-09-04 13:36
Ah, sorry. I missed that in the mailing list post. Your clients are running
rsyslogd on wheezy? Or something else?

Can we see the client configs as well? Thank you!

**Comment by FlorentCoppint** [comment] 2015-09-04 13:44
Yes rsyslog (5.8.11-3) on Wheezy.

Here is rsyslog.conf : 

$ModLoad imuxsock
$ModLoad imklog

$WorkDirectory /var/spool/rsyslog
$ActionQueueFileName remotesyslog
$ActionQueueMaxDiskSpace 1g
$ActionQueueSaveOnShutdown on
$ActionQueueType LinkedList
$ActionResumeRetryCount -1

*.* @@10.111.12.111:514

**Comment by bernd** [comment] 2015-09-08 08:51
Thank you, I will try to reproduce this.

**Comment by bernd** [comment] 2015-10-20 15:23
I am unable to reproduce this unfortunately. Sorry. :confused:

Closing this issue now, please re-open if you still run into this with the latest release and you have a way to reproduce this. Thank you!

**Closed by bernd** 2015-10-20 15:23 UTC

**Comment by pkoraca** [comment] 2015-12-15 16:20
Hello, we had similar issues issues with Keepalived/DR setup, and finally found out what was the problem. In case of LVS Direct Routing backend servers should not announce ARP for loopback interfaces. 

Try to put this to sysctl config:

```
net.ipv4.conf.all.arp_ignore = 1
net.ipv4.conf.eth0.arp_ignore = 1
net.ipv4.conf.all.arp_announce = 2
net.ipv4.conf.eth0.arp_announce = 2
```

Hope this is helpful.

**Comment by FlorentCoppint** [comment] 2015-12-15 16:34
Hi pkoraca, Thank you, but I'm not sure that's our issue. I only have this problem with Graylog backends, and we have a lot of others services behind LB.
And we configure backend with an iptables REDIRECT rule, not assigning an address to interface.

By the way, it seems that this problem is solved. We haven't restarted our Graylog servers for a long time and it seems ok now.

**Comment by bernd** [comment] 2015-12-15 16:34
@pkoraca Great, thank you for the update!
