### ISSUE TITLE
Got 404 page when trying to "Export as CSV"

### ISSUE THREAD

**Issue by isador999** [Graylog2/graylog2-server#2708] opened 2016-08-17 15:52 UTC
I'm trying to use the "Export as CSV" feature in Graylog2.  
But in any cases  (a lot of logs,  just 4 or 5 log entries, with or without fields ...) ,  I get the following address, and the returned page is 404  (with a monkey)  : 

https://host.domainname/streams/5729c6e4f8c02d1bbb7620ef/39ff1f54-393b-4abc-8ba5-b423d34db84c:session@/api/search/universal/relative/export?query=%2A&range=300&filter=streams%3A5729c6e4f8c02d1bbb7620ef&fields=source%2CApplication%2CEventReceivedTime%2Cfacility%2Cfile%2Cfull_message%2Cgl2_remote_ip%2Cgl2_remote_port%2Cgl2_source_input%2Cgl2_source_node%2Clevel%2Cline%2Clogger%2Cmessage%2CPathInfo%2CRemoteAddr%2CRequestURL%2CServletPath%2CSessionID%2Csome_env_var%2Csome_info%2CSourceModuleName%2CSourceModuleType%2Cstreams%2Cthread%2Ctimestamp%2CtimestampMs%2Cuser_id%2CUserPrincipal

There is nothing in Graylog or Elasticsearch logs... 
In Apache Logs, I've searched about ID : 5729c6e4f8c02d1bbb7620ef/39ff1f54-393b-4abc-8ba5-b423d34db84c    but the associated logs have a "200" code  (but ok,  maybe it's normal.). 

We can reproduce the problem on 2 servers,  so I think  either it's a misconfiguration of 'server.conf',  either it's really a bug.  
Maybe the generated URI is false..  I think my Apache rules are OK, according to the documentation with Apache 2.4...  : 

```
    <VirtualHost *:443>
        ServerName host.domainname

        SSLEngine On
        SSLCipherSuite ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:-SSLv2:+EXP:+eNULL

        SSLCertificateFile /etc/ssl/certs/host.domainname.crt
        SSLCertificateKeyFile /etc/ssl/private/host.domainname.key

        <Location />
            RequestHeader set X-Graylog-Server-URL "/api/"
            ProxyPass http://127.0.0.1:9000/
            ProxyPassReverse http://127.0.0.1:9000/
        </Location>

        <Location /api/>
            ProxyPass http://127.0.0.1:12900/
            ProxyPassReverse http://127.0.0.1:12900/
        </Location>

        ErrorLog /var/log/apache2/host.domainname.error.log
        LogLevel warn
        CustomLog /var/log/apache2/host.domainname.access.log combined
    </VirtualHost>
```

* Graylog Version: 2.0.2
* Elasticsearch Version: 2.3.1
* MongoDB Version: 3.2.6
* Apache : 2.4.7
* Operating System: Ubuntu 14.04
* Browser version: Firefox 48

**Comment by dennisoelkers** [comment] 2016-08-18 08:47
Do you have the option to try this with a recent 2.1.0 beta? I cannot reproduce it in the latest development version.

**Comment by dennisoelkers** [comment] 2016-08-18 14:43
This is a duplicate of #2661. Closing it in favor of that one.

**Closed by dennisoelkers** 2016-08-18 14:43 UTC
