### ISSUE TITLE
autogenerater query issue

### ISSUE THREAD

**Issue by 5kuby** [Graylog2/graylog2-server#4895] opened 2018-07-10 08:40 UTC
## Expected Behavior
using quick add icon (magnifier icon on the right of every fields) with field that contain special character the generated search must be ready to use
## Current Behavior
graylog generate a search composed of field name:field content between double quote. If there are special character such as backslash graylog don't add any escape character and the search don't work correctly. 

## Possible Solution
automatic add escape character when the query is generated
## Steps to Reproduce (for bugs)
1. create an event with this field: field\content, the field name isn't important
2.search field\content, the search must work correctly
3.click on the magnifier in the field, this must generate a query in this form: fieldname."field\content" and the search don't produce any result
4.modify6 the query on step 3 in fieldname."field\\\content" now the query must work fine

**Comment by joschi** [comment] 2018-07-10 08:43
@5kuby Please provide a link to the discussion topic in the Graylog Community forums with your examples.

**Comment by 5kuby** [comment] 2018-07-10 08:57
here a link to my topic https://community.graylog.org/t/search-issue-with-same-terms/5918

**Comment by bernd** [comment] 2020-11-14 22:45
I am unable to reproduce this with the new search implementation. The special characters are properly escaped and the search works. Closing this issue.

**Closed by bernd** 2020-11-14 22:45 UTC
Labels: bug, triaged
