### ISSUE TITLE
Unable to probe any host for Elasticsearch version

### ISSUE THREAD

**Issue by Ghostbird** [Graylog2/graylog2-server#9550] opened 2020-11-19 09:12 UTC
I upgraded my docker-compose configuration to Elasticsearch 7.9.3 and Graylog 4.0

After fixing some other issues that occurred due to errors on my side, it started fine. Then I stopped it, to bring it up as a system service, but it didn't work. So I tried to run it manually again, and now every time it spews a stack trace telling me it cannot connect to ElasticSearch.

I've even removed all docker images and containers related to graylog and let docker-compose rebuild everything, but the error stays.

## Expected Behavior
Graylog starts and connects to Elasticsearch 7 container.

## Current Behavior
Graylog attempts to start, then spews a stack trace that starts with:
 starting with:
```
graylog_1        | 2020-11-19 08:45:15,229 ERROR: org.graylog2.storage.versionprobe.VersionProbe - Unable to retrieve version from Elasticsearch node: 
graylog_1        | java.net.ConnectException: Failed to connect to elasticsearch/172.23.0.2:9200
```
…and ends with:
```
graylog_1        | ################################################################################
graylog_1        | 
graylog_1        | ERROR: Unable to probe any host for Elasticsearch version!
graylog_1        | 
graylog_1        | Please see the following link(s) to help you with this error:
graylog_1        | 
graylog_1        | * http://docs.graylog.org/en/4.0/pages/configuration/elasticsearch.html
graylog_1        | 
graylog_1        | Need further help?
graylog_1        | 
graylog_1        | * Official documentation: http://docs.graylog.org/
graylog_1        | * Community support: https://www.graylog.org/community-support/
graylog_1        | * Commercial support: https://www.graylog.com/support/
graylog_1        | 
graylog_1        | Terminating. :(
graylog_1        | 
graylog_1        | ################################################################################
graylog_graylog_1 exited with code 252
```
## Possible Solution
I'm not sure, but can it be that it tries to connect to the elasticsearch container before it is fully up and running? Or that it tries to connect to the wrong endpoint? A few seconds after the termination messages this line appears in the log:
```
elasticsearch_1  | {"type": "server", "timestamp": "2020-11-19T08:57:31,347Z", "level": "INFO", "component": "o.e.t.TransportService", "cluster.name": "docker-cluster", "node.name": "bb31f6972abe", "message": "publish_address {localhost/127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}" }
```

```
elasticsearch_1  | {"type": "server", "timestamp": "2020-11-19T08:45:31,356Z", "level": "INFO", "component": "o.e.c.r.a.AllocationService", "cluster.name": "docker-cluster", "node.name": "042982e184b2", "message": "Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[graylog_0][0]]]).", "cluster.uuid": "XjGNkRT4RLyy0tbdEHQdeg", "node.id": "KuhVWSrPRb-xY7ED5XrQlA"  }
```

## Steps to Reproduce (for bugs)
Run this [docker compose file](https://gist.github.com/Ghostbird/2365c64c6cb125566e1ee55737bedd5a)
Note: I have replaced GRAYLOG_PASSWORD_SECRET, GRAYLOG_ROOT_PASSWORD_SHA2, and GRAYLOG_HTTP_EXTERNAL_URI with the default values from the wiki.

## Context
Upgrade from graylog 3 to 4, elasticsearch 6 to 7

## Your Environment
Linux 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

* Graylog Version: 4.0 (docker)
* Java Version: System version openjdk 11.0.9 2020-10-20, but I think the version in Docker is used instead.
* Elasticsearch Version: 7.10 (docker)
* MongoDB Version: 4.4 (docker)
* Operating System: Ubuntu 20.04.1 LTS
* Browser version: Irrelevant for this issue

**Comment by dennisoelkers** [comment] 2020-11-19 09:18
Hey @Ghostbird,

the issue is that Graylog is probing for the ES version used on startup. It goes through the list of configured nodes and gives up if none of them are up. Can you make sure that ES is available before GL is starting up? If not, you can set the `elasticsearch_version` configuration setting to `7`, what effectively disables auto-sensing the version (please see [here](https://docs.graylog.org/en/4.0/pages/configuration/elasticsearch.html#automatic-version-sensing) for details).

**Comment by Ghostbird** [comment] 2020-11-19 09:22
@dennisoelkers Thanks for the quick reply. I saw that option, but it is not clear to me, how to set that through a docker-compose file. Could you assist me with that?

**Comment by dennisoelkers** [comment] 2020-11-19 10:48
Good to hear that you managed to get it up and running! You are saying:

> I guess this is mostly a problem for docker-compose file version 3 users, since that version demands that containers handle waits for dependency readiness internally.

Do you have a pointer for me to read up on this? This might force us to change the mechanism to retry instead of back off and bail out.

**Comment by jalogisch** [comment] 2020-11-19 12:03
@dennisoelkers 

we might want to include `healthcheck` command with a custom check on elasticsearch in our documentation docker-compose and all others. That would start Graylog only after a specific command returns "green" and will start Graylog after Elasticsearch and MongoDB are reachable. 

I'll work something out as this is not super complicated.

**Comment by Ghostbird** [comment] 2020-11-19 14:07
> Good to hear that you managed to get it up and running! You are saying:
> 
> > I guess this is mostly a problem for docker-compose file version 3 users, since that version demands that containers handle waits for dependency readiness internally.
> 
> Do you have a pointer for me to read up on this? This might force us to change the mechanism to retry instead of back off and bail out.

This comment, and the linked Moby issue comment give the best summary I could find. Moby is the core of Docker, in case you didn't know. I sure didn't
https://github.com/docker/compose/issues/4305#issuecomment-276527457

**Comment by dennisoelkers** [comment] 2020-11-19 14:35
Thanks a lot for the link. I will digest and decide if we should make some changes for one of the next versions. For now, you can stick with `elasticsearch_version` being explicitly set (in fact, it could even help with ES8, it _could_ work ootb with it), it is just less convenient configuration-wise.

I am closing this issue for now. If you have any additional information, feel free to reopen it.

**Closed by dennisoelkers** 2020-11-19 14:35 UTC
Labels: bug

**Comment by Ghostbird** [comment] 2020-11-20 10:54
> Thanks a lot for the link. I will digest and decide if we should make some changes for one of the next versions. For now, you can stick with `elasticsearch_version` being explicitly set (in fact, it could even help with ES8, it _could_ work ootb with it), it is just less convenient configuration-wise.
> 
> I am closing this issue for now. If you have any additional information, feel free to reopen it.

Thanks a lot for the assistance. I'll stick with the `GRAYLOG_ELASTICSEARCH_VERSION=7` in the docker compose environment settings. I think it's perfectly fine to close this issue. The remaining use it has now is that other people can find this workaround in case they need it.
