### ISSUE TITLE
Re-saving a saved search in beta 3 not defaulting to the loaded saved search name

### ISSUE THREAD

**Issue by kpointer** [Graylog2/graylog2-server#18832] opened 2024-03-27 12:31 UTC
In beta 3 loading a saved search, changing the search, then saving the search isn't using the name of the loaded saved search for the name. In my case it is using the name of the first saved search in my saved searches list and I end up with two saved searches with the same name.

## Expected Behavior

The name should default to the name of the search that was loaded.

## Steps to Reproduce (for bugs)

Load saved search
Make a change to the search
Save the search
Default save name is not the name of the loaded saved search. Cancelling the save, refreshing the page, then trying to save again gets the right name in.

## Your Environment

* Graylog Version: 6.0.0-beta.3
* Java Version: Eclipse Adoptium 17.0.10 
* OpenSearch Version: 2.12
* MongoDB Version: 6.0.14
* Operating System: Ubuntu 22.04
* Browser version: Firefox 124.0.1

**Comment by dennisoelkers** [comment] 2024-03-27 12:50
Thanks for reporting this, @kpointer! We have found the root cause of this and it will be fixed in the next beta.

**Closed** 2024-03-28 13:52 UTC
Labels: bug
