### ISSUE TITLE
cluster: automatically elect master node 

### ISSUE THREAD

**Issue by huegelc** [Graylog2/graylog2-server#4641] opened 2018-03-07 11:51 UTC
We are using a 3 node graylog cluster. According to the documentation [1], one node must be configured with the option `is_master = true` but it´s not clear how a (new) master is elected if the primary goes down for whatever reasons.  

[1] http://docs.graylog.org/en/2.4/pages/configuration/multinode_setup.html#graylog-multi-node

* Graylog Version: Graylog 2.4.3+2c41897 o
* Elasticsearch Version: 5.6.8
* MongoDB Version: 3.6.3
* Operating System: Ubuntu Xenial
* Browser version: any

**Comment by joschi** [comment] 2018-03-07 11:57
Duplicate of #810

**Comment by joschi** [comment] 2018-03-07 11:58
@huegelc There is no automatic master election in Graylog at the moment, so you need to perform a manual failover if the Graylog master node is down.

**Closed** 2018-03-07 11:58 UTC

**Comment by huegelc** [comment] 2018-03-07 22:12
ok, thanks for the info.
