### ISSUE TITLE
Searching from Streams pages > 1 results in "No streams found"

### ISSUE THREAD

**Issue by asachs01** [Graylog2/graylog2-server#10639] opened 2021-05-14 13:51 UTC
## Expected Behavior

When searching for streams from pages > 1, I expect that I'll be able to have results returned. 

## Current Behavior

Presently, when searching on any page > 1 from Streams, a message is returned: "No streams found"
![CleanShot 2021-05-14 at 09 35 25](https://user-images.githubusercontent.com/898627/118280179-f480a680-b499-11eb-9d33-702146e6c727.gif)

## Steps to Reproduce (for bugs)

1. Run a 4.X instance
2. Create multiple streams
3. Navigate to page 2
4. Attempt to search for a any stream

See HS-411104332

**Comment by thll** [comment] 2021-05-17 09:57
I think the issue is, that the UI is sending the current page number as a search parameter when initiating a new search. It should however reset the page parameter. In the example above, the UI attempts to display the **second** page of the result set. If there are not enough results to exceed a single page, nothing will be displayed.

This can be replicated when the search returns more results than would fit on one page. If the search is initiated on page 2, the second page of the result set is displayed. However, if the page navigation is then used to navigate back to page 1, the search term is lost from the query even though still displayed in the search form. So it seems that we have multiple inconsistencies regarding search pagination here.

**Comment by asachs01** [comment] 2021-05-20 14:54
@thll @bernd I've got a couple of additions here:

```
First: If one has a search result which returns more streams than 1 page displays the trying to go to page 2 in the search results ends up on the normal stream page 2 without search.

Second: The sorting in the non searching view is not alphabetical or anything, is this as is? If so we would like to place a feature(?) request to sort the streams alphabetically in the streams overview. Sorting even changes in our env if changing from 10 to 50 streams to display
```

Should I split those off into separate issue?

**Comment by kmerz** [comment] 2021-05-26 09:17
> @thll @bernd I've got a couple of additions here:
> 
> ```
> First: If one has a search result which returns more streams than 1 page displays the trying to go to page 2 in the search results ends up on the normal stream page 2 without search.
> 
> Second: The sorting in the non searching view is not alphabetical or anything, is this as is? If so we would like to place a feature(?) request to sort the streams alphabetically in the streams overview. Sorting even changes in our env if changing from 10 to 50 streams to display
> ```
> 
> Should I split those off into separate issue?

`First` should be fixed with this PR. But I can't reproduce `Second`. It is always sorted alphabetically.

**Closed** 2021-05-27 11:48 UTC
Labels: bug, triaged

**Comment by HenryTheSir** [comment] 2021-07-30 08:13
Hello,

this fix introduced a new bug, if the search has now more than one page of result clicking on second page resets full search and opens second page as if nothing was searched.

**Comment by linuspahl** [comment] 2021-07-30 09:40
@HenryTheSir Thank you for reporting this bug! We were able to reproduce it and will fix it with the next patch release.

Related issue: https://github.com/Graylog2/graylog2-server/issues/11091
