### ISSUE TITLE
API Browser Link is not replaced with web_endpoint_uri

### ISSUE THREAD

**Issue by peteeckel** [Graylog2/graylog2-server#3719] opened 2017-04-21 13:10 UTC
I am using Graylog behind a reverse proxy server for some reason, and everything works almost to my satisfaction. I set web_endpoint_api in the Graylog server configuration to the connection URI for the reverse proxy, and as far as I can see there are no problems, with one exception. 

The Link for the API browser in the /system/nodes page is not rewritten to the web_endpoint_uri but still uses the local value (in this case, http://127.0.0.1:9000) for the REST API behind the proxy. This way, the link obviously doesn't work via the reverse proxy.

This can easily be verified in the source for the UI element:

    <a href="/system/nodes/33d18463-c0e0-4c8d-9581-42868e49e2f8" class="btn btn-info" role="button" data-reactid=".0.2.0.0.0.1.0.1.$33d18463-c0e0-4c8d-9581-42868e49e2f8.0.0.0.0.0.0">Details</a>
    <a href="/system/metrics/node/33d18463-c0e0-4c8d-9581-42868e49e2f8" class="btn btn-info" role="button" data-reactid=".0.2.0.0.0.1.0.1.$33d18463-c0e0-4c8d-9581-42868e49e2f8.0.0.0.0.0.1">Metrics</a>
    <a href="http://127.0.0.1:9000/api/api-browser" target="_blank" class="btn btn-info" role="button" data-reactid=".0.2.0.0.0.1.0.1.$33d18463-c0e0-4c8d-9581-42868e49e2f8.0.0.0.0.0.2">
        <i class="fa fa-external-link" data-reactid=".0.2.0.0.0.1.0.1.$33d18463-c0e0-4c8d-9581-42868e49e2f8.0.0.0.0.0.2.0"></i>
        <span data-reactid=".0.2.0.0.0.1.0.1.$33d18463-c0e0-4c8d-9581-42868e49e2f8.0.0.0.0.0.2.1">&nbsp; API browser</span>
    </a>

Thinking about it, the issue might be that the API browser is specific to the node, not necessarily the node running the web UI, so replacing it with web_endpoint_uri might not be the smartest choice. An alternative would be to make the URI for the API Browser separately configurable on a per-node basis. 

* Graylog Version: 2.2.3-1
* Elasticsearch Version: 2.4.4-1
* MongoDB Version: 2.6.12-4.el7
* Operating System: CentOS 7.3
* Browser version: Safari 10.1, Firefox 53.0

**Comment by joschi** [comment] 2017-04-21 13:14
Duplicate of #3718.

**Closed by joschi** 2017-04-21 13:14 UTC
