### ISSUE TITLE
Search shows "searched in 0 indices"

### ISSUE THREAD

**Issue by gruselglatz** [Graylog2/graylog2-server#2920] opened 2016-10-04 11:47 UTC
Search shows "searched in 0 indices" until your search range is longer than your last range recalculation job was done.

Messages and everything are shown normally.
## Expected Behavior

The correct indices should be shown which was used to search.
## Current Behavior

Range re-calculated 5 hours ago in 791ms. 55 segments, 0 open search contexts, 0 deleted messages

Now search with "range < 5h" gives you "Found 191,931 messages  in 23 ms, searched in 0 indices."
Searches with range >=5h gives you "Found 18,226,516 messages  in 518 ms, searched in 1 index."
## Possible Solution

?
## Steps to Reproduce (for bugs)

described above
## Your Environment

Graylog 2.1.1+01d50e5 on syslog.xyz.local (Oracle Corporation 1.8.0_102 on Linux 3.10.0-327.22.2.el7.x86_64)
- Elasticsearch Version: 2.3.5
- MongoDB Version: 3.2.9

**Comment by joschi** [comment] 2017-01-09 17:10
@gruselglatz I've been trying to reproduce this issue for some time now but came out empty handed.

The index range calculation and search queries work as designed on Graylog 2.2.0-beta.4.

Here's one of the successful use cases:
```
# Calculation timestamps of the index ranges
$ curl -s -u admin:admin http://127.0.0.1:9000/api/system/indices/ranges | jq '.ranges[]?.calculated_at'
"2017-01-09T17:00:03.940Z"
"2017-01-09T15:14:13.539Z"
"2017-01-09T16:56:04.095Z"
"2017-01-09T17:00:33.995Z"

# Current timestamp on the machine
$ date -I'minutes' -u
2017-01-09T17:06+00:00

# Search query for the last minute (last index range calculation was 6 minutes ago)
$ curl -s -u admin:admin 'http://127.0.0.1:9000/api/search/universal/relative?query=*&range=60' | jq '.used_indices[].index_name'
"graylog2_93"

# Search query for the last 20 minutes
$ curl -s -u admin:admin 'http://127.0.0.1:9000/api/search/universal/relative?query=*&range=1200' | jq '.used_indices[].index_name'
"graylog2_91"
"graylog2_93"
"graylog2_92"
```

As I can't reproduce the error, I will close this issue. Please check if you still have problems with Graylog 2.2.0-beta.4 and add a comment if the problem persists.

**Closed by joschi** 2017-01-09 17:10 UTC
Labels: bug, triaged
