### ISSUE TITLE
automatic master election

### ISSUE THREAD

**Issue by schlitzered** [Graylog2/graylog2-server#2331] opened 2016-06-03 07:47 UTC
### Problem description
hey i would like to not be responsible for keeping a graylog server master up and running, they should instead be able to do master election by them self.

i guess you could ether integrate zookeeper into the binary, or rely on the underling database & try to implement some sort of exclusive lock that only one instance can hold.

**Comment by joschi** [comment] 2016-06-03 07:48
Closing as duplicate of #810.

**Closed by joschi** 2016-06-03 07:48 UTC
