### ISSUE TITLE
Impossible type any query, because any charackter is doubled, triplet, etc.

### ISSUE THREAD

**Issue by minzak** [Graylog2/graylog2-server#9451] opened 2020-11-11 14:42 UTC
I use graylog 3.2.6 in docker and my host is Debian buster with Firefox - and all is fine:

![normal](https://user-images.githubusercontent.com/12154217/98824452-01193900-243c-11eb-9800-8e89a29422ea.gif)

But when I try to upgrade graylog to upper any version, for example 3.2.8
I got this strange behaviour!
P.S. I also use in private mode, even other version Firefox normal and ESR - all the same.
In Console window (F12) all network result is fine, 200 - OK.
How to fix it, how to find it what is wrong?

I'm just trying type work **message** and additional some digits
![typing](https://user-images.githubusercontent.com/12154217/98824939-91f01480-243c-11eb-8b3e-63162d882eca.gif)

**Comment by dennisoelkers** [comment] 2020-11-11 14:44
Hey @minzak,

this is a duplicate of #8332. Please check that issue for advice on how to fix it.

**Closed by dennisoelkers** 2020-11-11 14:44 UTC
Labels: bug
