### ISSUE TITLE
Quick values histogram in all messages

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#4316] opened 2017-11-03 16:40 UTC
## Expected Behavior
Quick values histogram in all messages should draw available data.

## Current Behavior
Quick values histogram in all messages draws data since Jan 1st 1970:
<img width="1671" alt="screen shot 2017-11-03 at 17 19 31" src="https://user-images.githubusercontent.com/716185/32384466-45c93e98-c0bb-11e7-8c16-1d639ed9afd6.png">

## Possible Solution
One possible solution is to add boundaries into the server response containing the graph data, as we do in [histograms](https://github.com/Graylog2/graylog2-server/blob/aada4c64b6e8fae20bf972aa40fec330d5686137/graylog2-server/src/main/java/org/graylog2/rest/resources/search/SearchResource.java#L224).

## Steps to Reproduce (for bugs)
1. Open search page, search in all messages
2. Display quick values for a field
3. Show as histogram and see that the x-axis starts in 1970

## Your Environment
* Graylog Version: 2.4.0-beta.1

**Comment by bernd** [comment] 2020-11-14 21:49
I am unable to reproduce this with the new search. Closing the issue.

**Closed by bernd** 2020-11-14 21:49 UTC
Labels: #M, bug, improvement, triaged
