### ISSUE TITLE
Input "Show received messages" Search Timeframe Improvement

### ISSUE THREAD

**Issue by ryan-carroll-graylog** [Graylog2/graylog2-server#16436] opened 2023-09-12 19:09 UTC
## What?
Make the "Show received messages" search timeframe configurable or change it from All Time to something lower.

![image](https://github.com/Graylog2/graylog2-server/assets/103449971/2c77d48c-8162-46cd-a9ae-b11ca77ed5ff)

Currently this is hard coded to All Time:
https://github.com/Graylog2/graylog2-server/blob/f2e9d8f98f829fc5cede76b6b3c1eda710005239/graylog2-web-interface/src/components/inputs/InputListItem.jsx#L109

## Why?

This is causing problems for cloud customers who have a very high volume of logs and multiple users clicking this button, as they are forced to query for potentially GBs of data.

## Your Environment

* Graylog Version: 5.1
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by mpfz0r** [comment] 2023-09-12 19:50
refs https://github.com/Graylog2/graylog2-server/pull/5621

**Comment by dennisoelkers** [comment] 2023-09-13 06:19
Closing this as duplicate of #5260/#10260

**Closed by dennisoelkers** 2023-09-13 06:19 UTC
Labels: feature
