### ISSUE TITLE
Graylog There are 2 notifications

### ISSUE THREAD

**Issue by Nik0laev** [Graylog2/graylog2-server#2356] opened 2016-06-15 14:20 UTC
Hi all. Help to deal with the problem. set Graylog V2.0.2 Set up nodes on the Graylog2 server. After some time the problem appears. Tell me what to do?
Graylog Version: v2.0.2 ,Virtual Appliances, OVA
![error](https://cloud.githubusercontent.com/assets/19946029/16083350/c07e09b8-3325-11e6-970c-05a364d103c9.png)
![sys_info](https://cloud.githubusercontent.com/assets/19946029/16083355/c4e1959c-3325-11e6-9aa0-524d0a5c5a84.png)

**Comment by joschi** [comment] 2016-06-15 14:26
Closing as duplicate of Graylog2/graylog2-images#150.

@Nik0laev 
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Closed by joschi** 2016-06-15 14:26 UTC
