### ISSUE TITLE
Creating new input errors w/ Address already in use.

### ISSUE THREAD

**Issue by kurowskydb** [Graylog2/graylog2-server#1487] opened 2015-10-15 12:52 UTC
graylog-server 1.2.1

Creating a new input will fail no matter the type of input with the following error:
__Error starting this input: Address already in use.__
A restart of graylog-server is required.
Once the server is back up all new inputs are green and running.
Title of Input has wrong port number (created for testing)
![image](https://cloud.githubusercontent.com/assets/11399008/10514063/aae67012-7319-11e5-8fd2-b52c676fa565.png)

![image](https://cloud.githubusercontent.com/assets/11399008/10514109/df2ff53c-7319-11e5-8fd1-c96218952843.png)
```
2015-10-15T08:45:09.040-04:00 ERROR [InputLauncher] The [org.graylog2.inputs.syslog.tcp.SyslogTCPInput] input with ID <561f9fd4c2dcffeac2430f37> misfired. Reason: Address already in use.
org.graylog2.plugin.inputs.MisfireException: org.graylog2.plugin.inputs.MisfireException: org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:11514
        at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:161)
        at org.graylog2.shared.inputs.InputLauncher$1.run(InputLauncher.java:84)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.graylog2.plugin.inputs.MisfireException: org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:11514
        at org.graylog2.plugin.inputs.transports.NettyTransport.launch(NettyTransport.java:161)
        at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:158)
        ... 7 more
Caused by: org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:11514
        at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
        at org.graylog2.plugin.inputs.transports.NettyTransport.launch(NettyTransport.java:147)
        ... 8 more
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:414)
        at sun.nio.ch.Net.bind(Net.java:406)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        ... 3 more
```

**Comment by joschi** [comment] 2015-10-15 13:46
I just tried to reproduce this with Graylog 1.2.1 but everything worked as expected.
Are you 100% sure that no other process or no other input was bound to 0.0.0.0:11514/tcp at that time? Which operating system are you running the Graylog server node on?

**Comment by kurowskydb** [comment] 2015-10-15 15:00
Positive.  I'm running Centos7 minimum install.  
This is a just a testing setup, everything running on the same box.
Next to nothing else running on the box.

Now I think it just may be a false positive... netstat is showing the port as listening after launching 

Here's another example:

![image](https://cloud.githubusercontent.com/assets/11399008/10517704/f2cc5574-732b-11e5-8319-f6f0ca0eec34.png)

TCP ports listening before restarting graylog-server service:
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      1607/mongod
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1239/sshd
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1855/master
tcp6       0      0 127.0.0.1:12900         :::*                    LISTEN      1271/java
tcp6       0      0 :::9350                 :::*                    LISTEN      1271/java
tcp6       0      0 :::9000                 :::*                    LISTEN      1250/java
tcp6       0      0 :::12201                :::*                    LISTEN      1271/java
tcp6       0      0 :::9200                 :::*                    LISTEN      1241/java
tcp6       0      0 :::9300                 :::*                    LISTEN      1241/java
tcp6       0      0 :::22                   :::*                    LISTEN      1239/sshd
tcp6       0      0 ::1:25                  :::*                    LISTEN      1855/master


TCP ports listening after restarting graylog-server service:

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      1607/mongod
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1239/sshd
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1855/master
tcp6       0      0 127.0.0.1:12900         :::*                    LISTEN      1271/java
tcp6       0      0 :::9350                 :::*                    LISTEN      1271/java
tcp6       0      0 :::9000                 :::*                    LISTEN      1250/java
tcp6       0      0 :::12201                :::*                    LISTEN      1271/java
tcp6       0      0 :::9200                 :::*                    LISTEN      1241/java
tcp6       0      0 :::9300                 :::*                    LISTEN      1241/java
tcp6       0      0 :::22                   :::*                    LISTEN      1239/sshd
tcp6       0      0 ::1:25                  :::*                    LISTEN      1855/master
tcp6       0      0 :::20514                :::*                    LISTEN      1271/java  <-------

**Comment by kurowskydb** [comment] 2015-10-15 17:30
Uninstalling and reinstalling graylog-server appears to have corrected the issue.

**Comment by joschi** [comment] 2015-10-19 08:00
@kurowskydb Thanks for the feedback. I'm closing this issue as "can't reproduce".

**Closed by joschi** 2015-10-19 08:00 UTC

**Comment by qfissler** [comment] 2016-03-30 14:16
This issue has occured for me with the AWS AMI.

**Comment by akrasov** [comment] 2016-06-22 20:34
having the same with the AWS AMI

**Comment by rickmckeon** [comment] 2017-11-02 16:00
Solved in AWS AMI by setting the Input's bind_address to 0.0.0.0

**Comment by joschi** [comment] 2018-02-09 16:55
@juliohm1978 We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
