### ISSUE TITLE
Messages far in the future leads to broken search

### ISSUE THREAD

**Issue by gruselglatz** [Graylog2/graylog2-server#3286] opened 2017-01-03 11:44 UTC
If you get Messages form the Future, say 31.12.2017 due to a misconfig or something, the search ends up to search in the latest index and in the index with the future message in it.

But it wont show you any message until you do an index range recalc. It shows the same behavour like in this issue: #2920

## Expected Behavior
Messages should be showed anyway.

## Current Behavior
Search is broken

## Possible Solution
?

## Steps to Reproduce (for bugs)
1. Send message with a future date
2. rotate indices
3. recalc
4. wait 6 minutes
5. try to search messages for the last 5 minutes
6. see nothing

## Context
due to some misconfiguration it could happen to get a message from the future.

## Your Environment

Graylog 2.1.2+50e449a on xyz.local (Oracle Corporation 1.8.0_111 on Linux 3.10.0-327.22.2.el7.x86_64)

**Comment by joschi** [comment] 2017-01-03 11:48
@gruselglatz Searches with a relative time range "5 minutes ago" will do exactly that: search for messages with a timestamp between 5 minutes ago and "now". It will *not* search for messages with timestamps further in the future.

**Comment by gruselglatz** [comment] 2017-01-03 12:20
@joschi yes i know that, but it should show me something, i know it doesnt show me the messages from the future. When i delete the messages form the Future the search starts working normally.

**Comment by joschi** [comment] 2017-01-05 16:50
@gruselglatz I couldn't reproduce this on current `master` (which is basically Graylog 2.2.0-beta.4 as of now).

I've have an index set with multiple indices and sent a GELF message with a future timestamp (2018-01-01T00:00:00.000Z) to a GELF UDP input:
```
echo -n '{"version":"1.1", "message":"TEST", "timestamp": 1514764800}' | nc -u -w1 127.0.0.1 12201
```

The message was ingested successfully and can be queried with an absolute time range (e. g. from 2017-12-31T00:00:00.000Z to 2018-01-01T00:00:00.000Z). Other, existing messages with timestamps in the past (and which are in all of the existing indices) can still be found.

Since I couldn't reproduce the issue, I'm closing this issue.

**Closed by joschi** 2017-01-05 16:50 UTC
