### ISSUE TITLE
Saving new dashboard fails with error message

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#7017] opened 2019-12-18 13:49 UTC
## Expected Behavior
Saving a new dashboard using the "Save" action menu entry should not fail with an error message.

## Current Behavior
The menu shows both "Save" and "Save as", but only "Save as" asks for a title.
"Save" simply fails with a client error.

The console shows the following error:

<details>
{"type":"ApiError","message":"Cannot construct instance of `org.graylog.plugins.views.search.views.ViewDTO$Builder`, problem: Missing required properties: title\n at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 1353]"}
</details>

## Possible Solution
Either gracefully handle the error or avoid sending the broken request and ask for the missing attributes before doing so.

## Steps to Reproduce (for bugs)
![save-new-dashboard](https://user-images.githubusercontent.com/52014/71091315-28707300-21a5-11ea-9bda-a99deecdc37a.gif)

## Your Environment

* Graylog Version: 3.2.0-SNAPSHOT+c9c2ee7

**Comment by dennisoelkers** [comment] 2019-12-18 14:08
Duplicate of #6735?

**Closed** 2019-12-18 14:09 UTC
Labels: bug
