### ISSUE TITLE
support multiple plugin paths

### ISSUE THREAD

**Issue by cnf** [Graylog2/graylog2-server#2854] opened 2016-09-19 14:31 UTC
Hi,

If one uses the docker image for graylog, the plugins live in `/usr/share/graylog/plugin`. In order to add new ones, one can bind a host dir to the container `docker run -v /host/graylog/plugins:/usr/share/graylog/plugin`, but then you overwrite the supplied plugins.

One could copy the supplied plugins to the host dir, but then they would not be upgraded when a new version of graylog image is run.

**proposed solution**: If graylog can scan its plugin dir recursively, then one can bind mount the 3rd party plugins into the existing dir, and keep the supplied ones through upgrades: `docker run -v /host/graylog/plugins:/usr/share/graylog/plugin/3rdparty`

This would create a layout like this, for example:

```
/usr/share/graylog/plugin
|-- graylog-plugin-beats-1.1.1.jar
|-- graylog-plugin-collector-1.1.1.jar
|-- graylog-plugin-enterprise-integration-1.1.1.jar
|-- graylog-plugin-map-widget-1.1.1.jar
|-- graylog-plugin-pipeline-processor-1.1.1.jar
|-- usage-statistics-2.1.1.jar
`-- 3rdparty
    |-- graylog-plugin-netflow-0.1.1.jar
    |-- graylog-plugin-slack-2.2.1.jar
    |-- graylog2-plugin-input-httpmonitor-1.0.3.jar
```

The main plugin dir holds the included plugins, the 3rd party one the externally linked ones.

**Comment by bernd** [comment] 2020-11-15 01:45
Duplicate of https://github.com/Graylog2/graylog2-server/issues/6482

**Closed by bernd** 2020-11-15 01:45 UTC
Labels: feature, triaged
