### ISSUE TITLE
Graylog3 WebUI not working when adding paths

### ISSUE THREAD

**Issue by twky** [Graylog2/graylog2-server#5786] opened 2019-03-19 13:37 UTC
WebUI 'system' tab is not accessible/working in graylog 3 as in 2.4.6 though using migration guide running in docker. 

in version 2.4.6. i used 
rest_listen_uri= 0.0.0.0:9000/abc/

now it should be:
http_bind_address = 0.0.0.0:9000
http_publish_uri = http://server.name.org:8080/abc/

published docker ports: 8080:9000

## Expected Behavior
Adding paths should work as in 2.4.6
## Current Behavior
the path is added once too often
![image](https://user-images.githubusercontent.com/48345644/54609738-d5ba2d00-4a53-11e9-8ce6-acbcb1928ff5.png)

## Your Environment
official docker images

* Graylog Version: 3
* Elasticsearch Version: 6.6.1
* MongoDB Version: 3
* Operating System: CentOS 7
* Browser version: Chrome 72.0.3626.121

**Comment by dennisoelkers** [comment] 2019-03-19 13:43
Duplicate of #5702. Expect this to be fixed in `3.0.1`.

**Closed by dennisoelkers** 2019-03-19 13:43 UTC
