### ISSUE TITLE
api-browser takes ~120 seconds to load

### ISSUE THREAD

**Issue by drewmmiranda** [Graylog2/graylog2-server#2922] opened 2016-10-04 15:55 UTC
## Expected Behavior
servername:port/api-browser should load within a second or 2.

## Current Behavior
Page takes 120 SECONDS to fully load.

## Steps to Reproduce (for bugs)

1. Navigate to servername:port/api-browser
2. observe page hanging with no feedback

## Context
Not a huge issue, but could be impactful if we wanted to build and test new API queries. This issue occurs on all 3 of our Graylog Nodes (data nodes 1 and 2 as well as web interface node). This issue seems to have been introduced with 2.x or possibly 2.1

It appears that the following 3 files are causing the request to hang:
(via chrome debug tools)
1. swagger-ui.js (1.5 min)
2. highlight.7.3.pack.js (1.5 min)
3. sha256.js (1.5 min)

## Your Environment

* Graylog Version: Graylog 2.1.1+01d50e5
* Elasticsearch Version: 2.3.3
* MongoDB Version: 2.6.11
* Operating System: CentOS 7 x86_64 , Linux 3.10.0-229.11.1.el7.x86_64
* Browser version: Chrome53 , Firefox 49

**Comment by drewmmiranda** [comment] 2016-10-04 15:58
Hi @joschi , apologies if this was already submitted. I couldn't find any existing issues.

**Comment by joschi** [comment] 2016-10-04 15:58
@drewmmiranda Thanks for reporting this!

The problem is being caused by the GZip compression on the Graylog REST API and will be addressed in Graylog 2.2.0.

As workaround, try setting [`rest_enable_gzip = false`](https://github.com/Graylog2/graylog2-server/blob/2.1.1/misc/graylog.conf#L97-L99) in your Graylog configuration.

Refs #2894

**Closed by joschi** 2016-10-04 15:58 UTC
Labels: known issue

**Comment by drewmmiranda** [comment] 2016-10-04 16:00
FYI, the default must have been changed. The configuration file implies this is disabled by default. I am not explicitly setting this. I will uncomment the line and set to false.

**Comment by joschi** [comment] 2016-10-04 17:23
@drewmmiranda 
> FYI, the default must have been changed.

Yes, it did.

> The configuration file implies this is disabled by default.

Default values are explicitly given (in the comments), the rest is just provided as an example.
