### ISSUE TITLE
Too many SetIndexReadOnly system jobs scheduled?

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#920] opened 2015-01-26 16:24 UTC
there's no indication of which index they are for, possibly caused by my incredibly low retention/rotation settings.
need to investigate
![screenshot](https://cloud.githubusercontent.com/assets/52014/5903116/204e67f0-a580-11e4-9735-64814d647c28.png)

**Comment by kroepke** [comment] 2015-03-03 16:02
maybe not possible to display the index the job is for, if not this is not critical. just go and read the code again to make sure it's not completely broken (which is unlikely, but still)

**Comment by joschi** [comment] 2015-03-10 14:21
FWIW, I couldn't reproduce the issue with low rotation interval.

**Comment by kroepke** [comment] 2015-03-10 14:24
possibly this was an artifact of something else, my rotation interval was really short and load was really high.

**Comment by joschi** [comment] 2015-03-11 17:12
Closed by merging #1054 and Graylog2/graylog2-web-interface#1161

**Closed by joschi** 2015-03-11 17:12 UTC
Labels: bug
