### ISSUE TITLE
Getting java exception in graylog server.log

### ISSUE THREAD

**Issue by nilroy** [Graylog2/graylog2-server#1650] opened 2015-12-23 12:56 UTC
Hi,

We are using graylog 1.3.2 and we are getting some consistent errors in graylog server.log majorly the below ones. One thing I noticed is all these messages are having a playload size more than 1024 bytes(not sure if that is the cause of the errors). We are trying to find out the issue. Any kind of help will be highly appreciated.
```
2015-12-23T11:26:58.250Z ERROR [DecodingProcessor] Error processing message RawMessage{id=140912a0-a968-11e5-a39c-12fc6716df61, journalOffset=6911478187, codec=gelf, payloadSize=2369, timestamp=2015-12-23T11:26:58.250Z}
java.util.zip.ZipException: invalid distance too far back
[...]
2015-12-23T11:27:00.394Z ERROR [DecodingProcessor] Error processing message RawMessage{id=15501190-a968-11e5-a39c-12fc6716df61, journalOffset=6911479405, codec=gelf, payloadSize=1448, timestamp=2015-12-23T11:27:00.393Z}
java.io.EOFException: Unexpected end of ZLIB input stream
[...]
2015-12-23T11:27:02.808Z ERROR [DecodingProcessor] Error processing message RawMessage{id=16c06a70-a968-11e5-a39c-12fc6716df61, journalOffset=6911480847, codec=gelf, payloadSize=1820, timestamp=2015-12-23T11:27:02.807Z}
java.util.zip.ZipException: Corrupt GZIP trailer
```

**Comment by kroepke** [comment] 2015-12-23 12:58
Are you using GELF over UDP? 
If so you are likely seeing packet loss or truncated packets, please check you network stats for UDP errors or drops.
If possible I'd try to use TCP for larger packets.

**Comment by nilroy** [comment] 2015-12-28 10:28
Yes we are using GELF over UDP... Previously we were not seeing these many errors and it started coming from last two months. I shall try seeing the UDP packet drops

**Comment by VictorSlavov** [comment] 2016-01-05 13:05
Hi,
I recently set up a graylog server version 1.3.0 (later updated to 1.3.2)
I see the same exceptions in the graylog-server.log.
What I did in order to figure where is the problem is to capture all the messages coming through the GELF UDP input for a short period. During this period I received few of the exceptions in the graylog-server.log. Then I manually extracted and gun-zipped all the messages from the captured stream and non of them had errors.
At first I also suspected network problem and drop of packages. But this test makes me think it is something in graylog itself, something related to writing/reading to/from the journal.
My setup is still up and running if you need some more info I can provide it.

**Comment by VictorSlavov** [comment] 2016-01-08 12:30
Hi kroepke,
Can you guess what this might be. Any hint what to check?

**Comment by VictorSlavov** [comment] 2016-01-11 15:41
I started second graylog server node without journal and redirected the load to it. Unfortunately I see the same errors again.
[graylog_errors.txt](https://github.com/Graylog2/graylog2-server/files/85957/graylog_errors.txt)

**Comment by VictorSlavov** [comment] 2016-01-16 11:19
Not sure why I put this here any more, but here is what I could find.
This is some problem with the chunked gelf messages. I use gelfj to send the messages to the graylog server. All chunked messages end up like this:

[gelf_chunks_map.txt](https://github.com/Graylog2/graylog2-server/files/92861/gelf_chunks_map.txt)
Capturing UDP packets shows that the third packed arrived, but for some reason the graylog server ignored it. I can successfully re-assemble the captured UDP packets manually and de-compress the message.

**Comment by nilroy** [comment] 2016-02-19 13:12
@VictorSlavov  Thanks for your insight on this issue. I am hoping that this bug is resolved soon.

**Comment by VictorSlavov** [comment] 2016-02-19 13:52
@nilroy It's not graylog server bug. It was a problem in gelfj library we are using. The problem was with long UDP chunked messages. It was fixed in gelfj-1.1.13

**Comment by nilroy** [comment] 2016-02-19 13:55
@VictorSlavov Ahh thats a valuable input.. I shall try that one

**Comment by joschi** [comment] 2016-02-19 14:14
@VictorSlavov Thanks for the update! I'm closing this issue since it's not a bug in Graylog.

**Closed by joschi** 2016-02-19 14:14 UTC
Labels: bug, P4, S2
