### ISSUE TITLE
Grok pattern Extractors crashes and drop logs

### ISSUE THREAD

**Issue by BaptisteBdn** [Graylog2/graylog2-server#7363] opened 2020-02-04 09:38 UTC
After I upgraded Graylog to 3.2 I found that one extractor containing a grok pattern was constantly crashing, the logs were then forever lost. 

## Expected Behavior
When I add an extractor with a grok pattern for syslog and select "Always try to extract", graylog should not drop the logs that failed!

## Current Behavior
I added the following extractor : 
![Screenshot_2020-02-04 Graylog - New extractor for input Beats(1)](https://user-images.githubusercontent.com/31347719/73732090-d7f3ab80-4739-11ea-9260-c2b275a3bf62.png)

And I can see in graylog-server logs : 
```
2020-02-04T10:16:09.713+01:00 WARN  [ProcessBufferProcessor] Unable to process message <fb393704-472e-11ea-bb88-4256e21dfc8e>: java.lang.ClassCastException: Cannot cast java.lang.String to org.joda.time.DateTime
2020-02-04T10:16:09.713+01:00 WARN  [ProcessBufferProcessor] Unable to process message <fb393705-472e-11ea-bb88-4256e21dfc8e>: java.lang.ClassCastException: Cannot cast java.lang.String to org.joda.time.DateTime
2020-02-04T10:16:09.713+01:00 WARN  [ProcessBufferProcessor] Unable to process message <fb393706-472e-11ea-bb88-4256e21dfc8e>: java.lang.ClassCastException: Cannot cast java.lang.String to org.joda.time.DateTime
2020-02-04T10:16:09.958+01:00 WARN  [ProcessBufferProcessor] Unable to process message <fb5e7245-472e-11ea-bb88-4256e21dfc8e>: java.lang.ClassCastException: Cannot cast java.lang.String to org.joda.time.DateTime
2020-02-04T10:16:09.958+01:00 WARN  [ProcessBufferProcessor] Unable to process message <fb5e7244-472e-11ea-bb88-4256e21dfc8e>: java.lang.ClassCastException: Cannot cast java.lang.String to org.joda.time.DateTime
2020-02-04T10:16:09.958+01:00 WARN  [ProcessBufferProcessor] Unable to process message <fb5e7243-472e-11ea-bb88-4256e21dfc8e>: java.lang.ClassCastException: Cannot cast java.lang.String to org.joda.time.DateTime
2020-02-04T10:16:10.076+01:00 WARN  [ProcessBufferProcessor] Unable to process message <fb709ab4-472e-11ea-bb88-4256e21dfc8e>: java.lang.ClassCastException: Cannot cast java.lang.String to org.joda.time.DateTime
2020-02-04T10:16:10.077+01:00 WARN  [ProcessBufferProcessor] Unable to process message <fb70c1c0-472e-11ea-bb88-4256e21dfc8e>: java.lang.ClassCastException: Cannot cast java.lang.String to org.joda.time.DateTime
```
When this happened, I have lost a lot of logs that were not indexed in graylog.
When I delete the extractor everything work smoothly. 

## Possible Solution
Catch the error so that the logs can be indexed even tho the extractor failed ? 

## Steps to Reproduce (for bugs)
1. Graylog in 3.2
2. Add an extractor with the Grok Pattern from above
3. Add logs that do not match the Grok Pattern to Graylog

## Context
This bug automatically dropped logs without warning.

## Your Environment

* Graylog Version: 3.2
* Elasticsearch Version: 
* MongoDB Version:
* Operating System: Linux/Debian
* Browser version: Firefox

**Comment by bernd** [comment] 2020-02-04 09:41
@BaptisteBdn thank you for the report! This related to https://github.com/Graylog2/graylog2-server/issues/7364 and we are currently working on a fix for that.

**Comment by mpfz0r** [comment] 2020-02-04 10:46
Duplicate of #7364

**Closed by mpfz0r** 2020-02-04 10:46 UTC
Labels: bug, processing
