### ISSUE TITLE
JSON extractor fails to parse timestamp in ISO8601 format

### ISSUE THREAD

**Issue by tiagomlalves-talkdesk** [Graylog2/graylog2-server#2030] opened 2016-04-05 14:12 UTC
### Problem description

JSON extractor fails to parse timestamp in ISO8601 UTC format. Input is '2016-04-05T13:13:09.633Z' and exception is:

message [MapperParsingException[failed to parse [timestamp]]; nested: MapperParsingException[failed to parse date field [2016-04-05T13:13:09.633Z], tried both date format [yyyy-MM-dd HH:mm:ss.SSS], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: "2016-04-05T13:13:09.633Z" is malformed at "T13:13:09.633Z"]; ]

My expectation would be that at least JSON parser would fall back to interpret this field as string and not fail altogether. The better solution would be parsing this field correctly.

### Steps to reproduce the problem

1. Create a JSON extractor
2. Load a sample log:

`{"application":{"name":"dummy-app","component":"dummy-component"},"timestamp":"2016-04-05T14:09:02.670Z","measurement":{"source":"method","metric":"throughput","value":0.537671}}`

3. Click "Try!" Here the preview works perfectly showing that the son was extracted correctly
4. Click "Create Extractor"
5. Check graylog2-server logs and see that messages as from the sample are creating JSON parsing exceptions. 

### Environment

Docker image graylog2/allinone retrieved on 2016-04-05.
graylog-web-interface v1.3.4 (0d67a80) (Oracle Corporation 1.8.0_66 / Linux 4.1.19-boot2docker) on 777153dc2b18

**Comment by kroepke** [comment] 2016-04-11 09:47
You need to convert the timestamp field to a proper timestamp using the "flex date" converter, the JSON extractor does not interpret the field value at all in this case.
The elasticsearch mapping expects a certain format, which unfortunately is not ISO 8601.

I'll close the issue for now, as this is not a bug per se.

Thanks,
Kay

**Closed by kroepke** 2016-04-11 09:47 UTC
Labels: question

**Comment by eli-jordan** [comment] 2016-04-23 08:33
I have run into this problem too. What is the date format that elastic search understands? I can have a timestamp generated in that format. Otherwise, is it possible to use a converter on a field that is extracted using the json extractor? I couldn't see how to do this.

**Comment by joschi** [comment] 2016-04-23 09:50
@eli-jordan The format of the `timestamp` field in Graylog's index mapping is defined as "yyyy-MM-dd HH:mm:ss.SSS" (see https://github.com/Graylog2/graylog2-server/blob/2.0.0-rc.1/graylog2-server/src/main/java/org/graylog2/plugin/Tools.java#L60).
