### ISSUE TITLE
Introduce stripped down DTOs for search and dashboard endpoints

### ISSUE THREAD

**Issue by alex-konn** [Graylog2/graylog2-server#7457] opened 2020-02-14 10:35 UTC
Search/dashboard endpoints should read & return only summary (id, title, description) of entities, to:  
- reduce the size of the payload for listing entities
- prevent that the addition/removal of fields in the views makes listing them fail

**Comment by dennisoelkers** [comment] 2020-02-24 09:20
Duplicate of #7051.

**Closed by dennisoelkers** 2020-02-24 09:20 UTC
Labels: improvement, search
