### ISSUE TITLE
Change absolute paths referenced in "api-browser" to relatives

### ISSUE THREAD

**Issue by pdepaepe** [Graylog2/graylog2-server#1602] opened 2015-12-03 14:59 UTC
Hello,

It's currently quite difficult to serve api-browser behind a proxy with an other url, ie "api/graylog/api-browser" because (at least) hard-coded absolute paths references in this file:

https://github.com/Graylog2/graylog2-server/blob/d002467fae770bfe045bad75ce79850cfb2dee0b/graylog2-server/src/main/resources/swagger/index.html

May you please consider to change theses to relative access?

Thanks.

**Comment by bernd** [comment] 2016-01-29 13:42
Duplicate of #1576. Please see that issue for updates. Thank you!

**Closed by bernd** 2016-01-29 13:42 UTC
