### ISSUE TITLE
LDAP intergration with AD - LDAP filter only returns one 'memberof' entry, can't filter on group membership

### ISSUE THREAD

**Issue by timcoop3r** [Graylog2/graylog2-server#1279] opened 2015-07-01 14:45 UTC
Hi,

I am trying to setup the LDAP integration with a filter than only allows users that are 'memberof' a specific Graylog Security group, however the LDAP feature only seems to return one 'memberof' entry for a user and as such the filter only works if you specify that they are a member of that specific group that it will return, rather than the Graylog group. Clearly this doesn't work well for users that are members of more than one group. Am I doing something wrong or is this something that needs fixing?

My filter is as follows:

(&(objectClass=user)(sAMAccountName={0})(memberof=cn=Graylog,OU=Security Groups,OU=example group,DC=example,DC=local))

If I change this to:

(&(objectClass=user)(sAMAccountName={0})(memberof=cn=working-group,OU=Security Groups,OU=example group,DC=example,DC=local))

The test login works and returns the users details and a single under 'memberof':

memberof
CN=working-group,OU=Security Groups,OU=example group,DC=example,DC=local

**Comment by kroepke** [comment] 2015-07-23 17:03
At this moment Graylog does not support groups, but we are working on it right now.

This is also a duplicate of #951, so I'll close it. Please track the other issue.

Thanks,
Kay

**Closed by kroepke** 2015-07-23 17:03 UTC
