### ISSUE TITLE
RFC5424 structured data parsing

### ISSUE THREAD

**Issue by cybermedi** [Graylog2/graylog2-server#845] opened 2015-01-06 21:40 UTC
Base on Jochen recommendation https://groups.google.com/forum/#!searchin/graylog2/5424/graylog2/KO91vcZIOXo/vcEPEwAT6e4J

I would like to create issue:

I have an application which creates log in RFC5424 and send them to my central rsyslog server. Logs are resend to graylog2 via syslog protocol. Graylog2 runs local INPUT tcp syslog on 10514.
Configuration of rsyslog resending looks like:

```
$template GRAYLOGRFC5424,"<%pri%>%protocol-version% %timestamp:::date-rfc3339% %HOSTNAME% %app-name% %procid% %STRUCTURED-DATA% %msg%\n"
*.* @@172.100.100.100:10514;GRAYLOGRFC5424
```

all logs are received by graylog2 without any issue but they are not parsed properly. They are parsed like basic RFC5424 message. Structured data are handled like "message". 

the full message looks like:

```
<190>1 2015-01-06T20:56:33.287Z app-1 app - [mdc@18060 ip="::ffff:132.123.15.30" logger="{c.corp.Handler}" session="4ot7"  user="cybermedi@yahoo.com" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/7.1.2 Safari/537.85.11"] User page 13 requested
```
I recieve message fields like:
<b>application_name</b>
app

<b>facility</b>
local7

<b>level</b>
Info [6]
 
<b>message</b>
[mdc@18060 ip="::ffff:132.123.15.30" logger="{c.corp.Handler}" session="4ot7"  user="cybermedi@yahoo.com" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/7.1.2 Safari/537.85.11"] User page 13 requested

<b>source</b>
app-1

but there should be other ones based on structured data.
Like: 
<i>ip, logger, session, user, user-agent</i>
and in the message should be just:
<i>User page 13 requested</i>

**Comment by lennartkoopmann** [comment] 2015-01-07 10:47
Which Graylog2 version are you running? @bernd fixed something regarding this recently.

**Comment by cybermedi** [comment] 2015-01-07 18:36
Hi Lennart,
I have 0.92.3 (102a59f) (Moose)
Regards,
Martin

7. 1. 2015 v 2:47, Lennart Koopmann <notifications@github.com>:

**Comment by dfch** [comment] 2015-01-11 16:14
I can confirm this behaviour (also running 0.92.3). In addition, the field ```MSGID``` seems to be treated as part of the message as well. 

Message on the wire:

```<128>1 2015-01-11T16:35:21.335797+01:00 s000000.dfch.biz - - - - tralala```

... will have Graylog2 recognise the ```message``` field as:

```- - tralala```

See [6.5. Examples](https://tools.ietf.org/html/rfc5424#section-6.5) for an example.

I used See [modified syslog sender](https://github.com/kjacobsen/PowerShellSyslog/commit/4d9c0fd6e0bdb0ff09fd2a7c576a62e3330a04bb#commitcomment-9233535) for testing.

**Comment by bernd** [comment] 2015-01-13 17:45
@cybermedi There are several issues unfortunately.

1. Your rsyslog template is wrong. The `%MSGID%` is missing. See [our docs](https://www.graylog2.org/resources/documentation/sending/syslog) for a template example. (our example was also wrong until yesterday...)
1. There are two spaces after the "session" key in your example. Is that a copy & paste error? If not, rsyslog might generate a structured data block that is not valid according to the RFC.
1. The syslog parser we are using does not support whitespace in structured data values like the "user-agent" one.

I am currently investigating if we can fix the whitespace-in-value parsing issue in our syslog parser.

**Comment by bernd** [comment] 2015-01-13 17:46
@dfch This also seems to be an issue with the syslog parser. As said in the previous comment, I will investigate.

**Comment by cybermedi** [comment] 2015-01-14 01:01
OK I added msgid to template. And it seems that that there is still something wrong with parsing. Structured data was not parsed, and the message begins with "-" (i think it is the msgid). In my message I have app-name I do not have procid and msgid, that's why raw messages contains:
<code> "app - - [mdc@18060...". </code>
The message beings:
<code>"- [mdc@18060..."</code>
what is interesting that %STRUCTURED-DATA% when they are empty are sometimes replaced by space and sometimes not. But finally the message contains two or three spaces between msgid and msg
ex:
<code>
sshd 4988 -  Accepted public key for
</code>
<code>
sudo - -   cybermedi : TTY=pts/0
</code>
 
OH I do not how to show it here, the first example has two spaces and the second three. Maybe I will need to have two templates for messages with structured data and one without. Maybe this issue should be fixed in rsyslog.

**Comment by bernd** [comment] 2015-01-14 16:58
@cybermedi The next beta (beta.2) will have a fix for the structured data parsing.

It will also remove the structured data from the message field.

@dfch If there is a NILVALUE for the structured data like you posted, the "- -" will still be in the message field. This is a shortcoming in the syslog parser which we cannot fix for 1.0 unfortunately.

See Graylog2/graylog2-server#872 for the pull request.

I am closing this ticket now. Please re-open if you still have issues with the next beta. Thank you for the report!

**Comment by cybermedi** [comment] 2015-02-12 14:21
Hi Bernd,
I deployed 1.0.0-9.rc.2.
1) you mentioned the issue with parsing white space. Is it fixed?
2) The structured data is correctly removed from "message"
3) The structured data is still not parsed.
I use the corrected template configuration: 
```
$template GRAYLOGRFC5424,"<%PRI%>%PROTOCOL-VERSION% %TIMESTAMP:::date-rfc3339% %HOSTNAME% %APP-NAME% %PROCID% %MSGID% %STRUCTURED-DATA% %msg%n"
*.* @@10.19.10.1:5514;GRAYLOGRFC5424 # Graylog forwarding
```

**Comment by bernd** [comment] 2015-02-12 15:08
Hey @cybermedi, thanks for the feedback!

Did you enable the "Expand structured data?" option on the input?

**Comment by cybermedi** [comment] 2015-02-12 15:13
Hi, yes 

Martin

12. 2. 2015 v 16:09, Bernd Ahlers <notifications@github.com>:

**Comment by bernd** [comment] 2015-02-12 16:08
There is an issue if the "Expand structured data?" option is enabled. Without this, the structured data is parsed.

Thanks for the report!

**Comment by bernd** [comment] 2015-02-12 16:41
I created a pull request in #965.

@cybermedi As a workaround you can disable the "Expand structured data" option.

**Comment by bernd** [comment] 2015-02-12 16:56
@cybermedi The fix (#965) got merged and will be availablein an upcoming snapshot or RC.

**Closed by bernd** 2015-02-12 16:56 UTC
Labels: bug, processing

**Comment by cybermedi** [comment] 2015-02-13 11:26
thanx it works now.

**Comment by bernd** [comment] 2015-02-13 11:28
Great, thanks for the feedback!
