### ISSUE TITLE
Error starting this input: Cannot assign requested address.

### ISSUE THREAD

**Issue by kurtihnet** [Graylog2/graylog2-server#1869] opened 2016-02-27 07:34 UTC
### Problem description

While adding new input to Graylog master server, I'm getting the below error.
```
Error starting this input: Cannot assign requested address. 
```

I have tried syslog as TCP and UDP, got the same error.

```
vzstandby (Syslog UDP) failed

On node a7747720 / graylog.test.com
Error starting this input: Cannot assign requested address.

    override_source:
    recv_buffer_size: 262144
    allow_override_date: true
    bind_address: 67.222.101.167
    port: 1514

Throughput / Metrics
1 minute average rate: 0 msg/s
Network IO: 0B 0B (total: 0B 0B )
vzstandby1 (Syslog TCP) failed

On node a7747720 / graylog.test.com
Error starting this input: Cannot assign requested address.

    recv_buffer_size: 1048576
    port: 1514
    tls_key_file: admin
    tls_key_password: *******
    tls_client_auth_cert_file:
    max_message_size: 2097152
    tls_client_auth: optional
    override_source:
    allow_override_date: true
    bind_address: 67.222.101.167
    tls_cert_file:
```

I have opened the port 1514 on graylog master server  and added the graylog master details to client
```
[root@ ~]# cat /etc/rsyslog.d/90-graylog2.conf 
$template GRAYLOGRFC5424,"%protocol-version% %timestamp:::date-rfc3339% %HOSTNAME% %app-name% %procid% %msg%\n"
*.* @67.222.96.54:1514;GRAYLOGRFC5424
```
Is there any way to fix this?

### Steps to reproduce the problem

1.  

### Environment

* Graylog Version: 1.2.2
* Elasticsearch Version: 1.7.5
* MongoDB Version: 3.0.9
* Operating System: CentOS Linux release 7.2

**Comment by kurtihnet** [comment] 2016-03-01 17:16
Hi,

Is there any update on this?

**Comment by kurtihnet** [comment] 2016-03-01 21:10
Its one of our graylog client test server IP.

**Comment by joschi** [comment] 2016-03-02 08:49
@kurtihnet Replace that IP address with `0.0.0.0` and try again.

**Comment by kurtihnet** [comment] 2016-03-08 21:12
Hi,

That worked, thanks.

But when we were added the another server with bind address as "0.0.0.0", it was showing the address has already in use. Due to this, the logs were not recorded in graylog master server. 

We have used the below configuration in our client servers.

====
$template GRAYLOGRFC5424,"%protocol-version% %timestamp:::date-rfc3339% %HOSTNAME% %app-name% %procid% %msg%\n"
*.* @graylogmaster:1514;GRAYLOGRFC5424
====

Opened the port 1514 in master also.

Any suggestions?

**Comment by joschi** [comment] 2016-03-09 08:14
`0.0.0.0` basically means "bind to every network interface". If you want to use different inputs or processes on the same port, they have to use specific network interfaces and cannot all use "all network interfaces".

In your case, there's already some other input or process listening on port 1514.

Closing this issue as it's not a bug in Graylog. Please continue the discussion on the [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or in [#graylog on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

**Closed by joschi** 2016-03-09 08:14 UTC
Labels: question

**Comment by mdsahi** [comment] 2019-05-07 07:22
An input has failed to start (triggered 8 days ago)
Input 5cc2e01b476ab51563c7b174 has failed to start on node 67aabba5-eff6-477b-aadd-32ed5d06562a for this reason: »bind(..) failed: Cannot assign requested address.«. This means that you are unable to receive any messages from this input. This is mostly an indication for a misconfiguration or an error. You can click here to solve this.



Error Message:
    Unable to perform search query "Unauthorized"
Details:
    "Unauthorized"
Search status code:
    500
Search response:
    cannot GET http://192.168.2.25:9000/api/search/universal/relative?query=gl2_source_input%3A5cc2e01b476ab51563c7b174&range=0&limit=150&sort=timestamp%3Adesc (500)
