### ISSUE TITLE
Data Adapter page: Reduce of empty array with no initial value

### ISSUE THREAD

**Issue by mathieuchateau** [Graylog2/graylog2-server#7056] opened 2019-12-23 09:45 UTC
## Expected Behavior
From lookup table page, clicking on Data Adapters blue button, page should load.

## Current Behavior
Web site display "Something went wrong" on url : /system/lookuptables/data_adapters
![image](https://user-images.githubusercontent.com/4478521/71349988-908dd300-2570-11ea-9461-0bc7bc268b8c.png)

`Reduce of empty array with no initial value

Stack Trace:

TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at t.render (http://mygralogserver/assets/90afab18-1.af2f821c666e2573f8ad.js:1:14211)
    at ka (https://mygralogserver/assets/vendor.91c91d4a31d54d96392a.js:18:63009)
    at Sa (https://mygralogserver/assets/vendor.91c91d4a31d54d96392a.js:18:62804)
    at Da (https://mygralogserver/assets/vendor.91c91d4a31d54d96392a.js:18:66638)
    at Fo (https://mygralogserver/assets/vendor.91c91d4a31d54d96392a.js:18:90682)
    at Vo (https://mygralogserver/assets/vendor.91c91d4a31d54d96392a.js:18:91066)
    at Ys (https://mygralogserver/assets/vendor.91c91d4a31d54d96392a.js:18:97953)
    at Ss (https://mygralogserver/assets/vendor.91c91d4a31d54d96392a.js:18:97333)
    at Ls (https://mygralogserver/assets/vendor.91c91d4a31d54d96392a.js:18:96354)
    at Zo (https://mygralogserver/assets/vendor.91c91d4a31d54d96392a.js:18:95228)
    at Object.enqueueSetState (https://mygralogserver/assets/vendor.91c91d4a31d54d96392a.js:18:44755)
    at t.b.setState (https://mygralogserver/assets/vendor.91c91d4a31d54d96392a.js:26:1665)
    at a.n (https://mygralogserver/assets/vendor.91c91d4a31d54d96392a.js:10:1324)
    at a.emit (https://mygralogserver/assets/vendor.91c91d4a31d54d96392a.js:90:240635)
    at h.trigger (https://mygralogserver/assets/vendor.91c91d4a31d54d96392a.js:10:2199)
    at https://mygralogserver/assets/builtins.af2f821c666e2573f8ad.js:128:72142
    at l (https://mygralogserver/assets/builtins.af2f821c666e2573f8ad.js:104:88608)
    at O._settlePromiseFromHandler (https://mygralogserver/assets/builtins.af2f821c666e2573f8ad.js:104:61890)
    at O._settlePromise (https://mygralogserver/assets/builtins.af2f821c666e2573f8ad.js:104:62690)
    at O._settlePromise0 (https://mygralogserver/assets/builtins.af2f821c666e2573f8ad.js:104:63389)
    at O._settlePromises (https://mygralogserver/assets/builtins.af2f821c666e2573f8ad.js:104:64716)
    at https://mygralogserver/assets/builtins.af2f821c666e2573f8ad.js:104:18338

Component Stack:

    in MetricContainer
    in td
    in tr
    in tbody
    in t
    in table
    in t
    in span
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in span
    in t
    in LUTDataAdaptersPage
    in n
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in t
    in withRouter(t)
    in div
    in App
    in RouterContext
    in Router
    in h
    in t
    in n
    in AppFacade`

## Steps to Reproduce (for bugs)
1. Log on graylog 3.1.3
2. Go to System / Lookup Tables
3. Click on Data Adapters blue icon top right of the screen.
4. Error message display.

## Context
I want to create a data adapters for Geo location

## Your Environment
CentOS 8
Graylog 3.1.3

* Graylog Version: 3.1.3+cda805f
* Elasticsearch Version: 6.8.5-1 
* MongoDB Version: 4.2.2-1.el8
* Operating System: Centos 8
* Browser version: Chrome 79

**Comment by qarmin** [comment] 2020-01-30 11:31
I had today same error with different Stack Trace 
```
reduce of empty array with no initial value

Stack Trace:

render@https://Roman/assets/app.9019bbb55e618ace00d4.js:68:541053
go@https://Roman/assets/vendor.5452e7a2fdfb6282da0a.js:18:65535
yo@https://Roman/assets/vendor.5452e7a2fdfb6282da0a.js:18:65330
Qs@https://Roman/assets/vendor.5452e7a2fdfb6282da0a.js:18:99620
Is@https://Roman/assets/vendor.5452e7a2fdfb6282da0a.js:18:83908
Rs@https://Roman/assets/vendor.5452e7a2fdfb6282da0a.js:18:80933
Ps@https://Roman/assets/vendor.5452e7a2fdfb6282da0a.js:18:79506
_i/<@https://Roman/assets/vendor.5452e7a2fdfb6282da0a.js:18:41771
29/exports.unstable_runWithPriority@https://Roman/assets/vendor.5452e7a2fdfb6282da0a.js:42:3998
fi@https://Roman/assets/vendor.5452e7a2fdfb6282da0a.js:18:41500
_i@https://Roman/assets/vendor.5452e7a2fdfb6282da0a.js:18:41719
mi@https://Roman/assets/vendor.5452e7a2fdfb6282da0a.js:18:41652
Ds@https://Roman/assets/vendor.5452e7a2fdfb6282da0a.js:18:78497
enqueueSetState@https://Roman/assets/vendor.5452e7a2fdfb6282da0a.js:18:46463
24/b.prototype.setState@https://Roman/assets/vendor.5452e7a2fdfb6282da0a.js:26:1438
n@https://Roman/assets/vendor.5452e7a2fdfb6282da0a.js:10:1594
614/a.prototype.emit@https://Roman/assets/vendor.5452e7a2fdfb6282da0a.js:78:243907
trigger@https://Roman/assets/vendor.5452e7a2fdfb6282da0a.js:10:2469
list/r<@https://Roman/assets/builtins.9019bbb55e618ace00d4.js:68:8092
l@https://Roman/assets/builtins.9019bbb55e618ace00d4.js:76:90514
YPyIcTeH/</</<[22]</r.exports/O.prototype._settlePromiseFromHandler@https://Roman/assets/builtins.9019bbb55e618ace00d4.js:76:63769
YPyIcTeH/</</<[22]</r.exports/O.prototype._settlePromise@https://Roman/assets/builtins.9019bbb55e618ace00d4.js:76:64569
YPyIcTeH/</</<[22]</r.exports/O.prototype._settlePromise0@https://Roman/assets/builtins.9019bbb55e618ace00d4.js:76:65268
YPyIcTeH/</</<[22]</r.exports/O.prototype._settlePromises@https://Roman/assets/builtins.9019bbb55e618ace00d4.js:76:66595
YPyIcTeH/</</<[2]</s.prototype._drainQueue@https://Roman/assets/builtins.9019bbb55e618ace00d4.js:76:20459
YPyIcTeH/</</<[2]</s.prototype._drainQueues@https://Roman/assets/builtins.9019bbb55e618ace00d4.js:76:20520
s/this.drainQueues@https://Roman/assets/builtins.9019bbb55e618ace00d4.js:76:18743


Component Stack:

    in SystemJobsComponent
    in h
    in ConnectStoresWrapper[h] stores=currentUser
    in span
    in t
    in t
    in n
    in div
    in t
    in div
    in t
    in div
    in l
    in div
    in i
    in t
    in withRouter(t)
    in c
    in d
    in ConnectStoresWrapper[d] stores=currentUser
    in t
    in withRouter(t)
    in RouterContext
    in Router
    in m
    in t
    in n
    in t
    in c
    in AppFacade
```

    Graylog Version: 3.2.0-3.beta.3
    Elasticsearch Version: 6.8.6-1
    MongoDB Version: 4.0.14-1.el7
    Operating System: CentOS 7
    Browser version: Firefox 72.0.2

**Comment by edmundoa** [comment] 2020-01-30 11:37
So these are two different issues:

@mathieuchateau: The issue you reported is the same as https://github.com/Graylog2/graylog2-server/issues/6864, which should be fixed in 3.2.0.

@qarmin: The issue you reported is new to me, I'll try to reproduce it.

**Comment by qarmin** [comment] 2020-01-30 11:46
After connecting to Graylog a sidecar from CentOS machine, Graylog starts to really slow(very slow loading of tabs)

I restarted Graylog server and I got this error.

Logs, which have a lot of backtraces from MongoDB - [FFFFFFFFFFFFFFFFFFF.txt](https://github.com/Graylog2/graylog2-server/files/4133820/FFFFFFFFFFFFFFFFFFF.txt)

**Comment by edmundoa** [comment] 2020-01-30 13:01
@qarmin when you post different issues in the same one it gets really hard for other people to follow what is going on, so please try to keep each issue in a different tickets.

Additionally, we use GitHub issues for tracking bugs in Graylog itself, and I'm not sure your last error description is one, would you be so kind as to posting it in the [Graylog discussion forum](https://community.graylog.org/)?

Thank you!

**Comment by edmundoa** [comment] 2020-01-30 13:49
@qarmin I opened this ticket for your initial issue: https://github.com/Graylog2/graylog2-server/issues/7329

Since the initial issue is already fixed in https://github.com/Graylog2/graylog2-server/issues/6864, I'll close this ticket now. @mathieuchateau please reopen the issue if it still occurs in 3.2.0.

**Closed by edmundoa** 2020-01-30 13:49 UTC
Labels: to-verify
