### ISSUE TITLE
Input should stay stopped after "Edit input"

### ISSUE THREAD

**Issue by HolgerOpenSource** [Graylog2/graylog2-server#3479] opened 2017-02-10 09:33 UTC
**Manually stopped inputs are started again after we changed input parameters with "Edit input".**

## Expected Behavior
Input should stay in stopped state after edit input.

## Current Behavior
Input starts automatically after saving the changes in input definition.

## Possible Solution
Change code.

## Steps to Reproduce (for bugs)
1. stop input
2. edit input (change for instance the port number)
3. save changed input
4. input ist now in started state

## Context
Sometime we manually stop inputs to avoid overloading of Graylog during certain time frames. Manually stopped inputs must only start again when we do it manually.

## Your Environment

Versions:
- Graylog 2.1.2 
- elasticsearch 2.3.5
- mongoDB 3.2.1
- Linux SLES 11
- Browser Firefox ESR 45.2.0

**Comment by joschi** [comment] 2017-02-16 10:49
Almost a duplicate of #967.

**Comment by billmurrin** [comment] 2017-05-12 06:51
I wanted to solicit feedback from you guys on how you wanted to implement this. I don't mind helping code it (would be a fun project for me to learn more about under the hood), but I don't want to do it on my own without feedback on how you guys want it implemented in the system?

**Closed** 2017-05-16 12:05 UTC
Labels: bug, in progress, triaged
