### ISSUE TITLE
Folders/Categories for Streams

### ISSUE THREAD

**Issue by madiTG** [Graylog2/graylog2-server#4982] opened 2018-08-09 09:00 UTC
Having tons of streams i would like to create some categories/organize the,

## Expected Behavior
Tree like structure in streams view

## Current Behavior
Simple list of streams

## Possible Solution
:)

## Context
filtering for streams is ineffective, when I go into one, and then go back I loose the filter

## Your Environment

* Graylog Version: Graylog 2.4.6+ceaa7e4

**Comment by jalogisch** [comment] 2018-08-10 16:50
this is a duplicate of https://github.com/Graylog2/graylog2-server/issues/382

while this issue is quite old upcoming versions will improve this part of Graylog and I close this in favour of the old open issue.

**Closed by jalogisch** 2018-08-10 16:50 UTC
