### ISSUE TITLE
Sporadic login error with alpha.1

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#1762] opened 2016-02-04 09:39 UTC
I saw the following error *once* when I was trying to login to the web interface. There was also another report from a user.

```
error – the server returned: undefined
```
The error appears in the red error box above the user/password form.

This looks like an unhandled corner case when trying to login.

**Comment by edmundoa** [comment] 2016-02-04 10:58
I could only reproduce the issue while the server was not available during log-in. Since we merged #1754 today, we are able to detect that case and inform the user about that.

Please reopen if we have more information about it :+1:

**Closed by edmundoa** 2016-02-04 10:58 UTC
Labels: web

**Comment by marksie1988** [comment] 2016-02-09 11:03
I am seeing this issue also, fresh install of version alpha.1. when i deploy the VM i have run: 

```
sudo graylog-ctl set-timezone GMT
sudo graylog-ctl set-admin-username 
sudo graylog-ctl set-admin-password
sudo graylog-ctl reconfigure
```

i then try to login but it doesn't seem to be working. if you need me to check any logs etc please let me know.

**Comment by mariussturm** [comment] 2016-02-09 11:14
@marksie1988 how do you access the web interface? There are vasically three ways: HTTP via port 80, HTTPS via port 443 and directly via port 9000. Could you please test all three ports and see which one works?

**Comment by marksie1988** [comment] 2016-02-09 11:26
ok so if i do it HTTP it works fine, HTTPS throws the error, 9000 also works fine.

**Comment by joschi** [comment] 2016-02-09 11:31
@marksie1988 Which browser on which operating system are you using? Are there any error messages in the developer console of your browser?

* Chrome: https://developer.chrome.com/devtools/docs/console
* Firefox: https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console
* IE: https://msdn.microsoft.com/en-us/library/dn255006(v=vs.85).aspx

**Comment by marksie1988** [comment] 2016-02-09 11:42
I am currently using IE for this, developer tools show no errors. However in chrome i see this: 

`
vendor.js:402 Download the React DevTools for a better development experience: https://fb.me/react-devtools
client.js:1026 Mixed Content: The page at 'https://192.168.88.204/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://192.168.88.204:12900/system/sessions'. This request has been blocked; the content must be served over HTTPS.Request.end @ client.js:1026(anonymous function) @ index.js:61tryCatcher @ bluebird.js:4589Promise._resolveFromResolver @ bluebird.js:2668Promise @ bluebird.js:2258Request.promise @ index.js:60Request.then @ index.js:95json @ FetchProvider.js:74login @ SessionStore.js:45n @ vendor.js:31o.emit @ vendor.js:410e.exports.trigger @ vendor.js:31(anonymous function) @ vendor.js:31(anonymous function) @ vendor.js:31o.run @ vendor.js:1r @ vendor.js:1
`

**Comment by mariussturm** [comment] 2016-02-11 15:49
With the new web interface of Graylog 2.0 we need a different SSL configuration like we have currently on the appliances. The API and the web interface port need both encryption, a mixed mode leads to this error.
For alpha.2 we will disable the default configuration of HTTPS temporally. In this way you can only access the web interface via HTTP on port 80 or 9000. We will work on a way to automatically enable SSL on all needed ports vie `graylog-ctl`.
