### ISSUE TITLE
Search query on paginated tables is cleared when navigating to a different tab, but the actual table filtering isn't reset so table is empty

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#14318] opened 2022-12-27 16:22 UTC
Not sure how to explain this exactly. For example, when on page System / Lookup Tables, inputting a search query to filter the list of lookup tables will only show search matches:

![image](https://user-images.githubusercontent.com/107503402/209692842-a99692f5-4acb-4bde-a4d6-3eba2bd6205e.png)

When navigating to a different tab (not sure what these are called?)

![image](https://user-images.githubusercontent.com/107503402/209692928-481f81d7-86bc-4cf2-962b-9a325d8d7dcf.png)

The page is updated to show the contents of that tab. Everything is working as expected at this point.

Now, if you go back to the original "tab" (again not sure what we refer to these as?) the search box is empty but the page is blank:

![image](https://user-images.githubusercontent.com/107503402/209693145-f3ecf54b-15c8-4469-ac7f-a2df62f01256.png)

Using the reset box shows the page contents again:

![image](https://user-images.githubusercontent.com/107503402/209693215-6ee3e819-b4ef-448f-8d68-af13aac95cc2.png)

## Expected Behavior

Paginated search box results are always reset on page navigation or changing tabs on the page.

## Current Behavior

Page is empty with no results.

## Possible Solution

Not sure if related to https://github.com/Graylog2/graylog2-server/issues/14108

## Steps to Reproduce (for bugs)

1. Navigate to System / Lookup Tables
2. Input a search term that returns 0 results
3. Click on the 'Data Adapters' "tab"
4. Click on 'Lookup Tables' "tab" to return to original page
5. observe that page is empty

## Your Environment

* Graylog Version: 5.0.1
* Java Version: 17.0.5
* Elasticsearch Version: OpenSearch 2.4.1
* MongoDB Version: 5.0.14
* Operating System: Ubuntu 20.04 LTS
* Browser version: Google Chrome 108.0.5359.124

**Comment by drewmiranda-gl** [comment] 2022-12-27 16:22
I searched for similar issues to avoid creating a duplicate issue. I'm not certain if https://github.com/Graylog2/graylog2-server/issues/14108 is related or not.

**Comment by HungryHowies** [comment] 2023-01-04 01:39
@drewmiranda-gl 

I just tried your instruction on GL 4.3.10. Same thing 🤔

**Comment by boosty** [comment] 2023-01-09 15:32
@ousmaneo Could you check if this is similar to https://github.com/Graylog2/graylog2-server/issues/14108?

**Comment by ousmaneo** [comment] 2023-01-10 15:30
Hi @boosty, I looked, and the issue is slightly different from #14108. I went ahead and provided a fix for this one with this issue with this [PR](https://github.com/Graylog2/graylog2-server/pull/14405)

**Comment by boosty** [comment] 2023-01-10 15:36
@ousmaneo Great, thank you!

**Closed** 2023-01-13 10:40 UTC
Labels: bug, triaged, ux
