### ISSUE TITLE
Sidecar Configuration Path variable needs a better description

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#5044] opened 2018-08-30 20:49 UTC
I just got stuck for a good while because I did not understand what the Configuration Path variable is for.

![screenshot from 2018-08-30 15-48-06](https://user-images.githubusercontent.com/35022/44878318-2ca11600-ac6c-11e8-814e-2bc851d9cd36.png)

I now know that this is where the generate configuration file will be written to. We should describe that better. We should also note that the file has to exist (I had to `touch` it) and that it, of course, has to be writeable.

**Comment by bernd** [comment] 2018-08-31 06:45
We have a discussion in https://github.com/Graylog2/graylog2-server/issues/4887 to move generated configuration files into something like `/var/lib/graylog-sidecar/configurations`.

Also I was wondering if it's really useful for the user to be able to specify the generated configuration path. I am currently unable to come up with a use case where this is important. For the execution and test parameters we provide the `%s` placeholder where the path to the generated configuration file will be inserted later.

@lennartkoopmann @mariussturm @edmundoa Can you come up with any use cases where it's necessary to manually configure the path of the generated configuration on the sidecar node?

If we want to keep the configurable configuration path, we might want to consider to put the recommended configuration folder into the global sidecar configuration (System/Configurations) and expose another placeholder that can be used in the "Configuration Path" setting to avoid hardcoding the recommended path into every collector backend instance.

**Comment by lennartkoopmann** [comment] 2018-09-02 23:07
I can't come up with a use-case where I would want to specify my own path and specifying my own path lead to headaches about file permissions and general confusion.

If no one else can find a good use-case, I'm all in for removing that option and to use a standard path that we can maybe still make configurable through the sidecar config file.

**Comment by lennartkoopmann** [comment] 2018-09-02 23:17
Wait. I think I just came across a use-case:

For rsyslog, I want to create the configuration file at `/etc/rsyslog.d/51-graylog.conf` so it is automatically included when `rsyslogd` starts up. I don't want to manage *all* the rsyslog configuration using sidecar, but only the connection to Graylog.

Does that make sense? Can we maybe pre-fill the parameter with a standard path to avoid confusion?

**Comment by bernd** [comment] 2018-09-03 07:15
@lennartkoopmann See my comment in https://github.com/Graylog2/graylog2-server/issues/5051#issuecomment-418017186 about managing the system installation of rsyslogd and other system processes.

**Comment by mpfz0r** [comment] 2018-10-29 09:41
The decision in our meeting in Hamburg last week, was to remove the Configuration Path option.
We don't have a strong use case for this feature yet, thus it's better to start with less ;)

**Comment by mpfz0r** [comment] 2018-11-05 10:52
Move this to a fresh and less confusing bug:
Duplicate of #5265

**Closed by mpfz0r** 2018-11-05 10:52 UTC
Labels: sidecar
