### ISSUE TITLE
upstart init script does not set open files limit high enough

### ISSUE THREAD

**Issue by rblumen-desk** [Graylog2/graylog2-server#1601] opened 2015-12-03 02:05 UTC
Our graylog server ran out of socket connections.  See trace below.  The cause was that it ran at the default number of open files which is 4096.  This can be overridden in the graylog2-server.conf with a limit directive.

2015-11-27T18:21:29.302Z WARN  [AbstractNioSelector] Failed to accept a connection.
java.io.IOException: Too many open files
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
:

**Comment by joschi** [comment] 2015-12-03 11:18
Duplicate of Graylog2/fpm-recipes#52.

**Closed by joschi** 2015-12-03 11:18 UTC
