### ISSUE TITLE
Dashboard: Create Aggregation errors out

### ISSUE THREAD

**Issue by kyleknighted** [Graylog2/graylog2-server#10555] opened 2021-05-03 16:37 UTC
## Expected Behavior

- Create new Dashboard
- Click Create within left sidebar
- Choose `Generic Aggregation`
- Have widget load with no data

## Current Behavior

After choosing `Generic Aggregation` the Error Page loads with 
```Cannot read property 'first' of undefined```

**Comment by kmerz** [comment] 2021-05-31 14:39
Unable to reproduce. Probably fixed by now.

**Closed by kmerz** 2021-05-31 14:39 UTC
Labels: bug, dashboards, triaged, widgets
