### ISSUE TITLE
Crashing the API browser with a big size parameter (browser issue)

### ISSUE THREAD

**Issue by renapu** [Graylog2/graylog2-server#1743] opened 2016-02-01 12:45 UTC
Hi,

when you enter a number which is bigger than the allowed integer range the API-browser is going to die silently without an error. I think the API should return an error.

GET /search/universal/keyword/termsstats => set the size to 99999 and try it.

1.3.3 (0fda9dc) (Hansa)

EDIT: After some long time the api-browser is responding and  delivers some data. But the Cluster load  wasn't high

EDIT2: After some research we found out that chrome is the problem, and it cant handle the big output very well. Maybe you should limit the output in the API-Browser. I think most of the Time the API-Browser is used for convenient building queries for cmd-line.

**Comment by kroepke** [comment] 2016-02-04 14:30
The api browser is mostly for convenience purposes and to help browsing the api.
Currently we won't improve it to the point of providing the resiliency you requested. Furthermore the code is from the Swagger project and would take a lot of effort to "fix".
Closing this because it behaves as designed.

Thank you!

**Closed by kroepke** 2016-02-04 14:30 UTC
