### ISSUE TITLE
Copy token button no longer works

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#18788] opened 2024-03-25 19:17 UTC
When creating a token, a copy button is provided for convenience. This no longer copies the token.

![image](https://github.com/Graylog2/graylog2-server/assets/107503402/9d6f871c-b395-4055-a550-30be999a7fa0)

## Expected Behavior

Token is copied

## Current Behavior

token is not copied

## Steps to Reproduce (for bugs)

1. Create a new token
2. Click on the copy button

## Context

Testing sidecars in 6.0.beta.3

There are no web browser console errors.

## Your Environment

* Graylog Version: 6.0.beta.3
* Mac OS Sanoma 14.4.1
* Google Chrome Version 123.0.6312.87 (Official Build) (arm64)
* Also tested with Windows 11 and Firefox (same issue)

**Comment by ousmaneo** [comment] 2024-03-28 10:11
Hi @drewmiranda-gl, I couldn't reproduce the issue described here.
Can you give me more details on how to reproduce it?

**Comment by drewmiranda-gl** [comment] 2024-04-01 20:16
See in this video https://videos.graylog.com/watch/EJ6zJeRL2Pf2JLfUotHbZk?

I recorded the video using Graylog 6.0.0-beta.3 but just retested after upgrading to beta.4 and it still happens.

**Comment by drewmiranda-gl** [comment] 2024-04-01 20:21
This appears to not be unique to the token copy_content button, i observe the same issue with the scratch pad as well. Cannot use the copy_content button (it doesn't copy any text).

![image](https://github.com/Graylog2/graylog2-server/assets/107503402/a0197324-79c7-4502-9c88-cd57c4a1fb2f)

**Comment by drewmiranda-gl** [comment] 2024-04-01 20:22
i added my PC and browser details.

**Comment by ousmaneo** [comment] 2024-04-04 08:41
Thank you, @drewmiranda-gl, for the details. I checked your new info and found an issue with the Scratchpad copy that will be fixed with this [PR](https://github.com/Graylog2/graylog2-server/pull/18874).
Regarding the issue with the Create token copy, I still can't reproduce it, as you can see in the video below. Still, it might be related to a new component library providing the **CopyButton** we use on that page. I'm working on that one.

![copy](https://github.com/Graylog2/graylog2-server/assets/1381455/3bfc07ae-7b56-4d4f-8273-32031ee50cae)

**Closed** 2024-04-05 11:13 UTC
Labels: bug, triaged, test-day
