### ISSUE TITLE
Make Views and Saved Searchs exportable

### ISSUE THREAD

**Issue by yoke88** [Graylog2/graylog2-server#6810] opened 2019-11-15 01:12 UTC
Make Views and Saved Searchs exportable
## What?

I can not export views and saved searchs

## Why?

mainly i have a test environment and a product environment ,the saved search  and views can not export and import easyly , so these items is not reusable

## Your Environment

* Graylog Version:  Graylog 3.1.3+cda805f on localhost (Oracle Corporation 1.8.0_171 on Linux 3.10.0-1062.4.1.el7.x86_64)
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Centos 7.9
* Browser version: chrome 78.0.3904.97

**Comment by dennisoelkers** [comment] 2019-11-15 08:39
Thanks @yoke88 for reporting this. Can you tell us how your ideal workflow for exporting/importing views & saved searches would look like?

**Comment by jalogisch** [comment] 2019-11-15 10:22
I personal see this as a duplicate of: https://github.com/Graylog2/graylog2-server/issues/6596

**Comment by yoke88** [comment] 2019-11-15 11:37
if you have used grafana,  i wish i can export the view and saved search as json files,which i can import it back and i can edit it with a editor

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dennisoelkers** [comment] 2021-08-23 08:48
Duplicate of #6596.

**Closed by dennisoelkers** 2021-08-23 08:48 UTC
Labels: feature
