### ISSUE TITLE
Search field auto completion cuts results

### ISSUE THREAD

**Issue by HolgerOpenSource** [Graylog2/graylog2-server#3559] opened 2017-03-01 08:26 UTC
Results from auto completion are cut on cursor position when hitting the enter key. Search string is incomplete and search fails.

## Expected Behavior

Results from auto completion should stay in input field when hitting the enter key to start searching.

## Current Behavior

Results from auto completion will be cut on cursor position. Search string is incomplete and search will fail.

## Possible Solution

Change auto completion behaviour.

## Steps to Reproduce (for bugs)

1. Type incomplete search string in search field
2. Look for auto complete suggestions
3. Hit enter.
4. Search is cut at cursor position.

## Context

Reduce typing in search field. Work with auto complete results.

## Your Environment

Versions:
- Graylog 2.2.1 
- elasticsearch 2.4.4
- mongoDB 3.2.1
- Linux SLES 11
- Browser Firefox ESR 45.2.0

**Comment by edmundoa** [comment] 2017-03-01 09:51
Hi @HolgerOpenSource,

If I understood correctly, the behaviour you are describing is like that by design. Let me put an example to explain it.

Let's assume you typed `time` in the search field, and to make the example easier, suppose the auto-completion shows only `timestamp:` as suggestion.

Currently, typing enter would perform a search using the current query (`time`), and you would have to select the suggestion (either by clicking it with your mouse, selecting it with the arrow keys on your keyboard, or pressing tab) and press enter to use that suggestion as the search query. This makes relatively easy to use your current query and the suggestion, as it uses a design solution that is quite common.

With the changes you are requesting, pressing enter at that point would perform a search for `timestamp:`, but I don't see how you would be able to search for `time` if you actually wanted to do so. In my opinion that is a no go, as it would be way more confusing for users typing in there, and our suggestions are not quite as good as to be used as a default.

That said, maybe there's something I am missing. Please correct me in that case.

**Comment by HolgerOpenSource** [comment] 2017-03-03 10:15
Hi edmundoa,
in my case auto completion shows:
**\_exists\_:du**ration
Cursor is located after "u" and auto completion shows only one suggestion. If I hit enter, a broken search is processed.

**Comment by dennisoelkers** [comment] 2018-01-19 08:50
The workflow is to use the Tab-key when a suggestion matches, pressing enter afterwards. Making enter automatically accept the highlighted suggestion instead of what is being typed is a no-go, just like @edmundoa said. I am closing this issue because the product's behavior is correct in my opinion.

**Closed by dennisoelkers** 2018-01-19 08:50 UTC
Labels: bug, triaged
