### ISSUE TITLE
Timestamp problem

### ISSUE THREAD

**Issue by ceveyp** [Graylog2/graylog2-server#4663] opened 2018-03-17 04:00 UTC
## Expected Behavior
All the timestamps should be EST timezone

## Current Behavior
The timestamp field says one hour behind EST, and the timestamp on the syslog messages says 4 hours ahead

## Your Environment
I am using Ubuntu server 16.04 VM. The timezone is set to EST for the OS, user and in the graylog conf file. 

* Graylog Version: 2.4.3
* Elasticsearch Version: 5.5.3
* MongoDB Version: 3.2.19
* Operating System: Ubuntu server 16.04
* Browser version: Chrome 64.0.3282.186

**Comment by joschi** [comment] 2018-03-17 12:30
Duplicate of #3853

**Closed by joschi** 2018-03-17 12:30 UTC

**Comment by joschi** [comment] 2018-03-17 12:31
@ceveyp As a workaround, you could set the timezone of the messages received by the syslog input via a processing pipeline rule:
http://docs.graylog.org/en/2.4/pages/pipelines.html

If you have further questions about how to do this, please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by ceveyp** [comment] 2018-03-17 14:00
How can I confirm if the messages are actually do not have a timezone? Also, I appreciate your suggestion, I will make a pipeline to set the timestamp to EST. However, you only answered part of my question. Why is the timestamp field also off by one hour? The time changed with daylight savings time, about a week ago. Why is it not just using the system time?

**Comment by joschi** [comment] 2018-03-17 15:41
> How can I confirm if the messages are actually do not have a timezone?

@ceveyp Take a look at what your syslogd is sending to Graylog, either via Wireshark/tcpdump or by enabling the storage of the full message in Graylog (see configuration settings of the syslog input).

> The time changed with daylight savings time, about a week ago. Why is it not just using the system time?

The system time of which system exactly? Graylog could receive messages from systems with vastly different timezones, so which one should be chosen? 🤔 

Food for thought: http://yellerapp.com/posts/2015-01-12-the-worst-server-setup-you-can-make.html

**Comment by ceveyp** [comment] 2018-03-17 20:05
Well, I THOUGHT the timestamp field was when the message was received by Graylog, in which case it  could just use the local system time. Then I thought the timestamp in the syslog messages was the remote time?

**Comment by joschi** [comment] 2018-03-17 20:27
@ceveyp The syslog input tries to parse the date in the syslog message and puts that into the "timestamp" field.

**Comment by ceveyp** [comment] 2018-03-20 21:22
Hi, I'm using java DateTime class to change the timezone, however, it's not able to parse the timezone. Here this is in my pipeline:

let timestamp = $message.timestamp;
let timestamp = parse_date(to_string(timestamp), "yyyy-MM-dd'T'HH:mm:ss.SSSZZ");

And I get an exception, for example:

For rule 'Change Timezone to EST': In call to function 'parse_date' at 5:20 an exception was thrown: Invalid format: "2018-03-20T17:19:57.000-04:00" is malformed at "-04:00"

I'm pretty sure, according to the documentation, it's ZZ for timezone with a colon. Do you know how to  fix this?

**Comment by joschi** [comment] 2018-03-21 08:15
@ceveyp Please move this discussion to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).
