### ISSUE TITLE
"Show received messages" sometimes does not execute search

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#8850] opened 2020-08-22 18:20 UTC
## Expected Behavior

When clicking on the "Show received messages" button on an input, I expect to see all messages received by the input.

## Current Behavior

The button will lead me to a search page with a correct query filled out, but it appears like that query is not being executed. I see all messages in my Graylog setup until I press the search button manually. It appears like an `*` query is executed while the query box is already filled with the `gl2_source_input:xxx` query.

*Important*: I cannot reliably reproduce this. It just appears to happen from time to time.

* Graylog Version: Graylog 3.3.3+88d0659

**Comment by dennisoelkers** [comment] 2020-08-24 07:23
I cannot reproduce this either. Do you see anything in your browser's console when it happens?

**Comment by dennisoelkers** [comment] 2021-06-07 09:32
Unable to reproduce. Closing this for now.

**Closed by dennisoelkers** 2021-06-07 09:32 UTC
Labels: bug, cannot reproduce, to-verify
