### ISSUE TITLE
5.1 - Dashboards that have a message widget with a decorator fail to load, Something went wrong page shown

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#15248] opened 2023-04-17 21:01 UTC
Current builds of Graylog 5.1 cause any dashboard that has a message table with at least 1 decorator configured to return a 'Something went wrong' page:

![image](https://user-images.githubusercontent.com/107503402/232609209-c33fcb19-df89-491c-9098-4d99ef9721ef.png)

```
There was an error fetching a resource: . Additional information: Could not deserialize view: Unrecognized field "_id" (class org.graylog2.decorators.AutoValue_DecoratorImpl), not marked as ignorable (5 known properties: "stream", "type", "id", "order", "config"])
 at [Source: (String)"{"type":"DASHBOARD","title":"z Testing Decorators","summary":"","description":"","search_id":"643db268616bef515458e954","properties":[],"requires":{},"state":{"aa8c47c3-a5af-4545-9665-fe3d6efe9b6b":{"titles":{},"widgets":[{"id":"a24dba72-eb99-4463-ae9a-27b84c3d1f79","type":"messages","filters":[],"timerange":null,"query":null,"streams":[],"config":{"fields":["timestamp","source"],"show_message_row":true,"show_summary":true,"decorators":[{"_id":"643db268616bef515458e953","type":"org.graylog2.deco"[truncated 626 chars]; line: 1, column: 732] (through reference chain: org.graylog.plugins.views.search.views.$AutoValue_ViewDTO$Builder["state"]->java.util.LinkedHashMap["aa8c47c3-a5af-4545-9665-fe3d6efe9b6b"]->org.graylog.plugins.views.search.views.$AutoValue_ViewStateDTO$Builder["widgets"]->java.util.HashSet[0]->org.graylog.plugins.views.search.views.widgets.messagelist.AutoValue_MessageListConfigDTO$Builder["decorators"]->java.util.ArrayList[0]->org.graylog2.decorators.AutoValue_DecoratorImpl["_id"])
Graylog 5.1.0-SNAPSHOT+eacf8b2 on ip-172-31-22-114.ec2.internal (Eclipse Adoptium 17.0.6 on Linux 5.10.165-143.735.amzn2.x86_64)
```

## Expected Behavior

Dashboards with message tables that have decorators load as expected and without error.

## Current Behavior

Dashboards with message tables that have decorators do not load, 'Something went wrong' page displayed.

## Steps to Reproduce (for bugs)

1. Access https://success.secdev.torch.sh/dashboards/643db24824930378d8669688 
2. OR, using Graylog 5.1
3. Create a new dashboard
4. Add a message table
5. Edit message table widget to add a 'Format String' decorator
6. Save dashboard
7. refresh entire page

## Context

Dashboards are broken.

## Your Environment

* Graylog Version:
    * Graylog 5.1.0-SNAPSHOT+eacf8b2
    * Graylog Cloud 5.1.0 (373)
* Browser version: Google Chrome Version 112.0.5615.121 (Official Build) (arm64)

Please let me know if there are any questions, if there is any additional information i can provide, or if there is anything further i can test/troubleshoot.

**Comment by dennisoelkers** [comment] 2023-04-18 06:27
Hey @drewmiranda-gl, 

thanks for reporting this. We are already tracking this issue in #15086.

Duplicate of #15086.

**Closed by dennisoelkers** 2023-04-18 06:27 UTC
Labels: bug
