### ISSUE TITLE
Why did you break Content Alert Condition in 3.0 

### ISSUE THREAD

**Issue by mahnunchik** [Graylog2/graylog2-server#5794] opened 2019-03-22 13:43 UTC
Why did you break Content Alert Condition in 3.0 ? It is not cool! I've lost a bunch of `error` alerts!

## Expected Behavior

Alert type:  Content Alert Condition
Field: `message`
Value: `*error`
Global setting: `GRAYLOG_ALLOW_LEADING_WILDCARD_SEARCHES: "true"`

Match message: `KeyError: ('coordinates', 'occurred at index 1101')`

## Current Behavior

`KeyError: ('coordinates', 'occurred at index 1101')` not matched by `*error`

## Possible Solution

FIX IT AS IT WAS IN VERSION 2

## Your Environment

* Graylog Version: `graylog/graylog:3.0`
* Elasticsearch Version: `docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.2`
* MongoDB Version: `mongo:3.6`
* Operating System: Ubuntu 18.04
* Browser version: Netscape navigator 2.0

**Comment by mahnunchik** [comment] 2019-04-12 10:28
Message: `KeyError: ('CRK', 'occurred at index 3991')`

![image](https://user-images.githubusercontent.com/780935/56030876-a0d58900-5d26-11e9-9ac5-9cbab5b2fc58.png)

Alert haven't been triggered.

**Comment by dennisoelkers** [comment] 2019-05-16 09:32
@mahnunchik: From which 2.x version of Graylog did you upgrade to 3.x?

**Comment by dennisoelkers** [comment] 2019-05-16 10:18
I tried to verify the issue in 2.5.2 and it does not work either. Are you sure that you did not change the alert condition or the message format? Did you change the ES version you are using? If yes, from which version to which one?

**Comment by mahnunchik** [comment] 2019-05-16 12:04
Hi @dennisoelkers 

Current environment:

```yml
services:

  mongo:
    image: mongo:4

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.1

  graylog:
    image: graylog/graylog:3.0
```

Previous environment:

```yml
services:

  mongo:
    image: mongo:3.6

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4

  graylog:
    image: graylog/graylog:2.5

```

I didn't change any alert conditions.

**Comment by dennisoelkers** [comment] 2019-05-17 08:33
Thanks for the response. From my investigation, I am questioning the claim that defining an alert condition like that matched in the past, for the following reason:

  1.) A field value content alert condition generates a query string that looks like this: `field:"value"`, in your case `message:"*Error"` (notice the quoting of the value. In order to match a message like the one you described, it would need to be an [exact match](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_field_names), looking like: `message:*Error` (notice the missing quoting) instead.

  2.) This behavior is the same for 2.5.x and 3.0.x, as it has not changed [for a long](https://github.com/Graylog2/graylog2-server/blame/2.5.2/graylog2-server/src/main/java/org/graylog2/alerts/types/FieldContentValueAlertCondition.java#L119) [time](https://github.com/Graylog2/graylog2-server/blame/3.0.2/graylog2-server/src/main/java/org/graylog2/alerts/types/FieldContentValueAlertCondition.java#L119). 

I do understand that this is not the desirable behavior. Given that we have a configuration switch that allows us to enable/disable leading wildcards, it would be useful to be able to define a working alert condition like yours. I would suggest you create another issue requesting the removal of the field value quoting in this alert condition.

As this does not seem to be a regression, I am closing this issue. If I have overlooked something or you have new information, please reopen it.

**Closed by dennisoelkers** 2019-05-17 08:33 UTC

**Comment by mahnunchik** [comment] 2019-05-17 09:17
Hi @dennisoelkers 

Thank you for you investigation.

I'm using the following setting to allow leading wildcard `GRAYLOG_ALLOW_LEADING_WILDCARD_SEARCHES: "true"`. I think it should affect alert conditions too.
