### ISSUE TITLE
SSO authenticated users not shown as active

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2620] opened 2016-08-05 10:52 UTC
## Expected Behavior
Should be real remote IP of client

## Current Behavior
For me it shows 127.0.0.1
![image](https://cloud.githubusercontent.com/assets/17475270/17434554/c48e1dca-5b13-11e6-9a66-301d973269d0.png)

## Context
Maybe the problem caused by proxy.
Client actualy connects to proxy, and proxy to graylog.
Can graylog support `X-Forwarded-For` header?

## Your Environment
* Graylog Version: 2.1.0-beta2

**Comment by kroepke** [comment] 2016-08-05 11:01
Have you set the `trusted_proxies` option?

The default is not to trust any subnets when it comes to the `X-Forwarded-For` header, but you can add it in the config file, e.g. for localhost:
`trusted_proxies = 127.0.0.1/32, 0:0:0:0:0:0:0:1/128`

**Comment by hc4** [comment] 2016-08-05 11:08
Configured:
`trusted_proxies = 127.0.0.1/32, 0:0:0:0:0:0:0:1/128, 0.0.0.0/0`

but still no joy.
When does this client address get refreshed?

**Comment by hc4** [comment] 2016-08-05 11:11
It seems sessions not refreshing at all.
Entered under another user from another PC - and even no green light

**Comment by joschi** [comment] 2016-08-05 11:11
@hc4 Are you using a reverse proxy in front of Graylog?

**Comment by kroepke** [comment] 2016-08-05 11:14
The session should be updated every time the user interacts with Graylog, I'll double check.

**Comment by hc4** [comment] 2016-08-05 11:42
Yes, I'am using squid on same server with graylog.
And graylog hosted on 127.0.0.1

**Comment by hc4** [comment] 2016-08-05 11:44
I think the problem is in SSO auth.
If I login throught login screen - session info (including IP) updates correctly

**Comment by hc4** [comment] 2016-08-05 11:52
My auth config:
```
{
    "realm_order": 
    [
      "mongodb-session", 
      "access-token", 
      "sso", 
      "legacy-ldap", 
      "mongodb-password", 
      "root-user"
    ],
    "disabled_realms": ["legacy-ldap"]
}
```

**Comment by kroepke** [comment] 2016-08-05 11:53
I can confirm that, looks like somehow the session isn't created as it should.
Works via normal login, doesn't work via SSO-created session.

**Comment by kroepke** [comment] 2016-08-05 12:18
@hc4 Thanks for the report, the issue should be fixed in the next release!

**Closed** 2016-08-08 12:56 UTC
Labels: bug, P2, S3
