### ISSUE TITLE
graylog config template for sidecar filebeats on windows faulty

### ISSUE THREAD

**Issue by pvdh** [Graylog2/graylog2-server#8121] opened 2020-05-14 07:26 UTC
## Expected Behavior
When creating a "New Collector Configuration" for a sidecar, graylog provides some templates. Using the filebeat template for windows should work after changing the hosts-list.

## Current Behavior
The filebeat template for windows contains a typo, which is hard to spot when you are not used to configuring filebeat. This results in "no modules or inputs enabled and configuration reloading disabled. What files do you want me to watch?".

## current template

`# Needed for Graylog
fields_under_root: true
fields.collector_node_id: ${sidecar.nodeName}
fields.gl2_source_collector: ${sidecar.nodeId}

output.logstash:
   hosts: ["192.168.1.1:5044"]
path:
  data: C:\Program Files\Graylog\sidecar\cache\filebeat\data
  logs: C:\Program Files\Graylog\sidecar\logs
tags:
 - windows
filebeat.inputs:
  type: log
  enabled: true
  paths:
    - C:\logs\log.log
`
## improved template
`# Needed for Graylog
fields_under_root: true
fields.collector_node_id: ${sidecar.nodeName}
fields.gl2_source_collector: ${sidecar.nodeId}

output.logstash:
   hosts: ["192.168.1.1:5044"]
path:
  data: C:\Program Files\Graylog\sidecar\cache\filebeat\data
  logs: C:\Program Files\Graylog\sidecar\logs
tags:
 - windows
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - C:\logs\log.log
`

## Steps to Reproduce (for bugs)

1. create a sidecar
2. apply the default configuration

## Your Environment

* Graylog Version: 3.2.4
* Sidecar: 1.0.2

**Comment by mpfz0r** [comment] 2020-05-14 09:26
Thank you for the report.
This has already been fixed. But since the fix is done in a migration, it does only take effect on new installations (or if you remove the collector configuration and restart the server)

Duplicate of #6581

**Closed by mpfz0r** 2020-05-14 09:26 UTC
Labels: bug
