### ISSUE TITLE
Status for logged on users is incorrect

### ISSUE THREAD

**Issue by asachs01** [Graylog2/graylog2-server#9241] opened 2020-10-22 16:13 UTC
## Expected Behavior

When multiple users are logged into a cluster, their status should show as green.

## Current Behavior

Currently, if multiple users are logged into the UI, they're not showing as logged in.
<img width="250" alt="Screen Shot 2020-10-22 at 12 08 13 PM" src="https://user-images.githubusercontent.com/898627/96900260-e87eba00-145f-11eb-9e39-138423da9f7d.png">

In this case, me, Joe and Or were logged into the UI.

**Comment by bud1979** [comment] 2020-10-22 16:24
This is an issue as well on a single node install, and the IP address is not pulling up int he "Client Address" field.

**Comment by bernd** [comment] 2020-10-26 14:39
Duplicate of https://github.com/Graylog2/graylog2-server/issues/9175

**Closed by bernd** 2020-10-26 14:39 UTC
Labels: bug, triaged
