### ISSUE TITLE
In LDAP/AD integration user accounts are case sensitive while they should not be

### ISSUE THREAD

**Issue by gregvasilyev** [Graylog2/graylog2-server#4762] opened 2018-04-26 11:40 UTC
## Expected Behavior
When user enters an account name, "Administrator", "administrator", and "AdMiNiStRaToR" should be all mapped to the same "administrator" account entry in Graylog, assuming authentication is made against the same LDAP/AD identity store.

## Current Behavior
Every time a user enters the account name with other letters capitalized than before, a new entry is created in Graylog user table.

The issue is consistent across several deployments of Graylog that differ in OS version.

## Possible Solution
Always convert received user name to lower case, then do the validation.

## Steps to Reproduce (for bugs)

1. Enable LDAP/AD authentication.
2. Try to login to the system with the same account name, but each time capitalize various letters of the account name.
3. Observe multiple user entries created for the same account name in System -> Authentication -> Users.
4.

## Context
The issue creates overall confusion additional challenges when administering Graylog users and their capabilities in the system.

## Your Environment

* Graylog Version:  2.4.3+2c41897
* Elasticsearch Version: 2.4.6-1 
* MongoDB Version:  3.4.14-1.amzn1
* Operating System: CentOS Linux release 7.4.1708 3.10.0-693.21.1.el7.x86_64
* Browser version: Firefox 59.0.2, but the issue persists across a variety of browsers

<img width="339" alt="screen shot 2018-04-25 at 8 42 55 pm" src="https://user-images.githubusercontent.com/23131177/39303673-0bf90e30-4925-11e8-9bef-0175d7f99e39.png">

**Comment by joschi** [comment] 2018-04-26 11:58
Duplicate of #1361

**Closed by joschi** 2018-04-26 11:58 UTC
