### ISSUE TITLE
Syslog 

### ISSUE THREAD

**Issue by Thomas-1985** [Graylog2/graylog2-server#1272] opened 2015-06-30 07:16 UTC
Hi

I use the graylog appliance (graylog-web-interface v1.1.3 (611c8b2) (Oracle Corporation 1.8.0_45 / Linux 3.16.0-30-generic) on syslog ) and opened a syslog input at UDP (port 514). This works fine, however i need syslog on port TCP 610 as well, so i created another input. When i tried to launch it it gives me an "error: operation not permitted" error .

Best,

Thomas

**Comment by joschi** [comment] 2015-06-30 09:16
@Thomas-1985 Ports below 1024 may only be bound by a privileged user (e. g. "root"). There's an exception configured for port 514 in the virtual machine images but other privileged ports cannot be used without some changes.

If feasible, please use a non-privileged port (e. g. 1610/tcp) for the additional input.

I'm closing this issue as it's not a bug or feature request. Please post general support requests on the [mailing list](https://groups.google.com/forum/#!forum/graylog2) or on [IRC](https://webchat.freenode.net/?channels=%23graylog).

**Closed by joschi** 2015-06-30 09:16 UTC
