### ISSUE TITLE
Updating Extractor causes Input to fail

### ISSUE THREAD

**Issue by Bastidias** [Graylog2/graylog2-server#3906] opened 2017-06-12 19:43 UTC
When saving an extractor, the associated input will fail to restart with an error that "Address is already in use."

## Expected Behavior
Expected behavior is that the input should continue to work when an extractor is saved (even if no changes are made).

## Steps to Reproduce (for bugs)
1.  Open running input
2.  Open associated extractor
3.  Save extractor
4.  Graylog will alert "Failed to start" with a message "Address already in use."
5. Restart Graylog to resolve the error

## Context
This issue began after updating to the 2.3.0-alpha.3 build

## Your Environment
Issues replicated with sidecar connected to WinFileBeat and NxLog. 

* Graylog Version:  2.3.0-alpha.3
* Elasticsearch Version:  5 (packaged with Graylog)
* MongoDB Version:  3.4.1
* Operating System: Ubuntu 14.04.5 LTS
* Browser version: Chrome 58

**Comment by joschi** [comment] 2017-06-12 20:42
Duplicate of #3903.

**Closed by joschi** 2017-06-12 20:42 UTC
