### ISSUE TITLE
MongoDB: Namespace name generated from index name is too long

### ISSUE THREAD

**Issue by maedox** [Graylog2/graylog2-server#6364] opened 2019-08-28 13:46 UTC
After upgrading from 3.0 to 3.1 startup is aborted with this mongodb error:
```
ERROR: Unable to connect to MongoDB. Is it running and the configuration correct?

107715:Details: Command failed with error 67: 'namespace name generated from index name "58f9c025c0c6e36a06f1e6f8_graylog.processing_status.$updated_at_1_input_journal.uncommitted_entries_1_input_journal.written_messages_1m_rate_1" is too long (127 byte max)' on server graylog-shard-****.mongodb.net:27017. 
```

The full response is (part of the log message, prettified by me):
```json
{
	"operationTime": {
		"$timestamp": {
			"t": 1566470056,
			"i": 1
		}
	},
	"ok": 0.0,
	"errmsg": "namespace name generated from index name \"58f9c025c0c6e36a06f1e6f8_graylog.processing_status.$updated_at_1_input_journal.uncommitted_entries_1_input_journal.written_messages_1m_rate_1\" is too long (127 byte max)",
	"code": 67,
	"codeName": "CannotCreateIndex",
	"$clusterTime": {
		"clusterTime": {
			"$timestamp": {
				"t": 1566470056,
				"i": 1
			}
		},
		"signature": {
			"hash": {
				"$binary": "IlONky6vnIp/1kF0gbeI92p9feM=",
				"$type": "00"
			},
			"keyId": {
				"$numberLong": "6698374438712246273"
			}
		}
	}
}
```

## Possible Solution
...

## Steps to Reproduce (for bugs)
Upgrade Ubuntu packages from Graylog 3.0 to 3.1.

## Your Environment

* Graylog Version: 3.1.0 (Ubuntu package install)
* Elasticsearch Version: 6.6.1 (Hosted by Elastic)
* MongoDB Version: 4.0.12 (Hosted by MongoDB Atlas)
* Operating System: Ubuntu 18.04 (AWS)
* Browser version: N/A

[server.conf.txt](https://github.com/Graylog2/graylog2-server/files/3551180/server.conf.txt)

**Comment by mpfz0r** [comment] 2019-08-28 14:04
Duplicate of #6322 

Will be fixed in 3.1.1.
Here's a workaround in the meantime: https://github.com/Graylog2/graylog2-server/issues/6322#issuecomment-523445067

**Closed by mpfz0r** 2019-08-28 14:04 UTC
