### ISSUE TITLE
Graylog Server Crash on TLS1.3 with Curl

### ISSUE THREAD

**Issue by Tux12Fun** [Graylog2/graylog2-server#7400] opened 2020-02-05 13:27 UTC
## Expected Behavior

Server should be running

## Current Behavior

If curl acceses api via TLS1.3 Graylog Server consumes 100% cpu and hangs.

TOP:
 PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
22934 graylog   20   0 36.553g 0.011t  29632 R 99.9  4.0   3:47.37 /usr/bin/java -Xms24g -Xmx24g -XX:NewRatio=1 -server -XX:+ResizeTLAB -XX:+UseConcMarkS

## Possible Solution

Fix TLS to 1.2 in  /etc/graylog/server/server.conf
enabled_tls_protocols= TLSv1.2

or set -Djdk.tls.client.protocols=TLSv1.2 -Dhttps.protocols=TLSv1.2 -Djdk.tls.disabledAlgorithms=TLSv1.3 -Djdk.tls.server.protocols=TLSv1.2

## Steps to Reproduce (for bugs)

1. Start Graylog Configured with TLS 1.2/1.3
2. Connect with a current CURL Version to Graylog API
3. See Task Manger 
4. Graylog Gui isn't responding any more

## Your Environment

* Graylog Version:  3.2.1-1
* Elasticsearch Version: elasticsearch 5.6.16
* MongoDB Version: 1:3.6.3-0ubuntu1.1
* Operating System: (Ubuntu 18.4.03 on Linux 4.15.0-66-generic)
* Browser version: Chrome 79

Graylog:
`2020-02-05T14:22:52.535+01:00 INFO  [CodecFactoryUtil] Registered pre-bundled control factory: 1.2.840.113556.1.4.473
2020-02-05T14:22:52.535+01:00 INFO  [CodecFactoryUtil] Registered pre-bundled control factory: 1.2.840.113556.1.4.474
2020-02-05T14:22:52.535+01:00 INFO  [CodecFactoryUtil] Registered pre-bundled control factory: 1.2.840.113556.1.4.841
2020-02-05T14:22:52.536+01:00 INFO  [CodecFactoryUtil] Registered pre-bundled control factory: 1.2.840.113556.1.4.417
2020-02-05T14:22:52.536+01:00 INFO  [CodecFactoryUtil] Registered pre-bundled control factory: 1.2.840.113556.1.4.1413
2020-02-05T14:22:52.537+01:00 INFO  [CodecFactoryUtil] Registered pre-bundled control factory: 1.2.840.113556.1.4.528
2020-02-05T14:22:52.537+01:00 INFO  [CodecFactoryUtil] Registered pre-bundled extended operation factory: 1.3.6.1.1.8
2020-02-05T14:22:52.538+01:00 INFO  [CodecFactoryUtil] Registered pre-bundled extended operation factory: 1.3.6.1.4.1.18060.0.1.8
2020-02-05T14:22:52.539+01:00 INFO  [CodecFactoryUtil] Registered pre-bundled extended operation factory: 1.3.6.1.4.1.18060.0.1.3
2020-02-05T14:22:52.539+01:00 INFO  [CodecFactoryUtil] Registered pre-bundled extended operation factory: 1.3.6.1.4.1.18060.0.1.6
2020-02-05T14:22:52.540+01:00 INFO  [CodecFactoryUtil] Registered pre-bundled extended operation factory: 1.3.6.1.4.1.18060.0.1.5
2020-02-05T14:22:52.540+01:00 INFO  [CodecFactoryUtil] Registered pre-bundled extended operation factory: 1.3.6.1.4.1.4203.1.11.1
2020-02-05T14:22:52.541+01:00 INFO  [CodecFactoryUtil] Registered pre-bundled extended operation factory: 1.3.6.1.4.1.4203.1.11.3
2020-02-05T14:22:52.542+01:00 INFO  [CodecFactoryUtil] Registered pre-bundled extended operation factory: 1.3.6.1.4.1.1466.20037
2020-02-05T14:22:52.809+01:00 ERROR [LdapUserAuthenticator] Error during LDAP user account sync. Cannot log in user admin
java.lang.RuntimeException: ERR_02002_FAILURE_ON_UNDERLYING_CURSOR Failure on underlying Cursor.
        at org.apache.directory.api.ldap.model.cursor.CursorIterator.next(CursorIterator.java:89) ~[graylog.jar:?]
        at org.graylog2.security.ldap.LdapConnector.search(LdapConnector.java:142) ~[graylog.jar:?]
        at org.graylog2.security.realm.LdapUserAuthenticator.searchLdapUser(LdapUserAuthenticator.java:160) ~[graylog.jar:?]
        at org.graylog2.security.realm.LdapUserAuthenticator.doGetAuthenticationInfo(LdapUserAuthenticator.java:110) ~[graylog.jar:?]
        at org.apache.shiro.realm.AuthenticatingRealm.getAuthenticationInfo(AuthenticatingRealm.java:571) ~[graylog.jar:?]
        at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doMultiRealmAuthentication(ModularRealmAuthenticator.java:219) ~[graylog.jar:?]
        at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthenticate(ModularRealmAuthenticator.java:269) ~[graylog.jar:?]
        at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:198) ~[graylog.jar:?]
        at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106) ~[graylog.jar:?]
        at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:274) ~[graylog.jar:?]
        at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:260) ~[graylog.jar:?]
        at org.graylog2.shared.security.ShiroSecurityContext.loginSubject(ShiroSecurityContext.java:107) ~[graylog.jar:?]
        at org.graylog2.shared.security.ShiroAuthenticationFilter.filter(ShiroAuthenticationFilter.java:48) ~[graylog.jar:?]
        at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132) ~[graylog.jar:?]
        at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68) ~[graylog.jar:?]
        at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197) ~[graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:318) ~[graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[graylog.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) ~[graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) ~[graylog.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) ~[graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) ~[graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) ~[graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:181) ~[graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: org.apache.directory.api.ldap.model.cursor.CursorLdapReferralException
        at org.apache.directory.ldap.client.api.EntryCursorImpl.get(EntryCursorImpl.java:174) ~[graylog.jar:?]
        at org.apache.directory.ldap.client.api.EntryCursorImpl.get(EntryCursorImpl.java:52) ~[graylog.jar:?]
        at org.apache.directory.api.ldap.model.cursor.CursorIterator.next(CursorIterator.java:82) ~[graylog.jar:?]
        ... 30 more
`

**Comment by mpfz0r** [comment] 2020-02-05 13:30
Which java version are you using?

Java 11 still has problems because of a bug in grizzly:
cf https://github.com/Graylog2/graylog2-server/issues/6306

**Comment by Tux12Fun** [comment] 2020-02-05 13:41
Yes it's openjdk 11 if it's a known Bug, then it's no problem. I use the workaround TLS1.2

**Comment by mpfz0r** [comment] 2020-02-05 13:45
@Tux12Fun thanks, any chance you tried the recently released `11.0.6` version?
I've been wondering whether they've fixed something.
jdk 13 apparenlty works, but that's a non LTS release :-/

**Comment by Tux12Fun** [comment] 2020-02-05 14:15
Currently our Systems are Frozen to Ubuntu Repo Date 2019-11-26 I will test this with next update cycle.

**Comment by mpfz0r** [comment] 2020-11-10 09:41
Duplicate of #6306

**Closed by mpfz0r** 2020-11-10 09:41 UTC
Labels: bug, triaged
