### ISSUE TITLE
Reader user cannot delete search widget

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#12325] opened 2022-03-18 17:31 UTC
A reader user with owner permissions on a stream, cannot delete a search widget:

https://user-images.githubusercontent.com/716185/159053475-150d9a61-1f25-424e-b094-90bf5d7cb393.mp4

The resulting error is:

```
The permissions check for the following request failed,
while trying to access /streams/622b59f24d8235032b34b7cd/search.
There was an error fetching a resource: Forbidden. Additional information: Not authorized
```

I also noticed that when clicking on "Delete" (and before confirming the widget deletion) there is a background request that fails with a 403:

```
/api/plugins/org.graylog.plugins.report/reports/byWidget/undefined/85a342a7-da01-4bc3-9df7-90de29e2d3db
```

## Expected Behavior
Deleting a search widget should work when reader user has write or owner permissions on a stream.

## Current Behavior
Deleting a search widget does not seem to work for reader users.

## Steps to Reproduce (for bugs)
1. Open search or stream search
2. Delete a widget (it can be a new or existing one)

## Your Environment
* Graylog Version: Graylog 4.3.0-beta.2+a61a34c

**Comment by edmundoa** [comment] 2022-03-18 17:46
After further testing, it looks like the same happens on dashboard widgets as well.

**Comment by dennisoelkers** [comment] 2022-03-21 09:23
Thanks for reporting this, @edmundoa! I think this is a duplicate of #12320?

**Comment by edmundoa** [comment] 2022-03-22 12:21
@dennisoelkers I think so, just the places where it occur seem to be different. Feel free to close this one or leave open for double-checking when a fix is ready.

**Closed** 2022-03-23 12:59 UTC
Labels: bug, triaged, test-day
