### ISSUE TITLE
bugs on Web UI | lastest Graylog v2.0-beta.3

### ISSUE THREAD

**Issue by piellick** [Graylog2/graylog2-server#2090] opened 2016-04-15 14:36 UTC
### Problem description
strange time out, button stop working after on or two click

i made a screeencast :
https://www.youtube.com/watch?v=Ictdgpi00vg&feature=youtu.be&hd=1

### Steps to reproduce the problem

using beta webUI 

### Environment

* Graylog Version: lastest Graylog v2.0-beta.3 tar 
* Elasticsearch Version: 2.3.1
* MongoDB Version: 3.2.5
* Operating System: Debian 8
* Browser version: lastet chrome or firefox

**Comment by edmundoa** [comment] 2016-04-15 15:05
Hi,

I was doing the same actions you did locally and couldn't reproduce any of those issues. Please include the OS where your browser runs, and any errors from your browser's developers console.

Thank you!

**Comment by piellick** [comment] 2016-04-19 07:54
hi ,
there are two screen capture form lastest Firefox and Chrome engine.

![graylog_beta](https://cloud.githubusercontent.com/assets/18485789/14631620/9967dc8e-0614-11e6-99fb-522bdb6720c7.png)
![graylog_beta_firefox](https://cloud.githubusercontent.com/assets/18485789/14631621/997334f8-0614-11e6-9872-ec7f3370171c.png)

i'm running a windows 7 64 bits operating system.

**Comment by edmundoa** [comment] 2016-04-19 09:50
From the logs that you shared, I can see two different things:

1. There is what it seems to be a session timeout in the first part of the first screenshot, which is probably normal if you started by logging into Graylog
2. There is an error that got fixed in beta.3 (#2025), and looking at the error message, I am quite confident that you are not using beta.3 as you reported :smile:

Looking at the video again, the couple of issues I could spot in there were fixed in the latest beta, so my recommendation is to double check that you are indeed using beta.3, and update to it if you aren't. Could you please quickly copy the Graylog version displayed in the web interface footer?

**Comment by piellick** [comment] 2016-04-19 13:19
Ho god ... i apologize edmundoa ! I downloaded it on day before beta 3. I have just install it and evething look's good ! Thanks !

**Comment by edmundoa** [comment] 2016-04-19 13:23
No worries. Good to see that it looks better now! :+1:

**Closed by edmundoa** 2016-04-19 13:23 UTC
Labels: needs-input
