### ISSUE TITLE
Pipeline Concat Function Causes Page NotFound

### ISSUE THREAD

**Issue by estein9825** [Graylog2/graylog2-server#6987] opened 2019-12-12 18:22 UTC
On Graylog 3.0.2, if one creates a simple concat pipeline rule, the moment you add the closing parentheses, the page reloads to the Party Gorilla Page Not Found page.

## Expected Behavior
It should not cause the reload

## Current Behavior
Causes a page reload to /notfound page

## Possible Solution
Graylog 3.0.1 does not present this error

## Steps to Reproduce (for bugs)

1. Upgrade to 3.0.2 graylog
2. Go into System --> Pipelines --> Manage rules
3. Create a new rule with the contents:
```
rule "concat test"
let concat_test = concat("one","two")
```
The redirect will occur the moment you add the closing parentheses
## Context
I need concat to complete the rule.  I am uncertain if this works in 3.1, but I cannot upgrade due to how the alert configuration was changed.

## Your Environment
* Graylog Version: Graylog 3.0.2+1686930
* Elasticsearch Version: 6.8.5
* MongoDB Version: 4.0.13
* Java Version: Oracle Corporation 1.8.0_222
* Operating System: Linux 4.14.146-120.181.amzn2.x86_64
* Browser version: Tried on both Safari and Chrome

**Comment by jalogisch** [comment] 2019-12-13 08:47
He @estein9825 

I can not reproduce this on 3.1.3 with the following rule:

```
rule "concat test"
when
 true
then
 let concat_test = concat("one","two");
end
```

Do you mind updating your environment to the latest version and try again?

**Comment by estein9825** [comment] 2019-12-13 12:45
As I mentioned, upgrading to 3.1 is currently not an option. Is there any way to hotfix 3.0.2?

**Comment by jalogisch** [comment] 2019-12-16 13:11
@estein9825 it is not very likely. 

You might want to contact sales if you really need it: https://www.graylog.org/contact-sales

**Comment by estein9825** [comment] 2020-01-09 21:12
Okay, I just upgraded to 3.1.3 and I am still seeing the same issue.

**Comment by estein9825** [comment] 2020-01-09 21:13
Again, it was fine in 3.0.1.

**Comment by estein9825** [comment] 2020-01-10 21:02
Okay, I think I may have found the cause: 

I am using Cloudflare as my DNS provider, with a CNAME that translates into an AWS load balancer hosting my graylog connection. It seems when I am attempting to make a JSON request through the parse API using my Cloudflare-based DNS, Cloudflare blocks the entire page.  Perhaps because "concat" is a known javascript word. And since it's an HTML return and not a JSON response, Graylog can't load it and fails.

**Comment by estein9825** [comment] 2020-01-10 21:03
I'm curious, does 3.0.2+ change how rules are built?

**Comment by boosty** [comment] 2022-09-09 14:08
I am closing this since the original problem was solved on the user's side.

**Closed by boosty** 2022-09-09 14:08 UTC
Labels: bug, triaged
