### ISSUE TITLE
Sorting floats in a data table appear to sort by ascii sort order and not numerical

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#17706] opened 2023-12-14 15:00 UTC
Sorting floats in a data table appear to sort by ascii sort order and not numerical.

This occurs if the float data is not the first field. IF the float field is first the sort works as expected.

## Expected Behavior

Float can be sorted numerically and in the correct order.

## Current Behavior

Sorting a float does not sort numerically and is not listed in the correct order.

## Steps to Reproduce (for bugs)

1. Create an aggregation
2. create 2 group by
    1. first group by field: not important but should not be a float
    2. second group by field: float
3. Add a sort for the float field, descending

![image](https://github.com/Graylog2/graylog2-server/assets/107503402/7ec27207-9fe9-4b9c-87c7-54175198b16b)

If i change the order of the group by fields and put the float field first, the sort works as expected.

![image](https://github.com/Graylog2/graylog2-server/assets/107503402/cf378a25-530c-406e-984a-e1577bc1b32e)

## Context

I was testing out the new entropy pipeline function (which is very neat and very useful!) and noticed i had issues sorting floats correctly.

## Your Environment

* Graylog Version: 5.2.2
* Java Version: Bundled
* OpenSearch Version: 2.11.1
* MongoDB Version: 6.0.12
* Operating System: Ubuntu 22.04 LTS
* Browser version: Google Chrome Version 120.0.6099.109 (Official Build) (arm64)

Please let me know if there are any questions. Thanks!

**Comment by dennisoelkers** [comment] 2023-12-15 07:06
Hey @drewmiranda-gl, 

this is due to using two separate row groups. If you do it this way, then documents are put into distincts buckets and each bucket is sorted separately. If you want to sort tuples (field1, field2), then you need to put both fields into the same grouping.

As this is working as intended, I am closing this issue. Feel free to reopen if you have additional information.

**Closed by dennisoelkers** 2023-12-15 07:06 UTC
Labels: bug
