### ISSUE TITLE
Sending usage statistics while using output plugin decreases performance

### ISSUE THREAD

**Issue by pontusr** [Graylog2/graylog2-server#1727] opened 2016-01-26 16:46 UTC
Adding an output plugin to a stream decreases performance by 75-90% when sending anonymous usage statistics is enabled if the output plugin is using the internal logger.
We can reproduce this with several output plugins who use the internal Graylog logger on the Amazon AMIs for Graylog 1.3.3.
Steps to reproduce on server without any streams or output plugins configured:
1. Input messages at for example 2000msg/s. Monitor outgoing msgs/s which should handle the incoming load.
2. Add a stream which routes all messages (add rule: field 'message' must exist) into the outputs.
3. Start the stream.
4. Add an STDOUT output to the stream.
5. Enable "sending anonymous usage statistics."
6. Watch the outgoing msg/s drop.
(Bonus steps:)
7. Add second output to the stream, outgoing performance should not drop further.
8. Delete any of the two outputs, performance will not be restored.
9. Delete both outputs globally, watch the performance being restored right away.

**Comment by kroepke** [comment] 2016-04-12 13:30
I'm unable to reproduce this issue.

When enabling the usage states nothing runs immediately, but it simply toggles a flag. I cannot find any code that would be interfering with message processing.

However, the STDOUT is really only meant for debugging purposes. On our images the services, including graylog server, send their log output to the instance running. Could it be that you run into a feedback loop which overloads the server?

Even when I feed the entire message input back into Graylog multiple times I cannot trigger the described behavior. Could it be that you simply exceed the capacity of your instance?

I'll close this issue now, if you have additional information please reopen it.

Thanks,
Kay

**Closed by kroepke** 2016-04-12 13:30 UTC
Labels: bug, P2, S2
