### ISSUE TITLE
Dashboard: Overridden Date/Time causes issue in Widget Edit

### ISSUE THREAD

**Issue by kyleknighted** [Graylog2/graylog2-server#10554] opened 2021-05-03 16:26 UTC
## Expected Behavior

- Load Dashboard
- Add Date/Time override and click Search button
- Edit Widget and click Reset Filters button to be able to manage Widget Date/Time

## Current Behavior

After loading the Edit Widget screen you are greeted with a console.log error

```
react_devtools_backend.js:2557 Warning: Failed prop type: Invalid prop `children` supplied to `WidgetHeader`.
```

And if you click the `Reset Filters` button, Error Page loads with
`Cannot read property 'effective_timerange' of undefined`

**Comment by kmerz** [comment] 2021-06-01 09:06
Could not reproduce the problem! Probably fixed by now.

**Closed by kmerz** 2021-06-01 09:06 UTC
Labels: bug, dashboards, triaged, ux, widgets
